### PR TITLE
fix(nms): Cannot add user after editing an organisation

### LINKED ISSUE #12640: Cannot add users in the organization edit page of NMS
### Your Environment

- **Version:** master
- **Affected Component:** NMS
- **Deployment Environment:** local docker-compose (orc8r + NMS)

### Describe the Issue

grafik

The `Add Users` button does not allow to add users, but shows the same dialog as the `Edit` button.

### Expected behavior

The `Add Users` button should allow to add users.

### PR DESCRIPTION
**Pull request by thmsschmitt**
## Steps to reproduce

- Go to the organisation details view
Screenshot 2022-05-09 at 09 11 25
- Click "Edit" and save the organisation (no changes are required)
- Click "Add User" 
  - Bug the dialog opens with the "Edit" tab. It is not possible to add users without reloading.  
## Test Plan
Follow the steps to reproduce, make sure that it is not broken anymore.

### CODE REVIEW

File: nms/fbc_js_core/ui/host/OrganizationDialog.js [hunk 1]
```diff
@@ -167,6 +167,7 @@ export default function (props: Props) {
         return;
       }
       const newOrg = {
+        id: organization.id,
```
Comment (thmsschmitt) [inline nms/fbc_js_core/ui/host/OrganizationDialog.js:170]: When editing an organisation the id was lost, which caused the dialog to always show the first tab as if it was creating an organisation.

File: nms/fbc_js_core/ui/host/OrganizationInfoDialog.js [hunk 2]
```diff
@@ -59,7 +59,7 @@ export default function (props: DialogProps) {
       )}
       <AltFormField label={'Organization Name'}>
         <OutlinedInput
-          disabled={props.organization.id}
+          disabled={!!props.organization.id}
```
Comment (thmsschmitt) [inline nms/fbc_js_core/ui/host/OrganizationInfoDialog.js:62]: Drive by fix to silence the react warning that `disabled` should be a boolean.

**Review by HannaFar — APPROVED** [review]
