### PR TITLE
fix(agw): Defining macro for table 0

### LINKED ISSUE #11643: [mme] Use a macro for OVS table num controlled by MME, instead of 0
We have not done it anywhere in GTP application, have a look at call create_default_flow_mod(). '0' is passed from all GTP apps. I can post other incremental PR for this improvement.

_Originally posted by @pshelar in https://github.com/magma/magma/pull/11639#r808313987_

### PR DESCRIPTION
**Pull request by vikramgreddy**
## Summary
Fixes #11643 
Macro for OVS table num controlled by MME, instead of 0 

## Test Plan
Executed make test_oai
Executed s1ap integ_tests

### CODE REVIEW

File: lte/gateway/c/core/oai/lib/openflow/controller/OpenflowController.h [hunk 1]
```diff
@@ -32,6 +32,9 @@ namespace openflow {
 #define IP_ETH_TYPE 0x0800
 
 class Application {
+ public:
+  static const uint8_t SPGW_TABLE = 0;
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/lib/openflow/controller/OpenflowController.h]:
```suggestion
  static const uint8_t SPGW_OVS_TABLE_ID = 0;
```

**Review by ssanadhya — CHANGES_REQUESTED** [review]
Can we rename the macro to be more explicit, such as `SPGW_OVS_TABLE_ID` ?

**Review by ssanadhya — APPROVED** [review]
Lgtm

**Review by ssanadhya — CHANGES_REQUESTED** [review]
@vikramgreddy , looks like the last commit got undone when you update the branch 
https://github.com/magma/magma/compare/10d622062392a98d1f3805353edcaeaef8889409..7f48092442b5a82adaf99fff598a75849fc92a5b 

Could you please rename the macro to `SPGW_OVS_TABLE_ID`?

**Review by ssanadhya — APPROVED** [review]
Lgtm
