### PR TITLE
fix(xwf): fix docker gw0 mms size and CI

### LINKED ISSUE #8249: Xwfm tests failing on master
close this once it is back to being healthy
https://circleci.com/gh/magma/magma/332934
https://circleci.com/gh/magma/magma/332928

flagging @aharonnovo since he is the owner

### PR DESCRIPTION
**Pull request by aharonnovo**
[xwfm] fix ci on circleci and in local environment

## Summary

XWFM CI is broken due to some issues, this diff suppose to fix it by:

Change some docker-compose configuration
Fix XWFM mss tcp size
Fix RADIUS secret (add some logs to help us avoid it next time)
Upgrade Go version in CWAG and CWAG_TEST VMS

## Test Plan

working on my laptop
Ran the CWF integration test locally - @themarwhal 

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

File: cwf/gateway/docker/go/Dockerfile [hunk 1]
```diff
@@ -38,8 +38,8 @@ RUN apt-get update && apt-get install -y \
 
 # Install Golang 1.12.
```
Comment (quentinDERORY) [inline cwf/gateway/docker/go/Dockerfile]: Can you modify the comment too?

File: feg/radius/lib/go/radius/server-packet.go [hunk 2]
```diff
@@ -22,6 +22,8 @@ import (
 	"net"
 	"sync"
 	"sync/atomic"
+
```
Comment (quentinDERORY) [inline feg/radius/lib/go/radius/server-packet.go:25]: can you get rid of the empty line

**Review by quentinDERORY — APPROVED** [review]

**Review by themarwhal — APPROVED** [review]
