### PR TITLE
fix(mme): Changing the hashtable implementations for UE mgmt in amf to maps

### LINKED ISSUE #9780: [AMF]: Changing imsi_amf_ue_id_htbl and tun11_ue_context_htbl hashtables to map implementation
The requirement is to change the imsi_amf_ue_id_htbl and tun11_ue_context_htbl hashtables implementation to cmaps.

This is a subtask of #9610.

### PR DESCRIPTION
**Pull request by shashidhar-patil**
Signed-off-by: shashidhar-patil <shashidhar.patil@wavelabs.ai>

## Summary
Earlier: Hashtable implementation was used for UE mgmt in amf. 

Need for change: The reason for the movement is maps are inbuilt libraries and faster as compared to hashtables.They provide better hashing and in turn reduce collisions. 

Code changes:
As a part of this, the following four UE hashtable structures were converted into map implementations.
1. imsi_amf_ue_id_htbl
2. tun11_ue_context_htbl
3. gnb_ue_ngap_id_ue_context_htbl
4. guti_ue_context_htbl

Approach: A generic template structure is implemented for maps. All four maps are created using this generic structure. The generic structure has the basic get, insert and remove operations.

This document gives a brief on design changes: 
[Hastables_to_maps.pdf](https://github.com/magma/magma/files/7480746/Hastables_to_maps.pdf)
 

## Test Plan
- Verified basic sanity with UERANSIM.
- Please find attached logs and pcap snap for basic registration.
- Verified using UT cases.

Logs: (Dated: 09/11/21)
[mme.log](https://github.com/magma/magma/files/7503338/mme.log)

Snapshot of pcap: (Dated: 09/11/21)
mapPcap

UT test case: (Dated: 09/11/21)
maptest

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Comment by ulaskozat** [comment]
@ardzoht can you steer this PR?

File: lte/gateway/c/core/oai/tasks/amf/amf_map.h [hunk 1]
```diff
@@ -0,0 +1,181 @@
+
```
Comment (ardzoht) [inline lte/gateway/c/core/oai/tasks/amf/amf_map.h]: add magma LICENSE header

File: lte/gateway/c/core/oai/tasks/amf/amf_map.cpp [hunk 2]
```diff
@@ -0,0 +1,51 @@
+#include "amf_map.h"
```
Comment (ardzoht) [inline lte/gateway/c/core/oai/tasks/amf/amf_map.cpp]: add magma LICENSE header

File: lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp [hunk 3]
```diff
@@ -842,9 +844,86 @@ TEST(test_dnn, test_amf_validate_dnn) {
   int rc = amf_validate_dnn(&amf_ctx, dnn_string, &idx, ue_sent_dnn);
   EXPECT_TRUE(rc == RETURNok);
 }
-int main(int argc, char** argv) {
-  ::testing::InitGoogleTest(&argc, argv);
-  return RUN_ALL_TESTS();
+
+TEST(test_map, test_map) {
```
Comment (ardzoht) [inline lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp]: we should move this test to its own test file, `test_amf_map.cpp`

File: lte/gateway/c/core/oai/tasks/amf/amf_map.h [hunk 4]
```diff
@@ -0,0 +1,181 @@
...
+#include <pthread.h>
+
+#include <iostream>
+#include <unordered_map>
+#include <mutex>
+#include <string>
+
+#include "3gpp_23.003.h"
+
+namespace std {
```
Comment (ardzoht) [inline lte/gateway/c/core/oai/tasks/amf/amf_map.h]: can we move this file to a common folder for reuse? how about ../core/oai/include/map.h and rename `amf_map` to `map`? that will also help us in the future for migrating other usages of hashtable to this

File: lte/gateway/c/core/oai/tasks/amf/amf_map.h [hunk 5]
```diff
@@ -0,0 +1,181 @@
...
+// Helper Function Declarations:
+// Function to convert the return codes into string before logging them.
+std::string map_rc_code2string(map_rc_t rc);
+
+// Map Declarations:
+// Map- Key: uint64_t , Data: uint64_t
+typedef map_ts_s<uint64_t, uint64_t> map_uint64_ts_t;
+
+// Map Key: guti_m5_t Data: uint64_t;
+typedef map_ts_s<guti_m5_t, uint64_t> obj_map_uint64_ts_t;
```
Comment (ardzoht) [inline lte/gateway/c/core/oai/tasks/amf/amf_map.h]:
```suggestion
typedef map_ts_s<guti_m5_t, uint64_t> guti_m5_map_uint64_ts_t;
```

**Review by ardzoht — CHANGES_REQUESTED** [review]

File: lte/gateway/c/core/oai/tasks/amf/amf_map.h (hunk 4 above)
Comment (shashidhar-patil) [reply lte/gateway/c/core/oai/tasks/amf/amf_map.h]: How about moving both, amf_map.h and amf_map.cpp to a new folder "map" in ../core/oai/lib and renaming them to map.h and map.cpp respectively? If not, what would be an appropriate place for amf_map.cpp?

Comment (shashidhar-patil) [reply lte/gateway/c/core/oai/tasks/amf/amf_map.h]: Ignore the above comment. Will move the amf_map.h to ../core/oai/include/map.h

**Comment by shashidhar-patil** [comment]
@ardzoht  Addressed the review comments.

Logs: (Dated: 10/11/21)
[mme.log](https://github.com/magma/magma/files/7511328/mme.log)

Snapshot pcap: (Dated: 10/11/21)
mapPcapReview

File: lte/gateway/c/core/oai/tasks/amf/amf_map.h (hunk 1 above)
Comment (shashidhar-patil) [reply lte/gateway/c/core/oai/tasks/amf/amf_map.h]: This is comment is addressed.

File: lte/gateway/c/core/oai/tasks/amf/amf_map.cpp (hunk 2 above)
Comment (shashidhar-patil) [reply lte/gateway/c/core/oai/tasks/amf/amf_map.cpp]: This comment is addressed

File: lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp (hunk 3 above)
Comment (shashidhar-patil) [reply lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp]: This change has been done

File: lte/gateway/c/core/oai/tasks/amf/amf_map.h (hunk 4 above)
Comment (shashidhar-patil) [reply lte/gateway/c/core/oai/tasks/amf/amf_map.h]: This comment is addressed.

File: lte/gateway/c/core/oai/tasks/amf/amf_map.h (hunk 5 above)
Comment (shashidhar-patil) [reply lte/gateway/c/core/oai/tasks/amf/amf_map.h]: This comment has been addressed.

File: lte/gateway/c/core/oai/include/map.h [hunk 6]
```diff
@@ -0,0 +1,232 @@
...
+// Note: This HashFunc in turn calls the def_hashfunc which supports hashing
+// only for unit64
+template<>
+struct hash<guti_m5_t> {
+  size_t operator()(const guti_m5_t& k) const {
+    return def_hashfunc(&k, sizeof(k));
+  }
+};
+}  // namespace std
+namespace magma5g {
```
Comment (ardzoht) [inline lte/gateway/c/core/oai/include/map.h]: can we use `magma` namespace here? since this will be reused for hashtables on non-5g code as well

File: lte/gateway/c/core/oai/include/map.h [hunk 7]
```diff
@@ -0,0 +1,232 @@
...
+  ** Description: Takes key and valueP as parameters.If the key exists,     **
+  **              corresponding value is returned through the valueP,       **
+  **              else returns error.                                       **
+  **                                                                        **
+  ***************************************************************************/
+  map_rc_t get(const keyT key, valueT* valueP) {
+    if (umap.empty()) {
+      return MAP_EMPTY;
+    }
+    if (valueP == nullptr) {
```
Comment (ardzoht) [inline lte/gateway/c/core/oai/include/map.h:170]: this condition could be hit if the `valueP` pointer passed is not initialized, why do we return `MAP_BAD_PARAMETER_VALUE` here?

File: lte/gateway/c/core/oai/include/map.h [hunk 8]
```diff
@@ -0,0 +1,232 @@
...
+      return MAP_OK;
+    } else {
+      return MAP_KEY_NOT_EXISTS;
+    }
+  }
+};
+
+// Map Declarations:
+// Map- Key: uint64_t , Data: uint64_t
+typedef map_ts_s<uint64_t, uint64_t> map_uint64_ts_t;
```
Comment (ardzoht) [inline lte/gateway/c/core/oai/include/map.h]: I think it would be good to start using a definitive naming for the maps, could be `map_<keyType>_<valueType>_ts_t`, in this case (`map_uint64_uint64_ts_t`)

File: lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp [hunk 9]
```diff
@@ -51,6 +52,7 @@ void amf_ue_context_update_coll_keys(
     const amf_ue_ngap_id_t amf_ue_ngap_id, const imsi64_t imsi,
     const teid_t amf_teid_n11, const guti_m5_t* const guti_p) {
   hashtable_rc_t h_rc                 = HASH_TABLE_OK;
+  map_rc_t m_rc                       = MAP_OK;
   hash_table_ts_t* amf_state_ue_id_ht = get_amf_ue_state();
```
Comment (ardzoht) [inline lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp:57]: can we add a `TODO` here to note that we want to migrate this hash_table as well?

File: lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp [hunk 10]
```diff
@@ -280,15 +257,13 @@ static bool amf_app_construct_guti(
...
   uint64_t amf_ue_ngap_id64      = 0;
   ue_m5gmm_context_t* ue_context = NULL;
 
-  h_rc = obj_hashtable_uint64_ts_get(
-      amf_ue_context_p->guti_ue_context_htbl, (const void*) guti_p,
-      sizeof(*guti_p), &amf_ue_ngap_id64);
+  m_rc = amf_ue_context_p->guti_ue_context_htbl.get(*guti_p, &amf_ue_ngap_id64);
 
-  if (HASH_TABLE_OK == h_rc) {
+  if (MAP_OK == m_rc) {
```
Comment (ardzoht) [inline lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp]:
```suggestion
  if (m_rc == MAP_OK) {
```

**Review by ardzoht — CHANGES_REQUESTED** [review]
minor additional comments left, this is looking good, thanks @shashidhar-patil

File: lte/gateway/c/core/oai/include/map.h (hunk 7 above)
Comment (shashidhar-patil) [reply lte/gateway/c/core/oai/include/map.h:170]: Yes, this condition checks if the valueP is initialized. This is needed as, after fetching the key-value pair we are coping the fetched value into *valueP. If not, can you please suggest a better way of doing this?

File: lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp (hunk 9 above)
Comment (shashidhar-patil) [reply lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp:57]: This comment is addressed.

File: lte/gateway/c/core/oai/include/map.h (hunk 6 above)
Comment (shashidhar-patil) [reply lte/gateway/c/core/oai/include/map.h]: This change has been addressed.

File: lte/gateway/c/core/oai/include/map.h (hunk 8 above)
Comment (shashidhar-patil) [reply lte/gateway/c/core/oai/include/map.h]: This comment has been addressed.

File: lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp (hunk 10 above)
Comment (shashidhar-patil) [reply lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp]: This comment has been addressed.

File: lte/gateway/c/core/oai/include/map.h (hunk 7 above)
Comment (ardzoht) [reply lte/gateway/c/core/oai/include/map.h:170]: but this is done _before_ fetching the key-value pair no? or am i missing something else?

File: lte/gateway/c/core/oai/include/map.h [hunk 11]
```diff
@@ -0,0 +1,228 @@
...
+  **                                                                        **
+  ***************************************************************************/
+  map_rc_t get(const keyT key, valueT* valueP) {
+    if (umap.empty()) {
+      return MAP_EMPTY;
+    }
+    if (valueP == nullptr) {
+      return MAP_BAD_PARAMETER_VALUE;
+    }
+    std::lock_guard<std::mutex> lock(mutex_obj);
```
Comment (ulaskozat) [inline lte/gateway/c/core/oai/include/map.h]: @ardzoht do we need thread safety as each hash map is/should be local to the thread?

File: lte/gateway/c/core/oai/include/map.h (hunk 7 above)
Comment (ganeshg87) [reply lte/gateway/c/core/oai/include/map.h:170]: Agree. Before fetching the caller should provide valid key-value parameters.
this was a safety check if the caller passes valueP value nullptr unintentionally. below piece code will not crash.
```
    if (search_result != umap.end()) {
      *valueP = search_result->second;
      return MAP_OK;
      }
  ```
 it was our assumptions based on existing hash table validation checks.
 @ardzoht,  let's conclude from your side. we will address this accordingly.

File: lte/gateway/c/core/oai/include/map.h (hunk 11 above)
Comment (ardzoht) [reply lte/gateway/c/core/oai/include/map.h:175]: That's a good callout @ulaskozat, I think these can be removed following the expectation that the hashtables should be only used by its owner state thread. Given that we will iteratively will migrate these hashtables, we can follow that expectation during the process of the migration. @shashidhar-patil Let's remove the locking and update the name of the struct accordingly.

Comment (ardzoht) [reply lte/gateway/c/core/oai/include/map.h]: That's a good callout @ulaskozat, I think these can be removed following the expectation that the hashtables should be only used by its owner state thread. Given that we will iteratively will migrate these hashtables, we can follow that expectation during the process of the migration. @shashidhar-patil Let's remove the locking and update the name of the struct accordingly.

**Comment by ardzoht** [comment]
@shashidhar-patil Please resolve conflicts and let's remove locking on the `map` struct since we don't require thread safety given thread ownership of each hashtable

File: lte/gateway/c/core/oai/include/map.h (hunk 11 above)
Comment (shashidhar-patil) [reply lte/gateway/c/core/oai/include/map.h]: @ardzoht Okay will do that.

Comment (shashidhar-patil) [reply lte/gateway/c/core/oai/include/map.h]: Addressed this comment in the newest commit.

**Comment by shashidhar-patil** [comment]
@ardzoht removed locking on the map struct and resolved merge conflicts.

Logs: (Dated: 22/11/21)
[mme.log](https://github.com/magma/magma/files/7581597/mme.log)

Snap pcap: (Dated: 22/11/21)
mapLock

**Review by ardzoht — APPROVED** [review]
lgtm
