### PR TITLE
fix: Pass command through shell

### LINKED ISSUE #14341: Blocker for Bazel switch-over support
Collection for issues with the switch-over that should be fixed on-the-fly.

### LINKED ISSUE #14399: Fix errors in Bazel Bash completion generation
Since #14361 when destroying and re-provisioning the machine, several developers reported receiving errors like
```
Welcome to Ubuntu 20.04.5 LTS (GNU/Linux 5.4.0-128-generic x86_64)

 * Documentation:  https://help.ubuntu.com/
 * Management:     https://landscape.canonical.com/
 * Support:        https://ubuntu.com/advantage
-bash: 404:: command not found
```

And the completion file looks like this:
```
vagrant@magma-dev:~$ head ~/.bash_completion.d/bazel-complete.bash 
404: Not Found404: Not FoundBAZEL_COMMAND_LIST="analyze-profile aquery build canonicalize-flags clean config coverage cquery dump fetch help info license mobile-install print_action query run shutdown sync test version"
BAZEL_INFO_KEYS="
workspace
```

So it seems curl receives a 404 and writes that to the completion file.

### PR DESCRIPTION
**Pull request by jheidbrink**
## Summary

The parameters passed to the completion generation script were wrong because they were not expanded by a shell as expected. This fixes it. Also the `.bashrc` was overwritten, this PR appends to `.bashrc` instead.

Fixes #14399 

## Test Plan

```
vagrant destroy magma_test
vagrant up magma_test
```
Verify that completions are working.

### CODE REVIEW

File: bazel/scripts/setup_bazel_bash_completion.sh [hunk 1]
```diff
@@ -49,7 +49,7 @@ fi
 if ! grep --quiet bazel-complete.bash ~/.bashrc
 then
   log "Adapting ~/.bashrc to source completion script"
-  echo "source ~/.bash_completion.d/bazel-complete.bash" > ~/.bashrc
```
Comment (sebathomas) [inline bazel/scripts/setup_bazel_bash_completion.sh:52]: :grimacing:

**Review by sebathomas — APPROVED** [review]

**Review by LKreutzer — APPROVED** [review]
