### PR TITLE
fix(mme): Improving OAI-Logging for NAS/ESM layer.

### LINKED ISSUE #6396: [lte] Increase OAI IMSI logging on MME entities (emm, esm) gaps
### Description

Currently, MME makes use of macros to log each procedure on the tasks. For some of these procedures, we log information about the UE being processed, with information about the subscriber relevant to the MME service. For better tracing, we added macros that accept IMSI in `uint64` version so it's added as a prefix to each log line, however there are many gaps, particularly on `emm` and `esm` entities functions that don't have the IMSI information, making difficult to know which is the UE being processed. 

### Examples

Here is an example of `Authentication.c` procedure usage of OAI log macros, *without* IMSI prefix: https://github.com/magma/magma/blob/master/lte/gateway/c/core/oai/tasks/nas/emm/Authentication.c#L163-L167

Here is an example of `sgw_handlers.c` procedure usage of OAI log macros, *with* IMSI prefix: 
https://github.com/magma/magma/blob/master/lte/gateway/c/core/oai/tasks/sgw/sgw_handlers.c#L118-L121

### Code pointers of logging gaps

A good starting point to cover these gaps is any file under these directories:

- https://github.com/magma/magma/tree/master/lte/gateway/c/core/oai/tasks/nas/emm
- https://github.com/magma/magma/tree/master/lte/gateway/c/core/oai/tasks/nas/esm

For any questions, feel free to contact POC @ardzoht or @ulaskozat

### PR DESCRIPTION
**Pull request by Vyas20**
fix(mme): Improving OAI-Logging for NAS/ESM layer.

Adding an imsi_64 prefix in the existing NAS/ESM layer for better logging.

This addition is tested with S1AP-Tester and dstester.

### CODE REVIEW

File: lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr_context.c [hunk 1]
```diff
@@ -86,20 +86,21 @@ ebi_t esm_ebr_context_create(
...
       "for PDN connection (pid=%d) for ue_id " MME_UE_S1AP_ID_FMT "\n",
       (is_default) ? "default" : "dedicated", ebi, pid,
       ue_mm_context->mme_ue_s1ap_id);
 
   if (pid < MAX_APN_PER_UE) {
     if (ue_mm_context->pdn_contexts[pid] == NULL) {
-      OAILOG_ERROR(
-          LOG_NAS_ESM,
+      OAILOG_ERROR_UE(
+          LOG_NAS_ESM, ue_mm_context->emm_context._imsi64,
```
Comment (lionelgo) [inline lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr_context.c]: why not using parameter emm_context directly ?

File: lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr_context.c [hunk 2]
```diff
@@ -108,8 +109,8 @@ ebi_t esm_ebr_context_create(
      * Check the total number of active EPS bearers
      */
     else if (esm_ctx->n_active_ebrs > BEARERS_PER_UE) {
-      OAILOG_WARNING(
-          LOG_NAS_ESM,
+      OAILOG_WARNING_UE(
+          LOG_NAS_ESM, ue_mm_context->emm_context._imsi64,
```
Comment (lionelgo) [inline lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr_context.c]: why not using parameter emm_context directly ?

File: lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr_context.c [hunk 3]
```diff
@@ -124,8 +125,8 @@ ebi_t esm_ebr_context_create(
       if ((ue_mm_context->bearer_contexts[bidx]) &&
           (ESM_EBR_INACTIVE !=
            ue_mm_context->bearer_contexts[bidx]->esm_ebr_context.status)) {
-        OAILOG_WARNING(
-            LOG_NAS_ESM,
+        OAILOG_WARNING_UE(
+            LOG_NAS_ESM, ue_mm_context->emm_context._imsi64,
```
Comment (lionelgo) [inline lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr_context.c]: Same comment

File: lte/gateway/c/core/oai/tasks/nas/esm/esm_information.c [hunk 4]
```diff
@@ -183,8 +184,8 @@ status_code_e mme_app_handle_esm_information_t3489_expiry(
   struct ue_mm_context_s* ue_context_p = mme_app_get_ue_context_for_timer(
       mme_ue_s1ap_id, "Deactivate EPS Bearer Ctx Request T3489 Timer");
   if (ue_context_p == NULL) {
-    OAILOG_ERROR(
-        LOG_MME_APP,
+    OAILOG_ERROR_UE(
+        LOG_MME_APP, ue_context_p->emm_context._imsi64,
```
Comment (lionelgo) [inline lte/gateway/c/core/oai/tasks/nas/esm/esm_information.c]: if ue_context_p is null we cannot use it

File: lte/gateway/c/core/oai/tasks/nas/esm/esm_information.c [hunk 5]
```diff
@@ -202,8 +203,8 @@ status_code_e mme_app_handle_esm_information_t3489_expiry(
      * Increment the retransmission counter
      */
     esm_ebr_timer_data->count += 1;
-    OAILOG_WARNING(
-        LOG_NAS_ESM,
+    OAILOG_WARNING_UE(
+        LOG_NAS_ESM, ue_context_p->emm_context._imsi64,
```
Comment (lionelgo) [inline lte/gateway/c/core/oai/tasks/nas/esm/esm_information.c]: emm_context_p ?

File: lte/gateway/c/core/oai/tasks/nas/nas_proc.c [hunk 6]
```diff
@@ -358,14 +359,15 @@ status_code_e nas_proc_authentication_info_answer(
   }
 
   if (!(emm_ctxt_p)) {
-    OAILOG_ERROR(
-        LOG_NAS_EMM, "That's embarrassing as we don't know this IMSI\n");
+    OAILOG_ERROR_UE(
+        LOG_NAS_EMM, emm_ctxt_p->_imsi64,
+        "That's embarrassing as we don't know this IMSI\n");
```
Comment (lionelgo) [inline lte/gateway/c/core/oai/tasks/nas/nas_proc.c:364]: if emm_ctxt_p is null, you cannot access it

File: lte/gateway/c/core/oai/tasks/nas/nas_proc.c [hunk 7]
```diff
@@ -358,14 +359,15 @@ status_code_e nas_proc_authentication_info_answer(
...
     OAILOG_FUNC_RETURN(LOG_NAS_EMM, RETURNerror);
   }
 
   mme_ue_s1ap_id_t mme_ue_s1ap_id = ue_mm_context_p->mme_ue_s1ap_id;
-  OAILOG_INFO(
-      LOG_NAS_EMM,
+  OAILOG_INFO_UE(
+      LOG_NAS_EMM, ue_mm_context_p->emm_context._imsi64,
```
Comment (lionelgo) [inline lte/gateway/c/core/oai/tasks/nas/nas_proc.c]: you can use emm_ctxt_p

File: lte/gateway/c/core/oai/tasks/nas/nas_proc.c [hunk 8]
```diff
@@ -381,31 +383,34 @@ status_code_e nas_proc_authentication_info_answer(
...
+        LOG_NAS_EMM, imsi64,
+        "INFORMING NAS ABOUT AUTH RESP SUCCESS got %u vector(s)\n",
         aia->auth_info.nb_of_vectors);
     rc = nas_proc_auth_param_res(
         mme_ue_s1ap_id, aia->auth_info.nb_of_vectors,
         aia->auth_info.eutran_vector);
   } else {
-    OAILOG_ERROR(LOG_NAS_EMM, "INFORMING NAS ABOUT AUTH RESP ERROR CODE\n");
+    OAILOG_ERROR_UE(
+        LOG_NAS_EMM, (uint64_t*) aia->imsi,
```
Comment (lionelgo) [inline lte/gateway/c/core/oai/tasks/nas/nas_proc.c]: why don't you use imsi64 ?

File: lte/gateway/c/core/oai/tasks/nas/nas_proc.c [hunk 9]
```diff
@@ -381,31 +383,34 @@ status_code_e nas_proc_authentication_info_answer(
...
         "ue_attach", 1, 2, "result", "failure", "cause",
         "auth_info_failure_from_hss");
     /*
      * Inform NAS layer with the right failure
      */
     if (aia->result.present == S6A_RESULT_BASE) {
-      OAILOG_ERROR(
-          LOG_NAS_EMM,
+      OAILOG_ERROR_UE(
+          LOG_NAS_EMM, aia->imsi,
```
Comment (lionelgo) [inline lte/gateway/c/core/oai/tasks/nas/nas_proc.c]: imsi64 ?

File: lte/gateway/c/core/oai/tasks/nas/nas_proc.c [hunk 10]
```diff
@@ -381,31 +383,34 @@ status_code_e nas_proc_authentication_info_answer(
...
           "Auth info Rsp failure for imsi " IMSI_64_FMT
           ", base_error_code %d \n",
           imsi64, aia->result.choice.base);
```
Comment (lionelgo) [inline lte/gateway/c/core/oai/tasks/nas/nas_proc.c]: redundant print of imsi

File: lte/gateway/c/core/oai/tasks/nas/nas_proc.c [hunk 11]
```diff
@@ -578,13 +583,15 @@ status_code_e nas_proc_downlink_unitdata(
...
+  OAILOG_DEBUG_UE(
+      LOG_NAS_EMM, ctxt->_imsi64, "Handling imsi " IMSI_64_FMT "\n", imsi64);
 
   ctxt = emm_context_get_by_imsi(&_emm_data, imsi64);
 
   if (!(ctxt)) {
-    OAILOG_ERROR(
-        LOG_NAS_EMM, "That's embarrassing as we don't know this IMSI\n");
+    OAILOG_ERROR_UE(
+        LOG_NAS_EMM, ctxt->_imsi64,
```
Comment (lionelgo) [inline lte/gateway/c/core/oai/tasks/nas/nas_proc.c]: you cannot use ctxt, you can replace ctxt->_imsi64 with imsi64

File: lte/gateway/c/core/oai/tasks/nas/esm/sap/esm_recv.c [hunk 12]
```diff
@@ -487,8 +489,8 @@ esm_cause_t esm_recv_pdn_disconnect_request(
               ->bearer_contexts[EBI_TO_INDEX(msg->linkedepsbeareridentity)]
               ->pdn_cx_id;
     if (pid >= MAX_APN_PER_UE) {
-      OAILOG_ERROR(
-          LOG_NAS_ESM,
+      OAILOG_ERROR_UE(
+          LOG_NAS_ESM, ue_mm_context_p->emm_context._imsi64,
```
Comment (lionelgo) [inline lte/gateway/c/core/oai/tasks/nas/esm/sap/esm_recv.c]: you can use emm_context

File: lte/gateway/c/core/oai/tasks/nas/esm/sap/esm_recv.c [hunk 13]
```diff
@@ -507,26 +509,26 @@ esm_cause_t esm_recv_pdn_disconnect_request(
     // Check if the LBI received matches with the default bearer ID
     if (msg->linkedepsbeareridentity !=
         ue_mm_context_p->pdn_contexts[pid]->default_ebi) {
-      OAILOG_ERROR(
-          LOG_NAS_ESM,
+      OAILOG_ERROR_UE(
+          LOG_NAS_ESM, ue_mm_context_p->emm_context._imsi64,
```
Comment (lionelgo) [inline lte/gateway/c/core/oai/tasks/nas/esm/sap/esm_recv.c]: you can use emm_context

**Review by lionelgo — CHANGES_REQUESTED** [review]

File: lte/gateway/c/core/oai/tasks/nas/esm/esm_information.c (hunk 4 above)
Comment (ardzoht) [reply lte/gateway/c/core/oai/tasks/nas/esm/esm_information.c]: +1 on this, this will end up as a Segfault

File: lte/gateway/c/core/oai/tasks/nas/nas_proc.c (hunk 11 above)
Comment (ardzoht) [reply lte/gateway/c/core/oai/tasks/nas/nas_proc.c]: @Vyas20 if imsi64 is available let's use that instead of accessing the ctxt as Lionel states

**Review by ardzoht — CHANGES_REQUESTED** [review]
Please resolve @lionelgo comments, also if the given UE context is null, we won't be available to access its imsi64, let's remove those

File: lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr_context.c (hunk 1 above)
Comment (Vyas20) [reply lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr_context.c]: Resolved

File: lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr_context.c (hunk 2 above)
Comment (Vyas20) [reply lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr_context.c]: Resolved

File: lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr_context.c (hunk 3 above)
Comment (Vyas20) [reply lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr_context.c]: Resolved

File: lte/gateway/c/core/oai/tasks/nas/esm/esm_information.c (hunk 4 above)
Comment (Vyas20) [reply lte/gateway/c/core/oai/tasks/nas/esm/esm_information.c]: Resolved

File: lte/gateway/c/core/oai/tasks/nas/esm/esm_information.c (hunk 5 above)
Comment (Vyas20) [reply lte/gateway/c/core/oai/tasks/nas/esm/esm_information.c]: Resolved

File: lte/gateway/c/core/oai/tasks/nas/nas_proc.c (hunk 6 above)
Comment (Vyas20) [reply lte/gateway/c/core/oai/tasks/nas/nas_proc.c:364]: Resolved

File: lte/gateway/c/core/oai/tasks/nas/nas_proc.c (hunk 7 above)
Comment (Vyas20) [reply lte/gateway/c/core/oai/tasks/nas/nas_proc.c]: Resolved

File: lte/gateway/c/core/oai/tasks/nas/nas_proc.c (hunk 8 above)
Comment (Vyas20) [reply lte/gateway/c/core/oai/tasks/nas/nas_proc.c]: Resolved

File: lte/gateway/c/core/oai/tasks/nas/nas_proc.c (hunk 9 above)
Comment (Vyas20) [reply lte/gateway/c/core/oai/tasks/nas/nas_proc.c]: Resolved

File: lte/gateway/c/core/oai/tasks/nas/nas_proc.c (hunk 10 above)
Comment (Vyas20) [reply lte/gateway/c/core/oai/tasks/nas/nas_proc.c]: Resolved

File: lte/gateway/c/core/oai/tasks/nas/nas_proc.c (hunk 11 above)
Comment (Vyas20) [reply lte/gateway/c/core/oai/tasks/nas/nas_proc.c]: Resolved

File: lte/gateway/c/core/oai/tasks/nas/esm/sap/esm_recv.c (hunk 12 above)
Comment (Vyas20) [reply lte/gateway/c/core/oai/tasks/nas/esm/sap/esm_recv.c]: Resolved

File: lte/gateway/c/core/oai/tasks/nas/esm/sap/esm_recv.c (hunk 13 above)
Comment (Vyas20) [reply lte/gateway/c/core/oai/tasks/nas/esm/sap/esm_recv.c]: Resolved

File: lte/gateway/c/core/oai/tasks/nas/esm/DedicatedEpsBearerContextActivation.c [hunk 14]
```diff
@@ -427,8 +427,8 @@ status_code_e dedicated_eps_bearer_activate_t3485_handler(
   ue_mm_context_t* ue_mm_context = mme_app_get_ue_context_for_timer(
       ue_id, "EPS BEARER DEACTIVATE T3495 Timer");
   if (ue_mm_context == NULL) {
-    OAILOG_ERROR(
-        LOG_MME_APP,
+    OAILOG_ERROR_UE(
```
Comment (ardzoht) [inline lte/gateway/c/core/oai/tasks/nas/esm/DedicatedEpsBearerContextActivation.c]: this won't work since `ue_mm_context` is null, let's keep it as before

File: lte/gateway/c/core/oai/tasks/nas/esm/DefaultEpsBearerContextActivation.c [hunk 15]
```diff
@@ -357,8 +358,8 @@ status_code_e esm_proc_default_eps_bearer_context_reject(
     ue_mm_context_t* ue_context_p =
         PARENT_STRUCT(emm_context, struct ue_mm_context_s, emm_context);
     if (!ue_context_p) {
-      OAILOG_ERROR(
-          LOG_NAS_ESM,
+      OAILOG_ERROR_UE(
```
Comment (ardzoht) [inline lte/gateway/c/core/oai/tasks/nas/esm/DefaultEpsBearerContextActivation.c]: this will also complain since there is no `ue_context_p` retrieved, let's not change this

File: lte/gateway/c/core/oai/tasks/nas/esm/DefaultEpsBearerContextActivation.c [hunk 16]
```diff
@@ -415,14 +416,14 @@ status_code_e esm_proc_default_eps_bearer_context_failure(
...
-        LOG_NAS_ESM,
+    OAILOG_WARNING_UE(
+        LOG_NAS_ESM, emm_context->_imsi64,
         "ESM-PROC  - Default EPS bearer context activation "
         "failure (ue_id=" MME_UE_S1AP_ID_FMT ")\n",
         ue_id);
   } else {
-    OAILOG_WARNING(
-        LOG_NAS_ESM,
+    OAILOG_WARNING_UE(
```
Comment (ardzoht) [inline lte/gateway/c/core/oai/tasks/nas/esm/DefaultEpsBearerContextActivation.c]: `emm_context` does not exist in this else case, let's not change this

File: lte/gateway/c/core/oai/tasks/nas/esm/DefaultEpsBearerContextActivation.c [hunk 17]
```diff
@@ -495,8 +496,8 @@ status_code_e default_eps_bearer_activate_t3485_handler(
   ue_mm_context_t* ue_mm_context = mme_app_get_ue_context_for_timer(
       ue_id, "EPS BEARER DEACTIVATE T3495 Timer");
   if (ue_mm_context == NULL) {
-    OAILOG_ERROR(
-        LOG_MME_APP,
+    OAILOG_ERROR_UE(
+        LOG_MME_APP, ue_mm_context->emm_context._imsi64,
```
Comment (ardzoht) [inline lte/gateway/c/core/oai/tasks/nas/esm/DefaultEpsBearerContextActivation.c]: emm_context does not exist in this case, let's not change this

File: lte/gateway/c/core/oai/tasks/nas/esm/EpsBearerContextDeactivation.c [hunk 18]
```diff
@@ -417,8 +417,8 @@ status_code_e eps_bearer_deactivate_t3495_handler(
   ue_mm_context_t* ue_mm_context = mme_app_get_ue_context_for_timer(
       ue_id, "EPS BEARER DEACTIVATE T3495 Timer");
   if (ue_mm_context == NULL) {
-    OAILOG_ERROR(
-        LOG_MME_APP,
+    OAILOG_ERROR_UE(
+        LOG_MME_APP, ue_mm_context->emm_context._imsi64,
```
Comment (ardzoht) [inline lte/gateway/c/core/oai/tasks/nas/esm/EpsBearerContextDeactivation.c]: ue_mm_context does not exist in this case, let's not change this

File: lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr.c [hunk 19]
```diff
@@ -261,7 +261,9 @@ status_code_e esm_ebr_start_timer(
   ue_mm_context_t* ue_mm_context =
       PARENT_STRUCT(emm_context, struct ue_mm_context_s, emm_context);
   if (ue_mm_context == NULL) {
-    OAILOG_ERROR(LOG_NAS_ESM, "ESM-FSM   - ue mme context null..\n");
+    OAILOG_ERROR_UE(
```
Comment (ardzoht) [inline lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr.c]: ue_mm_context does not exist in this case, let's not change this

File: lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr.c [hunk 20]
```diff
@@ -486,21 +488,25 @@ status_code_e esm_ebr_set_status(
   OAILOG_FUNC_IN(LOG_NAS_ESM);
 
   if (emm_context == NULL) {
-    OAILOG_ERROR(LOG_NAS_ESM, "ESM-FSM   - emm context null... \n");
+    OAILOG_ERROR_UE(
```
Comment (ardzoht) [inline lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr.c]: emm_context does not exist in this case, let's not change this

File: lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr.c [hunk 21]
```diff
@@ -486,21 +488,25 @@ status_code_e esm_ebr_set_status(
...
+        LOG_NAS_ESM, emm_context->_imsi64,
         "ESM-FSM   - Invalid EPS bearer identity range ebi= (%d) \n", ebi);
     OAILOG_FUNC_RETURN(LOG_NAS_ESM, RETURNerror);
   }
 
   ue_mm_context_t* ue_mm_context =
       PARENT_STRUCT(emm_context, struct ue_mm_context_s, emm_context);
   if (ue_mm_context == NULL) {
-    OAILOG_ERROR(LOG_NAS_ESM, "ESM-FSM   - ue mme context null... \n");
+    OAILOG_ERROR_UE(
```
Comment (ardzoht) [inline lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr.c]: ue_mm_context does not exist in this case, let's not change this

File: lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr_context.c [hunk 22]
```diff
@@ -86,20 +86,21 @@ ebi_t esm_ebr_context_create(
   ue_mm_context_t* ue_mm_context =
       PARENT_STRUCT(emm_context, struct ue_mm_context_s, emm_context);
   if (ue_mm_context == NULL) {
-    OAILOG_ERROR(LOG_NAS_ESM, "ESM-PROC  - ue_mm_context null\n ");
+    OAILOG_ERROR_UE(
```
Comment (ardzoht) [inline lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr_context.c]: ue_mm_context does not exist in this case, let's not change this

File: lte/gateway/c/core/oai/tasks/nas/esm/sap/esm_recv.c [hunk 23]
```diff
@@ -431,13 +431,14 @@ esm_cause_t esm_recv_pdn_disconnect_request(
       PARENT_STRUCT(emm_context, struct ue_mm_context_s, emm_context);
 
   if (!ue_mm_context_p) {
-    OAILOG_WARNING(
-        LOG_NAS_ESM, "Failed to find ue context from emm context \n");
+    OAILOG_WARNING_UE(
```
Comment (ardzoht) [inline lte/gateway/c/core/oai/tasks/nas/esm/sap/esm_recv.c]: ue_mm_context does not exist in this case, let's not change this

File: lte/gateway/c/core/oai/tasks/nas/esm/sap/esm_recv.c [hunk 24]
```diff
@@ -646,8 +650,8 @@ status_code_e erab_setup_rsp_tmr_exp_handler(
   ue_mm_context_t* ue_mm_context = mme_app_get_ue_context_for_timer(
       ue_id, "EPS BEARER DEACTIVATE T3495 Timer");
   if (ue_mm_context == NULL) {
-    OAILOG_ERROR(
-        LOG_MME_APP,
+    OAILOG_ERROR_UE(
```
Comment (ardzoht) [inline lte/gateway/c/core/oai/tasks/nas/esm/sap/esm_recv.c]: ue_mm_context does not exist in this case, let's not change this

File: lte/gateway/c/core/oai/tasks/nas/nas_proc.c [hunk 25]
```diff
@@ -892,8 +898,9 @@ status_code_e nas_proc_pdn_disconnect_rsp(
   int rc            = RETURNerror;
   emm_sap_t emm_sap = {0};
 
-  OAILOG_DEBUG(
-      LOG_NAS_EMM, "Received pdn_disconnect_rsp for ue id %u\n",
+  OAILOG_DEBUG_UE(
+      LOG_NAS_EMM, emm_sap.u.emm_esm.ctx->_imsi64,
```
Comment (ardzoht) [inline lte/gateway/c/core/oai/tasks/nas/nas_proc.c]: This will always be invalid (since `emm_sap` its being allocated here), let's not change this one

**Review by ardzoht — CHANGES_REQUESTED** [review]

File: lte/gateway/c/core/oai/tasks/nas/esm/EpsBearerContextDeactivation.c (hunk 18 above)
Comment (Vyas20) [reply lte/gateway/c/core/oai/tasks/nas/esm/EpsBearerContextDeactivation.c]: Resolved

File: lte/gateway/c/core/oai/tasks/nas/esm/DefaultEpsBearerContextActivation.c (hunk 17 above)
Comment (Vyas20) [reply lte/gateway/c/core/oai/tasks/nas/esm/DefaultEpsBearerContextActivation.c]: Resolved

File: lte/gateway/c/core/oai/tasks/nas/esm/DefaultEpsBearerContextActivation.c (hunk 16 above)
Comment (Vyas20) [reply lte/gateway/c/core/oai/tasks/nas/esm/DefaultEpsBearerContextActivation.c]: Resolved

File: lte/gateway/c/core/oai/tasks/nas/esm/DefaultEpsBearerContextActivation.c (hunk 15 above)
Comment (Vyas20) [reply lte/gateway/c/core/oai/tasks/nas/esm/DefaultEpsBearerContextActivation.c]: Resolved

File: lte/gateway/c/core/oai/tasks/nas/esm/DedicatedEpsBearerContextActivation.c (hunk 14 above)
Comment (Vyas20) [reply lte/gateway/c/core/oai/tasks/nas/esm/DedicatedEpsBearerContextActivation.c]: Resolved

File: lte/gateway/c/core/oai/tasks/nas/esm/DefaultEpsBearerContextActivation.c (hunk 15 above)
Comment (Vyas20) [reply lte/gateway/c/core/oai/tasks/nas/esm/DefaultEpsBearerContextActivation.c]: Resolved

File: lte/gateway/c/core/oai/tasks/nas/esm/DefaultEpsBearerContextActivation.c (hunk 16 above)
Comment (Vyas20) [reply lte/gateway/c/core/oai/tasks/nas/esm/DefaultEpsBearerContextActivation.c]: Resolved

File: lte/gateway/c/core/oai/tasks/nas/esm/DefaultEpsBearerContextActivation.c (hunk 17 above)
Comment (Vyas20) [reply lte/gateway/c/core/oai/tasks/nas/esm/DefaultEpsBearerContextActivation.c]: Resolved

File: lte/gateway/c/core/oai/tasks/nas/esm/EpsBearerContextDeactivation.c (hunk 18 above)
Comment (Vyas20) [reply lte/gateway/c/core/oai/tasks/nas/esm/EpsBearerContextDeactivation.c]: Resolved

File: lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr.c (hunk 19 above)
Comment (Vyas20) [reply lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr.c]: Resolved

File: lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr.c (hunk 20 above)
Comment (Vyas20) [reply lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr.c]: Resolved

File: lte/gateway/c/core/oai/tasks/nas/nas_proc.c (hunk 25 above)
Comment (Vyas20) [reply lte/gateway/c/core/oai/tasks/nas/nas_proc.c]: Resolved

File: lte/gateway/c/core/oai/tasks/nas/esm/sap/esm_recv.c (hunk 23 above)
Comment (Vyas20) [reply lte/gateway/c/core/oai/tasks/nas/esm/sap/esm_recv.c]: Resolved

File: lte/gateway/c/core/oai/tasks/nas/esm/sap/esm_recv.c (hunk 24 above)
Comment (Vyas20) [reply lte/gateway/c/core/oai/tasks/nas/esm/sap/esm_recv.c]: Resolved

File: lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr_context.c (hunk 22 above)
Comment (Vyas20) [reply lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr_context.c]: Resolved

File: lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr.c (hunk 21 above)
Comment (Vyas20) [reply lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr.c]: Resolved

File: lte/gateway/c/core/oai/tasks/nas/nas_proc.c [hunk 26]
```diff
@@ -358,14 +359,15 @@ status_code_e nas_proc_authentication_info_answer(
   }
 
   if (!(emm_ctxt_p)) {
-    OAILOG_ERROR(
-        LOG_NAS_EMM, "That's embarrassing as we don't know this IMSI\n");
+    OAILOG_ERROR_UE(
+        imsi64, LOG_NAS_EMM,
```
Comment (ardzoht) [inline lte/gateway/c/core/oai/tasks/nas/nas_proc.c]: this imsi64 value will always be 0, as emm_ctxt_p is null, please update

File: lte/gateway/c/core/oai/tasks/nas/nas_proc.c [hunk 27]
```diff
@@ -578,13 +582,15 @@ status_code_e nas_proc_downlink_unitdata(
...
+  OAILOG_DEBUG_UE(
+      LOG_NAS_EMM, ctxt->_imsi64, "Handling imsi " IMSI_64_FMT "\n", imsi64);
 
   ctxt = emm_context_get_by_imsi(&_emm_data, imsi64);
 
   if (!(ctxt)) {
-    OAILOG_ERROR(
-        LOG_NAS_EMM, "That's embarrassing as we don't know this IMSI\n");
+    OAILOG_ERROR_UE(
+        LOG_NAS_EMM, imsi64,
```
Comment (ardzoht) [inline lte/gateway/c/core/oai/tasks/nas/nas_proc.c]: same comment as above, please update

**Review by ardzoht — CHANGES_REQUESTED** [review]
left 2 more comments, please update and I'll accept the PR, thanks!

File: lte/gateway/c/core/oai/tasks/nas/nas_proc.c (hunk 27 above)
Comment (Vyas20) [reply lte/gateway/c/core/oai/tasks/nas/nas_proc.c]: Resolved

File: lte/gateway/c/core/oai/tasks/nas/nas_proc.c (hunk 26 above)
Comment (Vyas20) [reply lte/gateway/c/core/oai/tasks/nas/nas_proc.c]: Here I was trying to print the value of imsi64 from line 343 and not from emm_ctxt_p

**Review by ardzoht — DISMISSED** [review]
lgtm

File: lte/gateway/c/core/oai/tasks/nas/esm/DefaultEpsBearerContextActivation.c [hunk 28]
```diff
@@ -140,8 +141,8 @@ status_code_e esm_proc_default_eps_bearer_context(
     OAILOG_FUNC_RETURN(LOG_NAS_ESM, RETURNok);
   }
 
-  OAILOG_ERROR(
-      LOG_NAS_ESM,
+  OAILOG_ERROR_UE(
+      LOG_NAS_ESM, emm_context->_imsi64,
       "ESM-PROC  - Failed to assign new EPS bearer context for "
```
Comment (lionelgo) [inline lte/gateway/c/core/oai/tasks/nas/esm/DefaultEpsBearerContextActivation.c]: May be we could log also the cause here

File: lte/gateway/c/core/oai/tasks/nas/esm/EpsBearerContextDeactivation.c [hunk 29]
```diff
@@ -431,8 +431,8 @@ status_code_e eps_bearer_deactivate_t3495_handler(
 
   bearer_context_t* bearer_context = ue_mm_context->bearer_contexts[bid];
   if (bearer_context == NULL) {
-    OAILOG_ERROR_UE(
-        LOG_NAS_ESM, ue_mm_context->emm_context._imsi64,
+    OAILOG_ERROR(
+        LOG_NAS_ESM,
```
Comment (lionelgo) [inline lte/gateway/c/core/oai/tasks/nas/esm/EpsBearerContextDeactivation.c]: I miss why you can't use imsi64 here

File: lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr.c [hunk 30]
```diff
@@ -321,8 +321,8 @@ status_code_e esm_ebr_start_timer(
   }
 
   if ((esm_ebr_timer_data) && (ebr_ctx->timer.id != NAS_TIMER_INACTIVE_ID)) {
-    OAILOG_INFO(
-        LOG_NAS_ESM,
+    OAILOG_INFO_UE(
+        LOG_NAS_ESM, ue_mm_context->emm_context._imsi64,
```
Comment (lionelgo) [inline lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr.c]: you can use emm_context instead of ue_mm_context

File: lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr.c [hunk 31]
```diff
@@ -383,8 +383,8 @@ status_code_e esm_ebr_stop_timer(emm_context_t* emm_context, ebi_t ebi) {
    * Stop the retransmission timer if still running
    */
   if (ebr_ctx->timer.id != NAS_TIMER_INACTIVE_ID || ebr_ctx->args) {
-    OAILOG_INFO(
-        LOG_NAS_ESM,
+    OAILOG_INFO_UE(
+        LOG_NAS_ESM,ue_mm_context->emm_context._imsi64,
```
Comment (lionelgo) [inline lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr.c]: same comment as above.
missing space after comma says Mr GH.

File: lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr.c [hunk 32]
```diff
@@ -523,17 +523,17 @@ status_code_e esm_ebr_set_status(
 
   if (status < ESM_EBR_STATE_MAX) {
     if (status != old_status) {
-      OAILOG_INFO(
-          LOG_NAS_ESM,
+      OAILOG_INFO_UE(
+          LOG_NAS_ESM, ue_mm_context->emm_context._imsi64,
```
Comment (lionelgo) [inline lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr.c]: you can use emm_context->_imsi64 directly ?

File: lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr.c [hunk 33]
```diff
@@ -523,17 +523,17 @@ status_code_e esm_ebr_set_status(
...
           ebi, esm_ebr_state_str[old_status], esm_ebr_state_str[status],
           ue_mm_context->mme_ue_s1ap_id);
       ebr_ctx->status = status;
       OAILOG_FUNC_RETURN(LOG_NAS_ESM, RETURNok);
     } else {
-      OAILOG_INFO(
-          LOG_NAS_ESM,
+      OAILOG_INFO_UE(
+          LOG_NAS_ESM, ue_mm_context->emm_context._imsi64,
           "ESM-FSM   - Status of EPS bearer context %d unchanged:"
```
Comment (lionelgo) [inline lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr.c:537]: Same comment as above.

File: lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr_context.c [hunk 34]
```diff
@@ -202,8 +202,8 @@ ebi_t esm_ebr_context_create(
           LOG_NAS_ESM, ue_mm_context->pdn_contexts[pid]->default_ebi);
     }
 
-    OAILOG_WARNING(
-        LOG_NAS_ESM,
+    OAILOG_WARNING_UE(
+        LOG_NAS_ESM, ue_mm_context->emm_context._imsi64,
```
Comment (lionelgo) [inline lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr_context.c]: emm_context->_imsi64 ?

File: lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr_context.c [hunk 35]
```diff
@@ -295,8 +295,8 @@ ebi_t esm_ebr_context_release(
      */
     if (*pid < MAX_APN_PER_UE) {
       if (!ue_mm_context->pdn_contexts[*pid]) {
-        OAILOG_ERROR(
-            LOG_NAS_ESM,
+        OAILOG_ERROR_UE(
+            LOG_NAS_ESM, ue_mm_context->emm_context._imsi64,
             "ESM-PROC  - PDN connection identifier %d "
```
Comment (lionelgo) [inline lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr_context.c:300]: emm_context->_imsi64 ?

File: lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr_context.c [hunk 36]
```diff
@@ -334,8 +334,8 @@ ebi_t esm_ebr_context_release(
       OAILOG_FUNC_RETURN(LOG_NAS_ESM, ESM_EBI_UNASSIGNED);
     }
 
-    OAILOG_INFO(
-        LOG_NAS_ESM,
+    OAILOG_INFO_UE(
+        LOG_NAS_ESM, ue_mm_context->emm_context._imsi64,
         "ESM-PROC  - Release EPS bearer context "
```
Comment (lionelgo) [inline lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr_context.c:339]: emm_context->_imsi64

File: lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr_context.c [hunk 37]
```diff
@@ -374,8 +374,8 @@ ebi_t esm_ebr_context_release(
        * * * * PDN, the UE shall delete all EPS bearer contexts associated to
        * * * * that PDN connection.
        */
-      OAILOG_INFO(
-          LOG_NAS_ESM,
+      OAILOG_INFO_UE(
+          LOG_NAS_ESM, ue_mm_context->emm_context._imsi64,
```
Comment (lionelgo) [inline lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr_context.c]: emm_context->_imsi64 ?

File: lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr_context.c [hunk 38]
```diff
@@ -397,8 +397,8 @@ ebi_t esm_ebr_context_release(
               ue_mm_context->pdn_contexts[*pid]->default_ebi) {
             continue;
           }
-          OAILOG_WARNING(
-              LOG_NAS_ESM,
+          OAILOG_WARNING_UE(
+              LOG_NAS_ESM, ue_mm_context->emm_context._imsi64,
```
Comment (lionelgo) [inline lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr_context.c]: emm_context->_imsi64 ?

File: lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr_context.c [hunk 39]
```diff
@@ -458,8 +458,8 @@ ebi_t esm_ebr_context_release(
 
       ue_mm_context->pdn_contexts[*pid]->is_active = false;
     } else {
-      OAILOG_INFO(
-          LOG_NAS_ESM,
+      OAILOG_INFO_UE(
+          LOG_NAS_ESM, ue_mm_context->emm_context._imsi64,
```
Comment (lionelgo) [inline lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr_context.c]: emm_context->_imsi64 ?

File: lte/gateway/c/core/oai/tasks/nas/esm/sap/esm_recv.c [hunk 40]
```diff
@@ -87,9 +87,9 @@ esm_cause_t esm_recv_status(
   int rc                = RETURNerror;
 
   OAILOG_FUNC_IN(LOG_NAS_ESM);
-  OAILOG_INFO(
-      LOG_NAS_ESM, "ESM-SAP   - Received ESM status message (pti=%d, ebi=%d)\n",
-      pti, ebi);
+  OAILOG_INFO_UE(
+      LOG_NAS_ESM, emm_context->_imsi64,
+      "ESM-SAP   - Received ESM status message (pti=%d, ebi=%d)\n", pti, ebi);
```
Comment (lionelgo) [inline lte/gateway/c/core/oai/tasks/nas/esm/sap/esm_recv.c:92]: checked that emm_context always not null.

File: lte/gateway/c/core/oai/tasks/nas/nas_proc.c [hunk 41]
```diff
@@ -358,14 +359,15 @@ status_code_e nas_proc_authentication_info_answer(
...
+        "That's embarrassing as we don't know this IMSI\n");
     OAILOG_FUNC_RETURN(LOG_NAS_EMM, RETURNerror);
   }
 
   mme_ue_s1ap_id_t mme_ue_s1ap_id = ue_mm_context_p->mme_ue_s1ap_id;
-  OAILOG_INFO(
-      LOG_NAS_EMM,
+  OAILOG_INFO_UE(
+      LOG_NAS_EMM, emm_ctxt_p->_imsi64,
       "Received Authentication Information Answer from S6A for"
```
Comment (lionelgo) [inline lte/gateway/c/core/oai/tasks/nas/nas_proc.c:371]: You can use same as imsi64 as bellow.

File: lte/gateway/c/core/oai/tasks/nas/nas_proc.c [hunk 42]
```diff
@@ -577,14 +581,14 @@ status_code_e nas_proc_downlink_unitdata(
   DevAssert(dl_unitdata);
 
   IMSI_STRING_TO_IMSI64(dl_unitdata->imsi, &imsi64);
-
-  OAILOG_DEBUG(LOG_NAS_EMM, "Handling imsi " IMSI_64_FMT "\n", imsi64);
-
   ctxt = emm_context_get_by_imsi(&_emm_data, imsi64);
+  OAILOG_DEBUG_UE(
+      LOG_NAS_EMM, ctxt->_imsi64, "Handling imsi " IMSI_64_FMT "\n", imsi64);
```
Comment (lionelgo) [inline lte/gateway/c/core/oai/tasks/nas/nas_proc.c:585]: ctxt can be null here.
You can move the log after testing ctxt.

**Review by lionelgo — CHANGES_REQUESTED** [review]

File: lte/gateway/c/core/oai/tasks/nas/esm/EpsBearerContextDeactivation.c (hunk 29 above)
Comment (ardzoht) [reply lte/gateway/c/core/oai/tasks/nas/esm/EpsBearerContextDeactivation.c]: @Vyas20 as lionel says we can use imsi64 here no need to update this

**Review by ardzoht — CHANGES_REQUESTED** [review]

File: lte/gateway/c/core/oai/tasks/nas/nas_proc.c (hunk 41 above)
Comment (Vyas20) [reply lte/gateway/c/core/oai/tasks/nas/nas_proc.c:371]: Resolved

File: lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr_context.c (hunk 39 above)
Comment (Vyas20) [reply lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr_context.c]: Resolved

File: lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr_context.c (hunk 38 above)
Comment (Vyas20) [reply lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr_context.c]: Resolved

File: lte/gateway/c/core/oai/tasks/nas/nas_proc.c [hunk 43]
```diff
@@ -358,14 +359,15 @@ status_code_e nas_proc_authentication_info_answer(
   }
 
   if (!(emm_ctxt_p)) {
-    OAILOG_ERROR(
-        LOG_NAS_EMM, "That's embarrassing as we don't know this IMSI\n");
+    OAILOG_ERROR_UE(
+         LOG_NAS_EMM,imsi64,
```
Comment (ardzoht) [inline lte/gateway/c/core/oai/tasks/nas/nas_proc.c]: missing comma here, you can run `make format_all` to fix this

**Review by ardzoht — APPROVED** [review]
lgtm, please run `make format_all` to fix formatting warnings

**Review by lionelgo — APPROVED** [review]

**Review by rdefosse — APPROVED** [review]
