### PR TITLE
[lte][agw] Accept eNB-initiated Reset from eNBs without UEs associated

### LINKED ISSUE #6779: [1.5] Support UE Context Release from Target eNB during handover
### Your Environment

- **Version:** Fuji/1.5
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** MME
- **Deployment Environment:** bare-metal (AGW)

### Describe the Issue

After an unsuccessful handover attempt, target eNB sends a UE context release request to the MME that is ignored with a log message `[0] UE_CONTEXT_RELEASE_REQUEST ignored, cause mismatch enb_ue_s1ap_id: ctxt 0x00001D != request 0x000031`. 

In this scenario the UE had not transitioned to the target eNB yet and the handover procedure had not completed. 

**Expected behavior**
Context Release request from target eNB should be handled gracefully and a context release command be sent back to the eNB.

See packet 41 in the pcap and line `011337` for corresponding log message in the attached logs. 

[Archive 3.zip](https://github.com/magma/magma/files/6431081/Archive.3.zip)

### LINKED ISSUE #6781: [1.5] S1AP Reset messages should be acknowledged by the MME
### Your Environment

- **Version:** 1.5
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** MME
- **Deployment Environment:**  bare-metal (AGW)

### Describe the Issue

Upon a unsuccessful handover attempt UE context in the target enb was not released (see #6779 ). 5 seconds after sending the context release request, the eNB sends a RESET message that is silently discarded by the MME citing `No UEs is connected.Ignoring ENB Initiated Reset.eNB Id = 13076` in the mme logs. 

Subsequent service requests / ics requests keeps failing because this particular eNB needs all previous s1ap contexts to be reset before proceeding to connect; instead eNB responds to all mme messaging with `ErrorIndication [RadioNetwork-cause-unknown-mme-ue-s1ap-id]`. 

**Expected behavior**
Acknowledge reset so UE is subsequently able to reconnect.

**Additional context**
See packet 44, 53, 55 and so on in the pcap attached and follow starting line `011358` in the attached mme log. 
[Archive 3.zip](https://github.com/magma/magma/files/6431101/Archive.3.zip)

### PR DESCRIPTION
**Pull request by shaddi**
## Summary

Accept eNB-initiated Reset procedures from eNBs, even when the MME isn't aware of any UEs associated with that eNB. This can happen during handover, or if the eNB has gotten into a bad state. Although this should not actually clean up any state on the MME, some eNodeBs seem to expect an acknowledgement and failing to send one prevents UEs from re-attaching. Closes #6781.

Signed-off-by: Shaddi Hasan <shasan@fb.com>

## Test Plan

Testing on CBRS testbed @ MPK
Integ tests

### CODE REVIEW

File: lte/gateway/c/oai/tasks/s1ap/s1ap_mme_handlers.c [hunk 1]
```diff
@@ -4124,12 +4124,13 @@ int s1ap_mme_handle_enb_reset(
   }
 
   if (enb_association->nb_ue_associated == 0) {
-    // ignore the message if there are no UEs connected
+    // Even if there are no UEs connected, we proceed -- this can happen if we
+    // receive a reset during a handover procedure, for example.
     OAILOG_INFO(
         LOG_S1AP,
-        "No UEs is connected.Ignoring ENB Initiated Reset.eNB Id = %d\n",
+        "No UEs connected, still proceding with ENB Initiated Reset.eNB Id = "
```
Comment (ulaskozat) [inline lte/gateway/c/oai/tasks/s1ap/s1ap_mme_handlers.c]: typo 'proceding'

Comment (ulaskozat) [reply lte/gateway/c/oai/tasks/s1ap/s1ap_mme_handlers.c]: add space after `.`.

**Review by ardzoht — APPROVED** [review]
lgtm

**Comment by ulaskozat** [comment]
@shaddi, @sudhikan  is this tested on CBRS testbed? @rsarwad I see a note has been removed that suggests that an error indication should be sent. Can you double check on the spec what needs to be done in this case?

**Comment by shaddi** [comment]
Yes, @sudhikan has tested this on the CBRS testbed. According to TS36.413, the Reset procedure can occur at any time and takes precedence over any other procedures. To my knowledge, the behavior of the MME when receiving a Reset for an unknown association is not defined. Specifically, 8.7.1.3 only defines abnormal conditions for Reset when certain IEs are missing from the reset message, which is not the case here, so I think ignoring the Reset (as we're currently doing) is actually violating the spec.

**Comment by rsarwad** [comment]
Hi @ulaskozat I agree with @shaddi As per 36.413 section 8.7.1.3 , On reception of Reset message at mme, even if no s1 signaling connection exists for the received eNB/MME s1ap id pair; mme needs send Reset ack with whatever UE-associated logical S1-connections are received in Reset message.
The TBD note has been existing from legacy OAI code

**Review by ulaskozat — APPROVED** [review]
LGTM
