### PR TITLE
[AGW] [MME] Clean up eNB state at restart to remove UEs without S1ap state

### LINKED ISSUE #5033: [Core][MME] segv in `s1ap_send_enb_deregistered_ind`
```
[New LWP 22866]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
bt
Core was generated by `/usr/local/bin/mme -c /var/opt/magma/tmp/mme.conf -s /var/opt/magma/tmp/spgw.co'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055ba9a4dbaed in s1ap_send_enb_deregistered_ind (keyP=<optimized out>, dataP=<optimized out>, argP=0x7f001d4bccc0, resultP=0x7f001d4bccb8) at /home/vagrant/magma/lte/gateway/c/oai/tasks/s1ap/s1ap_mme_handlers.c:2200
2200	/home/vagrant/magma/lte/gateway/c/oai/tasks/s1ap/s1ap_mme_handlers.c: No such file or directory.
[Current thread is 1 (Thread 0x7f001d4d8700 (LWP 22959))]
(gdb) bt
#0  0x000055ba9a4dbaed in s1ap_send_enb_deregistered_ind (keyP=<optimized out>, dataP=<optimized out>, argP=0x7f001d4bccc0, resultP=0x7f001d4bccb8) at /home/vagrant/magma/lte/gateway/c/oai/tasks/s1ap/s1ap_mme_handlers.c:2200
#1  0x000055ba9a912efe in hashtable_uint64_ts_apply_callback_on_elements (hashtblP=hashtblP@entry=0x616000014008, funct_cb=funct_cb@entry=0x55ba9a4db7d9 <s1ap_send_enb_deregistered_ind>, parameterP=parameterP@entry=0x7f001d4bccc0,
    resultP=resultP@entry=0x7f001d4bccb8) at /home/vagrant/magma/lte/gateway/c/oai/lib/hashtable/hashtable_uint64.c:507
#2  0x000055ba9a4de18a in s1ap_handle_sctp_disconnection (state=state@entry=0x60f00000b310, assoc_id=362, reset=<optimized out>) at /home/vagrant/magma/lte/gateway/c/oai/tasks/s1ap/s1ap_mme_handlers.c:2306
#3  0x000055ba9a493497 in handle_message (loop=<optimized out>, reader=<optimized out>, arg=<optimized out>) at /home/vagrant/magma/lte/gateway/c/oai/tasks/s1ap/s1ap_mme.c:158
#4  0x00007f00305fa7be in zloop_start () from /usr/lib/x86_64-linux-gnu/libczmq.so.4
#5  0x000055ba9a493201 in s1ap_mme_thread (args=<optimized out>) at /home/vagrant/magma/lte/gateway/c/oai/tasks/s1ap/s1ap_mme.c:319
#6  0x00007f0032dd94a4 in start_thread (arg=0x7f001d4d8700) at pthread_create.c:456
#7  0x00007f002f14dd0f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
```

https://drive.google.com/file/d/183hmHkHnxPGEN5aibzcnhUh2QmIOOzQ8/view?usp=sharing

### PR DESCRIPTION
**Pull request by ssanadhya**
Signed-off-by: Shruti Sanadhya <ssanadhya@fb.com>

## Summary

If the MME service restarts before UE has shared its IMSI with MME, the s1ap state does not have any context stored in Redis for this UE. However, the number of UEs associated with eNB reflect this UE with no IMSI. This leads to inconsistent state, leading to the "No valid UE context " error in `s1ap_send_enb_deregistered_ind`. The PR https://github.com/magma/magma/pull/4899 added an assertion to handles this scenario with an Assert and forcing service restart with clean Redis. This is not entirely needed.

This change adds logic to remove any  MME_UE_S1AP_ID from eNB `ue_id_coll` if it does not have a corresponding entry in the S1ap UE state map.

## Test Plan

- Functional testing
Before the change: `test_no_identity_rsp_with_mme_restart.py` was creating a seg fault on MME when SCTP disconnection was sent at the end of the test.
After the change, no seg fault on MME and the test succeeds.

- Regression testing
`make integ_test`

### CODE REVIEW

**Comment by ardzoht** [comment]
@ssanadhya what was the segfault about? trying to see if this is also a fix for an existing segfault during spirent AGW testing

File: lte/gateway/c/oai/tasks/s1ap/s1ap_state.cpp [hunk 1]
```diff
@@ -155,3 +157,74 @@ void delete_s1ap_ue_state(imsi64_t imsi64) {
...
+    }
+
+    if (enb_association_p->ue_id_coll.num_elements == 0) {
+      continue;
+    }
+
+    // for each ue comp_s1ap_id in eNB->ue_id_coll, check if it has an S1ap
+    // ue_context, if not delete it
+    mme_ue_id_no_imsi_list = (hash_key_t*) calloc(
+        enb_association_p->ue_id_coll.num_elements, sizeof(hash_key_t));
```
Comment (ulaskozat) [inline lte/gateway/c/oai/tasks/s1ap/s1ap_state.cpp:209]: shall we define this on the stack itself as an array?

File: lte/gateway/c/oai/tasks/s1ap/s1ap_state.cpp [hunk 2]
```diff
@@ -155,3 +157,74 @@ void delete_s1ap_ue_state(imsi64_t imsi64) {
...
+  hashtable_ts_get(s1ap_ue_state, (const hash_key_t) dataP, (void**) &ue_ref_p);
+  if (!ue_ref_p) {
+    *mme_id_list[(*num_ues_checked)++] = keyP;
+    OAILOG_DEBUG(
+        LOG_S1AP,
+        "Adding mme_ue_s1ap_id %lu to eNB clean up list with num_ues_checked "
+        "%u",
+        keyP, *num_ues_checked);
+  }
+}
```
Comment (ulaskozat) [inline lte/gateway/c/oai/tasks/s1ap/s1ap_state.cpp:179]: add an explicit return value.

File: lte/gateway/c/oai/tasks/s1ap/s1ap_state.cpp (hunk 1 above)
Comment (ssanadhya) [reply lte/gateway/c/oai/tasks/s1ap/s1ap_state.cpp:209]: @ulaskozat The challenge there is to define the size of this list, as the number of UEs connected to an eNB can vary a lot. What do you think?

**Comment by ssanadhya** [comment]
> @ssanadhya what was the segfault about? trying to see if this is also a fix for an existing segfault during spirent AGW testing

Screen Shot 2021-02-23 at 9 06 52 AM

File: lte/gateway/c/oai/tasks/s1ap/s1ap_state.cpp (hunk 1 above)
Comment (ulaskozat) [reply lte/gateway/c/oai/tasks/s1ap/s1ap_state.cpp:209]: Let's leave it as is then.

**Review by ulaskozat — APPROVED** [review]
LGTM
