### PR TITLE
[SessionD] Allow credits with 0 GSU to be initialized / received

### LINKED ISSUE #3549: Gy only relay no CCR-U after Top Up RAR/RAA exchange
### Your Environment

- **Version:** v1.3 Stable
- **Affected Component:** Federation Gateway, Access Gateway
- **Affected Subcomponent:** Session_proxy & Sessiond
- **Deployment Environment:** e.g. AWS (orc8r + FeG), bare-metal (AGW)

### Describe the Issue

When using external OCS, with Gy only relay, we see issue where after balance is exhausted, and top up is applied, after re-auth request / answer, magma does not perform update to get new quota to allow data flow to resume after top up. 

**To Reproduce**
1. Configure network for Gy only relay with external OCS
2. Configure a subscriber with zero balance
3. Attach the UE for that subscriber and observe FUI/FUA in the CCA-I
4. Apply a top up to the subscriber account in OCS
6. observe RAR/RAA are exchanged
7. observe in sessiond logs that "UPDATE NOT NEEDED" is logged and CCR-U for new quota is not sent to OCS <timestamp Oct 30 08:21:57>
8. observe data flow remains blocked after top up

**Expected behavior**
After the RAR/RAA exchange, and CCR-U should be sent to OCS with requested quota to allow data to flow after top up. 

**Additional context**
Attached are sessiond logs with gRPC logging enabled
FeG Gy pcap
AGW S1 pcap
[TopUP_noCCRU.zip](https://github.com/magma/magma/files/5466121/TopUP_noCCRU.zip)

Here is diagram of test network
[Magma + OCS FreedomFi Lab Topology.pdf](https://github.com/magma/magma/files/5466134/Magma.%2B.OCS.FreedomFi.Lab.Topology.pdf)

@joary @amarpad

### PR DESCRIPTION
**Pull request by themarwhal**
Signed-off-by: Marie Bremner <marwhal@fb.com>

## Summary
We should not be rejecting any successful credit grant that has 0 GSU. This should be counted as a valid credit just with 0 credit. For example, if we receive a 0 credit with FUA-redirect, we want to immediately go into the redirect state, not reject the credit.

New criteria for Gy credits: (We look at the cases in the following order)
1. If command level result code for CCA or MSCC level result code is not 2001, we will reject the credit. 
    * This means the credit is not maintained in SessionD. No rules with the rating group will be installed.
2. If GSU is empty (no valid total/rx/tx AVPs) AND there is no FUA specified, we will also reject the credit as there is no action to take. 
    * This means the credit is not maintained in SessionD. No rules with the rating group will be installed. 
3. If GSU is empty (no valid total/rx/tx AVPs) AND there is a FUA specified, we will accept the credit.
    * This means the credit will be tracked and the rules associated with the RG will be installed. 
    * In this case, the FUA will kick off right after the next usage update from PipelineD. (~1-2 seconds depending on configuration).
4. In all other cases, we accept the credit. 

## Test Plan
SessionD unit tests
CWF integ test

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

File: lte/gateway/c/session_manager/SessionState.cpp [hunk 1]
```diff
@@ -1175,73 +1175,60 @@ bool SessionState::reset_reporting_charging_credit(
...
-
-  charging_grant->receive_charging_grant(update.credit());
-  update_criteria.charging_credit_to_install[CreditKey(update)] =
-      charging_grant->marshal();
-  credit_map_[CreditKey(update)] = std::move(charging_grant);
-  return contains_credit(update.credit().granted_units()) ||
-         is_infinite_credit(update);
-}
-
-bool SessionState::contains_credit(const GrantedUnits& gsu) {
```
Comment (uri200) [inline lte/gateway/c/session_manager/SessionState.cpp:1236]: I think it is better not to remove this function and just remove the check for volumes (or if you want to keep the code as it is, just change `>` for `=>`

A non valid granted component doesn't mean 0

File: lte/gateway/c/session_manager/SessionState.cpp [hunk 2]
```diff
@@ -1175,73 +1175,60 @@ bool SessionState::reset_reporting_charging_credit(
...
-  return (gsu.total().is_valid() && gsu.total().volume() > 0) ||
-         (gsu.tx().is_valid() && gsu.tx().volume() > 0) ||
-         (gsu.rx().is_valid() && gsu.rx().volume() > 0);
-}
-
-bool SessionState::is_infinite_credit(const CreditUpdateResponse& response) {
```
Comment (uri200) [inline lte/gateway/c/session_manager/SessionState.cpp:1242]: aren't we checking this anymore

Comment (themarwhal) [reply lte/gateway/c/session_manager/SessionState.cpp:1242]: @uri200 The `is_inifinte_credit` function only existed because we were rejecting credits with empty GSU. So even if a credit was empty, if the credit was inifite, we would want to install it. But now that we are installing all successful credit, we don't need this check.

File: lte/gateway/c/session_manager/SessionState.cpp (hunk 1 above)
Comment (themarwhal) [reply lte/gateway/c/session_manager/SessionState.cpp:1236]: hmmmmmm yeah that is a good point. I suppose we could still receive a MSCC result code = 2001 but there is no grant AVP? 
Ok I will modify the PR to keep one function to verify the credit.

Comment (themarwhal) [reply lte/gateway/c/session_manager/SessionState.cpp:1236]: @uri200 Now the updated PR will
1. Reject credits with empty GSU (all credits are is_valid=false). This means the credit does not get added to the credit map and no rules are installed.
2. Valid credits with all 0 values, with at least one is_valid=true, will get added to the credit pool. the rules will also be installed.

I've just moved the `contains_credit` and `infinite_credit` functions to `ChargingGrant` class as it is only relevant for Gy.

**Review by uri200 — APPROVED** [review]

**Review by uri200 — APPROVED** [review]
