### PR TITLE
fix(nms): Disable sorting of subscribers table

### LINKED ISSUE #8951: NMS Subscribers Config table not being sorted by the sorting button
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Your Environment

- **Version:** 1.5
- **Affected Component:**  NMS
- **Affected Subcomponent:** NMS UI
- **Deployment Environment:** AWS (orc8r)

### Describe the Issue

The sorting function/button (in red on the image below) is not working for the Subscribers Config table. When clicked, nothing happens.

Captura de Tela 2021-09-03 às 09 36 00

Tested with Firefox Developer Edition 92.0b9 and Chrome 92.0.4515.159.

**To Reproduce**
1. Go to NMS UI > Network Management > Subscribers > Config
2. Click on the right side of any column header (Name, IMSI, Service, Current Usage, Daily Average, or Last Reported Time)
3. The up arrow button should sort the rows accordingly
4. See the issue: rows are not sorted.

**Expected behavior**

The subscriber rows should be sorted accordingly, by alphabetical order, timestamp, data amount, etc.

### PR DESCRIPTION
**Pull request by thmsschmitt**
## Summary

The subscribers are fetched paginated therefore the sorting has to be done in the orchestrator and is just not implemented at the moment. As quick "fix" we are disabling sorting on the table for now.

- fixes #8951

## Test Plan

Make sure that no sort indicators are shown on the subscribers table.

### CODE REVIEW

File: nms/app/views/subscriber/SubscriberTable.tsx [hunk 1]
```diff
@@ -497,7 +497,7 @@ function SubscribersTable(props: WithAlert) {
               filter={() => (
                 <Grid
                   container
-                  justify="flex-end"
```
Comment (thmsschmitt) [inline nms/app/views/subscriber/SubscriberTable.tsx:500]: This caused a deprecation warning

File: nms/app/views/subscriber/SubscriberTable.tsx [hunk 2]
```diff
@@ -593,6 +593,8 @@ function SubscribersTable(props: WithAlert) {
                 },
               ]}
               options={{
+                idSynonym: 'imsi',
```
Comment (thmsschmitt) [inline nms/app/views/subscriber/SubscriberTable.tsx:596]: This fixes the warning that the rows have no ids

**Review by Neudrino — APPROVED** [review]
