### PR TITLE
bug(agw): V1.6 check if UE context exists when timer expires

### LINKED ISSUE #9662: [HIL] TC010 sanity failed on non-nat setup with core
TC010 - 600UE attached at 3ue/sec and run traffic @500kbps / UE for 3mins.
this test resulted in coredump on 1.6.1 non-nat sanity run.

### Your Environment

- **Version:**1.6.1-1634100297-71f9bccc
- **Affected Component:** Access Gateway mme
- **Affected Subcomponent:** AGW service
- **Deployment Environment:** physical AGW

### Describe the Issue

during the automated sanity test run below core is observed

`Core was generated by `/usr/local/bin/mme -c /var/opt/magma/tmp/mme.conf -s /var/opt/magma/tmp/spgw.co'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  get_nas_common_procedure (ctxt=ctxt@entry=0x6210000531c0, proc_type=proc_type@entry=EMM_COMM_PROC_IDENT) at /home/vagrant/magma/lte/gateway/c/core/oai/tasks/nas/nas_procedures.c:73
73	/home/vagrant/magma/lte/gateway/c/core/oai/tasks/nas/nas_procedures.c: No such file or directory.
[Current thread is 1 (Thread 0x7ff3b25f0700 (LWP 205335))]
(gdb) bt
#0  get_nas_common_procedure (ctxt=ctxt@entry=0x6210000531c0, proc_type=proc_type@entry=EMM_COMM_PROC_IDENT) at /home/vagrant/magma/lte/gateway/c/core/oai/tasks/nas/nas_procedures.c:73
#1  0x000055abdc1ac0ce in get_nas_common_procedure_identification (ctxt=ctxt@entry=0x6210000531c0) at /home/vagrant/magma/lte/gateway/c/core/oai/tasks/nas/nas_procedures.c:163
#2  0x000055abdc1c29a3 in identification_t3470_handler (args=0x6210000531c0, imsi64=0x7ff3b25e1988) at /home/vagrant/magma/lte/gateway/c/core/oai/tasks/nas/emm/Identification.c:399
#3  0x000055abdc1b5644 in mme_app_nas_timer_handle_signal_expiry (timer_id=105621835869920, cb=0x6020000771e0, imsi64=imsi64@entry=0x7ff3b25e1988)
    at /home/vagrant/magma/lte/gateway/c/core/oai/tasks/nas/util/nas_timer.c:114
#4  0x000055abdbe724e0 in handle_message (loop=<optimized out>, reader=<optimized out>, arg=<optimized out>) at /home/vagrant/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_main.c:275
#5  0x00007ff3bf4355c7 in zloop_start () from /lib/x86_64-linux-gnu/libczmq.so.4
#6  0x000055abdbe729f2 in mme_app_thread (args=<optimized out>) at /home/vagrant/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_main.c:532
#7  0x00007ff3c0029609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#8  0x00007ff3bee07293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95`

core file - http://ens-spirent-test-summary.com.s3-us-west-1.amazonaws.com/cores/core-1634108740-TASK_MME_APP-205312-1.6.1-1634100297-71f9bccc.tgz

logs: - http://ens-spirent-test-summary.com.s3-us-west-1.amazonaws.com/performance/test_result_1.6.1-1633382405-5d6fa069_2021-10-11%2013:24:01.html

### PR DESCRIPTION
**Pull request by ssanadhya**
Signed-off-by: Shruti Sanadhya <ssanadhya@fb.com>

## Summary

MME can experience a race condition, where a timer fires for a UE, just as its context has been removed. This can lead to invalid memory access for UE context. HIL sanity test failed with one such occurrence in https://github.com/magma/magma/issues/9662. This change adds a guard to check whether UE context exists even when the timer id is valid.

This issue does not exist in v1.7 which uses LibZMQ timers that are maintained by each task in its own context.

## Test Plan

- Regression testing: S1ap integration tests
- Functional testing: Multiple runs of sanity tests in HIL setup

### CODE REVIEW

File: lte/gateway/c/core/oai/tasks/nas/util/nas_timer.c [hunk 1]
```diff
@@ -111,6 +112,18 @@ void mme_app_nas_timer_handle_signal_expiry(
...
   }
+
+  // check if a UE context still exists for this UE
+  ue_mm_context_t* ue_context = mme_ue_context_exists_mme_ue_s1ap_id(cb->ue_id);
+  if (!ue_context) {
+    OAILOG_ERROR(
+        LOG_NAS,
+        "Timer id %ld fired for ue_id " MME_UE_S1AP_ID_FMT
+        " which does not have any UE context\n",
+        timer_id, cb->ue_id);
```
Comment (ulaskozat) [inline lte/gateway/c/core/oai/tasks/nas/util/nas_timer.c:123]: since we are here, that means timer exists and need to be removed by calling `mme_app_remove_mme_ue_id_timer_id(cb->ue_id, timer_id)`.

Comment (ssanadhya) [reply lte/gateway/c/core/oai/tasks/nas/util/nas_timer.c:123]: Good catch, this is addressed in commit https://github.com/magma/magma/pull/9663/commits/b56c2a5dfac89f516f0676fa866304702f57f957

**Review by ulaskozat — APPROVED** [review]
LGTM
