### PR TITLE
test(cwg): Stabilizing `TestGyCreditExhaustionRedirect`

### LINKED ISSUE #13838: Fix CWAG TestGyCreditExhaustionRedirect as it is responsible for about 50% of all cwag integ test failures
## Summary

Currently TestGyCreditExhaustionRedirect fails about 10-20% of all cwag runs. This is responsible for making the CWAG integ tests run very frequently

# Tasks
* [ ] Reproduce failed test locally - see https://docs.magmacore.org/docs/next/cwf/dev_testing#run-integration-tests
* [ ] Understand and fix the timeouts
* [ ] Prepare internal review meeting

 ## Example run
https://storage.googleapis.com/magma-ci.appspot.com/cwf_integ_test_a94f1efd61ffb4de31fa05c140b4a6e471d5e1c7.html

### PR DESCRIPTION
**Pull request by MoritzThomasHuebner**
Fixes #13838

Signed-off-by: Moritz Huebner <moritz.huebner@tngtech.com>

## Summary

I modified the specified quota and requested traffic to make the test less flaky. The requested 10 Megabytes in `TestGyCreditExhaustionRedirect` is larger than any other traffic request in the `cwf` integration tests. It appears that larger traffic requests are more likely to fail for reasons we do not fully understand. The test is run with three reattempts on the CI, so it is sufficient to tune it so that is unlikely to fail four times consecutively.

## Test Plan

Unfortunately, I was not able to reproduce this problem locally. So I used an [upterm Github action](https://github.com/lhotari/action-upterm) to tune this on the Github runner remotely. I executed on the test on the state of `master` ten times and had seven failures. This result implies that we get `(0.7**4) = 24%` failure rate with reattempts on `master`, which is consistent with what is mentioned in #13838. 

I tuned the quotas and ran the test 100 times without reattempts with the state of this branch triggering only 13 failures. This yields a `(0.13**4) = 0.029%` failure rate once reattempts are considered.

## Additional Information

`TestGyCreditExhaustionRedirect` is not the only flaky `cwag` test. I found at least 15 other tests that fail at least occasionally but usually succeed in the reattempts. We could consider increasing the number of reattempts to make the workflow more stable overall.

- [ ] This change is backwards-breaking

### CODE REVIEW

File: cwf/gateway/integ_tests/gy_enforcement_test.go [hunk 1]
```diff
@@ -378,22 +378,24 @@ func TestGyLinksFailureOCStoFEG(t *testing.T) {
 	assert.Empty(t, recordsBySubID["IMSI"+ue.Imsi])
 }
 
-// - Set an expectation for a CCR-I to be sent up to OCS, to which it will
```
Comment (crasu) [inline cwf/gateway/integ_tests/gy_enforcement_test.go:381]: @MoritzThomasHuebner I would be great if reformatting goes to a seperate pr?

File: cwf/gateway/integ_tests/gy_enforcement_test.go [hunk 2]
```diff
@@ -447,19 +447,17 @@ func TestGyCreditExhaustionRedirect(t *testing.T) {
...
 	_, err := tr.GenULTraffic(req)
 	assert.NoError(t, err)
 
 	// Check that enforcement stats flow was not removed and data was passed
 	assert.Eventually(t,
-		tr.WaitForEnforcementStatsForRuleGreaterThan(imsi, "static-pass-all-ocs2", 3*MegaBytes), time.Minute, 2*time.Second)
+		tr.WaitForEnforcementStatsForRuleGreaterThan(imsi, "static-pass-all-ocs2", 1*MegaBytes), time.Minute, 2*time.Second)
 	// Wait for service deactivation
 	assert.Eventually(t,
 		tr.WaitForEnforcementStatsForRule(imsi, "redirect"), time.Minute, 2*time.Second)
```
Comment (crasu) [inline cwf/gateway/integ_tests/gy_enforcement_test.go:465]: Did you check if the test fails when you generate less than 1M traffic?

**Review by crasu — CHANGES_REQUESTED** [review]
Cloud you please add a full cwag run from your repo to the branch.

File: cwf/gateway/integ_tests/gy_enforcement_test.go [hunk 3]
```diff
@@ -491,7 +491,7 @@ func TestGyCreditExhaustionRedirect(t *testing.T) {
 
 	// Check that enforcement stats flow was not removed and data was passed
 	assert.Eventually(t,
-		tr.WaitForEnforcementStatsForRuleGreaterThan(imsi, "static-pass-all-ocs2", 1*MegaBytes), time.Minute, 2*time.Second)
+		tr.WaitForEnforcementStatsForRuleGreaterThan(imsi, "static-pass-all-ocs2", 0.25*MegaBytes), time.Minute, 2*time.Second)
 
 	// When we initiate a UE disconnect, we expect a terminate request to go up
```
Comment (crasu) [inline cwf/gateway/integ_tests/gy_enforcement_test.go:500]: The tests seems to missing a check that not redirect rule is present in this second case. Could you try to add one?

File: cwf/gateway/integ_tests/gy_enforcement_test.go (hunk 2 above)
Comment (MoritzThomasHuebner) [reply cwf/gateway/integ_tests/gy_enforcement_test.go:465]: Yes, this does fail:

```
    gy_enforcement_test.go:461: 
        	Error Trace:	gy_enforcement_test.go:461
        	Error:      	Condition never satisfied
        	Test:       	TestGyCreditExhaustionRedirect
```

File: cwf/gateway/integ_tests/gy_enforcement_test.go (hunk 3 above)
Comment (MoritzThomasHuebner) [reply cwf/gateway/integ_tests/gy_enforcement_test.go:500]: I added a check that it does in my latest commit. I had to manually implement this, but effectively we can assert this by waiting for a minute that no redirect rule appears for a minute.

File: cwf/gateway/integ_tests/gy_enforcement_test.go [hunk 4]
```diff
@@ -115,15 +115,15 @@ func provisionRestrictRules(t *testing.T, tr *TestRunner, ruleManager *RuleManag
...
-// - Set an expectation for a CCR-I to be sent up to OCS, to which it will
-//   respond with a quota grant of 4M.
-//   Generate traffic and assert the CCR-I is received.
-// - Set an expectation for a CCR-U with >80% of data usage to be sent up to
-// 	 OCS, to which it will response with more quota.
-//   Generate traffic and assert the CCR-U is received with final quota grant.
-// - Generate 5M traffic to exceed 100% of the quota and trigger session termination
-// - Assert that UE flows are deleted.
-// - Expect a CCR-T, trigger a UE disconnect, and assert the CCR-T is received.
+//   - Set an expectation for a CCR-I to be sent up to OCS, to which it will
```
Comment (voisey) [inline cwf/gateway/integ_tests/gy_enforcement_test.go:118]: Why have these extra two spaces been added for lists?

Comment (MoritzThomasHuebner) [reply cwf/gateway/integ_tests/gy_enforcement_test.go:118]: This is convention enforced by `gofmt` https://tip.golang.org/doc/comment (scroll down to the heading "Lists"). IntelliJ with the Go plugin reformatted these comments for me automatically pre commit.

Comment (MoritzThomasHuebner) [reply cwf/gateway/integ_tests/gy_enforcement_test.go:118]: Moreover, the reason why this was enforced for me is because I use a 1.19 go compiler locally and not 1.18. I suggest keeping the comment changes for this PR and I will downgrade back to 1.18 so that I don't pollute my other PRs with comment formatting going forward. We will eventually have to have a big comment formatting PR once we upgrade past 1.19.

**Comment by MoritzThomasHuebner** [comment]
> Cloud you please add a full cwag run from your repo to the branch.

https://github.com/MoritzThomasHuebner/magma/actions/runs/3064831256/jobs/4948619141

File: cwf/gateway/integ_tests/gy_enforcement_test.go (hunk 3 above)
Comment (crasu) [reply cwf/gateway/integ_tests/gy_enforcement_test.go:500]: just wait for 15sec make sure the rule is not there

**Review by crasu — APPROVED** [review]

File: cwf/gateway/integ_tests/gy_enforcement_test.go (hunk 3 above)
Comment (MoritzThomasHuebner) [reply cwf/gateway/integ_tests/gy_enforcement_test.go:500]: :+1:
