### PR TITLE
fix(cwg): fix radius udp listener

### LINKED ISSUE #14659: Track failing FeG radius unit tests
There are some flaky/failing FeG radius unit tests, which are skipped and therefore not run in the CI, having been excluded in https://github.com/magma/magma/pull/14655/. These tests should be investigated with the view to them no longer being skipped.

Currently skipped tests (where relevant, number of times failing when running `cd $MAGMA_ROOT/feg/radius/src && go clean -testcache && gotestsum ./...` locally):

Fixes merged:
- [x] TestPostODS https://github.com/magma/magma/pull/14698
- [x] TestBasicInsertGetRedis https://github.com/magma/magma/pull/14692
- [x] TestMultipleConcurrentInsertDeleteGetRedis https://github.com/magma/magma/pull/14692
- [x] TestCoaFixed https://github.com/magma/magma/pull/14701
- [x] TestCoaNas https://github.com/magma/magma/pull/14701
- [x] TestCoaNasNoResponse https://github.com/magma/magma/pull/14701
- [x] TestCoaNasFieldInvalid https://github.com/magma/magma/pull/14701
- [x] TestLBServeProxiesRequestToRadiusAndReturnsResponse https://github.com/magma/magma/pull/14701
- [x] TestLBServeFailsWithRadiusError https://github.com/magma/magma/pull/14701
- [x] TestProxy https://github.com/magma/magma/pull/14845
- [x] TestSendOdsCounters https://github.com/magma/magma/pull/14845
- [x] TestCoaDynamic https://github.com/magma/magma/pull/14880
- [x] TestAnalyticsModulesAuthenticate https://github.com/magma/magma/pull/14906
- [x] TestAnalyticsModulesAccountingStart https://github.com/magma/magma/pull/14906
- [x] TestAnalyticsModulesAccountingUpdate https://github.com/magma/magma/pull/14906
- [x] TestAnalyticsModulesAccountingStop https://github.com/magma/magma/pull/14906
- [x] TestFullRADIUSSessiontWithAnalyticsModules https://github.com/magma/magma/pull/14906
- [x] TestRequestWithModules https://github.com/magma/magma/pull/14906
- [x] TestModuleFailsToHandle https://github.com/magma/magma/pull/14906
- [x] TestFilterFailsToProcess https://github.com/magma/magma/pull/14906
- [x] TestDedup https://github.com/magma/magma/pull/14906

### LINKED ISSUE #14879: Fix UDP Listener in FEG Radius
Part of #14659 

## Summary

Currently, when setting up a UDP listener in the FEG Radius, it runs into a 10min timeout when trying to check if the listener finished setting up.

## Task

Change the broken checking logic to a proper health check setup.

### PR DESCRIPTION
**Pull request by wolfseb**
Part of #14659 
Closes #14879 

## Summary

This PR fixes the `UDPListener` by replacing the broken logic in `ListenAndServe` with a health check, which waits until the Listener is reachable. The health check is done by sending `CodeAccessRequest` packets to the server until a response is received or a timeout is reached.

For some tests the mocks needed to be changed slightly to make the health check work, but keep the remaining test logic as is, as these tests deal with e.g. intended unresponsive radius servers.

* `TestDedup`: This test makes a mocked radius server where the handler returns `nil` responses, which will not be send. The purpose is to check the deduplication function of the UDP listener (i.e. to drop repeated identical requests from the same source). Since there is no response coming back, the request will automatically be resend. The mock is adjusted so that the radius server will respond to the health check, but not to the test packet by using different packet codes.
* `TestModuleFailsToHandle`: Similar to `TestDedup`, but the radius server sends an error. Same principle of adjusting the mock.
* `TestFilterFailsToProcess`: The packet filter is mocked to always return an error, which interferes with the health check as well. The filter mock is adjusted to return a `nil` error for the health check, and the mock function was adjusted to allow `nil` errors.

## Test Plan

Run `go clean -testcache && gotestsum -- -p 1 ./...` in /magma/feg/radius/src/server

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

File: feg/radius/src/server/server_test.go [hunk 1]
```diff
@@ -349,30 +333,30 @@ func TestFilterFailsToProcess(t *testing.T) {
...
-	t.Skip("Skipped because test runs for 10 minutes before failing") // TODO GH14659
-
 	// Arrange
 	logger, err := zap.NewDevelopment()
 	require.NoError(t, err, "failed to get logger")
 	moduleChain := []string{"auth"}
 	moduleCount := []int{1}
 	config := getConfigWithAuthListener(t, moduleChain, moduleCount, true)
-	mModule1 := createMockHandlerWithReturn(nil, nil)
+	// mModule1 := createMockHandlerWithReturn(&modules.Response{Code: radius.CodeAccessAccept}, nil)
```
Comment (MoritzThomasHuebner) [inline feg/radius/src/server/server_test.go]: Remove this unused line

File: feg/radius/src/server/server_test.go [hunk 2]
```diff
@@ -386,6 +370,7 @@ func TestDedup(t *testing.T) {
 	// Assert
 	loader.AssertExpectations(t)
 	mModule1.AssertExpectations(t)
+	// mModule2.AssertExpectations(t)
```
Comment (MoritzThomasHuebner) [inline feg/radius/src/server/server_test.go]: Remove this unused line

**Review by MoritzThomasHuebner — CHANGES_REQUESTED** [review]
LGTM, just remove the commented out lines that you added.

File: feg/radius/src/server/server_test.go (hunk 1 above)
Comment (wolfseb) [reply feg/radius/src/server/server_test.go]: Thanks, I removed this.

File: feg/radius/src/server/server_test.go (hunk 2 above)
Comment (wolfseb) [reply feg/radius/src/server/server_test.go]: Thanks, I removed this.

**Review by MoritzThomasHuebner — APPROVED** [review]
