### PR TITLE
fix(orc8r): fix error messages in go http endpoints in orc8r

### LINKED ISSUE #14707: Empty error messages in Go HTTP endpoints
In many cases, `echo.NewHTTPError` is used with a Go error object to return an error in HTTP endpoints. However, this will not return the error message to the client. Instead, the message must be passed as a string.

This might have been broken when the logging middleware was introduced in #9767.

Follow-up of #14683.

### PR DESCRIPTION
**Pull request by wolfseb**
Signed-off-by: Sebastian Wolf <sebastian.wolf@tngtech.com>
Part of #14707.

## Summary

The method `echo.NewHTTPError` takes the error as a string. Currently, however, it is passed as an error object. This PR fixes this in the orc8r codebase. The following changes are made:

* `err` --> `err.Error()`
* `fmt.Errorf("text: %w", err)` --> `fmtSprintf("text: %v", err)`
* `fmt.Errorf(...)` --> `fmt.Sprintf(...)`
* `fmt.Errorf("%s", sendErr.Message)`, `sendErr`, etc --> `fmt.Sprintf("%s", sendErr.Message)`
* `fmt.Errors("...")`, `errors.New("...")` --> `"..."`

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

File: orc8r/cloud/go/services/metricsd/prometheus/handlers/alert_config_handler.go [hunk 1]
```diff
@@ -127,46 +127,46 @@ func GetViewFiringAlertHandler(alertmanagerURL string, client HttpClient) func(c
...
 	errs := rule.Validate()
 	if len(errs) != 0 {
-		return echo.NewHTTPError(http.StatusBadRequest, fmt.Errorf("invalid rule: %v\n", errs))
+		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("invalid rule: %v", errs))
 	}
 
 	sendErr := sendConfig(rule, url, http.MethodPost, client)
 	if sendErr != nil {
-		return echo.NewHTTPError(sendErr.Code, sendErr)
+		return echo.NewHTTPError(sendErr.Code, fmt.Sprintf("%s", sendErr.Message))
```
Comment (sebathomas) [inline orc8r/cloud/go/services/metricsd/prometheus/handlers/alert_config_handler.go]: I think you could return `sendErr` directly. This is already a `HTTPError`.

File: orc8r/cloud/go/services/metricsd/prometheus/handlers/alert_config_handler.go [hunk 2]
```diff
@@ -218,33 +218,33 @@ func deleteAlertRule(c echo.Context, url string, client HttpClient) error {
...
 	if alertName == "" {
-		return echo.NewHTTPError(http.StatusBadRequest, fmt.Errorf("alert name not provided"))
+		return echo.NewHTTPError(http.StatusBadRequest, "alert name not provided")
 	}
 	url += fmt.Sprintf("/%s", neturl.PathEscape(alertName))
 
 	sendErr := sendConfig(rule, url, http.MethodPut, client)
 	if sendErr != nil {
-		return echo.NewHTTPError(sendErr.Code, sendErr)
+		return echo.NewHTTPError(sendErr.Code, fmt.Sprintf("%s", sendErr.Message))
```
Comment (sebathomas) [inline orc8r/cloud/go/services/metricsd/prometheus/handlers/alert_config_handler.go]: Same here.

File: orc8r/cloud/go/services/metricsd/prometheus/handlers/alert_receiver_handlers.go [hunk 3]
```diff
@@ -118,44 +118,44 @@ func retrieveAlertReceivers(c echo.Context, url string, client HttpClient) error
...
 	if receiverName != receiver.Name {
-		return echo.NewHTTPError(http.StatusBadRequest, fmt.Errorf("new receiver configuration must have same name"))
+		return echo.NewHTTPError(http.StatusBadRequest, "new receiver configuration must have same name")
 	}
 	url += fmt.Sprintf("/%s", neturl.PathEscape(receiverName))
 
 	sendErr := sendConfig(receiver, url, http.MethodPut, client)
 	if sendErr != nil {
-		return echo.NewHTTPError(sendErr.Code, sendErr)
+		return echo.NewHTTPError(sendErr.Code, fmt.Sprintf("%s", sendErr.Message))
```
Comment (sebathomas) [inline orc8r/cloud/go/services/metricsd/prometheus/handlers/alert_receiver_handlers.go]: And here.

**Review by sebathomas — APPROVED** [review]
Some small points but looking good. :+1:

**Review by sebathomas — CHANGES_REQUESTED** [review]
I think the latest change was a misunderstanding. The idea is that you can return `sendErr` directly, not `echo.NewHTTPError(sendErr.Code, sendErr)`.

**Comment by wolfseb** [comment]
> I think the latest change was a misunderstanding. The idea is that you can return `sendErr` directly, not `echo.NewHTTPError(sendErr.Code, sendErr)`.

Done. Is it ok now @sebathomas ?

**Review by sebathomas — APPROVED** [review]
