### PR TITLE
fix(orc8r): Allow updating QoS profiles

### LINKED ISSUE #12307: Cannot change QoSProfile for a policy
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Your Environment

- **Version:** 1.6.1
- **Affected Component:** Orchestrator
- **Affected Subcomponent:** Orchestrator pod/service 
- **Deployment Environment:** bare-metal (AGW)

### Describe the Issue

**To Reproduce**
1. On NMS UI, Make sure you have a few QoS Profiles defined under Traffic>Policies>Profiles
2. On NMS UI go to Traffic>Policies>Policies
3. Edit a existing policy and change the QoS Profile for it. Say earlier it was Policy1 now make it Policy2.
4. Click Save.
5. Open the same policy for edit again. You can see that it still points to Policy1 and not the updated Policy2.

**Expected behavior**
The policy change should be applied and new policy should be visible in the UI.

### PR DESCRIPTION
**Pull request by sebathomas**
## Summary

Updating of QoS profiles was broken because the update handler did not remove old associations from the DB.
Fixes #12307.

## Test Plan

- Adapted integration test to include an update that changes between profiles.
- Started NMS and confirmed that changing profiles is now possible.

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Review by andreilee — APPROVED** [review]

File: lte/cloud/go/services/policydb/obsidian/handlers/policy_handlers_test.go [hunk 1]
```diff
@@ -1194,9 +1232,9 @@ func TestPolicyWithQoSProfile(t *testing.T) {
 	// Delete profile
 	tc = tests.Test{
 		Method:         "DELETE",
-		URL:            "/magma/v1/lte/n1/policy_qos_profiles/profile0",
+		URL:            "/magma/v1/lte/n1/policy_qos_profiles/profile1",
```
Comment (maxhbr) [inline lte/cloud/go/services/policydb/obsidian/handlers/policy_handlers_test.go:1235]: shouldn't you also delete `profile0`?

**Review by maxhbr — COMMENTED** [review]
Just a question.

File: lte/cloud/go/services/policydb/obsidian/handlers/policy_handlers_test.go (hunk 1 above)
Comment (sebathomas) [reply lte/cloud/go/services/policydb/obsidian/handlers/policy_handlers_test.go:1235]: It's not necessary for the test logic since it's no longer associated to the policy after the PUT from line 1195. (I don't think the DELETEs are needed to clean up test data, the test generates other entities that are not removed at the end.)

Comment (maxhbr) [reply lte/cloud/go/services/policydb/obsidian/handlers/policy_handlers_test.go:1235]: Thanks, that clarifies it

**Review by maxhbr — APPROVED** [review]
LGTM
