### PR TITLE
[cwf] Fix reauth tests to wait and check for a conditional

### LINKED ISSUE #2745: TestGxReAuthQuotaRefill failure
https://app.circleci.com/pipelines/github/magma/magma/2986/workflows/63921373-df46-4ae7-a57c-430ffc1464fc/jobs/30440/parallel-runs/0/steps/0-108

[magma@10.240.0.57] out: [vagrant@127.0.0.1:2201] out: Finished Discconnecting UE
[magma@10.240.0.57] out: [vagrant@127.0.0.1:2201] out: wait for flows to get deactivated
[magma@10.240.0.57] out: [vagrant@127.0.0.1:2201] out: --- FAIL: TestGxReAuthQuotaRefill (19.84s)
[magma@10.240.0.57] out: [vagrant@127.0.0.1:2201] out:     gx_reauth_test.go:436: 
[magma@10.240.0.57] out: [vagrant@127.0.0.1:2201] out:         	Error Trace:	gx_reauth_test.go:436
[magma@10.240.0.57] out: [vagrant@127.0.0.1:2201] out:         	Error:      	Should be true
[magma@10.240.0.57] out: [vagrant@127.0.0.1:2201] out:         	Test:       	TestGxReAuthQuotaRefill
[magma@10.240.0.57] out: [vagrant@127.0.0.1:2201] out:         	Messages:   	static-pass-all-raa1 did not pass any data
[magma@10.240.0.57] out: [vagrant@127.0.0.1:2201] out: === RUN   TestGyCreditExhaustionWithCRRU

### LINKED ISSUE #3062: TestGxReAuthWithMidSessionPolicyInstallAndRemoval failure
```[magma@10.240.0.5] out: [vagrant@127.0.0.1:2201] out: ************************* Adding PCRF Usage Monitor for UE with IMSI: 813826653812057
[magma@10.240.0.5] out: [vagrant@127.0.0.1:2201] out: --- FAIL: TestGxReAuthWithMidSessionPolicyInstallAndRemoval (12.46s)
[magma@10.240.0.5] out: [vagrant@127.0.0.1:2201] out:     gx_reauth_test.go:373: 
[magma@10.240.0.5] out: [vagrant@127.0.0.1:2201] out:         	Error Trace:	gx_reauth_test.go:373
[magma@10.240.0.5] out: [vagrant@127.0.0.1:2201] out:         	Error:      	Received unexpected error:
[magma@10.240.0.5] out: [vagrant@127.0.0.1:2201] out:         	            	rpc error: code = Unknown desc = write tcp 127.0.0.1:50003->127.0.0.1:50004: use of closed network connection
[magma@10.240.0.5] out: [vagrant@127.0.0.1:2201] out:         	Test:       	TestGxReAuthWithMidSessionPolicyInstallAndRemoval
[magma@10.240.0.5] out: [vagrant@127.0.0.1:2201] out: panic: runtime error: invalid memory address or nil pointer dereference [recovered]
[magma@10.240.0.5] out: [vagrant@127.0.0.1:2201] out: 	panic: runtime error: invalid memory address or nil pointer dereference
[magma@10.240.0.5] out: [vagrant@127.0.0.1:2201] out: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x12024b6]
[magma@10.240.0.5] out: [vagrant@127.0.0.1:2201] out: 
[magma@10.240.0.5] out: [vagrant@127.0.0.1:2201] out: goroutine 1044 [running]:
[magma@10.240.0.5] out: [vagrant@127.0.0.1:2201] out: testing.tRunner.func1(0xc0009a7a00)
[magma@10.240.0.5] out: [vagrant@127.0.0.1:2201] out: 	/usr/local/go/src/testing/testing.go:830 +0x392
[magma@10.240.0.5] out: [vagrant@127.0.0.1:2201] out: panic(0x1410720, 0x21860f0)
[magma@10.240.0.5] out: [vagrant@127.0.0.1:2201] out: 	/usr/local/go/src/runtime/panic.go:522 +0x1b5
[magma@10.240.0.5] out: [vagrant@127.0.0.1:2201] out: magma/cwf/gateway/integ_tests.TestGxReAuthWithMidSessionPolicyInstallAndRemoval(0xc0009a7a00)
[magma@10.240.0.5] out: [vagrant@127.0.0.1:2201] out: 	/home/vagrant/magma/cwf/gateway/integ_tests/gx_reauth_test.go:377 +0xb06
[magma@10.240.0.5] out: [vagrant@127.0.0.1:2201] out: testing.tRunner(0xc0009a7a00, 0x1614ce8)
[magma@10.240.0.5] out: [vagrant@127.0.0.1:2201] out: 	/usr/local/go/src/testing/testing.go:865 +0xc0
[magma@10.240.0.5] out: [vagrant@127.0.0.1:2201] out: created by testing.(*T).Run
[magma@10.240.0.5] out: [vagrant@127.0.0.1:2201] out: 	/usr/local/go/src/testing/testing.go:916 +0x35a
[magma@10.240.0.5] out: [vagrant@127.0.0.1:2201] out: exit status 2
[magma@10.240.0.5] out: [vagrant@127.0.0.1:2201] out: FAIL	magma/cwf/gateway/integ_tests	540.282s
[magma@10.240.0.5] out: [vagrant@127.0.0.1:2201] out: 
[magma@10.240.0.5] out: [vagrant@127.0.0.1:2201] out: === Skipped```

### PR DESCRIPTION
**Pull request by karthiksubraveti**
## Summary

There is a lot of flakiness in the reauth test due to the way we sleep for 4-5 seconds and test for raa. Modifying this to instead poll for a condition to be true atleast for a minute. 
[skipJenkins]

### CODE REVIEW

File: cwf/gateway/integ_tests/gx_reauth_test.go [hunk 1]
```diff
@@ -374,7 +390,13 @@ func TestGxReAuthWithMidSessionPolicyInstallAndRemoval(t *testing.T) {
 	tr.WaitForReAuthToProcess()
 
 	// Check ReAuth success
-	assert.Contains(t, raa.SessionId, "IMSI"+imsi)
+	WaitForReAuthToProcess := func() bool {
```
Comment (xjtian) [inline cwf/gateway/integ_tests/gx_reauth_test.go]: this callback should have a factory function that creates an instance bound to the specific closure you care about, don't copypasta this everywhere

**Review by xjtian — CHANGES_REQUESTED** [review]

File: cwf/gateway/integ_tests/gx_reauth_test.go (hunk 1 above)
Comment (karthiksubraveti) [reply cwf/gateway/integ_tests/gx_reauth_test.go]: Thanks for catching this :-). Was being lazy here. Will fix it.

**Review by themarwhal — APPROVED** [review]

File: cwf/gateway/integ_tests/gx_reauth_test.go [hunk 2]
```diff
@@ -445,10 +440,8 @@ func TestGxReAuthQuotaRefill(t *testing.T) {
 		},
 	)
 	assert.NoError(t, err)
-	tr.WaitForReAuthToProcess()
+	assert.Eventually(t, tr.WaitForReAuthToProcess(raa, imsi), time.Minute, 2*time.Second)
```
Comment (uri200) [inline cwf/gateway/integ_tests/gx_reauth_test.go]: Does it have to be such a big vaule? If they all fail, we will have to wait for a minute in all the cases. 

If CI takes like 10 s to execute a reauth then maybe we do have a problem.

**Review by uri200 — APPROVED** [review]

File: cwf/gateway/integ_tests/gx_reauth_test.go (hunk 2 above)
Comment (karthiksubraveti) [reply cwf/gateway/integ_tests/gx_reauth_test.go]: That's a good point. Hopefully we fail far fewer times than we pass. Also we could monitor the test completion times and change this over time.

**Comment by uri200** [comment]
I think my previous comment was not submitted, let me add it again: 

What about of reducing the timeout time from 1 min to few seconds? If for any reason we have a legit failure in all the tests, do we really want to wait for 1 min to time out? Wouldn't be a value like ~10s big enough for us to consider the test/Ci is not performing properly?

**Comment by karthiksubraveti** [comment]
> I think my previous comment was not submitted, let me add it again:
> 
> What about of reducing the timeout time from 1 min to few seconds? If for any reason we have a legit failure in all the tests, do we really want to wait for 1 min to time out? Wouldn't be a value like ~10s big enough for us to consider the test/Ci is not performing properly?

Since the tests are already flaky, I am afraid to set it to 10s and see the tests fail again because we didn't wait enough. Perhaps if we have a rough average of time taken for this wait every single time we can then just set the timeout  based on that.

**Review by xjtian — APPROVED** [review]

**Comment by xjtian** [comment]
precommit is failing
