### PR TITLE
[NMS] Adding network from network selector is broken

### LINKED ISSUE #3489: New network creation broken from networks selector pane

### PR DESCRIPTION
**Pull request by karthiksubraveti**
Signed-off-by: Karthik Subraveti <ksubraveti@fb.com>

## Summary

Adding network from network selector button is broken currently. LTE context is not passed down to 
the network selector here. This patch fixes this issue. It moves the LTEContextProvider to the enclose
the network selector as well. 

## Test Plan
Added e2e test to verify the fix

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

File: nms/app/packages/magmalte/app/e2e/__tests__/FegLte-test.js [hunk 1]
```diff
@@ -84,6 +84,93 @@ describe('Admin component', () => {
...
+
+      await page.waitForSelector(networkNameSelector);
+      await page.click(networkNameSelector);
+      await page.type(networkNameSelector, 'test_network');
+
+      await page.waitForSelector(networkDescriptionSelector);
+      await page.click(networkDescriptionSelector);
+      await page.type(networkDescriptionSelector, 'test_network');
+
+      // TODO need to figure out why we need to add this delay
```
Comment (andreilee) [inline nms/app/packages/magmalte/app/e2e/__tests__/FegLte-test.js:121]: attach a github user ID here

File: nms/app/packages/magmalte/app/e2e/__tests__/FegLte-test.js [hunk 2]
```diff
@@ -84,6 +84,93 @@ describe('Admin component', () => {
...
+      await page.waitFor(500);
+
+      const saveButtonSelector = '[data-testid="saveButton"]';
+      await page.waitForSelector(saveButtonSelector);
+      await page.click(saveButtonSelector);
+
+      // let [saveButton] = await page.$x(`//span[text()='Save And Continue']`);
+      // await saveButton.click();
```
Comment (andreilee) [inline nms/app/packages/magmalte/app/e2e/__tests__/FegLte-test.js]: remove

**Review by andreilee — APPROVED** [review]
