### PR TITLE
[SessionD][Redis] Check session store ready state before accessing

### LINKED ISSUE #5543: [SessionD] Occasional coredump on SessionD restart
### Your Environment

- **Version:** master
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** AGW service - sessiond
- **Deployment Environment:** Vagrant (AGW)

### Describe the Issue
Back trace: 
```
[Current thread is 1 (Thread 0x7f955f49ea80 (LWP 12747))]
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f955cccf42a in __GI_abort () at abort.c:89
#2  0x00007f955d5e60ad in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007f955d5e4066 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007f955d5e3089 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007f955d5e39dd in __gxx_personality_v0 () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007f955d049f33 in ?? () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#7  0x00007f955d04a29b in _Unwind_RaiseException () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#8  0x00007f955d5e42bc in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x0000564c1e4ff809 in magma::lte::RedisStoreClient::read_all_sessions[abi:cxx11]() (this=0x564c20a298c0) at /home/vagrant/magma/lte/gateway/c/session_manager/RedisStoreClient.cpp:88
#10 0x0000564c1e4f5a50 in magma::lte::SessionStore::read_all_sessions[abi:cxx11]() (this=0x564c20a14fa0) at /home/vagrant/magma/lte/gateway/c/session_manager/SessionStore.cpp:47
#11 0x0000564c1e41d59f in magma::LocalSessionManagerHandlerImpl::<lambda()>::operator()(void) const (__closure=0x7f9520004f20) at /home/vagrant/magma/lte/gateway/c/session_manager/LocalSessionManagerHandler.cpp:52
#12 0x0000564c1e427281 in folly::detail::function::FunctionTraits<void()>::callBig<magma::LocalSessionManagerHandlerImpl::ReportRuleStats(grpc::ServerContext*, const magma::lte::RuleRecordTable*, std::function<void(grpc::Status, magma::orc8r::Void)>)::<lambda()> >(folly::detail::function::Data &) (p=...) at /usr/local/include/folly/Function.h:321
#13 0x00007f955e9cef8e in folly::NotificationQueue<folly::Function<void ()> >::Consumer::consumeMessages(bool, unsigned long*) () from /usr/local/lib/libfolly.so.57
#14 0x00007f955a6fb5a0 in event_base_loop () from /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5
#15 0x00007f955e9c9d30 in folly::EventBase::loopBody(int) () from /usr/local/lib/libfolly.so.57
#16 0x00007f955e9cb376 in folly::EventBase::loopForever() () from /usr/local/lib/libfolly.so.57
#17 0x0000564c1e3dffc9 in main (argc=1, argv=0x7ffd48a18e58) at /home/vagrant/magma/lte/gateway/c/session_manager/sessiond_main.cpp:401
```
Seems to happen everytime SessionD restarts. 

The solution would be to reject all incoming requests until Redis is ready.

### PR DESCRIPTION
**Pull request by themarwhal**
Signed-off-by: Marie Bremner <marwhal@fb.com>

## Summary
We are seeing SessionD crashes due to it throwing an exception when Redis is unavailable. Specifically, SessionD would crash if PipelineD sends a ReportRuleStats to SessionD before redis client is available. 
In order to get around this, the new logic is to check the SessionStore readiness before accessing. For ReportRuleStats, we will ignore messages since the interface doesn't allow for error propagation. For LocalCreateSession, we will respond with error. 

## Test Plan
Run `make restart` multiple times in a row to see if sessiond cores are produced. 
-> before this change -> core per-restart
-> after this change -> no cores

Run the s1ap test locally

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

File: lte/gateway/c/session_manager/LocalSessionManagerHandler.cpp [hunk 1]
```diff
@@ -47,11 +47,21 @@ void LocalSessionManagerHandlerImpl::ReportRuleStats(
     PrintGrpcMessage(
         static_cast<const google::protobuf::Message&>(request_cpy));
   }
-  MLOG(MDEBUG) << "Aggregating " << request_cpy.records_size() << " records";
   enforcer_->get_event_base().runInEventBaseThread([this, request_cpy]() {
+    if (!session_store_.is_ready()) {
+      // Since PipelineD reports a delta value for usage, this could lead to
+      // SessionD missing some usage if Redis becomes. However, since we usually
```
Comment (uri200) [inline lte/gateway/c/session_manager/LocalSessionManagerHandler.cpp]: i think you are missing something after `becomes`

File: lte/gateway/c/session_manager/LocalSessionManagerHandler.cpp [hunk 2]
```diff
@@ -47,11 +47,21 @@ void LocalSessionManagerHandlerImpl::ReportRuleStats(
...
+      // only see this case on service restarts, we'll let this slide for now.
+      // Once we move to flat-rate reporting from PipelineD this will no longer
+      // be an issue.
```
Comment (uri200) [inline lte/gateway/c/session_manager/LocalSessionManagerHandler.cpp]: so for now we will give free data while redis is not available, right?

**Review by uri200 — APPROVED** [review]

File: lte/gateway/c/session_manager/LocalSessionManagerHandler.cpp (hunk 2 above)
Comment (themarwhal) [reply lte/gateway/c/session_manager/LocalSessionManagerHandler.cpp]: Yes.
