### PR TITLE
fix(agw): Convert log level from mconfig correctly

### LINKED ISSUE #10911: Log levels from mconfig are inverted in C++ services
### Your Environment

- **Version:** 1.7
- **Affected Component:** AGW
- **Affected Subcomponent:** C++ services
- **Deployment Environment:** Vagrant (AGW)

### Describe the Issue

While looking into configurable logging for SCTPd for #10904, it came up that the log levels from mconfig are not used correctly.

I think there's a mismatch between the values in `magma::orc8r::LogLevel` and the `magma_logging.h` constants. Putting this into the main
```cpp
magma::set_verbosity(magma::orc8r::LogLevel::DEBUG);
magma::set_verbosity(magma::orc8r::LogLevel::INFO);
magma::set_verbosity(magma::orc8r::LogLevel::WARNING);
magma::set_verbosity(magma::orc8r::LogLevel::ERROR);
magma::set_verbosity(magma::orc8r::LogLevel::FATAL);
magma::set_verbosity(MDEBUG);
magma::set_verbosity(MINFO);
magma::set_verbosity(MWARNING);
magma::set_verbosity(MERROR);
magma::set_verbosity(MFATAL);
```
results in:
```
I1216 15:31:06.167461 203384 magma_logging_init.h:28] Setting verbosity to 0
I1216 15:31:06.167547 203384 magma_logging_init.h:28] Setting verbosity to 1
I1216 15:31:06.167569 203384 magma_logging_init.h:28] Setting verbosity to 2
I1216 15:31:06.167587 203384 magma_logging_init.h:28] Setting verbosity to 3
I1216 15:31:06.167603 203384 magma_logging_init.h:28] Setting verbosity to 4
I1216 15:31:06.167619 203384 magma_logging_init.h:28] Setting verbosity to 4
I1216 15:31:06.167635 203384 magma_logging_init.h:28] Setting verbosity to 3
I1216 15:31:06.167675 203384 magma_logging_init.h:28] Setting verbosity to 2
I1216 15:31:06.167696 203384 magma_logging_init.h:28] Setting verbosity to 1
I1216 15:31:06.167714 203384 magma_logging_init.h:28] Setting verbosity to 0
```
So there's still a conversion missing. Sessiond, liagent and connection tracker have a function  `get_log_verbosity` that will return the mconfig value directly if it's not overwritten by the config.

**Expected behavior**
`magma::orc8r::LogLevel`s need to be converted before setting verbosity.

### PR DESCRIPTION
**Pull request by sebathomas**
## Summary

When reading the log level from an mconfig file, it needs to be inverted before setting it as verbosity. Extract a new function MConfigLoader to do that and use it for sessiond, li_agent and connection_tracker.

Fixes #10911.

## Test Plan

Start sessiond locally with the following gateway.mconfig:
```
[...]
"sessiond": {
    "@type": "type.googleapis.com/magma.mconfig.SessionD",
    "logLevel": "INFO",
    [...]
},
[...]
```

Output before the change:
```
I1222 12:14:14.918968 150611 magma_logging_init.h:28] Setting verbosity to 1
```

Output after the change:
```
I1222 12:15:17.982623 150734 magma_logging_init.h:28] Setting verbosity to 3
```

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

File: orc8r/gateway/c/common/config/includes/MConfigLoader.h [hunk 1]
```diff
@@ -42,4 +42,6 @@ bool load_service_mconfig(const std::string& service_name,
                           google::protobuf::Message* message);
 
 void get_mconfig_file(std::ifstream* file);
+
+uint32_t get_log_verbosity_from_mconfig(uint32_t mconfig_log_level);
```
Comment (themarwhal) [inline orc8r/gateway/c/common/config/includes/MConfigLoader.h:46]:
```suggestion
uint32_t get_log_verbosity_from_mconfig(const uint32_t mconfig_log_level);
```

File: orc8r/gateway/c/common/config/MConfigLoader.cpp [hunk 2]
```diff
@@ -113,4 +113,11 @@ bool load_service_mconfig(const std::string& service_name,
   return status.ok();
 }
 
+uint32_t get_log_verbosity_from_mconfig(uint32_t mconfig_log_level) {
```
Comment (themarwhal) [inline orc8r/gateway/c/common/config/MConfigLoader.cpp]: Let's write a small unit test for this just so we have coverage :)

Comment (sebathomas) [reply orc8r/gateway/c/common/config/MConfigLoader.cpp]: Added a small test. :+1:

**Review by themarwhal — APPROVED** [review]
