### PR TITLE
fix(mme): make GCC warnings disappear

### LINKED ISSUE #10166: GCC warning annotations seen on unrelated PR
https://github.com/magma/magma/pull/10149/files <- seeing some unrelated GCC warning annotations. Might be good to address these.

In case the annotation goes away, I'll take screenshots of the warnings. 

Screen Shot 2021-11-08 at 10 50 08 AM

### PR DESCRIPTION
**Pull request by tenpercent**
Issue: https://github.com/magma/magma/issues/10166

## Summary

Looks like pointers of functions with different function signatures have been assigned.

```
[lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_upf.c#L36](https://github.com/magma/magma/commit/005c5f378725a43d3040b380796cd8fade8c7bad#annotation_2776830515)
initialization of 'int (*)(struct in_addr,  struct in6_addr *, int,  struct in_addr,  struct in6_addr *, uint32_t,  uint32_t,  Imsi_t,  struct ip_flow_dl *, uint32_t,  char *)' {aka 'int (*)(struct in_addr,  struct in6_addr *, int,  struct in_addr,  struct in6_addr *, unsigned int,  unsigned int,  struct <anonymous>,  struct ip_flow_dl *, unsigned int,  char *)'} from incompatible pointer type 'int (*)(struct in_addr,  struct in6_addr *, int,  struct in_addr,  uint32_t,  uint32_t,  Imsi_t,  struct ip_flow_dl *, uint32_t,  char *)' {aka 'int (*)(struct in_addr,  struct in6_addr *, int,  struct in_addr,  unsigned int,  unsigned int,  struct <anonymous>,  struct ip_flow_dl *, unsigned int,  char *)'} [-Wincompatible-pointer-types]

[lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_upf.c#L37](https://github.com/magma/magma/commit/005c5f378725a43d3040b380796cd8fade8c7bad#annotation_2776830518)
initialization of 'int (*)(struct in_addr,  struct in6_addr *, struct in_addr,  struct in6_addr *, uint32_t,  uint32_t,  struct ip_flow_dl *)' {aka 'int (*)(struct in_addr,  struct in6_addr *, struct in_addr,  struct in6_addr *, unsigned int,  unsigned int,  struct ip_flow_dl *)'} from incompatible pointer type 'int (*)(struct in_addr,  struct in_addr,  struct in6_addr *, uint32_t,  uint32_t,  struct ip_flow_dl *)' {aka 'int (*)(struct in_addr,  struct in_addr,  struct in6_addr *, unsigned int,  unsigned int,  struct ip_flow_dl *)'} [-Wincompatible-pointer-types]

[lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_upf.c#L40](https://github.com/magma/magma/commit/005c5f378725a43d3040b380796cd8fade8c7bad#annotation_2776830521)
initialization of 'int (*)(Imsi_t,  struct in_addr,  struct in6_addr *)' {aka 'int (*)(struct <anonymous>,  struct in_addr,  struct in6_addr *)'} from incompatible pointer type 'int (*)(struct in_addr)' [-Wincompatible-pointer-types]

[lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_upf.c#L41](https://github.com/magma/magma/commit/005c5f378725a43d3040b380796cd8fade8c7bad#annotation_2776830523)
initialization of 'int (*)(struct in_addr, struct in6_addr *)' from incompatible pointer type 'int (*)(struct in_addr)' [-Wincompatible-pointer-types]
```

Added unused parameters so that signatures match.

## Test Plan

```
cd /workspaces/magma/lte/gateway
make build_oai
```
Compilation successful

### CODE REVIEW

File: lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_upf.h [hunk 1]
```diff
@@ -37,6 +37,7 @@ int upf_forward_data_on_tunnel(struct in_addr ue, struct in6_addr* ue_ipv6,
                                uint32_t i_tei, struct ip_flow_dl* flow_dl,
                                uint32_t flow_precedence_dl);
 
-int upf_add_paging_rule(struct in_addr ue);
+int upf_add_paging_rule(Imsi_t unused0, struct in_addr ue,
```
Comment (ardzoht) [inline lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_upf.h]:
```suggestion
int upf_add_paging_rule(Imsi_t unused_imsi_t, struct in_addr ue,
```

File: lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_upf.h [hunk 2]
```diff
@@ -37,6 +37,7 @@ int upf_forward_data_on_tunnel(struct in_addr ue, struct in6_addr* ue_ipv6,
...
+                        struct in6_addr* unused1);
```
Comment (ardzoht) [inline lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_upf.h]:
```suggestion
                        struct in6_addr* unused_in6_addr);
```

**Review by ardzoht — CHANGES_REQUESTED** [review]
minor nits on formatting

File: lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_upf.c [hunk 3]
```diff
@@ -49,17 +49,17 @@ const struct gtp_tunnel_ops* upf_gtp_tunnel_ops_init_openflow(void) {
 }
 
 int upf_add_tunnel(struct in_addr ue, struct in6_addr* ue_ipv6, int vlan,
-                   struct in_addr enb, uint32_t i_tei, uint32_t o_tei,
-                   Imsi_t imsi, struct ip_flow_dl* flow_dl,
+                   struct in_addr enb, struct in6_addr* unused, uint32_t i_tei,
```
Comment (ardzoht) [inline lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_upf.c]: can we also update all added unused params with pattern: `unused_<type_of_param>`

**Review by ardzoht — CHANGES_REQUESTED** [review]

File: lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_upf.c (hunk 3 above)
Comment (tenpercent) [reply lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_upf.c]: Please see revision [e0b4607]

**Review by ardzoht — APPROVED** [review]
lgtm
