### PR TITLE
fix(amf): SSC Mode setting incorrectly in PDU Session Establisment accept message

### LINKED ISSUE #10484: [AMF]: SSC Mode setting incorrectly in PDU Session Establisment accept message

### PR DESCRIPTION
**Pull request by shashidhar-patil**
Signed-off-by: shashidhar-patil <shashidhar.patil@wavelabs.ai>

## Summary
Issue: SSC mode was being set incorrectly.

Info: 
- SSC mode is an optional parameter in PDU session establishment request message and its length is 1 byte.
- SSC mode is a mandatory parameter in PDU session establishment accept message and its length is 1 nibble (1/2 octet).

Changes: 
Changes are made in the encoding and decoding logic to account for the optional parameter case.

Spec references:
MicrosoftTeams-image (5)

MicrosoftTeams-image (6)

 

## Test Plan
- Verified basic sanity with UERANSIM.
- Please find attached logs and pcap snap for basic registration.

Pcap Snap:
sscPcap

Test_oai Snap:
sscModeTest

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

File: lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp [hunk 1]
```diff
@@ -752,7 +752,8 @@ int amf_app_handle_pdu_session_accept(
   smf_msg->msg.pdu_session_estab_accept.message_type.msg_type =
       PDU_SESSION_ESTABLISHMENT_ACCEPT;
   smf_msg->msg.pdu_session_estab_accept.pdu_session_type.type_val = 1;
-  smf_msg->msg.pdu_session_estab_accept.ssc_mode.mode_val         = 1;
+  smf_msg->msg.pdu_session_estab_accept.ssc_mode.mode_val =
+      (pdu_session_resp->selected_ssc_mode + 1);
```
Comment (ulaskozat) [inline lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp:756]: where do we pick/configure the ssc mode? cc @panyogesh

Comment (panyogesh) [reply lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp:756]: Its copied from UE, as in  set_amf_smf_context() "smf_ctx->smf_proc_data.ssc_mode  = message->ssc_mode". Its send to sesssiond and replayed back to AMF.

Comment (ulaskozat) [reply lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp:756]: Should not we pick one from AMF configs? It should be up to the core to pick SSC mode as it does not have to support all modes. E.g., similar to how we pick integration protection.

Comment (ulaskozat) [reply lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp:756]: I will stamp and land this code to unblock the team, but can you create and track the issue for future extension for mobility support @panyogesh

**Review by ulaskozat — APPROVED** [review]
LGTM

File: lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp (hunk 1 above)
Comment (panyogesh) [reply lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp:756]: @ulaskozat : Thanks. I have raised a new task #10547 for configuration and selection logic of SSC mode.
