### PR TITLE
[NMS] Handle newly migrated enodeb configurations

### LINKED ISSUE #3676: [NMS] enodeb edit fails with `config not found` error

### PR DESCRIPTION
**Pull request by karthiksubraveti**
Signed-off-by: Karthik Subraveti <ksubraveti@fb.com>

## Summary

In migrated enodeb configurations, the "config" attribute shows up as null and "enodeb_config" shows up as a default entity with { config_type : "" }. This migrated configuration isn't valid when we attempt to submit it. Fixing it in NMS where we replace the invalid configs with valid defaults.

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

File: nms/app/packages/magmalte/app/views/equipment/EnodebDetailConfigEdit.js [hunk 1]
```diff
@@ -519,6 +519,17 @@ export function ConfigEdit(props: Props) {
           return;
         }
       }
+
+      // fill in default or undefined values here
```
Comment (andreilee) [inline nms/app/packages/magmalte/app/views/equipment/EnodebDetailConfigEdit.js]: Please add a `TODO` with github user ID attached to remove these two blocks later.

**Review by andreilee — APPROVED** [review]
As this looks like a mitigation rather than a root cause fix, I'd prefer if there were an issue filed to track the root cause.

File: nms/app/packages/magmalte/app/views/equipment/EnodebDetailConfigEdit.js (hunk 1 above)
Comment (karthiksubraveti) [reply nms/app/packages/magmalte/app/views/equipment/EnodebDetailConfigEdit.js]: This is not a todo, this is actually describing what i'm doing here
