### PR TITLE
fix(amf): Supporting the Implicit deregistration timer, fixing the TAC Value in Registration Accept message.

### LINKED ISSUE #13141: TAC value is different in Registration Accept message
- **Version:**   1.7.0-1648152173-73e61141                  

As per the pcap log we have analysis that the we have configured different tac value in MME & gNB. When UE is sending Initial Registration request message with different tac value and we have received registration accept message from AMF with different TAC value.

[https://app.zenhub.com/files/170803235/09d9c7a5-d932-41b4-b223-bdd787c5cb91/download](https://app.zenhub.com/files/170803235/09d9c7a5-d932-41b4-b223-bdd787c5cb91/download)

### PR DESCRIPTION
**Pull request by sreedharkumartn**
Signed-off-by: sreedharkumartn <sreedhar.kumar@wavelabs.ai>

### Issues Resolved:
**Issue - 1:** Implicit deregistration timer is not getting triggered.
**Fix - 1:** Fixed the part of fetching Implicit deregistration timer value.

**Issue - 2:** TAC value is different in Registration Accept from the one we are getting in Initial UE Message.
image
image
**Fix - 2:** Fixed the TAC value in Registration Accept message now.
image
image

### Testing Scenarios:

**Test 1:** Tested below case using UERANSIM. 
**Case :** As per spec _3GPP TS 24.501 version 15.1.0 Release 15_ now, if UE is gone to IDLE mode then mobile reachable timer triggers. After mobile reachable timer got expires, implicit deregistration timer triggers. After Implicit deregistration timer expires, then Implicit deregistration is happened.
- mme log.
[mme_12july_2.log](https://github.com/magma/magma/files/9093782/mme_12july_2.log)

**Test 2:** Tested TAC value using UERANSIM.
- PCAP snap shot.
image
[mme_tac_fix.log](https://github.com/magma/magma/files/9093808/mme_tac_fix.log)
- mme log.
[mme_tac_fix.log](https://github.com/magma/magma/files/9093898/mme_tac_fix.log)

**Test 3:** Tested basic sanity using UERANSIM.
- PCAP snap shot.
image
image
- mme log.
[mme_basic_sanity.log](https://github.com/magma/magma/files/9093888/mme_basic_sanity.log)

**Test 4:** Tested Service Request with traffic using UERANSIM.
- PCAP snap shot.
image
- mme log.
[mme_service_request.log](https://github.com/magma/magma/files/9093924/mme_service_request.log)

**Test 5:** Tested UT.
UT

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

File: lte/gateway/c/core/oai/tasks/amf/amf_app_ue_context.cpp [hunk 1]
```diff
@@ -785,13 +800,29 @@ void amf_ue_context_update_ue_sig_connection_state(
             AMF_APP_TIMER_INACTIVE_ID) {
       ue_context_p->m5_mobile_reachability_timer.sec =
           (amf_config.nas_config.t3512_min + 4 * 60);
```
Comment (ajahl) [inline lte/gateway/c/core/oai/tasks/amf/amf_app_ue_context.cpp]: btw: Is this calculation correct regarding multiplication first?

File: lte/gateway/c/core/oai/tasks/amf/amf_app_ue_context.cpp [hunk 2]
```diff
@@ -785,13 +800,29 @@ void amf_ue_context_update_ue_sig_connection_state(
...
-            ue_context_p->amf_ue_ngap_id);
+      ue_context_p->m5_implicit_deregistration_timer.sec =
+          ue_context_p->m5_mobile_reachability_timer.sec;
+
+      // Start Mobile Reachability timer only if it is not running
+      if ((ue_context_p->m5_mobile_reachability_timer.id = amf_app_start_timer(
+               ue_context_p->m5_mobile_reachability_timer.sec * 1000,
+               TIMER_REPEAT_ONCE,
+               amf_app_handle_mobile_reachability_timer_expiry,
+               ue_context_p->amf_ue_ngap_id)) == -1) {
```
Comment (ajahl) [inline lte/gateway/c/core/oai/tasks/amf/amf_app_ue_context.cpp]: Can we create and use a constant for -1 here?

**Review by ajahl — CHANGES_REQUESTED** [review]

File: lte/gateway/c/core/oai/tasks/amf/amf_app_ue_context.cpp (hunk 2 above)
Comment (sreedharkumartn) [reply lte/gateway/c/core/oai/tasks/amf/amf_app_ue_context.cpp]: Addressed Review Comment

File: lte/gateway/c/core/oai/tasks/amf/amf_app_ue_context.cpp (hunk 1 above)
Comment (sreedharkumartn) [reply lte/gateway/c/core/oai/tasks/amf/amf_app_ue_context.cpp]: Added additional brackets.

**Review by ganeshg87 — APPROVED** [review]
lgtm

**Review by ajahl — APPROVED** [review]
