### PR TITLE
[feg] Diameter failed connection recovery (possible fix for issue #7496)

### LINKED ISSUE #7496: [FeGW] TCP diameter Gx/Gy links failure
### Federated LTE Network 

- **Version:**
- **Affected Component:** Federation gateway
- **Affected Subcomponent:** Federation gateway, NMS
- **Deployment Environment:** local docker-compose (orc8r), Openstack AGW/FeG

### Describe the Issue
Diameter links Gx/Gy are configured with TCP port to a DRA. Randomly, these links are getting down from time to time. The way we get back the links is with a manual restart of services of dockers. The links does not drop off at the same time, there is no patron of time.

``` 
[36msession_proxy    |[0m E0603 02:46:04.104037       1 diameter_client.go:150] diameter error on 10.68.152.61:5112: read tcp 10.30.26.57:3871->10.68.152.61:5112: use of closed network connection
[36msession_proxy    |[0m E0603 11:52:27.999359       1 diameter_client.go:150] diameter error on 10.68.152.61:5111: read tcp 10.30.26.57:3870->10.68.152.61:5111: use of closed network connection
``` 

The S6a link is configured with SCTP port and never happens this issue.

**Expected behavior**
Links must estable all the time, otherwise will generate alarms in the DRA's side. 

**Additional context**
Attached the logs of session_proxy docker and the traces of Gx and Gy. Consider these info:
Gy (TCP port 5112) down time -> 02/06 21:46
Gx (TCP port 5111) down time -> 03/06 06:52
Each pcap file name ends with the interface name that got down within that capture

[GxGy_down.zip](https://github.com/magma/magma/files/6639810/GxGy_down.zip)

### PR DESCRIPTION
**Pull request by emakeev**
Signed-off-by: Evgeniy Makeev <evgeniym@fb.com>

## Summary

Diameter failed connection recovery (possible fix for issue #7496)

## Test Plan
 unit tests; try to reproduce issue #7496
 
 From the latest PR build logs:
 ```
 session_proxy    | I0618 21:53:56.243525       1 impl.go:51] Mconfig refresh succeeded from: /var/opt/magma/configs/gateway.mconfig
session_proxy    | E0618 21:53:57.407516       1 diameter_client.go:164] diameter connection 172.16.1.13:3907->172.16.1.6:3868 error: diameter error on 172.16.1.6:3868: read tcp 172.16.1.13:3907->172.16.1.6:3868: use of closed network connection
session_proxy    | I0618 21:53:57.408293       1 connection.go:180] destroyed 172.16.1.13:3907->172.16.1.6:3868 connection
session_proxy    | I0618 21:53:57.409293       1 diameter_client.go:179] diameter connection 172.16.1.13:3907->172.16.1.6:3868 is successfully recovered
session_proxy    | I0618 21:54:00.374577       1 connection_manager.go:115] ConnectionManager: enabling connections
```
We were able to reproduce the issue in the lab & the introduced recovery logic seemed to fix the connection (reconnect) in less than 3 seconds.

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

File: feg/gateway/diameter/connection_manager.go [hunk 1]
```diff
@@ -98,12 +112,45 @@ func (cm *ConnectionManager) DisableFor(period time.Duration) {
...
+		return nil
+	}
+	cm.rwl.RLock()
+	defer cm.rwl.RUnlock()
+	for _, conn := range cm.connMap {
+		if conn != nil {
+			if conn.conn == dc {
+				return conn
+			}
+			glog.V(2).Infof("connection mismatch: %+v (%T) != %+v (%T)", conn.conn, conn.conn, dc, dc)
```
Comment (uri200) [inline feg/gateway/diameter/connection_manager.go:133]: do we really need this line anymore?

File: feg/gateway/diameter/diameter_client.go [hunk 2]
```diff
@@ -133,21 +133,66 @@ func NewClient(clientCfg *DiameterClientConfig) *Client {
...
+
+						time.Sleep(backoff)
+						backoff *= 2
+					}
+				}(conn)
+			} else {
+				glog.Errorf("cannot find connection for %s", connStr)
+			}
+		} else {
+			glog.Error(err)
```
Comment (uri200) [inline feg/gateway/diameter/diameter_client.go:194]: since err is `diam.ErrorReport` , wouldn't it be better to print the whole thing with %+v

File: feg/gateway/diameter/connection_manager.go [hunk 3]
```diff
@@ -98,12 +112,45 @@ func (cm *ConnectionManager) DisableFor(period time.Duration) {
...
+// Find returns connection object matching given diameter connection or nil if not found
+func (cm *ConnectionManager) Find(dc diam.Conn) *Connection {
+	if cm == nil || dc == nil {
+		return nil
+	}
+	cm.rwl.RLock()
+	defer cm.rwl.RUnlock()
+	for _, conn := range cm.connMap {
+		if conn != nil {
+			if conn.conn == dc {
```
Comment (uri200) [inline feg/gateway/diameter/connection_manager.go:130]: not from this PR, but maybe it would be good to change the field `conn` on the Connection strunct and use  `diamCon`

```
type Connection struct {
	diamConn     diam.Conn         <- this
	metadata *smpeer.Metadata
	server   *DiameterServerConfig
	client   *sm.Client
	mutex    sync.Mutex
}
```

That confused me when I was reading the code

**Review by uri200 — APPROVED** [review]

File: feg/gateway/diameter/connection_manager.go (hunk 1 above)
Comment (emakeev) [reply feg/gateway/diameter/connection_manager.go:133]: it's V(2) - shouldn't show up in regular logs, but can be useful in the future debugging

File: feg/gateway/diameter/diameter_client.go (hunk 2 above)
Comment (emakeev) [reply feg/gateway/diameter/diameter_client.go:194]: String() of ErrorReport pretty much stringifies anything that is useful in it, *Message wold be irrelevant to the error cause anyway.

Comment (uri200) [reply feg/gateway/diameter/diameter_client.go:194]: Ya that is right. I thought the object may have a stringify method. But it does not.
