### PR TITLE
fix(agw): Added code to handle sctp-reset when s1ap task and mme_app task goes out of sync

### LINKED ISSUE #8854: mme asserts seg fault when number of UE between eNB / mme s1 ids is mismatch
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Your Environment

- **Version:** 1.5 agw
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** MME
- **Deployment Environment:** AWS (orc8r), bare-metal (AGW)

### Describe the Issue

MME in operation asserted seg fault when UE counts were miss aligned with eNB. This assert caused restart of SCTPd, mme, mobilityd, and pipelined. 

**To Reproduce**
1. Unknown

**Expected behavior**
Can such a scenario be handled gracefully without service restarts? 

**Syslog Snippet**
```
Aug 24 20:37:33 FreedomFi-Gateway state[30266]: DEBUG:root:key IMSI314030000010738:directory_record already read on this iteration, skipping
Aug 24 20:37:33 FreedomFi-Gateway state[30266]: DEBUG:root:key IMSI314030000010735:directory_record already read on this iteration, skipping
Aug 24 20:37:33 FreedomFi-Gateway state[30266]: DEBUG:root:key IMSI314030000010747:directory_record already read on this iteration, skipping
Aug 24 20:37:33 FreedomFi-Gateway state[30266]: DEBUG:root:key IMSI314030000010739:directory_record already read on this iteration, skipping
Aug 24 20:37:33 FreedomFi-Gateway state[30266]: DEBUG:root:key IMSI314030000024172:directory_record already read on this iteration, skipping
Aug 24 20:37:33 FreedomFi-Gateway state[30266]: DEBUG:root:key IMSI314030000010749:directory_record already read on this iteration, skipping
Aug 24 20:37:33 FreedomFi-Gateway state[30266]: DEBUG:root:key IMSI314030000010736:directory_record already read on this iteration, skipping
Aug 24 20:37:33 FreedomFi-Gateway state[30266]: DEBUG:root:key IMSI314030000010731:directory_record already read on this iteration, skipping
Aug 24 20:37:33 FreedomFi-Gateway state[30266]: DEBUG:root:key IMSI314030000010378:directory_record already read on this iteration, skipping
Aug 24 20:37:33 FreedomFi-Gateway state[30266]: DEBUG:root:key IMSI314030000010748:directory_record already read on this iteration, skipping
Aug 24 20:37:33 FreedomFi-Gateway state[30266]: DEBUG:root:key IMSI314030000010742:directory_record already read on this iteration, skipping
Aug 24 20:37:33 FreedomFi-Gateway state[30266]: DEBUG:root:key IMSI314030000010743:directory_record already read on this iteration, skipping
Aug 24 20:37:33 FreedomFi-Gateway control_proxy[8846]: 2021-08-24T20:37:33.514Z [127.0.0.1 -> state-controller.freedomfi.com,8443] “POST /magma.orc8r.StateService/ReportStates HTTP/2” 200 5bytes 0.087s
Aug 24 20:37:33 FreedomFi-Gateway state[30266]: DEBUG:root:Successfully replicated state for: deviceID: IMSI314030000010743,type: SPGW, version: 49814
Aug 24 20:37:33 FreedomFi-Gateway state[30266]: DEBUG:root:Successfully replicated state for: deviceID: IMSI314030000010743,type: MME, version: 185613
Aug 24 20:37:33 FreedomFi-Gateway state[30266]: DEBUG:root:Not garbage collecting state. No state to delete!
Aug 24 20:37:33 FreedomFi-Gateway state[30266]: DEBUG:root:
Aug 24 20:37:33 FreedomFi-Gateway smsd[30223]: INFO:root:mme non_eps_service_config is not SMS_ORC8R, sleeping.
Aug 24 20:37:34 FreedomFi-Gateway sctpd[29962]: I0824 20:37:34.923867 30736 sctp_connection.cpp:167] HandleClientSock sd = 21
Aug 24 20:37:34 FreedomFi-Gateway sctpd[29962]: I0824 20:37:34.923938 30736 sctp_connection.cpp:189] SCTP association change event received
Aug 24 20:37:34 FreedomFi-Gateway sctpd[29962]: I0824 20:37:34.923957 30736 sctp_connection.cpp:291] Handling sctp reset
Aug 24 20:37:34 FreedomFi-Gateway mme[9435]: Assertion (enb_association->nb_ue_associated == enb_association->ue_id_coll.num_elements) failed!
Aug 24 20:37:34 FreedomFi-Gateway mme[9435]: In s1ap_handle_sctp_disconnection() /home/admin/workspace/build/build_agw_packages/lte/gateway/c/oai/tasks/s1ap/s1ap_mme_handlers.c:3684
Aug 24 20:37:34 FreedomFi-Gateway mme[9435]: Num UEs associated with eNB (21) is more than the UEs with valid mme_ue_s1ap_id (13). This is a deadlock state potentially caused by misbehaving eNB; restarting MME. In stateless mode, health management service will eventually detect multiple MME restarts due t
Aug 24 20:37:34 FreedomFi-Gateway mme[9435]:  Will Intentionaly raise SEGFAULT to be catched by GDB!
Aug 24 20:37:34 FreedomFi-Gateway mme[9435]: Received SGW IP Address 0x628000007f50
Aug 24 20:37:34 FreedomFi-Gateway mme[9435]: Obtained 7 stack frames.
Aug 24 20:37:34 FreedomFi-Gateway mme[9435]: /usr/local/bin/mme(display_backtrace+0x20) [0x55a679d75b81]
Aug 24 20:37:34 FreedomFi-Gateway mme[9435]: /usr/local/bin/mme(s1ap_handle_sctp_disconnection+0x2fd) [0x55a679ddac94]
Aug 24 20:37:34 FreedomFi-Gateway mme[9435]: /usr/local/bin/mme(+0x8272dd) [0x55a679d882dd]
Aug 24 20:37:34 FreedomFi-Gateway mme[9435]: /usr/lib/x86_64-linux-gnu/libczmq.so.4(zloop_start+0x47e) [0x7f87cd5127be]
Aug 24 20:37:34 FreedomFi-Gateway mme[9435]: /usr/local/bin/mme(+0x826d44) [0x55a679d87d44]
Aug 24 20:37:34 FreedomFi-Gateway mme[9435]: /lib/x86_64-linux-gnu/libpthread.so.0(+0x74a4) [0x7f87cfcf14a4]
Aug 24 20:37:34 FreedomFi-Gateway mme[9435]: /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7f87cc064d0f]
Aug 24 20:37:34 FreedomFi-Gateway kernel: TASK_S1AP[9619]: segfault at 0 ip 000055a679ddacab sp 00007f87b9bbbca0 error 6 in mme[55a679561000+113e000]
Aug 24 20:37:34 FreedomFi-Gateway sctpd[29962]: I0824 20:37:34.943938 30736 sctp_connection.cpp:167] HandleClientSock sd = 21
Aug 24 20:37:34 FreedomFi-Gateway sctpd[29962]: I0824 20:37:34.944036 30736 sctp_connection.cpp:220] [sd:21] msg of len 38 on 13:0
Aug 24 20:37:34 FreedomFi-Gateway systemd[1]: Started Process Core Dump (PID 29041/UID 0).
Aug 24 20:37:34 FreedomFi-Gateway systemd-coredump[29042]: Core file was truncated to 1000000 bytes.
Aug 24 20:37:35 FreedomFi-Gateway systemd-coredump[29042]: Process 9435 (mme) of user 0 dumped core.
                                                           Stack trace of thread 9619:
                                                           #0  0x000055a679ddacab s1ap_handle_sctp_disconnection (/usr/local/bin/mme)
Aug 24 20:37:35 FreedomFi-Gateway sctpd[29962]: I0824 20:37:35.057359 30736 sctpd_uplink_client.cpp:38] sctpul.sendul error
Aug 24 20:37:35 FreedomFi-Gateway sctpd[29962]: I0824 20:37:35.057426 30736 sctpd_uplink_client.cpp:39] grpc error (14): OS Error
Aug 24 20:37:35 FreedomFi-Gateway systemd[1]: magma@mme.service: Main process exited, code=killed, status=11/SEGV
Aug 24 20:37:35 FreedomFi-Gateway systemd[1]: magma@td-agent-bit.service: Service hold-off time over, scheduling restart.
Aug 24 20:37:35 FreedomFi-Gateway systemd[1]: Stopped TD Agent Bit.
Aug 24 20:37:35 FreedomFi-Gateway systemd[1]: Starting TD Agent Bit...
Aug 24 20:37:35 FreedomFi-Gateway systemd[1]: magma@mme.service: Unit entered failed state.
Aug 24 20:37:35 FreedomFi-Gateway systemd[1]: magma@mme.service: Failed with result ‘signal’.
Aug 24 20:37:36 FreedomFi-Gateway env[29051]: WARNING:root:Error loading yml config
Aug 24 20:37:36 FreedomFi-Gateway systemd[1]: Started TD Agent Bit.
Aug 24 20:37:36 FreedomFi-Gateway td-agent-bit[29056]: Fluent Bit v1.8.3

```
@ardzoht Amar said you may have seen such issues before.

### PR DESCRIPTION
**Pull request by rsarwad**
Added code to handle sctp-reset when s1ap task and mme_app task goes out of sync

## Summary
The PR fixes the issue, https://github.com/magma/magma/issues/8854
Changes are made as discussed in issue, https://github.com/magma/magma/issues/8854
1.  On reception of sctp-reset, if s1ap task finds miss-match between nb_ue_associated and number of entries within ue_id_coll hash list. S1ap task shall move all the UEs to idle mode for UEs that are present in hash list, ue_id_coll
2. If there are no entries present hash list, ue_id_coll; then s1ap task shall clear local ue contexts from hash list, s1ap_ue_state and update the counter, nb_ue_associated.
3. Once nb_ue_associated become zero; move the eNB state to INIT state.
4. While handling multiple UEs, there could be scenario such that s1ap task received sctp-reset while mme_app task is processing initial ue messages; as part of which mme_app task assigns mme_ue_s1ap_id and notifies to s1ap task. 
If s1ap is processing sctp-reset message then s1ap task will reject the mme_ue_s1ap_id notification from mme_app task and send de-reg indication to mme_app task.
## Test Plan
To re-create the scenario, modified code at both s1ap task and mme_app task. Following modifications are made
1. Added sleep at mme_app task after processing 5 UEs and added sleep at s1ap task after processing 6 UEs
2. Increased 3460 timer value, because of added sleep; it was always expiring and was taking into different scenario
3. By default, while test case exits. s1ap task would send sctp-shut down, in order to get sctp-reset; commented the code not to send sctp-shutdown message

Patch file with these modification shall be uploaded

[re_creat_sctp_reset.zip](https://github.com/magma/magma/files/8160877/re_creat_sctp_reset.zip)

### CODE REVIEW

File: lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.c [hunk 1]
```diff
@@ -3626,21 +3666,47 @@ status_code_e s1ap_handle_sctp_disconnection(s1ap_state_t* state,
...
-        enb_association->nb_ue_associated ==
-            enb_association->ue_id_coll.num_elements,
-        "Num UEs associated with eNB (%u) is more than the UEs with valid "
-        "mme_ue_s1ap_id (%zu). This is a deadlock state potentially caused by "
-        "misbehaving eNB; restarting MME. In stateless mode, health management "
-        "service will eventually detect multiple MME restarts due to this "
-        "deadlock state and force sctpd and hence all services to restart.",
-        enb_association->nb_ue_associated,
-        enb_association->ue_id_coll.num_elements);
+    /* Check if the UE counters for eNB are equal.
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.c]: Please put this logic in a function call, so it can be reused during Sctp reset and at S1Setup request

File: lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.c [hunk 2]
```diff
@@ -511,21 +523,57 @@ status_code_e s1ap_mme_handle_s1_setup_request(s1ap_state_t* state,
...
+          num_elements++;
+          oldnode = node;
+          node = node->next;
+          if (oldnode->data) {
+            unlock = false;
+            pthread_mutex_unlock(&hashtblP->lock_nodes[i]);
+            s1ap_remove_ue(state, node->data);
+          }
+        }
+        if (unlock) {
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.c]: When is unlock set to true?

File: lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.c [hunk 3]
```diff
@@ -511,21 +523,57 @@ status_code_e s1ap_mme_handle_s1_setup_request(s1ap_state_t* state,
...
+          node = hashtblP->nodes[i];
+        }
+        while (node) {
+          num_elements++;
+          oldnode = node;
+          node = node->next;
+          if (oldnode->data) {
+            unlock = false;
+            pthread_mutex_unlock(&hashtblP->lock_nodes[i]);
+            s1ap_remove_ue(state, node->data);
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.c]: Considering a multi-eNB setup, we need to check if this UE was connected to the particular eNB which is resetting

**Review by ssanadhya — CHANGES_REQUESTED** [review]

File: lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.c (hunk 2 above)
Comment (rsarwad) [reply lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.c]: During initialization unlock is set true, https://github.com/magma/magma/pull/11869/files#diff-cacc260c2f044ba3a92919fafccb6e8c903d33b8900a88ddd94758793792cc3bR538

Comment (ssanadhya) [reply lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.c]: Yes, but once it is set to `false` in line 555 above, it is never reset to `true`. So once it is set to false, none of the locks will get released.

Comment (rsarwad) [reply lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.c]: Okay got it
I shall set to true at the start of while loop, https://github.com/magma/magma/pull/11869/files#diff-cacc260c2f044ba3a92919fafccb6e8c903d33b8900a88ddd94758793792cc3bR546

File: lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.c (hunk 3 above)
Comment (rsarwad) [reply lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.c]: Yes I verified the changes for multi eNB scenario using test case, test_multi_enb_multi_ue.py. The changes are working fine

Comment (ssanadhya) [reply lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.c]: Did you check for the scenario where:
1. Two eNBs connect to MME, with some UEs per eNB
2. One eNB sends SCTP reset while non-zero UEs are connected and the metrics for that eNB are out of sync.

File: lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.c [hunk 4]
```diff
@@ -450,7 +450,10 @@ static status_code_e s1ap_clear_ue_ctxt_for_unknown_mme_ue_s1ap_id(
       num_elements++;
       oldnode = node;
       node = node->next;
-      if (oldnode->data) {
+      if (oldnode->data &&
+          (sctp_assoc_id ==
+           ((ue_description_t*)oldnode->data)->sctp_assoc_id)) {
+        OAILOG_ERROR(LOG_S1AP, "Rashmi--------assoc ID matches ");
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.c]: Please clean up log message

**Review by ssanadhya — CHANGES_REQUESTED** [review]

File: lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.c [hunk 5]
```diff
@@ -416,6 +428,44 @@ void clean_stale_enb_state(s1ap_state_t* state,
...
+    while (node) {
+      num_elements++;
+      oldnode = node;
+      node = node->next;
+      if (oldnode->data &&
+          (sctp_assoc_id ==
+           ((ue_description_t*)oldnode->data)->sctp_assoc_id)) {
+        unlock = false;
+        pthread_mutex_unlock(&hashtblP->lock_nodes[i]);
+        s1ap_remove_ue(state, oldnode->data);
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.c:457]: You need to re-acquire the lock after `s1ap_remove_ue`, since you are still traversing through the list of nodes at `hashtblP->nodes[i]` inside this while loop

**Review by ssanadhya — CHANGES_REQUESTED** [review]

**Review by ssanadhya — APPROVED** [review]
Lgtm, please check the failing CI checks
