### PR TITLE
fix(sessiond): save new session state in redis while waiting for a response from PolicyDB/FeG

### LINKED ISSUE #7867: multi APN concurrent attach some times results in missing sessions on sessiond and pipelind
### Your Environment
Physical Ubuntu AGW
Bridge mode with each UEs coming online with 3 APN associated with them concurrently.
rate of online = 3

- **Version:**  1.6.0-1625058082-58fc8527
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** AGW service pipelined/sessiond
- **Deployment Environment:** bare-metal (AGW), 

- ### Describe the Issue
When UEs gets attached 10 or 20. their state does not match across processes
mobilityd - e.g 60 (20 *3 for 20 UEs and 3 apns)
however sessiond/pipelined show lesser numbers and thus traffic for that subscriber does not work

**To Reproduce**
1. Do UE with 3 or more APN and does network attach

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here (e.g. logs).

`root@phy-u7:/usr/local/bin# pipelined_cli.py enforcement get_policy_usage| grep records| wc -l
118
root@phy-u7:/usr/local/bin# pipelined_cli.py enforcement get_policy_usage| grep internet| wc -l
20
root@phy-u7:/usr/local/bin# pipelined_cli.py enforcement get_policy_usage| grep movefast| wc -l
19
root@phy-u7:/usr/local/bin# pipelined_cli.py enforcement get_policy_usage| grep fbinternal| wc -l
20
root@phy-u7:/usr/local/bin# /home/magma/state_check.sh
MME_state = 20
S1AP_state = 20
SPGQ_state = 20
table0 flows = 303
table12 flows = 120
table13 flows = 238
Mobilityd state = 60

Jun 30 12:10:42 phy-u7 sessiond[11137]: I0630 12:10:42.878383 11137 LocalSessionManagerHandler.cpp:675] Received a LocalCreateSessionRequest for IMSI001011234560509 with APN:fbinternal, default bearer ID:6, PLMN ID:00101, IMSI PLMN ID:00101, User location: 82 00 f1 10 00 01 00 f1 10 00 00 09 01
Jun 30 12:10:42 phy-u7 sessiond[11137]: I0630 12:10:42.880956 11137 LocalSessionManagerHandler.cpp:302] Sending a CreateSessionRequest to fetch policies for IMSI001011234560509-64535
Jun 30 12:10:42 phy-u7 sessiond[11137]: I0630 12:10:42.881470 11137 LocalSessionManagerHandler.cpp:675] Received a LocalCreateSessionRequest for IMSI001011234560509 with APN:movefast, default bearer ID:7, PLMN ID:00101, IMSI PLMN ID:00101, User location: 82 00 f1 10 00 01 00 f1 10 00 00 09 01
Jun 30 12:10:42 phy-u7 sessiond[11137]: I0630 12:10:42.882652 11137 LocalSessionManagerHandler.cpp:302] Sending a CreateSessionRequest to fetch policies for IMSI001011234560509-574531
Jun 30 12:10:42 phy-u7 policydb[9392]: INFO:root:Creating a session for subscriber ID: IMSI001011234560509
Jun 30 12:10:42 phy-u7 policydb[9392]: INFO:root:Creating a session for subscriber ID: IMSI001011234560509
Jun 30 12:10:42 phy-u7 sessiond[11137]: I0630 12:10:42.898571 11137 LocalSessionManagerHandler.cpp:312] Processing a CreateSessionResponse for IMSI001011234560509-574531
Jun 30 12:10:42 phy-u7 sessiond[11137]: I0630 12:10:42.900530 11137 LocalSessionManagerHandler.cpp:319] Successfully initialized new session IMSI001011234560509-574531 in SessionD for subscriber IMSI001011234560509
Jun 30 12:10:42 phy-u7 sessiond[11137]: I0630 12:10:42.901173 11137 LocalSessionManagerHandler.cpp:312] Processing a CreateSessionResponse for IMSI001011234560509-64535
Jun 30 12:10:42 phy-u7 sessiond[11137]: I0630 12:10:42.902446 11137 LocalSessionManagerHandler.cpp:319] Successfully initialized new session IMSI001011234560509-64535 in SessionD for subscriber IMSI001011234560509
Jun 30 12:10:42 phy-u7 directoryd[9387]: INFO:redis_lock.acquire:Got lock for 'lock:IMSI001011234560509:directory_record:lock'.
Jun 30 12:10:42 phy-u7 sctpd[10667]: I0630 12:10:42.910504 10855 sctpd_downlink_impl.cpp:76] SctpdDownlinkImpl::SendDl starting
Jun 30 12:10:42 phy-u7 sctpd[10667]: I0630 12:10:42.911046 10856 sctp_connection.cpp:167] HandleClientSock sd = 64
Jun 30 12:10:42 phy-u7 sctpd[10667]: I0630 12:10:42.911125 10856 sctp_connection.cpp:193] Unhandled notification type 32777
Jun 30 12:10:42 phy-u7 sctpd[10667]: I0630 12:10:42.911170 10856 sctp_connection.cpp:167] HandleClientSock sd = 64
Jun 30 12:10:42 phy-u7 sctpd[10667]: I0630 12:10:42.911208 10856 sctp_connection.cpp:220] [sd:64] msg of len 40 on 59:1
Jun 30 12:10:42 phy-u7 sctpd[10667]: I0630 12:10:42.913213 10856 sctp_connection.cpp:167] HandleClientSock sd = 64
Jun 30 12:10:42 phy-u7 sctpd[10667]: I0630 12:10:42.913312 10856 sctp_connection.cpp:220] [sd:64] msg of len 57 on 59:1
Jun 30 12:10:42 phy-u7 directoryd[9387]: INFO:redis_lock.acquire:Got lock for 'lock:IMSI001011234560509:directory_record:lock'.
Jun 30 12:10:42 phy-u7 mobilityd[11785]: INFO:mobilityd.dhcp.sniff:Record DHCP for: v168.8a_02_9d_a1_ca_00 state: state: OFFER    requested state: DISCOVER mac 8a:02:9d:a1:ca:00 ip 10.22.169.218 subnet 10.22.168.0/22 DHCP: 10.22.168.1 router 10.22.168.1 lease time 2021-06-30 14:10:42.927842, renew 2021-06-30 12:10:42.927877 xid 73 vlan 168
Jun 30 12:10:42 phy-u7 sctpd[10667]: I0630 12:10:42.932338 10856 sctp_connection.cpp:167] HandleClientSock sd = 63
Jun 30 12:10:42 phy-u7 sctpd[10667]: I0630 12:10:42.932438 10856 sctp_connection.cpp:220] [sd:63] msg of len 71 on 58:1
Jun 30 12:10:42 phy-u7 kernel: [ 5437.337332] HTB: quantum of class 10077 is small. Consider r2q change.
Jun 30 12:10:42 phy-u7 sctpd[10667]: I0630 12:10:42.934195 10856 sctp_connection.cpp:167] HandleClientSock sd = 63
Jun 30 12:10:42 phy-u7 sctpd[10667]: I0630 12:10:42.934280 10856 sctp_connection.cpp:220] [sd:63] msg of len 69 on 58:1
Jun 30 12:10:42 phy-u7 sctpd[10667]: I0630 12:10:42.935416 10856 sctp_connection.cpp:167] HandleClientSock sd = 65
Jun 30 12:10:42 phy-u7 sctpd[10667]: I0630 12:10:42.935497 10856 sctp_connection.cpp:220] [sd:65] msg of len 80 on 60:1
Jun 30 12:10:42 phy-u7 sessiond[11137]: I0630 12:10:42.943539 11137 LocalEnforcer.cpp:892] Could not find session for IMSI001011234560509 and bearer 7 during update tunnelIds
Jun 30 12:10:42 phy-u7 kernel: [ 5437.353275] HTB: quantum of class 10040 is small. Consider r2q change.
Jun 30 12:10:42 phy-u7 sctpd[10667]: I0630 12:10:42.959342 10855 sctpd_downlink_impl.cpp:76] SctpdDownlinkImpl::SendDl starting
Jun 30 12:10:42 phy-u7 sctpd[10667]: I0630 12:10:42.959748 10856 sctp_connection.cpp:167] HandleClientSock sd = 64
Jun 30 12:10:42 phy-u7 sctpd[10667]: I0630 12:10:42.959805 10856 sctp_connection.cpp:193] Unhandled notification type 32777
Jun 30 12:10:42 phy-u7 sctpd[10667]: I0630 12:10:42.959837 10856 sctp_connection.cpp:167] HandleClientSock sd = 64
Jun 30 12:10:42 phy-u7 sctpd[10667]: I0630 12:10:42.959874 10856 sctp_connection.cpp:220] [sd:64] msg of len 40 on 59:1
Jun 30 12:10:42 phy-u7 sctpd[10667]: I0630 12:10:42.961226 10856 sctp_connection.cpp:167] HandleClientSock sd = 64
Jun 30 12:10:42 phy-u7 sctpd[10667]: I0630 12:10:42.961318 10856 sctp_connection.cpp:220] [sd:64] msg of len 57 on 59:1
Jun 30 12:10:42 phy-u7 kernel: [ 5437.369187] HTB: quantum of class 10072 is small. Consider r2q change.
Jun 30 12:10:42 phy-u7 kernel: [ 5437.375213] HTB: quantum of class 10076 is small. Consider r2q change.
`

### PR DESCRIPTION
**Pull request by themarwhal**
## Summary
We currently have a bug where SessionD cannot handle concurrent attaches for multiple APNs of a same IMSI. (See attached issue for more info) 
This is due to SessionD holding on to the SessionMap between the time we send a CreateSessionRequest into PolicyDB / FeG and get back a response. This logic makes an assumption that the SessionMap entry for the IMSI does not change during this time. With the multi APN case, this is not a safe assumption to make. 

The solution here is to save the newly created Session BEFORE we send a CreateSessionRequest to PolicyDB / FeG. When we receive back a CreateSessionResponse, one of two things can happen:
1. Success, update the existing session (which we read from SessionStore) with the response and tgpp information.
2. Failure, remove the existing session by using the `is_session_ended` flag in SessionStateUpdateCriteria structure. This will ensure the session will be removed when the map is written back into SessionStore.

## Main Changes
1. When the Session is created (while we wait for the CreateSessionResponse), it will be in a `CREATING` state. When we receive back the response and it is successful, we transition into the `ACTIVE` state. The state here is mostly used for logging, so not much should change here.
2. Logic changes in LocalSessionManagerHandler to reflect the logic above^
3. create session response value in SessionState will now have to be updated via an update criteria. So added some logic to make that happen. (See StoredState.cpp/h and SessionState.cpp)
4. Lots of unit test changes to adapt to the new interfaces

## Test Plan
Ran s1ap tests
Ran CWF integration tests
CI precommit checks

Ran the following on teravm
```
ng40test gxgy05_capacity_oriol.ntl
ng40test gxgy05.ntl
ng40test gxgy04.ntl
ng40test gxgy03.ntl
```

## Additional Information

- [ ] This change is backwards-breaking

Signed-off-by: Marie Bremner <marwhal@fb.com>

### CODE REVIEW

**Comment by pshelar** [comment]
nit: you can use 'refactor' as type for refactoring PR.

**Comment by themarwhal** [comment]
> nit: you can use 'refactor' as type for refactoring PR.

thanks! will change it up.

**Comment by uri200** [comment]
I am going back to the point I made in previous PR: if you are storing the session now before sending the create session request to the core, wouldn't it be better to just add a new `ACTIVATING` state, so instead of having to use that `action` object at recycle session, we can just check the state of the session? 

http://github.com/magma/magma/blob/master/lte/gateway/c/session_manager/Types.h#L149-L149

File: lte/gateway/c/session_manager/LocalSessionManagerHandler.cpp [hunk 1]
```diff
@@ -250,97 +250,137 @@ void LocalSessionManagerHandlerImpl::CreateSession(
...
+            // abort and send back a failure response to access
+            action.set_status(
+                Status(grpc::ABORTED, "Failed to update SessionStore"));
+          }
+        }
+        if (action.status_back_to_access) {
+          send_local_create_session_response(
+              *(action.status_back_to_access), action.session_id_to_send_back,
+              response_callback);
+        }
```
Comment (uri200) [inline lte/gateway/c/session_manager/LocalSessionManagerHandler.cpp:314]: I may be missing the point, but I don't understand the logic here. Is action being used for multiple things? 

Action was the object that defined if a session was in a creating state. But here it seems that it also defines if we have to provide a response to MME? Wouldn't it be better just use booleans and different variables.

Comment (themarwhal) [reply lte/gateway/c/session_manager/LocalSessionManagerHandler.cpp:314]: Maybe the naming is confusing here. It was more of a way to wrap multiple return values into one struct. 
Some things to consider are:
1. Depending on whether we're creating a new session or recycling, the session ID we need to return is different
2. Sometimes we need to end existing sessions for the IMSI+APN pair before sending a request
3. Sometimes we just need to return to MME directly either due to there already being a session (recycling) or some other failure

I wanted a way to return all those information in one struct since whether we decide to recycle or not depends on different logic for each rat type.

Comment (themarwhal) [reply lte/gateway/c/session_manager/LocalSessionManagerHandler.cpp:314]: that's why I called it SessionActionOrStatus so that it contains either 
1. grpc::Status that needs to be returned to MME right away 
2. different actions that need to be taken : end session / create session in policydb , etc.

Comment (themarwhal) [reply lte/gateway/c/session_manager/LocalSessionManagerHandler.cpp:314]: I'll try this clean this up a bit though.

Comment (uri200) [reply lte/gateway/c/session_manager/LocalSessionManagerHandler.cpp:314]: Sure. 

I still think we should be better capturing the state using `ACTIVATING` flag.

But as long as it works i am fine👍

Comment (themarwhal) [reply lte/gateway/c/session_manager/LocalSessionManagerHandler.cpp:314]: Yeah let me attempt using the session state flag. Might be a cleaner approach.

**Review by uri200 — APPROVED** [review]
as long as it works i am fine with either or
