### PR TITLE
fix(amf): AMF support SuciProfile Encryption in Identity procedure

### LINKED ISSUE #13038: [AMF]: Support for SUCI-Profile Encryption in case of Identity-Procedure
**Your Environment**

Version: 1.8.0-1652928411-01faf444
Affected Component: Access Gateway
Affected Subcomponent: AGW service , NMS
Deployment Environment: bare-metal (AGW)-VM Based , Local NMS

**Describe the Issue:**
AMF should support SUCI-Profile Encryption in case of Identity-Procedure.

**To Reproduce**
Step 1 : Register UE with SUCI- Profile-A/Profile-B encryption 
Step 2 : Once the SUCI Registration is Completed , Try to Re-Trigger GUTI-Registration from UE.
 
**Expected behavior**
AMF should support Identity-Procedure  with SUCI-Profile-A / Profile-B

Please find attach logs.
[https://app.zenhub.com/files/170803235/5bbb561c-44e6-4930-9559-8128429bd003/download](https://app.zenhub.com/files/170803235/5bbb561c-44e6-4930-9559-8128429bd003/download)

### PR DESCRIPTION
**Pull request by Akshayp77**
Signed-off-by: Akshayp77 <aksahy.patidar@wavelabs.ai>

## Summary
Fix #13038 , #13708
Handle SUCI-GUTI Registration
AMF Should support SUCI Profile Encryption in case of Identity Procedure.
Add support for SUCI registration in case of Profile B failing due to public key length.
## Test Plan

- Tested with UT
- Tested with Abot
- Tested with Spirent
[SUCI_logs.zip](https://github.com/magma/magma/files/9699019/SUCI_logs.zip)

## Additional Information

- [ ] This change is backwards-breaking

UT_snapshot

### CODE REVIEW

**Comment by maxhbr** [comment]
> Signed-off-by: vagrant [vagrant@magma-dev.magma.com](mailto:vagrant@magma-dev.magma.com)

That is not a valid sign-off, please fix that and use your name

File: lte/gateway/c/core/oai/tasks/amf/amf_recv.cpp [hunk 1]
```diff
@@ -686,48 +687,59 @@ status_code_e amf_handle_identity_response(
         imsi.u.value[2] = ((supi_imsi.plmn.mnc_digit2 << 4) & 0xf0) |
                           (supi_imsi.plmn.mnc_digit3 & 0xf);
       }
+      /* SUPI as IMSI retrieved from SUCI.Generate GUTI based on incoming
```
Comment (panyogesh) [inline lte/gateway/c/core/oai/tasks/amf/amf_recv.cpp]: Comments should be in '//' format

File: lte/gateway/c/core/oai/tasks/amf/amf_recv.cpp [hunk 2]
```diff
@@ -686,48 +687,59 @@ status_code_e amf_handle_identity_response(
...
-    if (ue_context) {
+      /*
+       * Execute the identification completion procedure
+       */
+      rc = amf_proc_identification_complete(ue_id, p_imsi, p_imei, p_imeisv,
+                                            reinterpret_cast<uint32_t*>(p_tmsi),
+                                            amf_ctx_guti);
+      OAILOG_FUNC_RETURN(LOG_NAS_EMM, rc);
+    } else {
+      /*
```
Comment (panyogesh) [inline lte/gateway/c/core/oai/tasks/amf/amf_recv.cpp]: Change comments to '//'

**Review by panyogesh — APPROVED** [review]
LGTM

File: lte/gateway/python/magma/subscriberdb/protocols/m5g_auth_servicer.py [hunk 3]
```diff
@@ -179,11 +179,11 @@ def M5GDecryptMsinSUCIRegistration(self, request, context):
                 profile,
             )
 
-            if len(request.ue_pubkey) != 32:
+            if len(request.ue_pubkey) != 32 and len(request.ue_pubkey) != 33:
```
Comment (sebathomas) [inline lte/gateway/python/magma/subscriberdb/protocols/m5g_auth_servicer.py]: Should we check here that the key length fits the profile (32 for A and 33 for B if I understand it correctly)?

Comment (Akshayp77) [reply lte/gateway/python/magma/subscriberdb/protocols/m5g_auth_servicer.py]: Yes it is needed because unprotect function needs key length 32 bytes in case of Profile A and 33 bytes in case of Profile B.

Comment (sebathomas) [reply lte/gateway/python/magma/subscriberdb/protocols/m5g_auth_servicer.py]: But with the current implementation we don't check the length depending on the profile. So we would allow 33 bytes for profile A.

Comment (Akshayp77) [reply lte/gateway/python/magma/subscriberdb/protocols/m5g_auth_servicer.py]: Added check for public key length depending on the profile.

**Review by sebathomas — APPROVED** [review]
Thanks for adding the check! The Python changes look good to me.

(Sorry for the slow review, I was on holiday last week.)
