### PR TITLE
fix(mme): fix asan error in mme_app_ip_imsi

### LINKED ISSUE #11539: [mme] Invalid read in mme_app_remove_ue_ipv4_addr
Valgrind memcheck report from
https://github.com/magma/magma/blob/a5c1867207866946f2d03717e5a88c3ab5b3c4dd/lte/gateway/c/core/oai/tasks/mme_app/mme_app_ip_imsi.cpp#L116-L122

Trying to access a map element after `erase`
```
 ==304617== Thread 19:
 54 ==304617== Invalid read of size 8
 55 ==304617==    at 0x406B42: __gnu_cxx::__normal_iterator<unsigned long*, std::vector<unsigned long, std::allocator<unsigned long> > >::__normal_iterator(unsigned long* const&) (stl_iterator.h:807)
 56 ==304617==    by 0x405D99: std::vector<unsigned long, std::allocator<unsigned long> >::end() (stl_vector.h:827)
 57 ==304617==    by 0x405365: mme_app_remove_ue_ipv4_addr (mme_app_ip_imsi.cpp:122)
 58 ==304617==    by 0x3E4AC4: mme_app_handle_delete_session_rsp (mme_app_bearer.c:931)
 59 ==304617==    by 0x3E2BAF: handle_message (mme_app_main.c:194)
 60 ==304617==    by 0x5EEA5C6: zloop_start (in /usr/lib/x86_64-linux-gnu/libczmq.so.4.2.0)
 61 ==304617==    by 0x3E3196: mme_app_thread (mme_app_main.c:502)
 62 ==304617==    by 0x535C608: start_thread (pthread_create.c:477)
 63 ==304617==    by 0x65D6292: clone (clone.S:95)
 64 ==304617==  Address 0xb374aa0 is 48 bytes inside a block of size 72 free'd
 65 ==304617==    at 0x483CFBF: operator delete(void*) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
 66 ==304617==    by 0x4087C3: __gnu_cxx::new_allocator<std::__detail::_Hash_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<unsigned long, std::allocator<unsigned long> > >, true> >::deal    locate(std::__detail::_Hash_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<unsigned long, std::allocator<unsigned long> > >, true>*, unsigned long) (new_allocator.h:128)
 67 ==304617==    by 0x407DD2: std::allocator_traits<std::allocator<std::__detail::_Hash_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<unsigned long, std::allocator<unsigned long> > >, t    rue> > >::deallocate(std::allocator<std::__detail::_Hash_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<unsigned long, std::allocator<unsigned long> > >, true> >&, std::__detail::_Has    h_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<unsigned long, std::allocator<unsigned long> > >, true>*, unsigned long) (alloc_traits.h:470)
 68 ==304617==    by 0x4089E2: std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<unsigned long, std::allocator<unsigned lo    ng> > >, true> > >::_M_deallocate_node_ptr(std::__detail::_Hash_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<unsigned long, std::allocator<unsigned long> > >, true>*) (hashtable_pol    icy.h:2113)
 69 ==304617==    by 0x408019: std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<unsigned long, std::allocator<unsigned lo    ng> > >, true> > >::_M_deallocate_node(std::__detail::_Hash_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<unsigned long, std::allocator<unsigned long> > >, true>*) (hashtable_policy.    h:2103)
 70 ==304617==    by 0x408452: std::_Hashtable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<unsigned long, st    d::allocator<unsigned long> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<unsigned long, std::allocator<unsigned long> > > >, std::__detail::_Select1st, std::equal_to<    std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, st    d::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_erase(unsigned long, std::__detail::_Hash_node_base*, std::__detail::_Hash_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::alloc    ator<char> > const, std::vector<unsigned long, std::allocator<unsigned long> > >, true>*) (hashtable.h:1886)
 71 ==304617==    by 0x407984: std::_Hashtable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<unsigned long, st    d::allocator<unsigned long> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<unsigned long, std::allocator<unsigned long> > > >, std::__detail::_Select1st, std::equal_to<    std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, st    d::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_erase(std::integral_constant<bool, true>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (hashtable.h:1912)
 72 ==304617==    by 0x406DB9: std::_Hashtable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<unsigned long, st    d::allocator<unsigned long> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<unsigned long, std::allocator<unsigned long> > > >, std::__detail::_Select1st, std::equal_to<    std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, st    d::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::erase(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (hashtable.h:772)
 73 ==304617==    by 0x405FE6: std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<unsigned long, std::allocator<unsigned long> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<cha    r>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector    <unsigned long, std::allocator<unsigned long> > > > >::erase(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (unordered_map.h:815)
 74 ==304617==    by 0x405315: mme_app_remove_ue_ipv4_addr (mme_app_ip_imsi.cpp:116)
 75 ==304617==    by 0x3E4AC4: mme_app_handle_delete_session_rsp (mme_app_bearer.c:931)
 76 ==304617==    by 0x3E2BAF: handle_message (mme_app_main.c:194)

### LINKED ISSUE #11955: Explore failing //lte/gateway/c/core/oai/test/mme_app_task:mme_procedures_test with --config=asan
- Passes with `--config=lsan` and without `--config`.
- With `--config=asan` we get the logging:
```
TASK_MME_APP terminated
lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp:2435: Failure
Actual function call count doesn't match EXPECT_CALL(*s1ap_handler, s1ap_mme_handle_handover_command( check_params_in_mme_app_handover_command( mme_ue_s1ap_id, new_enb_id)))...
         Expected: to be called once
           Actual: never called - unsatisfied and active
lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp:2424: Failure
Actual function call count doesn't match EXPECT_CALL(*s1ap_handler, s1ap_mme_handle_handover_request( check_params_in_mme_app_handover_request( mme_ue_s1ap_id, 0)))...
         Expected: to be called once
           Actual: never called - unsatisfied and active

```

### PR DESCRIPTION
**Pull request by LKreutzer**
Signed-off-by: Lars Kreutzer <lars.kreutzer@tngtech.com>

## Summary

- Fix asan error in mme_app_ip_imsi 
- Note: Can be applied to current master
- Note: This fixes one of the asan errors found in https://github.com/magma/magma/issues/11955 when running 
  `bazel test //lte/gateway/c/core/oai/test/mme_app_task:mme_procedures_test --test_output=all --config=asan`
  on the `scott/pr-giant-bazel-mme-rebase` branch

### Details
The asan error (`ERROR: AddressSanitizer: heap-use-after-free`) originates from accessing `itr_map->second.end()` after `ueip_imsi_map.erase(ipv4)` has been carried out. In `mme_app_ip_imsi.cpp` line 174 and after:
```
auto itr_map = ueip_imsi_map.find(ipv4);
```
```
if (itr_map->second.empty()) {
          ueip_imsi_map.erase(ipv4);
 }
```
```
if (vec_it == itr_map->second.end()) {...
```

## Test Plan

- Run `make test_oai`
- CI

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

File: lte/gateway/c/core/oai/tasks/mme_app/mme_app_ip_imsi.cpp [hunk 1]
```diff
@@ -191,7 +191,8 @@ void mme_app_remove_ue_ipv4_addr(uint32_t ipv4_addr, imsi64_t imsi64) {
         break;
       }
     }
-    if (vec_it == itr_map->second.end()) {
+    if (ueip_imsi_map.find(ipv4) != ueip_imsi_map.end() &&
```
Comment (themarwhal) [inline lte/gateway/c/core/oai/tasks/mme_app/mme_app_ip_imsi.cpp:194]: Good catch!

**Review by themarwhal — APPROVED** [review]

**Review by ardzoht — APPROVED** [review]
lgtm, thanks for the fix

**Comment by ssanadhya** [comment]
This also fixes https://github.com/magma/magma/issues/11539
