### PR TITLE
test(agw): Negative unit test for dedicated bearers

### LINKED ISSUE #11362: mme: Potentially flaky unit test
GH Action job for MME_TEST
* https://github.com/magma/magma/runs/5011064260?check_suite_focus=true
* https://github.com/magma/magma/runs/5021229013?check_suite_focus=true
* https://github.com/magma/magma/runs/5011521864?check_suite_focus=true
* https://github.com/magma/magma/runs/4998037131?check_suite_focus=true

Seen inside GitHub codespaces
```
[2148/2167] Building CXX object tasks/amf/CMakeFiles/TASK_AMF_APP.dir/amf_client_servicer.cpp.o
[2149/2167] Building CXX object test/amf/CMakeFiles/amf_app_test.dir/util_s6a_update_location.cpp.o
[2150/2167] Linking CXX static library tasks/amf/libTASK_AMF_APP.a
[2151/2167] Building CXX object test/amf/CMakeFiles/amf_app_test.dir/amf_app_test_util.cpp.o
[2152/2167] Building CXX object test/ngap/CMakeFiles/ngap_test.dir/test_ngap_handle_new_association.cpp.o
[2153/2167] Building CXX object test/amf/CMakeFiles/amf_app_test.dir/test_amf_algorithm_selection.cpp.o
[2154/2167] Building CXX object test/amf/CMakeFiles/amf_app_test.dir/test_amf_map.cpp.o
[2155/2167] Building CXX object test/amf/CMakeFiles/amf_app_test.dir/test_amf_common_utils.cpp.o
[2156/2167] Building CXX object test/ngap/CMakeFiles/ngap_test.dir/test_ngap_state_converter.cpp.o
[2157/2167] Building CXX object test/ngap/CMakeFiles/ngap_test.dir/test_ngap_flows.cpp.o
[2158/2167] Building CXX object test/n11/CMakeFiles/auth_service_client.dir/test_auth_service_client.cpp.o
/workspaces/magma/lte/gateway/c/core/oai/test/n11/test_auth_service_client.cpp: In member function ‘virtual void magma::lte::test_get_decrypt_imsi_info_get_decrypt_imsi_info_Test::TestBody()’:
/workspaces/magma/lte/gateway/c/core/oai/test/n11/test_auth_service_client.cpp:130:28: warning: hex escape sequence out of range
  130 |   std::string ciphertext = "\xfc\xf0b\xfc\xad";
      |                            ^~~~~~~~~~~~~~~~~~~
/workspaces/magma/lte/gateway/c/core/oai/test/n11/test_auth_service_client.cpp:131:28: warning: hex escape sequence out of range
  131 |   std::string mac_tag    = "\xa2;\xef\x01\xad\xe1\xd7e";
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
[2159/2167] Linking CXX executable test/ngap/ngap_test
[2160/2167] Linking CXX executable test/n11/auth_service_client
[2161/2167] Building CXX object test/amf/CMakeFiles/amf_app_test.dir/test_amf_procedures.cpp.o
[2162/2167] Building CXX object test/amf/CMakeFiles/amf_app_test.dir/test_amf_stateless.cpp.o
[2163/2167] Building CXX object test/amf/CMakeFiles/amf_app_test.dir/test_amf_encode_decode.cpp.o
[2164/2167] Linking CXX executable oai_mme/mme
[2165/2167] Building CXX object test/mme_app_task/CMakeFiles/mme_app_test.dir/test_mme_procedures.cpp.o
[2166/2167] Linking CXX executable test/amf/amf_app_test
[2167/2167] Linking CXX executable test/mme_app_task/mme_app_test
[16/16] Completed 'MagmaCore'
cd  /workspaces/magma/build/c/core/oai && ctest --output-on-failure -R  ".*"
Test project /workspaces/magma/build/c/core/oai
      Start  1: test_mme_app_ue_context
 1/23 Test  #1: test_mme_app_ue_context ....................   Passed    0.16 sec
      Start  2: test_mme_app_nas_encode_decode
 2/23 Test  #2: test_mme_app_nas_encode_decode .............   Passed    0.02 sec
      Start  3: test_nas_eps_quality_of_service
 3/23 Test  #3: test_nas_eps_quality_of_service ............   Passed    0.02 sec
      Start  4: test_nas_apn_ambr
 4/23 Test  #4: test_nas_apn_ambr ..........................   Passed    0.02 sec
      Start  5: test_mme_app
 5/23 Test  #5: test_mme_app ...............................***Failed   37.58 sec
Initializing OAI Logging
Initializing OAI Logging to syslog
Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163923.16950![==========] Running 91 tests from 5 test suites.
[----------] Global test environment set-up.
[----------] 15 tests from EMMEncodeDecodeTest
[ RUN      ] EMMEncodeDecodeTest.TestDecodeEncodeAttachRequest
[       OK ] EMMEncodeDecodeTest.TestDecodeEncodeAttachRequest (0 ms)
[ RUN      ] EMMEncodeDecodeTest.TestEncodeDecodeAttachRequest2
[       OK ] EMMEncodeDecodeTest.TestEncodeDecodeAttachRequest2 (0 ms)
[ RUN      ] EMMEncodeDecodeTest.TestDecodeAttachRequestPixel
[       OK ] EMMEncodeDecodeTest.TestDecodeAttachRequestPixel (0 ms)
[ RUN      ] EMMEncodeDecodeTest.TestEncodeDecodeEmmInformation
[       OK ] EMMEncodeDecodeTest.TestEncodeDecodeEmmInformation (0 ms)
[ RUN      ] EMMEncodeDecodeTest.TestEncodeDecodeUplinkNasTransport
[       OK ] EMMEncodeDecodeTest.TestEncodeDecodeUplinkNasTransport (0 ms)
[ RUN      ] EMMEncodeDecodeTest.TestEncodeDecodeTAURequest
[       OK ] EMMEncodeDecodeTest.TestEncodeDecodeTAURequest (1 ms)
[ RUN      ] EMMEncodeDecodeTest.TestEncodeDecodeTAUAccept
[       OK ] EMMEncodeDecodeTest.TestEncodeDecodeTAUAccept (0 ms)
[ RUN      ] EMMEncodeDecodeTest.TestEncodeDecodeTAUReject
[       OK ] EMMEncodeDecodeTest.TestEncodeDecodeTAUReject (0 ms)
[ RUN      ] EMMEncodeDecodeTest.TestEncodeDecodeCSServiceNotification
[       OK ] EMMEncodeDecodeTest.TestEncodeDecodeCSServiceNotification (0 ms)
[ RUN      ] EMMEncodeDecodeTest.TestEncodeDecodeAttachAcceptConsecutiveTACs
[       OK ] EMMEncodeDecodeTest.TestEncodeDecodeAttachAcceptConsecutiveTACs (0 ms)
[ RUN      ] EMMEncodeDecodeTest.TestEncodeDecodeSMCCommand
[       OK ] EMMEncodeDecodeTest.TestEncodeDecodeSMCCommand (0 ms)
[ RUN      ] EMMEncodeDecodeTest.TestEncodeDecodeSMCComplete
[       OK ] EMMEncodeDecodeTest.TestEncodeDecodeSMCComplete (0 ms)
[ RUN      ] EMMEncodeDecodeTest.TestEncodeDecodeExtendedServiceRequest
[       OK ] EMMEncodeDecodeTest.TestEncodeDecodeExtendedServiceRequest (0 ms)
[ RUN      ] EMMEncodeDecodeTest.TestEncodeDecodeServiceRequest
[       OK ] EMMEncodeDecodeTest.TestEncodeDecodeServiceRequest (0 ms)
[ RUN      ] EMMEncodeDecodeTest.TestEncodeDecodeAuthenticationResponse
[       OK ] EMMEncodeDecodeTest.TestEncodeDecodeAuthenticationResponse (0 ms)
[----------] 15 tests from EMMEncodeDecodeTest (1 ms total)

[----------] 22 tests from ESMEncodeDecodeTest
[ RUN      ] ESMEncodeDecodeTest.TestActivateDefaultEpsBearerContextRequest
[       OK ] ESMEncodeDecodeTest.TestActivateDefaultEpsBearerContextRequest (0 ms)
[ RUN      ] ESMEncodeDecodeTest.TestActivateDefaultEpsBearerContextAccept
[       OK ] ESMEncodeDecodeTest.TestActivateDefaultEpsBearerContextAccept (0 ms)
[ RUN      ] ESMEncodeDecodeTest.TestActivateDefaultEpsBearerContextReject
[       OK ] ESMEncodeDecodeTest.TestActivateDefaultEpsBearerContextReject (0 ms)
[ RUN      ] ESMEncodeDecodeTest.TestActivateDedicatedEpsBearerContextRequest
[       OK ] ESMEncodeDecodeTest.TestActivateDedicatedEpsBearerContextRequest (0 ms)
[ RUN      ] ESMEncodeDecodeTest.TestActivateDedicatedEpsBearerContextAccept
[       OK ] ESMEncodeDecodeTest.TestActivateDedicatedEpsBearerContextAccept (0 ms)
[ RUN      ] ESMEncodeDecodeTest.TestActivateDedicatedEpsBearerContextReject
[       OK ] ESMEncodeDecodeTest.TestActivateDedicatedEpsBearerContextReject (0 ms)
[ RUN      ] ESMEncodeDecodeTest.TestBearerResourceAllocationRequest
[       OK ] ESMEncodeDecodeTest.TestBearerResourceAllocationRequest (0 ms)
[ RUN      ] ESMEncodeDecodeTest.TestBearerResourceAllocationReject
[       OK ] ESMEncodeDecodeTest.TestBearerResourceAllocationReject (0 ms)
[ RUN      ] ESMEncodeDecodeTest.TestBearerResourceModificationRequest
[       OK ] ESMEncodeDecodeTest.TestBearerResourceModificationRequest (0 ms)
[ RUN      ] ESMEncodeDecodeTest.TestBearerResourceModificationReject
[       OK ] ESMEncodeDecodeTest.TestBearerResourceModificationReject (0 ms)
[ RUN      ] ESMEncodeDecodeTest.TestDeactivateEpsBearerContextRequest
[       OK ] ESMEncodeDecodeTest.TestDeactivateEpsBearerContextRequest (0 ms)
[ RUN      ] ESMEncodeDecodeTest.TestDeactivateEpsBearerContextAccept
[       OK ] ESMEncodeDecodeTest.TestDeactivateEpsBearerContextAccept (0 ms)
[ RUN      ] ESMEncodeDecodeTest.TestEsmInformationRequest
[       OK ] ESMEncodeDecodeTest.TestEsmInformationRequest (0 ms)
[ RUN      ] ESMEncodeDecodeTest.TestEsmInformationResponse
[       OK ] ESMEncodeDecodeTest.TestEsmInformationResponse (1 ms)
[ RUN      ] ESMEncodeDecodeTest.TestEsmStatus
[       OK ] ESMEncodeDecodeTest.TestEsmStatus (0 ms)
[ RUN      ] ESMEncodeDecodeTest.TestModifyEpsBearerContextRequest
[       OK ] ESMEncodeDecodeTest.TestModifyEpsBearerContextRequest (0 ms)
[ RUN      ] ESMEncodeDecodeTest.TestModifyEpsBearerContextAccept
[       OK ] ESMEncodeDecodeTest.TestModifyEpsBearerContextAccept (0 ms)
[ RUN      ] ESMEncodeDecodeTest.TestModifyEpsBearerContextReject
[       OK ] ESMEncodeDecodeTest.TestModifyEpsBearerContextReject (0 ms)
[ RUN      ] ESMEncodeDecodeTest.TestPdnConnectivityRequest
[       OK ] ESMEncodeDecodeTest.TestPdnConnectivityRequest (0 ms)
[ RUN      ] ESMEncodeDecodeTest.TestPdnConnectivityReject
[       OK ] ESMEncodeDecodeTest.TestPdnConnectivityReject (0 ms)
[ RUN      ] ESMEncodeDecodeTest.TestPdnDisconnectRequest
[       OK ] ESMEncodeDecodeTest.TestPdnDisconnectRequest (0 ms)
[ RUN      ] ESMEncodeDecodeTest.TestPdnDisconnectReject
[       OK ] ESMEncodeDecodeTest.TestPdnDisconnectReject (0 ms)
[----------] 22 tests from ESMEncodeDecodeTest (1 ms total)

[----------] 14 tests from MMEConfigTest
[ RUN      ] MMEConfigTest.TestOneTai
[       OK ] MMEConfigTest.TestOneTai (0 ms)
[ RUN      ] MMEConfigTest.TestParTaiListWithConsecutiveTacs
[       OK ] MMEConfigTest.TestParTaiListWithConsecutiveTacs (0 ms)
[ RUN      ] MMEConfigTest.TestTwoParTaiListsWithConsecutiveTacs
[       OK ] MMEConfigTest.TestTwoParTaiListsWithConsecutiveTacs (0 ms)
[ RUN      ] MMEConfigTest.TestParTaiListWithNonConsecutiveTacs
[       OK ] MMEConfigTest.TestParTaiListWithNonConsecutiveTacs (0 ms)
[ RUN      ] MMEConfigTest.TestTwoParTaiListsWithNonConsecutiveTacs
[       OK ] MMEConfigTest.TestTwoParTaiListsWithNonConsecutiveTacs (0 ms)
[ RUN      ] MMEConfigTest.TestTwoParTaiListsWithConsAndNonConsecutiveTacs
[       OK ] MMEConfigTest.TestTwoParTaiListsWithConsAndNonConsecutiveTacs (0 ms)
[ RUN      ] MMEConfigTest.TestParTaiListWithManyPlmns
[       OK ] MMEConfigTest.TestParTaiListWithManyPlmns (0 ms)
[ RUN      ] MMEConfigTest.TestMixedParTaiLists
[       OK ] MMEConfigTest.TestMixedParTaiLists (0 ms)
[ RUN      ] MMEConfigTest.TestParseHealthyConfig
[       OK ] MMEConfigTest.TestParseHealthyConfig (2 ms)
[ RUN      ] MMEConfigTest.TestParseHealthyConfigDisplay
Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163923.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163923.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163923.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163923.16950![       OK ] MMEConfigTest.TestParseHealthyConfigDisplay (7 ms)
[ RUN      ] MMEConfigTest.TestMissingSctpdConfig
[       OK ] MMEConfigTest.TestMissingSctpdConfig (0 ms)
[ RUN      ] MMEConfigTest.TestMissingSctpdUpstreamSockConfig
[       OK ] MMEConfigTest.TestMissingSctpdUpstreamSockConfig (0 ms)
[ RUN      ] MMEConfigTest.TestHealthySctpdConfig
[       OK ] MMEConfigTest.TestHealthySctpdConfig (2 ms)
[ RUN      ] MMEConfigTest.TestCopyAmfConfigFromMMEConfig
Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163923.16950![       OK ] MMEConfigTest.TestCopyAmfConfigFromMMEConfig (2 ms)
[----------] 14 tests from MMEConfigTest (13 ms total)

[----------] 38 tests from MmeAppProcedureTest
[ RUN      ] MmeAppProcedureTest.TestInitialUeMessageFaultyNasMsg

GMOCK WARNING:
/workspaces/magma/lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp:268: Too many actions specified in EXPECT_CALL(*s1ap_handler, s1ap_handle_conn_est_cnf(_))...
Expected to be never called, but has 0 WillOnce()s and a WillRepeatedly().
GMOCK WARNING:
/workspaces/magma/lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp:268: Too many actions specified in EXPECT_CALL(*s1ap_handler, s1ap_handle_ue_context_release_command())...
Expected to be never called, but has 0 WillOnce()s and a WillRepeatedly().
GMOCK WARNING:
/workspaces/magma/lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp:268: Too many actions specified in EXPECT_CALL(*spgw_handler, sgw_handle_delete_session_request())...
Expected to be never called, but has 0 WillOnce()s and a WillRepeatedly().Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163923.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163923.16950!TASK_MME_APP terminated
[       OK ] MmeAppProcedureTest.TestInitialUeMessageFaultyNasMsg (686 ms)
[ RUN      ] MmeAppProcedureTest.TestImsiAttachEpsOnlyDetach
Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163924.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163924.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163924.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163924.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163924.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163924.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163924.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163924.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163924.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163924.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163924.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163924.16950![/workspaces/magma/orc8r/gateway/c/common/config/ServiceConfigLoader.cpp:34] Override file not found for service control_proxy
[/workspaces/magma/orc8r/gateway/c/common/config/ServiceConfigLoader.cpp:34] Override file not found for service service_registry
Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163924.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163924.16950!TASK_MME_APP terminated
[       OK ] MmeAppProcedureTest.TestImsiAttachEpsOnlyDetach (651 ms)
[ RUN      ] MmeAppProcedureTest.TestGutiAttachEpsOnlyDetach
Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163925.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163925.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163925.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163925.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163925.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163925.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163925.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163925.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163925.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163925.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163925.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163925.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163925.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163925.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163925.16950!TASK_MME_APP terminated
[       OK ] MmeAppProcedureTest.TestGutiAttachEpsOnlyDetach (694 ms)
[ RUN      ] MmeAppProcedureTest.TestImsiAttachEpsOnlyAirFailure

GMOCK WARNING:
/workspaces/magma/lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp:481: Too many actions specified in EXPECT_CALL(*s1ap_handler, s1ap_handle_conn_est_cnf(_))...
Expected to be never called, but has 0 WillOnce()s and a WillRepeatedly().
GMOCK WARNING:
/workspaces/magma/lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp:481: Too many actions specified in EXPECT_CALL(*spgw_handler, sgw_handle_delete_session_request())...
Expected to be never called, but has 0 WillOnce()s and a WillRepeatedly().Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163925.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163925.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163925.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163925.16950!TASK_MME_APP terminated
[       OK ] MmeAppProcedureTest.TestImsiAttachEpsOnlyAirFailure (625 ms)
[ RUN      ] MmeAppProcedureTest.TestImsiAttachEpsOnlyAirTimeout

GMOCK WARNING:
/workspaces/magma/lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp:519: Too many actions specified in EXPECT_CALL(*s1ap_handler, s1ap_handle_conn_est_cnf(_))...
Expected to be never called, but has 0 WillOnce()s and a WillRepeatedly().
GMOCK WARNING:
/workspaces/magma/lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp:519: Too many actions specified in EXPECT_CALL(*spgw_handler, sgw_handle_delete_session_request())...
Expected to be never called, but has 0 WillOnce()s and a WillRepeatedly().Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163926.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163926.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163926.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163928.16950!TASK_MME_APP terminated
[       OK ] MmeAppProcedureTest.TestImsiAttachEpsOnlyAirTimeout (2676 ms)
[ RUN      ] MmeAppProcedureTest.TestImsiAttachEpsOnlyAuthMacFailure

GMOCK WARNING:
/workspaces/magma/lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp:554: Too many actions specified in EXPECT_CALL(*s1ap_handler, s1ap_handle_conn_est_cnf(_))...
Expected to be never called, but has 0 WillOnce()s and a WillRepeatedly().
GMOCK WARNING:
/workspaces/magma/lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp:554: Too many actions specified in EXPECT_CALL(*spgw_handler, sgw_handle_delete_session_request())...
Expected to be never called, but has 0 WillOnce()s and a WillRepeatedly().Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163929.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163929.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163929.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163929.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163929.16950!TASK_MME_APP terminated
[       OK ] MmeAppProcedureTest.TestImsiAttachEpsOnlyAuthMacFailure (2677 ms)
[ RUN      ] MmeAppProcedureTest.TestImsiAttachEpsOnlyAuthSynchFailure
Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163931.16950!
GMOCK WARNING:
/workspaces/magma/lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp:609: Too many actions specified in EXPECT_CALL(*s1ap_handler, s1ap_handle_conn_est_cnf(_))...
Expected to be never called, but has 0 WillOnce()s and a WillRepeatedly().
GMOCK WARNING:
/workspaces/magma/lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp:609: Too many actions specified in EXPECT_CALL(*spgw_handler, sgw_handle_delete_session_request())...
Expected to be never called, but has 0 WillOnce()s and a WillRepeatedly().Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163931.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163931.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163931.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163931.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163931.16950!TASK_MME_APP terminated
[       OK ] MmeAppProcedureTest.TestImsiAttachEpsOnlyAuthSynchFailure (2646 ms)
[ RUN      ] MmeAppProcedureTest.TestImsiAttachEpsOnlyUlaFailure

GMOCK WARNING:
/workspaces/magma/lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp:667: Too many actions specified in EXPECT_CALL(*s1ap_handler, s1ap_handle_conn_est_cnf(_))...
Expected to be never called, but has 0 WillOnce()s and a WillRepeatedly().
GMOCK WARNING:
/workspaces/magma/lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp:667: Too many actions specified in EXPECT_CALL(*spgw_handler, sgw_handle_delete_session_request())...
Expected to be never called, but has 0 WillOnce()s and a WillRepeatedly().Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163934.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163934.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163934.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163934.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163934.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163934.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163934.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163934.16950!TASK_MME_APP terminated
[       OK ] MmeAppProcedureTest.TestImsiAttachEpsOnlyUlaFailure (678 ms)
[ RUN      ] MmeAppProcedureTest.TestImsiAttachExpiredNasTimers
Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163934.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163934.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163935.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163935.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163935.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163935.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163935.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163935.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163935.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163935.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163935.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163935.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163935.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163935.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163935.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163935.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163935.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163935.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163935.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163935.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163935.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163935.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163935.16950!TASK_MME_APP terminated
[       OK ] MmeAppProcedureTest.TestImsiAttachExpiredNasTimers (780 ms)
[ RUN      ] MmeAppProcedureTest.TestImsiAttachRejectAuthRetxFailure

GMOCK WARNING:
/workspaces/magma/lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp:817: Too many actions specified in EXPECT_CALL(*s1ap_handler, s1ap_handle_conn_est_cnf(_))...
Expected to be never called, but has 0 WillOnce()s and a WillRepeatedly().
GMOCK WARNING:
/workspaces/magma/lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp:817: Too many actions specified in EXPECT_CALL(*spgw_handler, sgw_handle_delete_session_request())...
Expected to be never called, but has 0 WillOnce()s and a WillRepeatedly().Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163935.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163935.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163935.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163935.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163935.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163935.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163935.16950!TASK_MME_APP terminated
[       OK ] MmeAppProcedureTest.TestImsiAttachRejectAuthRetxFailure (695 ms)
[ RUN      ] MmeAppProcedureTest.TestImsiAttachRejectSmcRetxFailure

GMOCK WARNING:
/workspaces/magma/lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp:855: Too many actions specified in EXPECT_CALL(*s1ap_handler, s1ap_handle_conn_est_cnf(_))...
Expected to be never called, but has 0 WillOnce()s and a WillRepeatedly().
GMOCK WARNING:
/workspaces/magma/lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp:855: Too many actions specified in EXPECT_CALL(*spgw_handler, sgw_handle_delete_session_request())...
Expected to be never called, but has 0 WillOnce()s and a WillRepeatedly().Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163936.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163936.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163936.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163936.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163936.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163936.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163936.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163936.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163936.16950!TASK_MME_APP terminated
[       OK ] MmeAppProcedureTest.TestImsiAttachRejectSmcRetxFailure (673 ms)
[ RUN      ] MmeAppProcedureTest.TestGutiAttachExpiredIdentity
Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163937.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163937.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163937.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163937.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163937.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163937.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163937.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163937.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163937.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163937.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163937.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163937.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163937.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163937.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163937.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163937.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163937.16950!TASK_MME_APP terminated
[       OK ] MmeAppProcedureTest.TestGutiAttachExpiredIdentity (690 ms)
[ RUN      ] MmeAppProcedureTest.TestImsiAttachRejectIdentRetxFailure

GMOCK WARNING:
/workspaces/magma/lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp:993: Too many actions specified in EXPECT_CALL(*s1ap_handler, s1ap_handle_conn_est_cnf(_))...
Expected to be never called, but has 0 WillOnce()s and a WillRepeatedly().
GMOCK WARNING:
/workspaces/magma/lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp:993: Too many actions specified in EXPECT_CALL(*spgw_handler, sgw_handle_delete_session_request())...
Expected to be never called, but has 0 WillOnce()s and a WillRepeatedly().Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163937.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163937.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163937.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163937.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163937.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163937.16950!TASK_MME_APP terminated
[       OK ] MmeAppProcedureTest.TestImsiAttachRejectIdentRetxFailure (2687 ms)
[ RUN      ] MmeAppProcedureTest.TestIcsRequestTimeout
Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163940.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163940.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163940.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163940.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163940.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163940.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163940.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163940.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163940.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163940.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163940.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163940.16950!TASK_MME_APP terminated
[       OK ] MmeAppProcedureTest.TestIcsRequestTimeout (703 ms)
[ RUN      ] MmeAppProcedureTest.TestImsiAttachIcsFailure
Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163941.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163941.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163941.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163941.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163941.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163941.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163941.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163941.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163941.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163941.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163941.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163941.16950!TASK_MME_APP terminated
[       OK ] MmeAppProcedureTest.TestImsiAttachIcsFailure (665 ms)
[ RUN      ] MmeAppProcedureTest.TestCreateSessionFailure

GMOCK WARNING:
/workspaces/magma/lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp:1147: Too many actions specified in EXPECT_CALL(*s1ap_handler, s1ap_handle_conn_est_cnf(_))...
Expected to be never called, but has 0 WillOnce()s and a WillRepeatedly().Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163941.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163941.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163941.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163941.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163941.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163941.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163941.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163941.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163941.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163943.16950!TASK_MME_APP terminated
[       OK ] MmeAppProcedureTest.TestCreateSessionFailure (2706 ms)
[ RUN      ] MmeAppProcedureTest.TestNwInitiatedDetach
Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163944.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163944.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163944.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163944.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163944.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163944.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163944.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163944.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163944.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163944.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163944.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163944.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163944.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163944.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163944.16950!TASK_MME_APP terminated
[       OK ] MmeAppProcedureTest.TestNwInitiatedDetach (681 ms)
[ RUN      ] MmeAppProcedureTest.TestNwInitiatedExpiredDetach
Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163945.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163945.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163945.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163945.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163945.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163945.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163945.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163945.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163945.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163945.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163945.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163945.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163945.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163945.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163945.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163945.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163945.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163945.16950!TASK_MME_APP terminated
[       OK ] MmeAppProcedureTest.TestNwInitiatedExpiredDetach (685 ms)
[ RUN      ] MmeAppProcedureTest.TestNwInitiatedDetachRetxFailure
Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163945.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163945.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163945.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163946.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163946.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163946.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163946.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163946.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163946.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163946.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163946.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163946.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163946.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163946.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163946.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163946.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163946.16950!TASK_MME_APP terminated
[       OK ] MmeAppProcedureTest.TestNwInitiatedDetachRetxFailure (715 ms)
[ RUN      ] MmeAppProcedureTest.TestAttachIdleDetach
Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163946.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163946.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163946.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163946.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163946.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163946.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163946.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163946.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163946.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163946.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163946.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163946.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163946.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163946.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163946.16950!TASK_MME_APP terminated
[       OK ] MmeAppProcedureTest.TestAttachIdleDetach (689 ms)
[ RUN      ] MmeAppProcedureTest.TestAttachIdleServiceReqDetach
Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163947.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163947.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163947.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163947.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163947.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163947.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163947.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163947.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163947.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163947.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163947.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163947.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163947.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163947.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163947.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163947.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163947.16950!TASK_MME_APP terminated
[       OK ] MmeAppProcedureTest.TestAttachIdleServiceReqDetach (643 ms)
[ RUN      ] MmeAppProcedureTest.TestPagingMaxRetx
Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163948.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163948.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163948.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163948.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163948.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163948.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163948.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163948.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163948.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163948.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163948.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163948.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163948.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163948.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163948.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163948.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163948.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163948.16950!TASK_MME_APP terminated
[       OK ] MmeAppProcedureTest.TestPagingMaxRetx (686 ms)
[ RUN      ] MmeAppProcedureTest.TestNwInitiatedActivateDeactivateDedicatedBearerRequest
Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163948.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163948.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163948.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163948.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163948.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163948.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163948.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163948.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163948.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163948.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163948.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163948.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163948.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163948.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163948.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163948.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163948.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163948.16950!TASK_MME_APP terminated
[       OK ] MmeAppProcedureTest.TestNwInitiatedActivateDeactivateDedicatedBearerRequest (680 ms)
[ RUN      ] MmeAppProcedureTest.TestNwInitiatedActivateDeactivateDedicatedBearerWithT3485T3495Expirations
Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163949.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163949.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163949.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163949.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163949.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163949.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163949.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163949.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163949.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163949.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163949.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163949.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163949.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163949.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163949.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163949.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163949.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163949.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163949.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163949.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163949.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163949.16950!TASK_MME_APP terminated
[       OK ] MmeAppProcedureTest.TestNwInitiatedActivateDeactivateDedicatedBearerWithT3485T3495Expirations (768 ms)
[ RUN      ] MmeAppProcedureTest.TestAttachIdlePeriodicTauReqWithActiveFlag
Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163950.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163950.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163950.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163950.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163950.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163950.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163950.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163950.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163950.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163950.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163950.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163950.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163950.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163950.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163950.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163950.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163950.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163950.16950!TASK_MME_APP terminated
[       OK ] MmeAppProcedureTest.TestAttachIdlePeriodicTauReqWithActiveFlag (682 ms)
[ RUN      ] MmeAppProcedureTest.TestAttachIdlePeriodicTauReqWithoutActiveFlag
Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163950.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163950.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163950.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163950.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163950.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163950.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163950.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163950.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163950.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163950.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163950.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163950.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163950.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163950.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163950.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163950.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163950.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163950.16950!TASK_MME_APP terminated
[       OK ] MmeAppProcedureTest.TestAttachIdlePeriodicTauReqWithoutActiveFlag (704 ms)
[ RUN      ] MmeAppProcedureTest.TestAttachIdleNormalTauReqWithActiveFlag
Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163951.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163951.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163951.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163951.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163951.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163951.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163951.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163951.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163951.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163951.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163951.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163951.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163951.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163951.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163951.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163951.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163951.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163951.16950!TASK_MME_APP terminated
[       OK ] MmeAppProcedureTest.TestAttachIdleNormalTauReqWithActiveFlag (686 ms)
[ RUN      ] MmeAppProcedureTest.TestAttachIdleNormalTauReqWithoutActiveFlag
Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163952.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163952.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163952.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163952.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163952.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163952.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163952.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163952.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163952.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163952.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163952.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163952.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163952.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163952.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163952.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163952.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163952.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163952.16950!TASK_MME_APP terminated
[       OK ] MmeAppProcedureTest.TestAttachIdleNormalTauReqWithoutActiveFlag (636 ms)
[ RUN      ] MmeAppProcedureTest.TestAttachNormalTauReqInConnectedState
Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163952.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163952.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163952.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163952.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163952.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163952.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163952.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163952.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163952.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163952.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163952.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163952.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163952.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163952.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163952.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163952.16950!TASK_MME_APP terminated
[       OK ] MmeAppProcedureTest.TestAttachNormalTauReqInConnectedState (716 ms)
[ RUN      ] MmeAppProcedureTest.TestTauRejDueToInvalidTac
Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163953.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163953.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163953.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163953.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163953.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163953.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163953.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163953.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163953.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163953.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163953.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163953.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163953.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163953.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163953.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163953.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163953.16950!TASK_MME_APP terminated
[       OK ] MmeAppProcedureTest.TestTauRejDueToInvalidTac (630 ms)
[ RUN      ] MmeAppProcedureTest.TestFailedPagingForPendingBearers
Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163954.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163954.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163954.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163954.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163954.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163954.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163954.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163954.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163954.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163954.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163954.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163954.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163954.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163954.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163954.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163954.16950!TASK_MME_APP terminated
[       OK ] MmeAppProcedureTest.TestFailedPagingForPendingBearers (686 ms)
[ RUN      ] MmeAppProcedureTest.TestMobileReachabilityTimer
Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163954.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163954.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163954.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163954.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163954.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163954.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163954.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163954.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163954.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163954.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163954.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163954.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163954.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163955.16950!TASK_MME_APP terminated
[       OK ] MmeAppProcedureTest.TestMobileReachabilityTimer (1665 ms)
[ RUN      ] MmeAppProcedureTest.TestX2HandoverPathSwitchSuccess
Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163956.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163956.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163956.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163956.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163956.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163956.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163956.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163956.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163956.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163956.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163956.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163956.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163956.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163956.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163956.16950!TASK_MME_APP terminated
[       OK ] MmeAppProcedureTest.TestX2HandoverPathSwitchSuccess (695 ms)
[ RUN      ] MmeAppProcedureTest.TestX2HandoverPathSwitchFailure
Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163957.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163957.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163957.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163957.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163957.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163957.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163957.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163957.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163957.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163957.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163957.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163957.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163957.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163957.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163957.16950!TASK_MME_APP terminated
[       OK ] MmeAppProcedureTest.TestX2HandoverPathSwitchFailure (699 ms)
[ RUN      ] MmeAppProcedureTest.TestNormalTauReqWithEpsBearerCtxStsInactiveDefBearer
Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163957.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163957.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163957.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163957.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163957.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163957.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163957.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163957.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163957.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163957.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163957.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163957.16950!/workspaces/magma/lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp:3618: Failure
Expected equality of these values:
  decoder_rc
    Which is: -11
  nas_msg->slen
    Which is: 67
Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163957.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163957.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163957.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163957.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163957.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163957.16950!
GMOCK WARNING:
Uninteresting mock function call - returning directly.
    Function call: sgw_handle_nw_initiated_actv_bearer_rsp()
NOTE: You can safely ignore the above warning unless this call should not happen.  Do not suppress it by blindly adding an EXPECT_CALL() if you don't mean to enforce the call.  See https://github.com/google/googletest/blob/master/googlemock/docs/cook_book.md#knowing-when-to-expect for details.
Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163957.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163957.16950!/workspaces/magma/lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp:3567: Failure
Mock function called more times than expected - returning directly.
    Function call: s1ap_generate_downlink_nas_transport(16-byte object <02-00 00-00 00-00 00-00 30-CB 0B-00 20-60 00-00>)
         Expected: to be called 3 times
           Actual: called 4 times - over-saturated and active
Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163957.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163957.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-163957.16950!/workspaces/magma/lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp:3567: Failure
Mock function called more times than expected - returning directly.
    Function call: s1ap_handle_ue_context_release_command()
         Expected: to be called twice
           Actual: called 3 times - over-saturated and active
/workspaces/magma/lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp:3742: Failure
Expected equality of these values:
  mme_state_p->nb_ue_connected
    Which is: 1
  0
TASK_MME_APP terminated
/workspaces/magma/lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp:3567: Failure
Actual function call count doesn't match EXPECT_CALL(*spgw_handler, sgw_handle_modify_bearer_request())...
         Expected: to be called 3 times
           Actual: called twice - unsatisfied and active
/workspaces/magma/lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp:3567: Failure
Actual function call count doesn't match EXPECT_CALL(*s1ap_handler, s1ap_handle_conn_est_cnf(_))...
         Expected: to be called twice
           Actual: called once - unsatisfied and active
[  FAILED  ] MmeAppProcedureTest.TestNormalTauReqWithEpsBearerCtxStsInactiveDefBearer (2658 ms)
[ RUN      ] MmeAppProcedureTest.TestNormalTauReqWithEpsBearerCtxStsInactiveDedBearer
Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-164000.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-164000.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-164000.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-164000.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-164000.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-164000.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-164000.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-164000.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-164000.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-164000.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-164000.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-164000.16950!/workspaces/magma/lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp:3810: Failure
Expected equality of these values:
  decoder_rc
    Which is: -11
  nas_msg->slen
    Which is: 67
Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-164000.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-164000.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-164000.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-164000.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-164000.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-164000.16950!
GMOCK WARNING:
Uninteresting mock function call - returning directly.
    Function call: sgw_handle_nw_initiated_actv_bearer_rsp()
NOTE: You can safely ignore the above warning unless this call should not happen.  Do not suppress it by blindly adding an EXPECT_CALL() if you don't mean to enforce the call.  See https://github.com/google/googletest/blob/master/googlemock/docs/cook_book.md#knowing-when-to-expect for details.
Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-164000.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-164000.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-164000.16950!/workspaces/magma/lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp:3759: Failure
Mock function called more times than expected - returning directly.
    Function call: s1ap_generate_downlink_nas_transport(16-byte object <02-00 00-00 00-00 00-00 50-26 0F-00 20-60 00-00>)
         Expected: to be called 3 times
           Actual: called 4 times - over-saturated and active
/workspaces/magma/lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp:3918: Failure
Expected equality of these values:
  mme_state_p->nb_s1u_bearers
    Which is: 0
  2
Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-164000.16950!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220201-164000.16950!=================================================================
/workspaces/magma/lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp:3759: Failure
Mock function called more times than expected - returning directly.
    Function call: s1ap_handle_ue_context_release_command()
         Expected: to be called twice
           Actual: called 3 times - over-saturated and active
==16950==ERROR: AddressSanitizer: heap-use-after-free on address 0x6110003e3838 at pc 0x5620bad904d9 bp 0x7ff9b74bd130 sp 0x7ff9b74bd120
READ of size 8 at 0x6110003e3838 thread T369
    #0 0x5620bad904d8 in free_esm_bearer_context /workspaces/magma/lte/gateway/c/core/oai/tasks/nas/esm/esm_data_context.c:41
    #1 0x5620ba9885bb in mme_app_free_bearer_context /workspaces/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_bearer_context.c:77
    #2 0x5620ba88b437 in mme_app_ue_context_free_content /workspaces/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_context.c:255
    #3 0x5620ba8947cd in mme_remove_ue_context /workspaces/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_context.c:742
    #4 0x5620ba8bd9bb in mme_app_handle_delete_session_rsp /workspaces/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_bearer.c:1038
    #5 0x5620ba8a3dd1 in handle_message /workspaces/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_main.c:194
    #6 0x7ff9db2a85c6 in zloop_start (/lib/x86_64-linux-gnu/libczmq.so.4+0x295c6)
    #7 0x5620ba8a65f9 in mme_app_thread /workspaces/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_main.c:503
    #8 0x7ff9db2f6608 in start_thread /build/glibc-eX1tMB/glibc-2.31/nptl/pthread_create.c:477
    #9 0x7ff9d9847292 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x122292)

0x6110003e3838 is located 120 bytes inside of 200-byte region [0x6110003e37c0,0x6110003e3888)
freed by thread T369 here:
    #0 0x7ff9dcf897cf in __interceptor_free (/lib/x86_64-linux-gnu/libasan.so.5+0x10d7cf)
    #1 0x5620bb011ee5 in free_wrapper /workspaces/magma/lte/gateway/c/core/oai/common/dynamic_memory_check.c:47
    #2 0x5620ba9885d9 in mme_app_free_bearer_context /workspaces/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_bearer_context.c:78
    #3 0x5620ba8e946f in mme_app_handle_nw_init_bearer_deactv_req /workspaces/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_bearer.c:3398
    #4 0x5620ba8a5447 in handle_message /workspaces/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_main.c:380
    #5 0x7ff9db2a85c6 in zloop_start (/lib/x86_64-linux-gnu/libczmq.so.4+0x295c6)

previously allocated by thread T369 here:
    #0 0x7ff9dcf89bc8 in malloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
    #1 0x5620ba9883c7 in mme_app_create_bearer_context /workspaces/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_bearer_context.c:64
    #2 0x5620bad99573 in esm_ebr_context_create /workspaces/magma/lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr_context.c:145
    #3 0x5620bad7eea3 in esm_proc_dedicated_eps_bearer_context /workspaces/magma/lte/gateway/c/core/oai/tasks/nas/esm/DedicatedEpsBearerContextActivation.c:128
    #4 0x5620badabb26 in esm_sap_send /workspaces/magma/lte/gateway/c/core/oai/tasks/nas/esm/sap/esm_sap.c:211
    #5 0x5620bad3b3fd in emm_cn_activate_dedicated_bearer_req /workspaces/magma/lte/gateway/c/core/oai/tasks/nas/emm/sap/emm_cn.c:781
    #6 0x5620bad40caa in emm_cn_send /workspaces/magma/lte/gateway/c/core/oai/tasks/nas/emm/sap/emm_cn.c:1188
    #7 0x5620bad5e17e in emm_sap_send /workspaces/magma/lte/gateway/c/core/oai/tasks/nas/emm/sap/emm_sap.c:113
    #8 0x5620babd66aa in nas_proc_create_dedicated_bearer /workspaces/magma/lte/gateway/c/core/oai/tasks/nas/nas_proc.c:519
    #9 0x5620ba8e6601 in mme_app_handle_nw_init_ded_bearer_actv_req /workspaces/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_bearer.c:3210
    #10 0x5620ba8a52c7 in handle_message /workspaces/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_main.c:368
    #11 0x7ff9db2a85c6 in zloop_start (/lib/x86_64-linux-gnu/libczmq.so.4+0x295c6)

Thread T369 created by T0 here:
    #0 0x7ff9dceb6805 in pthread_create (/lib/x86_64-linux-gnu/libasan.so.5+0x3a805)
    #1 0x5620bae5f1fd in itti_create_task /workspaces/magma/lte/gateway/c/core/oai/lib/itti/intertask_interface.c:343
    #2 0x5620ba8a6e7a in mme_app_init /workspaces/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_main.c:543
    #3 0x5620ba80a452 in magma::lte::MmeAppProcedureTest::SetUp() (/workspaces/magma/build/c/core/oai/test/mme_app_task/mme_app_test+0x8b1452)
    #4 0x5620bae97030 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) googletest/src/gtest.cc:2433
    #5 0x5620bae97030 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) googletest/src/gtest.cc:2469

SUMMARY: AddressSanitizer: heap-use-after-free /workspaces/magma/lte/gateway/c/core/oai/tasks/nas/esm/esm_data_context.c:41 in free_esm_bearer_context
Shadow bytes around the buggy address:
  0x0c22800746b0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c22800746c0: fd fd fd fd fd fd fd fd fa fa fa fa fa fa fa fa
  0x0c22800746d0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c22800746e0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c22800746f0: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
=>0x0c2280074700: fd fd fd fd fd fd fd[fd]fd fd fd fd fd fd fd fd
  0x0c2280074710: fd fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c2280074720: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c2280074730: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c2280074740: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x0c2280074750: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==16950==ABORTING

      Start  6: test_ngap
 6/23 Test  #6: test_ngap ..................................   Passed    0.18 sec
      Start  7: test_itti
 7/23 Test  #7: test_itti ..................................   Passed    4.23 sec
      Start  8: test_amf_app
 8/23 Test  #8: test_amf_app ...............................   Passed    0.23 sec
      Start  9: test_smf_service_client
 9/23 Test  #9: test_smf_service_client ....................   Passed    0.06 sec
      Start 10: test_auth_service_client
10/23 Test #10: test_auth_service_client ...................   Passed    0.08 sec
      Start 11: test_s1ap
11/23 Test #11: test_s1ap ..................................   Passed   37.10 sec
      Start 12: test_nas_converter
12/23 Test #12: test_nas_converter .........................   Passed    0.08 sec
      Start 13: test_bstr
13/23 Test #13: test_bstr ..................................   Passed    0.02 sec
      Start 14: test_3gpp
14/23 Test #14: test_3gpp ..................................   Passed    0.02 sec
      Start 15: test_openflow_controller
15/23 Test #15: test_openflow_controller ...................   Passed    0.02 sec
      Start 16: test_imsi_encoder
16/23 Test #16: test_imsi_encoder ..........................   Passed    0.02 sec
      Start 17: test_gtp_app
17/23 Test #17: test_gtp_app ...............................   Passed    0.04 sec
      Start 18: test_spgw_state_converter
18/23 Test #18: test_spgw_state_converter ..................   Passed    0.05 sec
      Start 19: test_spgw_procedures
19/23 Test #19: test_spgw_procedures .......................   Passed   36.24 sec
      Start 20: test_pgw_pco
20/23 Test #20: test_pgw_pco ...............................   Passed    0.10 sec
      Start 21: test_spgw_procedures_with_injected_state
21/23 Test #21: test_spgw_procedures_with_injected_state ...   Passed   21.21 sec
      Start 22: test_pipelined_client
22/23 Test #22: test_pipelined_client ......................   Passed    0.03 sec
      Start 23: test_sgw_s8
23/23 Test #23: test_sgw_s8 ................................   Passed   22.56 sec

96% tests passed, 1 tests failed out of 23

Total Test time (real) = 160.09 sec

The following tests FAILED:
          5 - test_mme_app (Failed)
Errors while running CTest
make: *** [Makefile:219: test_oai] Error 8
@themarwhal ➜ /workspaces/magma/lte/gateway (master) $ 
```

### LINKED ISSUE #11493: [MME Unit Tests] Flakiness in MmeAppProcedureTest.TestNormalTauReqWithEpsBearerCtxStsInactiveDefBearer
The test passes in local setup but failed in CI, as seen in https://github.com/magma/magma/runs/5131939859?check_suite_focus=true 

```
[ RUN      ] MmeAppProcedureTest.TestNormalTauReqWithEpsBearerCtxStsInactiveDefBearer
/workspaces/magma/lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp:3618: Failure
Expected equality of these values:
  decoder_rc
    Which is: -11
  nas_msg->slen
    Which is: 67

GMOCK WARNING:
Uninteresting mock function call - returning directly.
    Function call: sgw_handle_nw_initiated_actv_bearer_rsp()
NOTE: You can safely ignore the above warning unless this call should not happen.  Do not suppress it by blindly adding an EXPECT_CALL() if you don't mean to enforce the call.  See https://github.com/google/googletest/blob/master/googlemock/docs/cook_book.md#knowing-when-to-expect for details.
/workspaces/magma/lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp:3567: Failure
Mock function called more times than expected - returning directly.
    Function call: s1ap_generate_downlink_nas_transport(16-byte object <02-00 00-00 00-00 00-00 10-D3 0A-00 20-60 00-00>)
         Expected: to be called 3 times
           Actual: called 4 times - over-saturated and active
/workspaces/magma/lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp:3567: Failure
Mock function called more times than expected - returning directly.
    Function call: s1ap_handle_ue_context_release_command()
         Expected: to be called twice
           Actual: called 3 times - over-saturated and active
/workspaces/magma/lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp:3742: Failure
Expected equality of these values:
  mme_state_p->nb_ue_connected
    Which is: 1
  0
TASK_MME_APP terminated
/workspaces/magma/lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp:3567: Failure
Actual function call count doesn't match EXPECT_CALL(*spgw_handler, sgw_handle_modify_bearer_request())...
         Expected: to be called 3 times
           Actual: called twice - unsatisfied and active
/workspaces/magma/lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp:3567: Failure
Actual function call count doesn't match EXPECT_CALL(*s1ap_handler, s1ap_handle_conn_est_cnf(_))...
         Expected: to be called twice
           Actual: called once - unsatisfied and active
[  FAILED  ] MmeAppProcedureTest.TestNormalTauReqWithEpsBearerCtxStsInactiveDefBearer (687 ms)
[ RUN      ] MmeAppProcedureTest.TestNormalTauReqWithEpsBearerCtxStsInactiveDedBearer
/workspaces/magma/lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp:3810: Failure
Expected equality of these values:
  decoder_rc
    Which is: -11
  nas_msg->slen
    Which is: 67
    
GMOCK WARNING:
Uninteresting mock function call - returning directly.
    Function call: sgw_handle_nw_initiated_actv_bearer_rsp()
NOTE: You can safely ignore the above warning unless this call should not happen.  Do not suppress it by blindly adding an EXPECT_CALL() if you don't mean to enforce the call.  See https://github.com/google/googletest/blob/master/googlemock/docs/cook_book.md#knowing-when-to-expect for details.
/workspaces/magma/lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp:3759: Failure
Mock function called more times than expected - returning directly.
    Function call: s1ap_generate_downlink_nas_transport(16-byte object <02-00 00-00 00-00 00-00 F0-07 0A-00 20-60 00-00>)
         Expected: to be called 3 times
           Actual: called 4 times - over-saturated and active
/workspaces/magma/lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp:3918: Failure
Expected equality of these values:
  mme_state_p->nb_s1u_bearers
    Which is: 0
  2
/workspaces/magma/lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp:3759: Failure
Mock function called more times than expected - returning directly.
    Function call: s1ap_handle_ue_context_release_command()
         Expected: to be called twice
           Actual: called 3 times - over-saturated and active

### PR DESCRIPTION
**Pull request by pruthvihebbani**
test(agw): Negative unit test for dedicated bearers
## Summary

1. Added negative unit tests for dedicated bearer activation and deactivation procedures for mme and spgw
2. Added common functions for attach procedure in test_mme_procedures.cpp and create session procedure in test_spgw_procedures.cpp
3. nas_message_decode() returns number of bytes decoded which is int, but the return value was collected as status_code_e. Fixed this issue.

## Test Plan

- Verified that the tests pass on multiple runs

### CODE REVIEW

File: lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp [hunk 1]
```diff
@@ -4260,5 +4262,370 @@ TEST_F(MmeAppProcedureTest, TestDuplicateAttach) {
...
+  send_activate_message_to_mme_app();
+  cv.wait_for(lock, std::chrono::milliseconds(STATE_MAX_WAIT_MS));
+  EXPECT_EQ(mme_state_p->nb_ue_attached, 1);
+  EXPECT_EQ(mme_state_p->nb_ue_connected, 1);
+  EXPECT_EQ(mme_state_p->nb_default_eps_bearers, 1);
+  EXPECT_EQ(mme_state_p->nb_ue_idle, 0);
+
+  // Send activate dedicated bearer request for lbi 5 mimicing SPGW
+  send_s11_create_bearer_req(5);
+  EXPECT_CALL(*s1ap_handler, s1ap_generate_s1ap_e_rab_setup_req()).Times(1);
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp]: This EXPECT_CALL should be placed before `send_s11_create_bearer_req`, since the ERAB setup request message to S1AP will be triggered by that.

File: lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp [hunk 2]
```diff
@@ -4260,5 +4262,370 @@ TEST_F(MmeAppProcedureTest, TestDuplicateAttach) {
...
+
+  // Send ERAB Setup Response mimicing S1AP
+  send_erab_setup_rsp(6);
+
+  // Constructing and sending Activate Dedicated Bearer Reject to mme_app
+  // mimicing S1AP
+  send_mme_app_uplink_data_ind(
+      nas_msg_activate_ded_bearer_reject,
+      sizeof(nas_msg_activate_ded_bearer_reject), plmn);
+  EXPECT_CALL(*spgw_handler, sgw_handle_nw_initiated_actv_bearer_rsp())
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp]: Move the EXPECT_CALL before call to `send_mme_app_uplink_data_ind`

File: lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp [hunk 3]
```diff
@@ -4260,5 +4262,370 @@ TEST_F(MmeAppProcedureTest, TestDuplicateAttach) {
...
+TEST_F(MmeAppProcedureTest, TestNwInitiatedActivateDedicatedBearerRej) {
+  mme_app_desc_t* mme_state_p =
+      magma::lte::MmeNasStateManager::getInstance().get_state(false);
+  std::condition_variable cv;
+  std::mutex mx;
+  std::unique_lock<std::mutex> lock(mx);
+
+  MME_APP_EXPECT_CALLS(3, 1, 1, 1, 1, 1, 1, 1, 0, 1, 3);
+
+  // Constructing and sending Initial Attach Request to mme_app mimicing S1AP
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp]: The initial attach call flow is repeating in several tests. Is it possible to abstract it into a function?

File: lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp [hunk 4]
```diff
@@ -4260,5 +4262,370 @@ TEST_F(MmeAppProcedureTest, TestDuplicateAttach) {
...
+  EXPECT_EQ(mme_state_p->nb_ue_connected, 1);
+  EXPECT_EQ(mme_state_p->nb_default_eps_bearers, 1);
+  EXPECT_EQ(mme_state_p->nb_s1u_bearers, 2);
+  EXPECT_EQ(mme_state_p->nb_ue_idle, 0);
+
+  uint8_t ebi_to_be_deactivated = 6;
+  // Constructing and sending deactivate bearer request
+  // for dedicated bearer that should trigger ERAB Release Command
+  send_s11_deactivate_bearer_req(1, &ebi_to_be_deactivated, false);
+  EXPECT_CALL(*s1ap_handler, s1ap_generate_s1ap_e_rab_rel_cmd())
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp:2913]: Move EXPECT_CALL before `send_s11_deactivate_bearer_req`

File: lte/gateway/c/core/oai/test/spgw_task/test_spgw_procedures.cpp [hunk 5]
```diff
@@ -1455,5 +1456,494 @@ TEST_F(SPGWAppProcedureTest, TestDeleteBearerCommand) {
...
+  // check that dedicated bearer is not created
+  EXPECT_TRUE(is_num_s1_bearers_valid(ue_sgw_teid, 1));
+
+  // Sleep to ensure that messages are received and contexts are released
+  std::this_thread::sleep_for(std::chrono::milliseconds(END_OF_TEST_SLEEP_MS));
+}
+
+TEST_F(SPGWAppProcedureTest, TestDedicatedBearerDeactivationInvalidImsi) {
+  spgw_state_t* spgw_state  = get_spgw_state(false);
+  status_code_e return_code = RETURNerror;
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/test/spgw_task/test_spgw_procedures.cpp:879]: The default bearer creation is repeated in multiple tests. Is it possible to abstract it into a function call?

File: lte/gateway/c/core/oai/test/spgw_task/test_spgw_procedures.cpp [hunk 6]
```diff
@@ -1455,5 +1456,494 @@ TEST_F(SPGWAppProcedureTest, TestDeleteBearerCommand) {
...
+              sample_gx_nw_init_ded_bearer_deactv_req.no_of_bearers,
+              sample_gx_nw_init_ded_bearer_deactv_req.ebi)))
+      .Times(0);
+
+  return_code = spgw_handle_nw_initiated_bearer_deactv_req(
+      &sample_gx_nw_init_ded_bearer_deactv_req, test_imsi64);
+
+  EXPECT_EQ(return_code, RETURNok);
+
+  // check that there 2 bearers
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/test/spgw_task/test_spgw_procedures.cpp]:
```suggestion
  // check that there are 2 bearers
```

File: lte/gateway/c/core/oai/test/spgw_task/test_spgw_procedures.cpp [hunk 7]
```diff
@@ -1455,5 +1456,494 @@ TEST_F(SPGWAppProcedureTest, TestDeleteBearerCommand) {
...
+              sample_gx_nw_init_ded_bearer_deactv_req.ebi)))
+      .Times(0);
+
+  return_code = spgw_handle_nw_initiated_bearer_deactv_req(
+      &sample_gx_nw_init_ded_bearer_deactv_req, test_imsi64);
+
+  EXPECT_EQ(return_code, RETURNok);
+
+  // verify that the dedicated bearer is not deleted
+  EXPECT_TRUE(is_num_s1_bearers_valid(ue_sgw_teid, 2));
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/test/spgw_task/test_spgw_procedures.cpp]: This is repeat of lines 1735-1755

**Review by ssanadhya — CHANGES_REQUESTED** [review]
Please check if review comments apply to multiple test cases and make respective changes.

File: lte/gateway/c/core/oai/test/spgw_task/test_spgw_procedures.cpp (hunk 7 above)
Comment (pruthvihebbani) [reply lte/gateway/c/core/oai/test/spgw_task/test_spgw_procedures.cpp]: The first call is with invalid IMSI and the second one is with invalid LBI. In both cases call flow will be same

Comment (ssanadhya) [reply lte/gateway/c/core/oai/test/spgw_task/test_spgw_procedures.cpp]: Lines 1783 - 1804 are for invalid LBI.
Lines 1735 - 1755 are for invalid IMSI
Lines 1760 - 1781 are also for invalid IMSI , which is a duplicate

File: lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp [hunk 8]
```diff
@@ -3946,60 +2798,11 @@ TEST_F(MmeAppProcedureTest, TestS1HandoverSuccess) {
...
 
-  // Check MME state after Modify Bearer Response
-  send_activate_message_to_mme_app();
-  cv.wait_for(lock, std::chrono::milliseconds(STATE_MAX_WAIT_MS));
-  EXPECT_EQ(mme_state_p->nb_ue_attached, 1);
-  EXPECT_EQ(mme_state_p->nb_ue_connected, 1);
-  EXPECT_EQ(mme_state_p->nb_default_eps_bearers, 1);
-  EXPECT_EQ(mme_state_p->nb_ue_idle, 0);
-  EXPECT_EQ(mme_state_p->nb_s1u_bearers, 1);
+  // EXPECT_EQ(mme_state_p->nb_s1u_bearers, 1);
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp]: Remove commented code

File: lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp [hunk 9]
```diff
@@ -252,51 +254,19 @@ class MmeAppProcedureTest : public ::testing::Test {
...
-  std::mutex mx;
-  std::unique_lock<std::mutex> lock(mx);
-
-  MME_APP_EXPECT_CALLS(3, 1, 1, 1, 1, 1, 1, 1, 0, 1, 2);
+  void attach_ue(std::condition_variable& cv,
+                 std::unique_lock<std::mutex>& lock,
+                 mme_app_desc_t* mme_state_p, guti_eps_mobile_identity_t* guti);
+};
 
+void MmeAppProcedureTest ::attach_ue(std::condition_variable& cv,
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp:268]: Thanks for adding this and cleaning up all the tests. Can we add a similar function call for detach_ue too?

File: lte/gateway/c/core/oai/test/spgw_task/test_spgw_procedures.cpp [hunk 10]
```diff
@@ -175,12 +176,19 @@ class SPGWAppProcedureTest : public ::testing::Test {
       .qci = 1,
       .gbr = {.br_ul = 200000000, .br_dl = 100000000},
       .mbr = {.br_ul = 200000000, .br_dl = 100000000}};
+
+  void create_default_session(spgw_state_t* spgw_state, teid_t* ue_sgw_teid);
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/test/spgw_task/test_spgw_procedures.cpp]: We can just return `ue_sgw_teid` from this function call, instead of passing pointers around
```suggestion
teid_t create_default_session(spgw_state_t* spgw_state);
```

**Review by ssanadhya — CHANGES_REQUESTED** [review]

File: lte/gateway/c/core/oai/test/spgw_task/test_spgw_procedures.cpp (hunk 10 above)
Comment (pruthvihebbani) [reply lte/gateway/c/core/oai/test/spgw_task/test_spgw_procedures.cpp]: I initially tried returning teid but this throws an error : error: void value not ignored as it ought to be ASSERT_EQ. If we want the function to return non-void value the  ASSERT_EQ  cannot be used in the function. Instead of ASSERT_EQ EXPECT_EQ should be used.  ASSERT_* macros cause termination of test case, EXPECT_* macros continue its evaluation.

Comment (ssanadhya) [reply lte/gateway/c/core/oai/test/spgw_task/test_spgw_procedures.cpp]: Let's use EXPECT_* macros as much as possible, since this is a function call which is mostly used to initialize the UE state before running the actual testing logic (such as dedicated bearer, etc). The expectation is that this should always pass. Further, in case of failure, having the test run fully will help expose multiple points of failures.

**Comment by ssanadhya** [comment]
@pruthvihebbani , please note that https://github.com/magma/magma/pull/11482, which makes changes to SPGW unit tests, will be merged soon. It might cause conflicts with this PR.

**Review by ssanadhya — APPROVED** [review]
LGTM, please resolve merge conflicts and mark as Ready2Merge
