### PR TITLE
fix(sessiond): Handling subscribed qos information coming from AMF

### LINKED ISSUE #11067: PDU Session Establishment is Retrying due to PDU Session Resource Request IE encode error
Magma Build Version
1.7.0-1641423148-a22acdb3
1.7.0-1641418334-fa760796
1.7.0-1641414680-d77cb8c3

Expected Behavior:  PDU Session Establishment should be Accepted and QOS parameters should be updated in PDUSessionResourceSetupRequest and PDU session establishment accept messages.

Actual Behavior:  PDU Session is Retrying due to PDU Session Resource Request IE encode Error.

Please check the attached logs and pcap for more information:
[https://app.zenhub.com/files/170803235/f3e86b7a-eba6-4cc0-b46c-42bb2a295867/download](https://app.zenhub.com/files/170803235/f3e86b7a-eba6-4cc0-b46c-42bb2a295867/download)

### PR DESCRIPTION
**Pull request by GANESH-WAVELABS**
Signed-off-by: GANESH-WAVELABS <ganesh.irrinki@wavelabs.ai>

## Summary
Problem: When static rules are configured in Orc8r via NMS dashboard corresponding QoS info missing ARP values, due to this AMF is failed to encode ARP values as it became mandatory parameter.

Solution: AMF will get APN configuration and default QoS profile with ARP values form subscriberdb and forward to Sessiond during PDU session establishment request, while responding back Sessiond will send back these subscribed qos values back to AMF, so there will not be any encode problem at AMF side.

## Test Plan
1) Tested PDU session establishment and release with sessiond stub CLI `magma/lte/gateway/python/scripts/smf_upf_integration_cli.py`
2) Also tested PDU session establishment and release with gNB simulator.

## Additional Information
1) Dependent AMF PR is #11261 
2) Corresponding zenhub task is #11067

### CODE REVIEW

**Comment by GANESH-WAVELABS** [comment]
PDU session establishment logs:
```
python) vagrant@magma-dev-focal:~/magma/lte/gateway/python/scripts$ ./smf_upf_integration_cli.py amf_context set_amf_session_tc1
=========TEST CASE-1 PDU SESSION ESTABLISHMENT===========
common_context {
  sid {
    id: "IMSI12345"
  }
  ue_ipv4: "192.168.128.11"
  apn: "BLR"
  rat_type: TGPP_NR
}
rat_specific_context {
  m5gsm_session_context {
    pdu_session_id: 1
    ssc_mode: SSC_MODE_3
    gnode_endpoint {
      teid: 10000
      end_ipv4_addr: "192.168.60.141"
    }
    subscribed_qos {
      apn_ambr_dl: 1000000
      apn_ambr_ul: 750000
      priority_level: 1
      preemption_capability: 1
      preemption_vulnerability: 1
      qos_class_id: 9
      br_unit: KBPS
    }
  }
}

Jan 24 18:10:52 magma-dev-focal sessiond[1498212]: I0124 18:10:52.570282 1498356 GrpcMagmaUtils.cpp:58]
Jan 24 18:10:52 magma-dev-focal sessiond[1498212]:   magma.lte.SetSMSessionContext {
Jan 24 18:10:52 magma-dev-focal sessiond[1498212]:       common_context {
Jan 24 18:10:52 magma-dev-focal sessiond[1498212]:         sid {
Jan 24 18:10:52 magma-dev-focal sessiond[1498212]:           id: "IMSI12345"
Jan 24 18:10:52 magma-dev-focal sessiond[1498212]:         }
Jan 24 18:10:52 magma-dev-focal sessiond[1498212]:         ue_ipv4: "192.168.128.11"
Jan 24 18:10:52 magma-dev-focal sessiond[1498212]:         apn: "BLR"
Jan 24 18:10:52 magma-dev-focal sessiond[1498212]:         rat_type: TGPP_NR
Jan 24 18:10:52 magma-dev-focal sessiond[1498212]:       }
Jan 24 18:10:52 magma-dev-focal sessiond[1498212]:       rat_specific_context {
Jan 24 18:10:52 magma-dev-focal sessiond[1498212]:         m5gsm_session_context {
Jan 24 18:10:52 magma-dev-focal sessiond[1498212]:           pdu_session_id: 1
Jan 24 18:10:52 magma-dev-focal sessiond[1498212]:           ssc_mode: SSC_MODE_3
Jan 24 18:10:52 magma-dev-focal sessiond[1498212]:           gnode_endpoint {
Jan 24 18:10:52 magma-dev-focal sessiond[1498212]:             teid: 10000
Jan 24 18:10:52 magma-dev-focal sessiond[1498212]:             end_ipv4_addr: "192.168.60.141"
Jan 24 18:10:52 magma-dev-focal sessiond[1498212]:           }
Jan 24 18:10:52 magma-dev-focal sessiond[1498212]:           subscribed_qos {
Jan 24 18:10:52 magma-dev-focal sessiond[1498212]:             apn_ambr_dl: 1000000
Jan 24 18:10:52 magma-dev-focal sessiond[1498212]:             apn_ambr_ul: 750000
Jan 24 18:10:52 magma-dev-focal sessiond[1498212]:             priority_level: 1
Jan 24 18:10:52 magma-dev-focal sessiond[1498212]:             preemption_capability: 1
Jan 24 18:10:52 magma-dev-focal sessiond[1498212]:             preemption_vulnerability: 1
Jan 24 18:10:52 magma-dev-focal sessiond[1498212]:             qos_class_id: 9
Jan 24 18:10:52 magma-dev-focal sessiond[1498212]:             br_unit: KBPS
Jan 24 18:10:52 magma-dev-focal sessiond[1498212]:           }
Jan 24 18:10:52 magma-dev-focal sessiond[1498212]:         }
Jan 24 18:10:52 magma-dev-focal sessiond[1498212]:       }
Jan 24 18:10:52 magma-dev-focal sessiond[1498212]:   }
Jan 24 18:10:52 magma-dev-focal sessiond[1498212]: I0124 18:10:52.572553 1498212 SetMessageManagerHandler.cpp:152] Requested session from UE with IMSI: IMSI12345 PDU ID 1
```

PDU session release logs:

```
(python) vagrant@magma-dev-focal:~/magma/lte/gateway/python/scripts$ ./smf_upf_integration_cli.py amf_context set_amf_session_tc2
=========TEST CASE-2 PDU SESSION RELEASE============
common_context {
  sid {
    id: "IMSI12345"
  }
  ue_ipv4: "192.168.128.11"
  apn: "BLR"
  rat_type: TGPP_NR
  sm_session_state: RELEASED_4
  sm_session_version: 6
}
rat_specific_context {
  m5gsm_session_context {
    pdu_session_id: 1
    request_type: EXISTING_PDU_SESSION
  }
}

Jan 24 18:11:06 magma-dev-focal sessiond[1498212]:   magma.lte.SetSMSessionContext {
Jan 24 18:11:06 magma-dev-focal sessiond[1498212]:       common_context {
Jan 24 18:11:06 magma-dev-focal sessiond[1498212]:         sid {
Jan 24 18:11:06 magma-dev-focal sessiond[1498212]:           id: "IMSI12345"
Jan 24 18:11:06 magma-dev-focal sessiond[1498212]:         }
Jan 24 18:11:06 magma-dev-focal sessiond[1498212]:         ue_ipv4: "192.168.128.11"
Jan 24 18:11:06 magma-dev-focal sessiond[1498212]:         apn: "BLR"
Jan 24 18:11:06 magma-dev-focal sessiond[1498212]:         rat_type: TGPP_NR
Jan 24 18:11:06 magma-dev-focal sessiond[1498212]:         sm_session_state: RELEASED_4
Jan 24 18:11:06 magma-dev-focal sessiond[1498212]:         sm_session_version: 6
Jan 24 18:11:06 magma-dev-focal sessiond[1498212]:       }
Jan 24 18:11:06 magma-dev-focal sessiond[1498212]:       rat_specific_context {
Jan 24 18:11:06 magma-dev-focal sessiond[1498212]:         m5gsm_session_context {
Jan 24 18:11:06 magma-dev-focal sessiond[1498212]:           pdu_session_id: 1
Jan 24 18:11:06 magma-dev-focal sessiond[1498212]:           request_type: EXISTING_PDU_SESSION
Jan 24 18:11:06 magma-dev-focal sessiond[1498212]:         }
Jan 24 18:11:06 magma-dev-focal sessiond[1498212]:       }
Jan 24 18:11:06 magma-dev-focal sessiond[1498212]:   }
Jan 24 18:11:06 magma-dev-focal sessiond[1498212]: I0124 18:11:06.148466 1498212 SetMessageManagerHandler.cpp:142] Release request for session from IMSI: IMSI12345 pdu_id 1
```

File: lte/gateway/c/session_manager/SessionStateEnforcer.cpp [hunk 1]
```diff
@@ -632,47 +633,56 @@ void SessionStateEnforcer::prepare_response_to_access(
...
-  if (!flag_set) {
-    auto* convg_qos = rsp->mutable_qos();
-    convg_qos->set_qci(FlowQos_Qci_QCI_9);
-    convg_qos->mutable_arp()->set_pre_vulnerability(
-        QosArp_PreVul_PRE_VUL_ENABLED);
-    convg_qos->mutable_arp()->set_pre_capability(QosArp_PreCap_PRE_CAP_ENABLED);
-    convg_qos->mutable_arp()->set_priority_level(1);
+  /* AMBR value need to compared from AMF and PCF, then fill the required
+   * values and sent to AMF. Otherwise sessiond will set default AMBR info.
+   */
```
Comment (uri200) [inline lte/gateway/c/session_manager/SessionStateEnforcer.cpp:672]: where is this comparison happening?

File: lte/gateway/c/session_manager/SessionStateEnforcer.cpp [hunk 2]
```diff
@@ -632,47 +633,56 @@ void SessionStateEnforcer::prepare_response_to_access(
...
+            .preemption_capability());
+    rsp->mutable_subscribed_qos()->set_preemption_vulnerability(
+        config.rat_specific_context.m5gsm_session_context()
+            .subscribed_qos()
+            .preemption_vulnerability());
+    rsp->mutable_subscribed_qos()->set_qos_class_id(
+        config.rat_specific_context.m5gsm_session_context()
+            .subscribed_qos()
+            .qos_class_id());
+
```
Comment (themarwhal) [inline lte/gateway/c/session_manager/SessionStateEnforcer.cpp]: this should be pulled into a separate function to keep this one easy to read

**Comment by themarwhal** [comment]
It looks like MME releated checks are failing on CI.

File: lte/gateway/c/session_manager/SessionStateEnforcer.cpp (hunk 2 above)
Comment (GANESH-WAVELABS) [reply lte/gateway/c/session_manager/SessionStateEnforcer.cpp]: Moved to separate function as suggested.

File: lte/gateway/c/session_manager/SessionStateEnforcer.cpp (hunk 1 above)
Comment (GANESH-WAVELABS) [reply lte/gateway/c/session_manager/SessionStateEnforcer.cpp:672]: Earlier I modified old comment partially, Now I updated the comment accordingly.

**Comment by GANESH-WAVELABS** [comment]
> It looks like MME releated checks are failing on CI.

As session_manager.proto changes also need AMF side code changes this MME related check is failing, this PR has dependency on AMF PR #11261

File: lte/gateway/c/session_manager/SessionStateEnforcer.cpp [hunk 3]
```diff
@@ -583,6 +584,42 @@ void SessionStateEnforcer::m5g_process_response_from_upf(
   }
 }
 
+void SessionStateEnforcer::set_subscribed_qos(
+    SessionState& session_state, magma::SetSMSessionContextAccess* response) {
```
Comment (themarwhal) [inline lte/gateway/c/session_manager/SessionStateEnforcer.cpp]:
```suggestion
    const SessionState& session_state, magma::SetSMSessionContextAccess* response) {
```
This should be const if it's not modified. If it's modified, let's make it a pointer

**Comment by uri200** [comment]
> > It looks like MME releated checks are failing on CI.
> 
> As session_manager.proto changes also need AMF side code changes this MME related check is failing, this PR has dependency on AMF PR #11261 

Do you need the AMF PR to be merged first? Or are both interrelated? 

If so you may need to merge both PRs once they she been reviewed.

**Comment by GANESH-WAVELABS** [comment]
> > > It looks like MME releated checks are failing on CI.
> > 
> > 
> > As session_manager.proto changes also need AMF side code changes this MME related check is failing, this PR has dependency on AMF PR #11261
> 
> Do you need the AMF PR to be merged first? Or are both interrelated?
> 
> If so you may need to merge both PRs once they she been reviewed.

Hi Oriol, Yes #11261 and this PR are interrelated, Yes as you suggested we may merge both PRs once AMF PR gets reviewed.

File: lte/gateway/c/session_manager/SessionStateEnforcer.cpp [hunk 4]
```diff
@@ -583,6 +584,42 @@ void SessionStateEnforcer::m5g_process_response_from_upf(
   }
 }
 
+void SessionStateEnforcer::set_subscribed_qos(
+    SessionState& session_state, magma::SetSMSessionContextAccess* response) {
+  const auto& config = session_state.get_config();
+  auto* rsp = response->mutable_rat_specific_context()
+                  ->mutable_m5g_session_context_rsp();
+
```
Comment (uri200) [inline lte/gateway/c/session_manager/SessionStateEnforcer.cpp:593]: i think this is the same as the other pr 
Use a reference to save some lines
```
      config.rat_specific_context.m5gsm_session_context()
          .subscribed_qos()
```

**Comment by ssanadhya** [comment]
@GANESH-WAVELABS , could you please rebase this PR since #11261 is merged

File: lte/gateway/c/session_manager/SessionStateEnforcer.cpp (hunk 3 above)
Comment (GANESH-WAVELABS) [reply lte/gateway/c/session_manager/SessionStateEnforcer.cpp]: Added `const` as suggested

File: lte/gateway/c/session_manager/SessionStateEnforcer.cpp (hunk 4 above)
Comment (GANESH-WAVELABS) [reply lte/gateway/c/session_manager/SessionStateEnforcer.cpp:593]: Modified the code as suggested.

**Review by uri200 — APPROVED** [review]

**Comment by uri200** [comment]
hey @pshelar  can you take a look at this. I think it needs your approval
