### PR TITLE
fix(mme): Fix gtp_app_test with ASAN enabled

### LINKED ISSUE #11992: Explore failing //lte/gateway/c/core/oai/test/openflow:gtp_app_test with --config=asan
- Running `bazel test //lte/gateway/c/core/oai/test/openflow:gtp_app_test --test_output=all` is passing
- Running `bazel test //lte/gateway/c/core/oai/test/openflow:gtp_app_test --test_output=all --config=lsan` is passing
- Running `bazel test //lte/gateway/c/core/oai/test/openflow:gtp_app_test --test_output=all --config=asan` results in:
```
==22139==ERROR: AddressSanitizer: global-buffer-overflow on address 0x7f70b4e5a894 at pc 0x7f70b23333d0 bp 0x7ffcad0de7f0 sp 0x7ffcad0de7e0
READ of size 1 at 0x7f70b4e5a894 thread T0
    #0 0x7f70b23333cf in mask_ipv6_address lte/gateway/c/core/oai/lib/openflow/controller/GTPApplication.cpp:295
    #1 0x7f70b23338b4 in add_downlink_match_ipv6 lte/gateway/c/core/oai/lib/openflow/controller/GTPApplication.cpp:314
    #2 0x7f70b233bb87 in openflow::GTPApplication::add_downlink_tunnel_flow_ipv6(openflow::AddGTPTunnelEvent const&, openflow::OpenflowMessenger const&, unsigned int, bool, bool) lte/gateway/c/core/oai/lib/openflow/controller/GTPApplication.cpp:491
    #3 0x7f70b233d37f in openflow::GTPApplication::add_downlink_tunnel_flow(openflow::AddGTPTunnelEvent const&, openflow::OpenflowMessenger const&, unsigned int, bool, bool) lte/gateway/c/core/oai/lib/openflow/controller/GTPApplication.cpp:525
    #4 0x7f70b2324719 in openflow::GTPApplication::event_callback(openflow::ControllerEvent const&, openflow::OpenflowMessenger const&) lte/gateway/c/core/oai/lib/openflow/controller/GTPApplication.cpp:55
    #5 0x7f70b23558fb in openflow::OpenflowController::dispatch_event(openflow::ControllerEvent const&) lte/gateway/c/core/oai/lib/openflow/controller/OpenflowController.cpp:107
    #6 0x55851f9e65d7 in TestBody lte/gateway/c/core/oai/test/openflow/test_gtp_app.cpp:607
    #7 0x7f7087b20c8d in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) external/com_google_googletest/googletest/src/gtest.cc:2439
    #8 0x7f7087b08b29 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) external/com_google_googletest/googletest/src/gtest.cc:2475
    #9 0x7f7087a98991 in testing::Test::Run() external/com_google_googletest/googletest/src/gtest.cc:2514
    #10 0x7f7087a9c062 in testing::TestInfo::Run() external/com_google_googletest/googletest/src/gtest.cc:2690
    #11 0x7f7087a9f5ff in testing::TestSuite::Run() external/com_google_googletest/googletest/src/gtest.cc:2822
    #12 0x7f7087ad9b37 in testing::internal::UnitTestImpl::RunAllTests() external/com_google_googletest/googletest/src/gtest.cc:5342
    #13 0x7f7087b270aa in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) external/com_google_googletest/googletest/src/gtest.cc:2439
    #14 0x7f7087b0e48f in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) external/com_google_googletest/googletest/src/gtest.cc:2475
    #15 0x7f7087acdbc5 in testing::UnitTest::Run() external/com_google_googletest/googletest/src/gtest.cc:4930
    #16 0x55851fa4f257 in RUN_ALL_TESTS() external/com_google_googletest/googletest/include/gtest/gtest.h:2472
    #17 0x7f7087ef89ff in main external/com_google_googletest/googlemock/src/gmock_main.cc:63
    #18 0x7f70862eb0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x240b2)
    #19 0x55851f9c13bd in _start (/tmp/bazel/execroot/__main__/bazel-out/k8-dbg/bin/lte/gateway/c/core/oai/test/openflow/gtp_app_test+0xa5d3bd)
```

### PR DESCRIPTION
**Pull request by themarwhal**
Signed-off-by: GitHub <noreply@github.com>

## Summary
Fix a typo to change the iteration size from 46 to 16. (Synched with @pshelar on the issue, he said it's a simple typing error)

## Test Plan
```bash
bazel test //lte/gateway/c/core/oai/test/openflow/... --config=asan --runs_per_test=10
...
INFO: Build completed successfully, 31 total actions
//lte/gateway/c/core/oai/test/openflow:gtp_app_test                      PASSED in 1.6s
  Stats over 10 runs: max = 1.6s, min = 1.4s, avg = 1.5s, dev = 0.1s
//lte/gateway/c/core/oai/test/openflow:imsi_encoder_test                 PASSED in 1.6s
  Stats over 10 runs: max = 1.6s, min = 1.3s, avg = 1.5s, dev = 0.1s
//lte/gateway/c/core/oai/test/openflow:openflow_controller_test          PASSED in 1.6s
  Stats over 10 runs: max = 1.6s, min = 1.5s, avg = 1.6s, dev = 0.0s
```

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Review by pshelar — APPROVED** [review]
LGTM

File: lte/gateway/c/core/oai/lib/openflow/controller/GTPApplication.cpp [hunk 1]
```diff
@@ -291,7 +291,7 @@ static void add_downlink_match(of13::FlowMod& downlink_fm,
 
 static void mask_ipv6_address(uint8_t* dst, const uint8_t* src,
                               const uint8_t* mask) {
-  for (int i = 0; i < INET6_ADDRSTRLEN; i++) {
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/lib/openflow/controller/GTPApplication.cpp:294]: @themarwhal , this macro is being used in other places as well, such as PagingApplication.cpp. It will be good to fix it in all places. cc: @pshelar

**Review by ssanadhya — CHANGES_REQUESTED** [review]

File: lte/gateway/c/core/oai/lib/openflow/controller/GTPApplication.cpp (hunk 1 above)
Comment (pshelar) [reply lte/gateway/c/core/oai/lib/openflow/controller/GTPApplication.cpp:294]: good find, its dup code, needs same fix.

Comment (themarwhal) [reply lte/gateway/c/core/oai/lib/openflow/controller/GTPApplication.cpp:294]: Do you mean this one? https://sourcegraph.com/github.com/magma/magma/-/blob/lte/gateway/c/core/oai/lib/openflow/controller/PagingApplication.cpp?L111 

I can fix that one too in this PR if it's the same issue.

Comment (themarwhal) [reply lte/gateway/c/core/oai/lib/openflow/controller/GTPApplication.cpp:294]: fixed! @ssanadhya

**Review by ssanadhya — APPROVED** [review]
lgtm
