### PR TITLE
test(orc8r): Make TestSingletonRun not flaky

### LINKED ISSUE #13537: Fix flaky cloud tests
* [x] Stabilize TestSingletonRun
  * Fixed in #13646
* [x] Stabilize TestGetSubscriberState
  * Made less flaky in #13565
  * Update: Looks like the error [can still occur](https://github.com/magma/magma/runs/7896850066), it's just much more rare now. We might think about an explicit sleep?
  * Update: An explicit sleep of 1 second [doesn't seem to help](https://github.com/magma/magma/pull/13701)...
* [x] Prepare internal review

Two cloud tests are frequently failing in the CI:

```
=== Failed
=== FAIL: services/state/indexer/reindex TestSingletonRun (4.08s)
I0704 04:22:09.190181    9485 service_config.go:161] Successfully loaded 'orc8r::accessd' service configs from '/etc/magma/configs/orc8r/accessd.yml'
I0704 04:22:09.834319    9485 service_config.go:161] Successfully loaded 'orc8r::certifier' service configs from '/etc/magma/configs/orc8r/certifier.yml'
I0704 04:22:09.834690    9485 service_config.go:161] Successfully loaded 'orc8r::configurator' service configs from '/etc/magma/configs/orc8r/configurator.yml'
I0704 04:22:09.835375    9485 service_config.go:161] Successfully loaded 'orc8r::device' service configs from '/etc/magma/configs/orc8r/device.yml'
I0704 04:22:09.841370    9485 service_config.go:161] Successfully loaded 'orc8r::state' service configs from '/etc/magma/configs/orc8r/state.yml'
    access.go:59: Test Gateway Certificate SN: 344F38CD5A71A1882E54B0EF229CD9F5
    access.go:59: Test Gateway Certificate SN: F6EA3AC40A3238D0D96284E61E9E3432
    access.go:59: Test Gateway Certificate SN: A2ED53B6720C280A294085442E804445
W0704 04:22:10.435740    9485 service_config.go:189] Cannot find '/etc/magma/configs/orc8r/some_indexerid_0.yml': stat /etc/magma/configs/orc8r/some_indexerid_0.yml: no such file or directory, or Legacy Service Registry Configuration: '/etc/magma/orc8r/some_indexerid_0.yml': stat /etc/magma/orc8r/some_indexerid_0.yml: no such file or directory
E0704 04:22:10.435773    9485 service_config.go:159] Error Loading orc8r::some_indexerid_0 configs from '/etc/magma/orc8r/some_indexerid_0.yml': open /etc/magma/orc8r/some_indexerid_0.yml: no such file or directory
W0704 04:22:10.435786    9485 service.go:98] Failed to load config for service some_indexerid_0: open /etc/magma/orc8r/some_indexerid_0.yml: no such file or directory
I0704 04:22:10.478279    9485 reindexer_singleton.go:150] Attempt at state reindex job {id: some_indexerid_0, from: 0, to: 10} took 0.040250 seconds
I0704 04:22:10.578420    9485 reindexer_singleton.go:62] Sleeping for 1 minute(s) before looking for new jobs to reindex
I0704 04:22:10.679095    9485 reindexer_singleton.go:62] Sleeping for 1 minute(s) before looking for new jobs to reindex
I0704 04:22:10.779667    9485 reindexer_singleton.go:62] Sleeping for 1 minute(s) before looking for new jobs to reindex
I0704 04:22:10.880732    9485 reindexer_singleton.go:62] Sleeping for 1 minute(s) before looking for new jobs to reindex
I0704 04:22:10.981176    9485 reindexer_singleton.go:62] Sleeping for 1 minute(s) before looking for new jobs to reindex
I0704 04:22:11.081713    9485 reindexer_singleton.go:62] Sleeping for 1 minute(s) before looking for new jobs to reindex
I0704 04:22:11.182168    9485 reindexer_singleton.go:62] Sleeping for 1 minute(s) before looking for new jobs to reindex
I0704 04:22:11.282710    9485 reindexer_singleton.go:62] Sleeping for 1 minute(s) before looking for new jobs to reindex
I0704 04:22:11.383305    9485 reindexer_singleton.go:62] Sleeping for 1 minute(s) before looking for new jobs to reindex
    reindexer_singleton_test.go:74: PASS:	GetID()
    reindexer_singleton_test.go:74: PASS:	GetVersion()
    reindexer_singleton_test.go:74: PASS:	PrepareReindex(indexer.Version,indexer.Version,bool)
    reindexer_singleton_test.go:74: PASS:	Index(string,string)
    reindexer_singleton_test.go:74: PASS:	CompleteReindex(indexer.Version,indexer.Version)
    reindexer_singleton_test.go:74: PASS:	GetTypes()
W0704 04:22:11.480780    9485 service_config.go:189] Cannot find '/etc/magma/configs/orc8r/some_indexerid_0.yml': stat /etc/magma/configs/orc8r/some_indexerid_0.yml: no such file or directory, or Legacy Service Registry Configuration: '/etc/magma/orc8r/some_indexerid_0.yml': stat /etc/magma/orc8r/some_indexerid_0.yml: no such file or directory
E0704 04:22:11.480806    9485 service_config.go:159] Error Loading orc8r::some_indexerid_0 configs from '/etc/magma/orc8r/some_indexerid_0.yml': open /etc/magma/orc8r/some_indexerid_0.yml: no such file or directory
W0704 04:22:11.480821    9485 service.go:98] Failed to load config for service some_indexerid_0: open /etc/magma/orc8r/some_indexerid_0.yml: no such file or directory
I0704 04:22:11.484486    9485 reindexer_singleton.go:62] Sleeping for 1 minute(s) before looking for new jobs to reindex
I0704 04:22:11.490344    9485 reindexer_singleton.go:150] Attempt at state reindex job {id: some_indexerid_0, from: 10, to: 100} took 0.003831 seconds
I0704 04:22:11.590872    9485 reindexer_singleton.go:62] Sleeping for 1 minute(s) before looking for new jobs to reindex
I0704 04:22:11.691391    9485 reindexer_singleton.go:62] Sleeping for 1 minute(s) before looking for new jobs to reindex
I0704 04:22:11.791837    9485 reindexer_singleton.go:62] Sleeping for 1 minute(s) before looking for new jobs to reindex
I0704 04:22:11.892412    9485 reindexer_singleton.go:62] Sleeping for 1 minute(s) before looking for new jobs to reindex
I0704 04:22:11.992853    9485 reindexer_singleton.go:62] Sleeping for 1 minute(s) before looking for new jobs to reindex
I0704 04:22:12.093329    9485 reindexer_singleton.go:62] Sleeping for 1 minute(s) before looking for new jobs to reindex
I0704 04:22:12.193883    9485 reindexer_singleton.go:62] Sleeping for 1 minute(s) before looking for new jobs to reindex
I0704 04:22:12.294321    9485 reindexer_singleton.go:62] Sleeping for 1 minute(s) before looking for new jobs to reindex
I0704 04:22:12.394754    9485 reindexer_singleton.go:62] Sleeping for 1 minute(s) before looking for new jobs to reindex
    reindexer_singleton_test.go:89: PASS:	GetID()
    reindexer_singleton_test.go:89: PASS:	GetVersion()
    reindexer_singleton_test.go:89: PASS:	PrepareReindex(indexer.Version,indexer.Version,bool)
    reindexer_singleton_test.go:89: PASS:	CompleteReindex(indexer.Version,indexer.Version)
    reindexer_singleton_test.go:89: PASS:	GetTypes()
    reindexer_singleton_test.go:89: PASS:	Index(string,string)
I0704 04:22:12.495309    9485 reindexer_singleton.go:62] Sleeping for 1 minute(s) before looking for new jobs to reindex
I0704 04:22:12.595822    9485 reindexer_singleton.go:62] Sleeping for 1 minute(s) before looking for new jobs to reindex
I0704 04:22:12.696229    9485 reindexer_singleton.go:62] Sleeping for 1 minute(s) before looking for new jobs to reindex
I0704 04:22:12.796639    9485 reindexer_singleton.go:62] Sleeping for 1 minute(s) before looking for new jobs to reindex
I0704 04:22:12.897358    9485 reindexer_singleton.go:62] Sleeping for 1 minute(s) before looking for new jobs to reindex
I0704 04:22:12.998074    9485 reindexer_singleton.go:62] Sleeping for 1 minute(s) before looking for new jobs to reindex
    access.go:59: Test Gateway Certificate SN: ED5E80A6A531700D314F2F2C1F33B846
E0704 04:22:13.021864    9485 interceptors.go:74] [ERROR /magma.orc8r.state.Indexer/Index]: rpc error: code = Unknown desc = handler panic: 
assert: mock: The method has been called over 3 times.
	Either do one more Mock.On("Index").Return(...), or remove extra call.
	This call was unexpected:
		Index(string,types.SerializedStatesByID)
		0: "some_networkid_3"
		1: types.SerializedStatesByID{types.ID{Type:"gw_state", DeviceID:"some_hwid_0"}:types.SerializedState{SerializedReportedState:[]uint8{0x7b, 0x22, 0x6d, 0x65, 0x74, 0x61, 0x22, 0x3a, 0x7b, 0x22, 0x66, 0x6f, 0x6f, 0x22, 0x3a, 0x22, 0x62, 0x61, 0x72, 0x22, 0x7d, 0x7d}, Version:0x0, ReporterID:"some_hwid_3", TimeMs:0x181c771cd1d}}
	at: [Indexer.go:103 test_indexer_servicer.go:52 indexer.pb.go:830 interceptors.go:90 server.go:1116 interceptors.go:90 server.go:1119 server_metrics.go:107 server.go:1119 interceptors.go:65 server.go:1119 interceptors.go:72 server.go:1119 server.go:1121 indexer.pb.go:832 server.go:1282 server.go:1616 server.go:921 asm_amd64.s:1571]; stack trace: goroutine 2382 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
magma/orc8r/cloud/go/service/middleware/unary.recoveryInterceptor.func1()
	/src/magma/orc8r/cloud/go/service/middleware/unary/interceptors.go:61 +0x6b
panic({0xe304e0, 0xc000b369a0})
	/usr/local/go/src/runtime/panic.go:838 +0x207
github.com/stretchr/testify/mock.(*Mock).fail(0xc00164d090, {0xff1ff5?, 0x20?}, {0xc0009cd680?, 0x2?, 0x2?})
	/go/pkg/mod/github.com/stretchr/testify@v1.7.0/mock/mock.go:254 +0x145
github.com/stretchr/testify/mock.(*Mock).MethodCalled(0xc00164d090, {0x1290b78, 0x5}, {0xc0016cffe0, 0x2, 0x2})
	/go/pkg/mod/github.com/stretchr/testify@v1.7.0/mock/mock.go:399 +0x29d
github.com/stretchr/testify/mock.(*Mock).Called(0xc0009ce3a0?, {0xc0016cffe0, 0x2, 0x2})
	/go/pkg/mod/github.com/stretchr/testify@v1.7.0/mock/mock.go:383 +0x148
magma/orc8r/cloud/go/services/state/indexer/mocks.(*Indexer).Index(0xc00164d090, {0xc0009ce3a0, 0x10}, 0xc0009a02d0)
	/src/magma/orc8r/cloud/go/services/state/indexer/mocks/Indexer.go:103 +0xd0
magma/orc8r/cloud/go/services/state/test_init.(*indexerServicer).Index(0xc000920ba0, {0x1115250?, 0x0?}, 0xc0006fcff0)
	/src/magma/orc8r/cloud/go/services/state/test_init/test_indexer_servicer.go:52 +0x64
magma/orc8r/cloud/go/services/state/protos._Indexer_Index_Handler.func1({0x11194e0, 0xc0009a0210}, {0xf17360?, 0xc0006fcff0})
	/src/magma/orc8r/cloud/go/services/state/protos/indexer.pb.go:830 +0x78
magma/orc8r/cloud/go/service/middleware/unary.makeInterceptorFromTemplate.func1({0x11194e0, 0xc0009a0210}, {0xf17360, 0xc0006fcff0}, 0xf341a0?, 0xc000ed66d8)
	/src/magma/orc8r/cloud/go/service/middleware/unary/interceptors.go:90 +0x8b
google.golang.org/grpc.chainUnaryInterceptors.func1.1({0x11194e0?, 0xc0009a0210?}, {0xf17360?, 0xc0006fcff0?})
	/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:1116 +0x5b
magma/orc8r/cloud/go/service/middleware/unary.makeInterceptorFromTemplate.func1({0x11194e0, 0xc0009a0210}, {0xf17360, 0xc0006fcff0}, 0xaa?, 0xc0009cd4c0)
	/src/magma/orc8r/cloud/go/service/middleware/unary/interceptors.go:90 +0x8b
google.golang.org/grpc.chainUnaryInterceptors.func1.1({0x11194e0?, 0xc0009a0210?}, {0xf17360?, 0xc0006fcff0?})
	/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:1119 +0x83
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1({0x11194e0, 0xc0009a0210}, {0xf17360, 0xc0006fcff0}, 0x8caa6f?, 0xc0009cd4c0)
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107 +0x87
google.golang.org/grpc.chainUnaryInterceptors.func1.1({0x11194e0?, 0xc0009a0210?}, {0xf17360?, 0xc0006fcff0?})
	/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:1119 +0x83
magma/orc8r/cloud/go/service/middleware/unary.recoveryInterceptor({0x11194e0?, 0xc0009a0210?}, {0xf17360?, 0xc0006fcff0?}, 0xc0009cd4c0?, 0x8?)
	/src/magma/orc8r/cloud/go/service/middleware/unary/interceptors.go:65 +0xa2
google.golang.org/grpc.chainUnaryInterceptors.func1.1({0x11194e0?, 0xc0009a0210?}, {0xf17360?, 0xc0006fcff0?})
	/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:1119 +0x83
magma/orc8r/cloud/go/service/middleware/unary.errlogInterceptor({0x11194e0?, 0xc0009a0210?}, {0xf17360?, 0xc0006fcff0?}, 0xc0016cffa0, 0x7f5c370a9101?)
	/src/magma/orc8r/cloud/go/service/middleware/unary/interceptors.go:72 +0x49
google.golang.org/grpc.chainUnaryInterceptors.func1.1({0x11194e0?, 0xc0009a0210?}, {0xf17360?, 0xc0006fcff0?})
	/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:1119 +0x83
google.golang.org/grpc.chainUnaryInterceptors.func1({0x11194e0, 0xc0009a0210}, {0xf17360, 0xc0006fcff0}, 0xc0016cffa0, 0xc000ed66d8)
	/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:1121 +0x12b
magma/orc8r/cloud/go/services/state/protos._Indexer_Index_Handler({0xec32a0?, 0xc000920ba0}, {0x11194e0, 0xc0009a0210}, 0xc000cf0d20, 0xc00033c400)
	/src/magma/orc8r/cloud/go/services/state/protos/indexer.pb.go:832 +0x138
google.golang.org/grpc.(*Server).processUnaryRPC(0xc001591340, {0x111c670, 0xc000f88820}, 0xc00189d560, 0xc00106bad0, 0x1912400, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc001591340, {0x111c670, 0xc000f88820}, 0xc00189d560, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:1616 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:919 +0x28a
W0704 04:22:13.022447    9485 service_config.go:189] Cannot find '/etc/magma/configs/orc8r/some_indexerid_5.yml': stat /etc/magma/configs/orc8r/some_indexerid_5.yml: no such file or directory, or Legacy Service Registry Configuration: '/etc/magma/orc8r/some_indexerid_5.yml': stat /etc/magma/orc8r/some_indexerid_5.yml: no such file or directory
E0704 04:22:13.022473    9485 service_config.go:159] Error Loading orc8r::some_indexerid_5 configs from '/etc/magma/orc8r/some_indexerid_5.yml': open /etc/magma/orc8r/some_indexerid_5.yml: no such file or directory
W0704 04:22:13.022485    9485 service.go:98] Failed to load config for service some_indexerid_5: open /etc/magma/orc8r/some_indexerid_5.yml: no such file or directory
I0704 04:22:13.099028    9485 reindexer_singleton.go:62] Sleeping for 1 minute(s) before looking for new jobs to reindex
E0704 04:22:13.131322    9485 remote_indexer.go:140] some_indexerid_0 service client initialization error: service some_indexerid_0 not registered
E0704 04:22:13.163559    9485 interceptors.go:74] [ERROR /magma.orc8r.state.Indexer/Index]: rpc error: code = Unknown desc = handler panic: 
assert: mock: The method has been called over 12 times.
	Either do one more Mock.On("Index").Return(...), or remove extra call.
	This call was unexpected:
		Index(string,types.SerializedStatesByID)
		0: "some_networkid_2"
		1: types.SerializedStatesByID{types.ID{Type:"gw_state", DeviceID:"some_hwid_0"}:types.SerializedState{SerializedReportedState:[]uint8{0x7b, 0x22, 0x6d, 0x65, 0x74, 0x61, 0x22, 0x3a, 0x7b, 0x22, 0x66, 0x6f, 0x6f, 0x22, 0x3a, 0x22, 0x62, 0x61, 0x72, 0x22, 0x7d, 0x7d}, Version:0x0, ReporterID:"some_hwid_2", TimeMs:0x181c771c303}}
	at: [Indexer.go:103 test_indexer_servicer.go:52 indexer.pb.go:830 interceptors.go:90 server.go:1116 interceptors.go:90 server.go:1119 server_metrics.go:107 server.go:1119 interceptors.go:65 server.go:1119 interceptors.go:72 server.go:1119 server.go:1121 indexer.pb.go:832 server.go:1282 server.go:1616 server.go:921 asm_amd64.s:1571]; stack trace: goroutine 2451 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
magma/orc8r/cloud/go/service/middleware/unary.recoveryInterceptor.func1()
	/src/magma/orc8r/cloud/go/service/middleware/unary/interceptors.go:61 +0x6b
panic({0xe304e0, 0xc000fdb130})
	/usr/local/go/src/runtime/panic.go:838 +0x207
github.com/stretchr/testify/mock.(*Mock).fail(0xc0006fd770, {0xff1ff5?, 0x20?}, {0xc00122b5c0?, 0x2?, 0x2?})
	/go/pkg/mod/github.com/stretchr/testify@v1.7.0/mock/mock.go:254 +0x145
github.com/stretchr/testify/mock.(*Mock).MethodCalled(0xc0006fd770, {0x1290b78, 0x5}, {0xc00040dca0, 0x2, 0x2})
	/go/pkg/mod/github.com/stretchr/testify@v1.7.0/mock/mock.go:399 +0x29d
github.com/stretchr/testify/mock.(*Mock).Called(0xc00122d280?, {0xc00040dca0, 0x2, 0x2})
	/go/pkg/mod/github.com/stretchr/testify@v1.7.0/mock/mock.go:383 +0x148
magma/orc8r/cloud/go/services/state/indexer/mocks.(*Indexer).Index(0xc0006fd770, {0xc00122d280, 0x10}, 0xc001498780)
	/src/magma/orc8r/cloud/go/services/state/indexer/mocks/Indexer.go:103 +0xd0
magma/orc8r/cloud/go/services/state/test_init.(*indexerServicer).Index(0xc000b36e80, {0x1115250?, 0x0?}, 0xc000da7450)
	/src/magma/orc8r/cloud/go/services/state/test_init/test_indexer_servicer.go:52 +0x64
magma/orc8r/cloud/go/services/state/protos._Indexer_Index_Handler.func1({0x11194e0, 0xc0014986c0}, {0xf17360?, 0xc000da7450})
	/src/magma/orc8r/cloud/go/services/state/protos/indexer.pb.go:830 +0x78
magma/orc8r/cloud/go/service/middleware/unary.makeInterceptorFromTemplate.func1({0x11194e0, 0xc0014986c0}, {0xf17360, 0xc000da7450}, 0xf341a0?, 0xc0011d5410)
	/src/magma/orc8r/cloud/go/service/middleware/unary/interceptors.go:90 +0x8b
google.golang.org/grpc.chainUnaryInterceptors.func1.1({0x11194e0?, 0xc0014986c0?}, {0xf17360?, 0xc000da7450?})
	/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:1116 +0x5b
magma/orc8r/cloud/go/service/middleware/unary.makeInterceptorFromTemplate.func1({0x11194e0, 0xc0014986c0}, {0xf17360, 0xc000da7450}, 0xaa?, 0xc00122b400)
	/src/magma/orc8r/cloud/go/service/middleware/unary/interceptors.go:90 +0x8b
google.golang.org/grpc.chainUnaryInterceptors.func1.1({0x11194e0?, 0xc0014986c0?}, {0xf17360?, 0xc000da7450?})
	/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:1119 +0x83
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1({0x11194e0, 0xc0014986c0}, {0xf17360, 0xc000da7450}, 0x8caa6f?, 0xc00122b400)
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107 +0x87
google.golang.org/grpc.chainUnaryInterceptors.func1.1({0x11194e0?, 0xc0014986c0?}, {0xf17360?, 0xc000da7450?})
	/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:1119 +0x83
magma/orc8r/cloud/go/service/middleware/unary.recoveryInterceptor({0x11194e0?, 0xc0014986c0?}, {0xf17360?, 0xc000da7450?}, 0xc00122b400?, 0x8?)
	/src/magma/orc8r/cloud/go/service/middleware/unary/interceptors.go:65 +0xa2
google.golang.org/grpc.chainUnaryInterceptors.func1.1({0x11194e0?, 0xc0014986c0?}, {0xf17360?, 0xc000da7450?})
	/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:1119 +0x83
magma/orc8r/cloud/go/service/middleware/unary.errlogInterceptor({0x11194e0?, 0xc0014986c0?}, {0xf17360?, 0xc000da7450?}, 0xc00040dc40, 0x7f5c370a9501?)
	/src/magma/orc8r/cloud/go/service/middleware/unary/interceptors.go:72 +0x49
google.golang.org/grpc.chainUnaryInterceptors.func1.1({0x11194e0?, 0xc0014986c0?}, {0xf17360?, 0xc000da7450?})
	/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:1119 +0x83
google.golang.org/grpc.chainUnaryInterceptors.func1({0x11194e0, 0xc0014986c0}, {0xf17360, 0xc000da7450}, 0xc00040dc40, 0xc0011d5410)
	/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:1121 +0x12b
magma/orc8r/cloud/go/services/state/protos._Indexer_Index_Handler({0xec32a0?, 0xc000b36e80}, {0x11194e0, 0xc0014986c0}, 0xc000e80000, 0xc000305380)
	/src/magma/orc8r/cloud/go/services/state/protos/indexer.pb.go:832 +0x138
google.golang.org/grpc.(*Server).processUnaryRPC(0xc001591880, {0x111c670, 0xc000f891e0}, 0xc000bc8a20, 0xc0009a1a40, 0x1912400, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc001591880, {0x111c670, 0xc000f891e0}, 0xc000bc8a20, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:1616 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:919 +0x28a
I0704 04:22:13.164076    9485 reindexer_singleton.go:150] Attempt at state reindex job {id: some_indexerid_5, from: 0, to: 60} took 0.060909 seconds
E0704 04:22:13.232311    9485 remote_indexer.go:140] some_indexerid_0 service client initialization error: service some_indexerid_0 not registered
I0704 04:22:13.264729    9485 reindexer_singleton.go:62] Sleeping for 1 minute(s) before looking for new jobs to reindex
E0704 04:22:13.268059    9485 interceptors.go:74] [ERROR /magma.orc8r.state.Indexer/PrepareReindex]: rpc error: code = Unknown desc = handler panic: 
assert: mock: The method has been called over 1 times.
	Either do one more Mock.On("PrepareReindex").Return(...), or remove extra call.
	This call was unexpected:
		PrepareReindex(indexer.Version,indexer.Version,bool)
		0: 0x0
		1: 0x3c
		2: true
	at: [Indexer.go:126 test_indexer_servicer.go:68 indexer.pb.go:866 interceptors.go:90 server.go:1116 interceptors.go:90 server.go:1119 server_metrics.go:107 server.go:1119 interceptors.go:65 server.go:1119 interceptors.go:72 server.go:1119 server.go:1121 indexer.pb.go:868 server.go:1282 server.go:1616 server.go:921 asm_amd64.s:1571]; stack trace: goroutine 2456 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
magma/orc8r/cloud/go/service/middleware/unary.recoveryInterceptor.func1()
	/src/magma/orc8r/cloud/go/service/middleware/unary/interceptors.go:61 +0x6b
panic({0xe304e0, 0xc00137ea70})
	/usr/local/go/src/runtime/panic.go:838 +0x207
github.com/stretchr/testify/mock.(*Mock).fail(0xc0006fd770, {0xff1ff5?, 0x20?}, {0xc00122be80?, 0x3?, 0x3?})
	/go/pkg/mod/github.com/stretchr/testify@v1.7.0/mock/mock.go:254 +0x145
github.com/stretchr/testify/mock.(*Mock).MethodCalled(0xc0006fd770, {0x1290bbb, 0xe}, {0xc001499710, 0x3, 0x3})
	/go/pkg/mod/github.com/stretchr/testify@v1.7.0/mock/mock.go:399 +0x29d
github.com/stretchr/testify/mock.(*Mock).Called(0xc0018d0680?, {0xc001499710, 0x3, 0x3})
	/go/pkg/mod/github.com/stretchr/testify@v1.7.0/mock/mock.go:383 +0x148
magma/orc8r/cloud/go/services/state/indexer/mocks.(*Indexer).PrepareReindex(0xc0006fd770, 0x419085?, 0x0?, 0x1)
	/src/magma/orc8r/cloud/go/services/state/indexer/mocks/Indexer.go:126 +0xec
magma/orc8r/cloud/go/services/state/test_init.(*indexerServicer).PrepareReindex(0x0?, {0x1115250?, 0x0?}, 0xc0014996b0?)
	/src/magma/orc8r/cloud/go/services/state/test_init/test_indexer_servicer.go:68 +0x2b
magma/orc8r/cloud/go/services/state/protos._Indexer_PrepareReindex_Handler.func1({0x11194e0, 0xc001499650}, {0xf355c0?, 0xc000da7b80})
	/src/magma/orc8r/cloud/go/services/state/protos/indexer.pb.go:866 +0x78
magma/orc8r/cloud/go/service/middleware/unary.makeInterceptorFromTemplate.func1({0x11194e0, 0xc001499650}, {0xf355c0, 0xc000da7b80}, 0xf341a0?, 0xc0013805a0)
	/src/magma/orc8r/cloud/go/service/middleware/unary/interceptors.go:90 +0x8b
google.golang.org/grpc.chainUnaryInterceptors.func1.1({0x11194e0?, 0xc001499650?}, {0xf355c0?, 0xc000da7b80?})
	/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:1116 +0x5b
magma/orc8r/cloud/go/service/middleware/unary.makeInterceptorFromTemplate.func1({0x11194e0, 0xc001499650}, {0xf355c0, 0xc000da7b80}, 0x16?, 0xc00122bd00)
	/src/magma/orc8r/cloud/go/service/middleware/unary/interceptors.go:90 +0x8b
google.golang.org/grpc.chainUnaryInterceptors.func1.1({0x11194e0?, 0xc001499650?}, {0xf355c0?, 0xc000da7b80?})
	/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:1119 +0x83
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1({0x11194e0, 0xc001499650}, {0xf355c0, 0xc000da7b80}, 0x8caa6f?, 0xc00122bd00)
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107 +0x87
google.golang.org/grpc.chainUnaryInterceptors.func1.1({0x11194e0?, 0xc001499650?}, {0xf355c0?, 0xc000da7b80?})
	/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:1119 +0x83
magma/orc8r/cloud/go/service/middleware/unary.recoveryInterceptor({0x11194e0?, 0xc001499650?}, {0xf355c0?, 0xc000da7b80?}, 0xc00122bd00?, 0x8?)
	/src/magma/orc8r/cloud/go/service/middleware/unary/interceptors.go:65 +0xa2
google.golang.org/grpc.chainUnaryInterceptors.func1.1({0x11194e0?, 0xc001499650?}, {0xf355c0?, 0xc000da7b80?})
	/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:1119 +0x83
magma/orc8r/cloud/go/service/middleware/unary.errlogInterceptor({0x11194e0?, 0xc001499650?}, {0xf355c0?, 0xc000da7b80?}, 0xc000f70320, 0x7f5c370a9501?)
	/src/magma/orc8r/cloud/go/service/middleware/unary/interceptors.go:72 +0x49
google.golang.org/grpc.chainUnaryInterceptors.func1.1({0x11194e0?, 0xc001499650?}, {0xf355c0?, 0xc000da7b80?})
	/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:1119 +0x83
google.golang.org/grpc.chainUnaryInterceptors.func1({0x11194e0, 0xc001499650}, {0xf355c0, 0xc000da7b80}, 0xc000f70320, 0xc0013805a0)
	/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:1121 +0x12b
magma/orc8r/cloud/go/services/state/protos._Indexer_PrepareReindex_Handler({0xec32a0?, 0xc000b36e80}, {0x11194e0, 0xc001499650}, 0xc000e817a0, 0xc000305380)
	/src/magma/orc8r/cloud/go/services/state/protos/indexer.pb.go:868 +0x138
google.golang.org/grpc.(*Server).processUnaryRPC(0xc001591880, {0x111c670, 0xc000f891e0}, 0xc000bc8d80, 0xc0009a1a40, 0x1912430, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc001591880, {0x111c670, 0xc000f891e0}, 0xc000bc8d80, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:1616 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:919 +0x28a
I0704 04:22:13.268439    9485 reindexer_singleton.go:150] Attempt at state reindex job {id: some_indexerid_5, from: 0, to: 60} took 0.001044 seconds
    reindexer_queue_test.go:437: should not receive anything from hook channel
DONE 548 tests, 1 failure in 181.955s
```
 

```
∅  tools/migrations/m014_enodeb_config

=== Failed
=== FAIL: services/subscriberdb/obsidian/handlers TestGetSubscriberState (0.40s)
E0801 09:45:13.156821   14187 service_config.go:159] Error Loading orc8r::subscriberdb configs from '/etc/magma/orc8r/subscriberdb.yml': open /etc/magma/orc8r/subscriberdb.yml: no such file or directory
    access.go:59: Test Gateway Certificate SN: C4F5F0523776780E59B3B6DD7563E476
    unit_test_utils.go:110: 
        	Error Trace:	unit_test_utils.go:110
        	            				handlers_test.go:956
        	Error:      	Not equal: 
        	            	expected: "{\"directory\":{\"location_history\":[\"foo\",\"bar\"]},\"mme\":{\"mme\":\"foo\"},\"mobility\":[{\"apn\":\"magma.apn\",\"ip\":\"192.168.128.134\"},{\"apn\":\"oai.ipv4\",\"ip\":\"192.168.128.174\"}],\"s1ap\":{\"s1ap\":\"foo\"},\"spgw\":{\"spgw\":\"foo\"},\"subscriber_state\":{\"session_state\":{\"apn\":\"apn0\",\"ipv4\":\"168.212.226.204\"},\"subscriber_state\":{\"imsi\":\"IMSI1234567890\",\"sessions\":[\"p0\",\"p1\"]}}}"
        	            	actual  : "{\"directory\":{\"location_history\":[\"foo\",\"bar\"]},\"mme\":{\"mme\":\"foo\"},\"mobility\":[{\"apn\":\"magma.apn\",\"ip\":\"192.168.128.134\"},{\"apn\":\"oai.ipv4\",\"ip\":\"192.168.128.174\"}],\"s1ap\":{\"s1ap\":\"foo\"},\"spgw\":{\"spgw\":\"foo\"}}"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-{"directory":{"location_history":["foo","bar"]},"mme":{"mme":"foo"},"mobility":[{"apn":"magma.apn","ip":"192.168.128.134"},{"apn":"oai.ipv4","ip":"192.168.128.174"}],"s1ap":{"s1ap":"foo"},"spgw":{"spgw":"foo"},"subscriber_state":{"session_state":{"apn":"apn0","ipv4":"168.212.226.204"},"subscriber_state":{"imsi":"IMSI1234567890","sessions":["p0","p1"]}}}
        	            	+{"directory":{"location_history":["foo","bar"]},"mme":{"mme":"foo"},"mobility":[{"apn":"magma.apn","ip":"192.168.128.134"},{"apn":"oai.ipv4","ip":"192.168.128.174"}],"s1ap":{"s1ap":"foo"},"spgw":{"spgw":"foo"}}
        	Test:       	TestGetSubscriberState

DONE 188 tests, 1 failure in 69.722s
make[1]: *** [test] Error 1
/src/magma/orc8r/cloud/go/module.mk:100: recipe for target 'test' failed
make[1]: Leaving directory '/src/magma/lte/cloud/go'
make: *** [/src/magma/lte_test] Error 2
Makefile:134: recipe for target '/src/magma/lte_test' failed
2
Creating build context in '/tmp/magma_orc8r_build'...
/tmp/magma_orc8r_build/gomod/src/magma/orc8r/cloud/go/go.mod
/tmp/magma_orc8r_build/gomod/src/magma/orc8r/cloud/api/v1/go/go.mod
/tmp/magma_orc8r_build/gomod/src/magma/orc8r/cloud/test/go.mod
/tmp/magma_orc8r_build/gomod/src/magma/orc8r/lib/go/go.mod
/tmp/magma_orc8r_build/gomod/src/magma/orc8r/lib/go/protos/go.mod
/tmp/magma_orc8r_build/gomod/src/magma/orc8r/gateway/go/go.mod
/tmp/magma_orc8r_build/gomod/src/magma/lte/cloud/go/go.mod
/tmp/magma_orc8r_build/gomod/src/magma/feg/cloud/go/go.mod
/tmp/magma_orc8r_build/gomod/src/magma/feg/cloud/go/protos/go.mod
/tmp/magma_orc8r_build/gomod/src/magma/cwf/cloud/go/go.mod
/tmp/magma_orc8r_build/gomod/src/magma/dp/cloud/go/go.mod
/tmp/magma_orc8r_build/gomod/src/magma/dp/cloud/go/active_mode_controller/go.mod
```

Investigate, try to reproduce, and fix the tests.

### PR DESCRIPTION
**Pull request by MoritzThomasHuebner**
Fixes #13537 

In pairing with @wolfseb 

## Summary

This test is flaky because it multiple threads that are not synced 100 % reliably. See the [discussion](https://github.com/magma/magma/issues/13537#issuecomment-1220594324) on the issue for details.

We solved this by splitting up the test to separate out the failing indexers. We then start running the reindexer after registering all indexers. This way, the reindexer consistently reindexes once all indexers have been registered. Due to the minimal sleep time of 100 ms even if `clock` sleeps are deactivated, the reindexer never reindexes again before being cancelled.

We also added some cosmetic changes:
- We changed the order of arguments in the assertions to be consistent with the conventional order of "expected", "actual".
- We refactored the reindexer setup functions in the file.

## Test Plan

- We removed logging and sleep commands in the reindexer's `Run` method to make the test fail more reliably
- We also successfully ran the test multiple hundred times on the Github CI after implementing our changes. We created the runs by temporarily copying the test and removing all other tests in magma.

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

File: orc8r/cloud/go/services/state/indexer/reindex/reindexer_singleton_test.go [hunk 1]
```diff
@@ -108,6 +111,35 @@ func TestSingletonRun(t *testing.T) {
 	idx5.AssertExpectations(t)
 	require.Equal(t, 3, reindexSuccessNum)
 	require.Equal(t, 3, reindexDoneNum)
+	cancel()
+}
+
+func TestSingletonRunFail(t *testing.T) {
+	// Make nullimpotent calls to handle code coverage indeterminacy
```
Comment (sebathomas) [inline orc8r/cloud/go/services/state/indexer/reindex/reindexer_singleton_test.go:118]: Nit: I think it's called "nullipotent".

File: orc8r/cloud/go/services/state/indexer/reindex/reindexer_singleton_test.go [hunk 2]
```diff
@@ -87,13 +87,16 @@ func TestSingletonRun(t *testing.T) {
...
+	require.Equal(t, 2, reindexSuccessNum)
+	require.Equal(t, 2, reindexDoneNum)
 
 	// Test that a network/hardware pair that has been added after Run
 	// will have its states reindexed as well
 
-	reportMoreState(t)
+	// reportAdditionalState reports enough directory records to cause 3 batches per network
+	// (with the +1 gateway status per network). It adds an extra network from 3 -> 4,
+	// so numBatches following this method will be 3 * 4 = 12
```
Comment (sebathomas) [inline orc8r/cloud/go/services/state/indexer/reindex/reindexer_singleton_test.go:98]: I think it would be good to leave the comment at the function definition, not where it's called.

**Review by sebathomas — APPROVED** [review]
Looking good, just some minor points.

**Comment by sebathomas** [comment]
I think there's a sign-off missing in the commit message.

File: orc8r/cloud/go/services/state/indexer/reindex/reindexer_singleton_test.go (hunk 1 above)
Comment (MoritzThomasHuebner) [reply orc8r/cloud/go/services/state/indexer/reindex/reindexer_singleton_test.go:118]: Fixed

File: orc8r/cloud/go/services/state/indexer/reindex/reindexer_singleton_test.go (hunk 2 above)
Comment (MoritzThomasHuebner) [reply orc8r/cloud/go/services/state/indexer/reindex/reindexer_singleton_test.go:98]: I added some extra comments at the function. However, this comment is specific to what happens in the test.

**Comment by MoritzThomasHuebner** [comment]
> I think there's a sign-off missing in the commit message.

Fixed
