### PR TITLE
fix(sessiond): prevent to un-suspend if we receive several transient errors

### LINKED ISSUE #10609: [Sessiond] Credits gets suspended and immediately un-suspended on CCA-U with FUA
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Your Environment

- **Version:** 1.5
- **Affected Component:** AGW
- **Affected Subcomponent:** Sessiond
- **Deployment Environment:** Federeted FWA with Gx/Gy federation

### Describe the Issue

When the subscriber quota ends the Gy will answer any CCR-U coming from magma with a CCA-U containing FUI and action configured to TERMINATE.

The behaviour seen is:

1. On the first CCA-U the rules are dropped as expected.
2. The next CCA-U the rules are dropped but are immediately reactivated
3. The subsequent CCA-U the rule is dropped again as expected.
4. The next CCA-U behavior on 2 reproduces

Follows the sessiond log for the suspention and imediatelly unsuspension seen in #2 and #4. (All IMSI values are the same)

image

**Expected behavior**

Magma should always drop the rules that are linked to the RG contained in the CCA-U with FUA TERMINATE

### PR DESCRIPTION
**Pull request by uri200**
Signed-off-by: Oriol Batalla <obatalla@fb.com>

## Summary

When we receive two a transient error, we set session into suspended stage. But if we receive another transient error, the session is un-suspended. This PR prevents this situation to happen

## Test Plan

extended test case `test_update_with_transient_error_suspendand_unsuspend` to capture suspension, send of a transient error while suspended and unsuspend using valid quota

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Review by themarwhal — APPROVED** [review]

File: lte/gateway/c/session_manager/LocalEnforcer.cpp [hunk 1]
```diff
@@ -1474,8 +1474,11 @@ void LocalEnforcer::update_charging_credits(
         session->receive_charging_credit(credit_update_resp, &uc);
     session->set_tgpp_context(credit_update_resp.tgpp_ctx(), &uc);
 
+    // Here we will decide if a traffic should be activated/un-suspended
     bool should_activate = session->is_credit_ready_to_be_activated(credit_key);
-    if (!should_activate) {
+    auto typeOfCredityValidity =
```
Comment (themarwhal) [inline lte/gateway/c/session_manager/LocalEnforcer.cpp]:
```suggestion
    auto type_of_credit_validity =
```

File: lte/gateway/c/session_manager/LocalEnforcer.cpp [hunk 2]
```diff
@@ -1474,8 +1474,11 @@ void LocalEnforcer::update_charging_credits(
...
+        ChargingGrant::is_valid_credit_response(credit_update_resp);
```
Comment (themarwhal) [inline lte/gateway/c/session_manager/LocalEnforcer.cpp]: Should we just rename it to `get_credit_response_type`?

File: lte/gateway/c/session_manager/LocalEnforcer.cpp [hunk 3]
```diff
@@ -1474,8 +1474,11 @@ void LocalEnforcer::update_charging_credits(
...
+    if (!should_activate || typeOfCredityValidity == TRANSIENT_ERROR) {
```
Comment (themarwhal) [inline lte/gateway/c/session_manager/LocalEnforcer.cpp]: Should we just put the TRANSIENT ERROR check inside of `is_credit_ready_to_be_activated` ?

Comment (uri200) [reply lte/gateway/c/session_manager/LocalEnforcer.cpp]: I was thinking on that but then we have to pass the response to the `is_credit_ready_to_be_activated`

My reasoning is, `is_credit_ready_to_be_activated ` is calculated out of a  current state of the session. `credit_validity_type == TRANSIENT_ERROR` is not a session state. 

So `credit_validity_type == TRANSIENT_ERROR` is just a condition that invalidates any state derived from the session 

That is why I didn't wanted to mix it and i wanted to make it explicit in the condition
