### PR TITLE
[AGW] [MME] Adding IP_ALLOCATION_RESPONSE to handle ip allocation process on SPGW…

### LINKED ISSUE #5155: [MME] SEGV in cpp_redis::network::redis_connection::send
### Your Environment

- **Version:**1.4.0-1614171043-7cd5877d
- **Affected Component:** Orchestrator, Access Gateway, or NMS
- **Affected Subcomponent:** Orchestrator pod/service or AGW service
- **Deployment Environment:** e.g. AWS (orc8r), local docker-compose (orc8r), bare-metal (AGW), Vagrant (AGW)

### Describe the Issue
core with bt
```
b[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
t
Core was generated by `/usr/local/bin/mme -c /var/opt/magma/tmp/mme.conf -s /var/opt/magma/tmp/spgw.co'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f358b36601d in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
[Current thread is 1 (Thread 0x7f35795d9700 (LWP 17125))]
(gdb) bt
#0  0x00007f358b36601d in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x0000563c38949577 in cpp_redis::network::redis_connection::send(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) ()
#2  0x0000563c3891d58c in cpp_redis::client::unprotected_send(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::function<void (cpp_redis::reply&)> const&) ()
#3  0x0000563c3891d794 in cpp_redis::client::send(std::vector<std::__cxx11::basic_string<char, 
```

[2021-Feb-23-07-27-22-core-1614094033-ITTI.zip](https://github.com/magma/magma/files/6045391/2021-Feb-23-07-27-22-core-1614094033-ITTI.zip)

### PR DESCRIPTION
**Pull request by ssanadhya**
… main thread

Signed-off-by: Alex Rodriguez <ardzoht@gmail.com>

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Comment by rdefosse** [comment]
MAGMA-OAI-TESTS

File: lte/gateway/c/oai/lib/mobility_client/MobilityClientAPI.cpp [hunk 1]
```diff
@@ -69,79 +70,61 @@ int get_assigned_ipv4_block(
...
-    itti_sgi_create_end_point_response_t sgi_create_endpoint_resp,
-    const char* pdn_type, spgw_state_t* spgw_state,
-    s_plus_p_gw_eps_bearer_context_information_t* new_bearer_ctxt_info_p,
-    s5_create_session_response_t s5_response) {
+    const char* pdn_type, teid_t context_teid, ebi_t eps_bearer_id) {
   MobilityServiceClient::getInstance().AllocateIPv4AddressAsync(
       subscriber_id, apn,
-      [=, &s5_response](
-          const Status& status, AllocateIPAddressResponse ip_msg) {
+      [addr, subscriber_id, apn, pdn_type, context_teid, eps_bearer_id](
```
Comment (ssanadhya) [inline lte/gateway/c/oai/lib/mobility_client/MobilityClientAPI.cpp]: We do not need to capture the addr from the caller scope here. It was originally used to capture the addr allocated by the RPC, but this will be taken care of through the ITTI message now.

File: lte/gateway/c/oai/lib/mobility_client/MobilityClientAPI.cpp [hunk 2]
```diff
@@ -69,79 +70,61 @@ int get_assigned_ipv4_block(
...
+        int vlan = atoi(ip_msg.vlan().c_str());
+        handle_allocate_ipv4_address_status(
+            status, *addr, vlan, subscriber_id, apn, pdn_type, context_teid,
+            eps_bearer_id);
       });
   return 0;
 }
 
-static itti_sgi_create_end_point_response_t handle_allocate_ipv4_address_status(
+static int handle_allocate_ipv4_address_status(
```
Comment (talkhasib) [inline lte/gateway/c/oai/lib/mobility_client/MobilityClientAPI.cpp]: Since caller is ignoring the return status, do you still need it?

File: lte/gateway/c/oai/tasks/sgw/sgw_handlers.c [hunk 3]
```diff
@@ -1866,6 +1893,78 @@ int sgw_handle_nw_initiated_deactv_bearer_rsp(
...
+  OAILOG_FUNC_IN(LOG_SPGW_APP);
+
+  OAILOG_DEBUG_UE(
+      LOG_SPGW_APP, imsi64,
+      "Received ip_allocation_rsp from gRPC task handler\n");
+
+  s_plus_p_gw_eps_bearer_context_information_t* bearer_ctxt_info_p =
+      sgw_cm_get_spgw_context(ip_allocation_rsp->context_teid);
+
+  if (bearer_ctxt_info_p) {
```
Comment (talkhasib) [inline lte/gateway/c/oai/tasks/sgw/sgw_handlers.c]: Add error or warning msg if context is not found

File: lte/gateway/c/oai/tasks/sgw/sgw_handlers.c [hunk 4]
```diff
@@ -1866,6 +1893,78 @@ int sgw_handle_nw_initiated_deactv_bearer_rsp(
...
+        /*
+         * This implies that UE session was not release properly.
+         * Release the IP address so that subsequent attempt is successfull
+         */
+        // TODO - Release the GTP-tunnel corresponding to this IP address
+        char* apn =
+            (char*) bearer_ctxt_info_p->sgw_eps_bearer_context_information
+                .pdn_connection.apn_in_use;
+        release_ipv4_address(imsi, apn, &ip_allocation_rsp->paa.ipv4_address);
+      }
```
Comment (talkhasib) [inline lte/gateway/c/oai/tasks/sgw/sgw_handlers.c]: Any reason for not leaving this logic inside the function "handle_allocate_ipv4_address_status" to simplify this handler

File: lte/gateway/c/oai/lib/mobility_client/MobilityClientAPI.cpp [hunk 5]
```diff
@@ -68,80 +69,63 @@ int get_assigned_ipv4_block(
...
-    const char* pdn_type, spgw_state_t* spgw_state,
-    s_plus_p_gw_eps_bearer_context_information_t* new_bearer_ctxt_info_p,
-    s5_create_session_response_t s5_response) {
+    const char* subscriber_id, const char* apn, const char* pdn_type,
+    teid_t context_teid, ebi_t eps_bearer_id) {
   MobilityServiceClient::getInstance().AllocateIPv4AddressAsync(
       subscriber_id, apn,
-      [=, &s5_response](
-          const Status& status, AllocateIPAddressResponse ip_msg) {
+      [subscriber_id, apn, pdn_type, context_teid, eps_bearer_id](
```
Comment (ulaskozat) [inline lte/gateway/c/oai/lib/mobility_client/MobilityClientAPI.cpp]: is passing subscriber_id and apn that are pointers to the lambda function a safe call? Can what they are pointing to be deleted by the spgw thread?

Comment (ulaskozat) [reply lte/gateway/c/oai/lib/mobility_client/MobilityClientAPI.cpp]: as discussed on the call, let's define std::string objects and pass those instead.

**Comment by ssanadhya** [comment]
MAGMA-OAI-TESTS

**Comment by ssanadhya** [comment]
LGTM, but I cannot approve it as I created the PR on behalf of @ardzoht, waiting for approval from other code-owners.

**Review by ulaskozat — APPROVED** [review]
LGTM
