### PR TITLE
[AGW][MME] Send ITTI message from PCEF create session callback

### LINKED ISSUE #4702: [MME][Stateless] Multiple cores generated from redis client
```
#0  0x000056409192d0e6 in tacopie::io_service::set_wr_callback(tacopie::tcp_socket const&, std::function<void (int)> const&) ()
#1  0x4b80a8c09193098f in ?? ()
#2  0x000060200005c020 in ?? ()
#3  0x00007fcd593bd948 in ?? ()
#4  0x0000564091930c30 in ?? ()
#5  0x0000564091930cb0 in ?? ()
#6  0x00007fcd593bda50 in ?? ()
#7  0x00007fcd593bd9d0 in ?? ()
#8  0x000060100001bf40 in ?? ()
#9  0x00005640918db83d in std::_Function_base::_Base_manager<cpp_redis::client::exec_cmd(std::function<cpp_redis::client& (std::function<void (cpp_redis::reply&)> const&)> const&)::{lambda(cpp_redis::reply&)#1}>::_M_manager(std::_Any_data&, std::_Function_base::_Base_manager<cpp_redis::client::exec_cmd(std::function<cpp_redis::client& (std::function<void (cpp_redis::reply&)> const&)> const&)::{lambda(cpp_redis::reply&)#1}> const&, std::_Manager_operation) ()
#10 0x00005640918fa03c in cpp_redis::client::unprotected_send(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::function<void (cpp_redis::reply&)> const&) ()
#11 0x0000000000000000 in ?? ()
```

[core.2.zip](https://github.com/magma/magma/files/5915222/core.2.zip)
[core.5.zip](https://github.com/magma/magma/files/5915224/core.5.zip)
[core.7.zip](https://github.com/magma/magma/files/5915226/core.7.zip)
[core.10.zip](https://github.com/magma/magma/files/5915227/core.10.zip)
[core.11.zip](https://github.com/magma/magma/files/5915228/core.11.zip)
[mme.zip](https://github.com/magma/magma/files/5915229/mme.zip)

### LINKED ISSUE #5155: [MME] SEGV in cpp_redis::network::redis_connection::send
### Your Environment

- **Version:**1.4.0-1614171043-7cd5877d
- **Affected Component:** Orchestrator, Access Gateway, or NMS
- **Affected Subcomponent:** Orchestrator pod/service or AGW service
- **Deployment Environment:** e.g. AWS (orc8r), local docker-compose (orc8r), bare-metal (AGW), Vagrant (AGW)

### Describe the Issue
core with bt
```
b[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
t
Core was generated by `/usr/local/bin/mme -c /var/opt/magma/tmp/mme.conf -s /var/opt/magma/tmp/spgw.co'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f358b36601d in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
[Current thread is 1 (Thread 0x7f35795d9700 (LWP 17125))]
(gdb) bt
#0  0x00007f358b36601d in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x0000563c38949577 in cpp_redis::network::redis_connection::send(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) ()
#2  0x0000563c3891d58c in cpp_redis::client::unprotected_send(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::function<void (cpp_redis::reply&)> const&) ()
#3  0x0000563c3891d794 in cpp_redis::client::send(std::vector<std::__cxx11::basic_string<char, 
```

[2021-Feb-23-07-27-22-core-1614094033-ITTI.zip](https://github.com/magma/magma/files/6045391/2021-Feb-23-07-27-22-core-1614094033-ITTI.zip)

### PR DESCRIPTION
**Pull request by ssanadhya**
Signed-off-by: Shruti Sanadhya <ssanadhya@fb.com>

## Summary

This change makes the PCEF Client create session callback send an ITTI message to SPGW task, instead of altering SPGW state in the context of the the PCEF GRPC handler thread.

Also cleaned up unused code to dump SPGW status into a file in `/tmp/`

## Test Plan

- `make integ_test`
- To be done: testing on Spirent AGW testbed

### CODE REVIEW

**Review by ulaskozat — APPROVED** [review]
LGTM

**Comment by ssanadhya** [comment]
MAGMA-OAI-TESTS

File: lte/gateway/c/oai/tasks/sgw/spgw_state.cpp [hunk 1]
```diff
@@ -42,6 +42,8 @@ spgw_state_t* get_spgw_state(bool read_from_db) {
 }
 
 hash_table_ts_t* get_spgw_ue_state() {
+  OAILOG_DEBUG(
```
Comment (ssanadhya) [inline lte/gateway/c/oai/tasks/sgw/spgw_state.cpp:45]: @talkhasib , The `itti_desc` variable is not globally available, so this is not straightforward at the moment. In future PR, we can add an API to expose the thread_id (given the task name) and use it to print a warning here.

**Comment by ssanadhya** [comment]
MAGMA-OAI-TESTS
