### PR TITLE
fix(amf): Reimplement PDU Session data structure as maps in amf_context

### LINKED ISSUE #9415: [AMF]: Reimplement PDU Session data structure as maps in amf_context
Right now the PDU Session is stored as Vectors in UE context under amf. Vectors implementation needs additional clean up. But while doing clean ups it was realized that its better to implement PDU Session Data structure as maps as the storage, lookup and traversal is much more optimized.

Following are the main changes to be taken up for PDU Sessions :
1. Replace the vector implementation by maps.
2. All lookups to be tuned.
3. Right some UT around that area.

### PR DESCRIPTION
**Pull request by sreedharkumartn**
Signed-off-by: sreedharkumartn <sreedhar.kumar@wavelabs.ai>

## Summary
Right now the PDU Session is stored as Vectors in UE context under amf. Vectors implementation needs additional clean up. But while doing clean ups it was realized that its better to implement PDU Session Data structure as maps as the storage, lookup and traversal is much more optimized.

Following are the main changes to be taken up for PDU Sessions :
1. Replace the vector implementation by maps.
2. All lookups to be tuned.

## Test Plan
- Verified basic sanity with UERANSIM.
- Please find attached logs and pcap snap for basic registration, PDU Session setup and PDU Session release.
- Verified UT cases.

Logs:
[maps in amf context.log](https://github.com/magma/magma/files/7310345/maps.in.amf.context.log)

Pcap snap:
maps in amf context

Test cases compiled:
UT test

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Comment by ulaskozat** [comment]
@ssanadhya could you shepherd this PR?

**Comment by sreedharkumartn** [comment]
@ssanadhya could you please review this PR.

File: lte/gateway/c/core/oai/tasks/amf/amf_app_ue_context.cpp [hunk 1]
```diff
@@ -208,49 +213,42 @@ ue_m5gmm_context_s* amf_ue_context_exists_amf_ue_ngap_id(
...
  **                                                                        **
  ** Name:    amf_smf_context_exists_pdu_session_id()                       **
  **                                                                        **
- ** Description: Get the smf context from the vector                       **
+ ** Description: Get the smf context from the map                          **
  **                                                                        **
  **                                                                        **
  ***************************************************************************/
-smf_context_t* amf_smf_context_exists_pdu_session_id(
+std::shared_ptr<smf_context_t> amf_smf_context_exists_pdu_session_id(
```
Comment (ulaskozat) [inline lte/gateway/c/core/oai/tasks/amf/amf_app_ue_context.cpp]: can you change this function name to something more meaningful such as `amf_get_smf_context_by_pdu_session_id`

Comment (sreedharkumartn) [reply lte/gateway/c/core/oai/tasks/amf/amf_app_ue_context.cpp]: Addressed the review comment.

**Comment by sreedharkumartn** [comment]
- Verified basic sanity with UERANSIM.
- Please find attached logs and pcap snap for basic registration, PDU Session setup and PDU Session release.
- Verified UT cases.

Logs:
[maps_in_amf_context_18_oct.log](https://github.com/magma/magma/files/7364161/maps_in_amf_context_18_oct.log)

Pcap snap:
maps_in_amf_context_18_oct

UT cases compiled:
UT_test_18_Oct

**Review by ulaskozat — APPROVED** [review]
LGTM
