### PR TITLE
[lte][agw] Fixing IPCP req options length counters on pgw_pco.c

### LINKED ISSUE #4326: [agw] Service interruption due to Disk filling up with logs
### Your Environment

- **Version: 1.3.1-1605904866-7933c82**
- **Affected Component:** AGW
- **Affected Subcomponent:** AGW Service
- **Deployment Environment:** bare-metal (AGW)

### Describe the Issue

There was service interruption due to AGW disk getting full. Checking mme logs, several messages with the following information were found:

PCO: Protocol identifier IPCP option 0x0000 unknown
PCO: Protocol identifier IPCP option 0x0000 unknown
PCO: Protocol identifier IPCP option 0x0000 unknown
PCO: Protocol identifier IPCP option 0x0000 unknown
PCO: Protocol identifier IPCP option 0x0000 unknown
PCO: Protocol identifier IPCP option 0x0000 unknown

### PR DESCRIPTION
**Pull request by ardzoht**
Signed-off-by: Alex Rodriguez <ardzoht@gmail.com>

## Summary

- This PR includes changes to update the length and remaining length counters for the IPCP PCO options request content, since to parse the content there's a case where it logs continuously without a valid exit condition, due to the remaining length not decreasing. 
- This also removes some UNUSED macros on the pgw_ipcp_pco_process_request function 

```
002637 Sat Jan  9 11:53:43 2021 7FB556FDA700 WARNI SPGW-A tasks/sgw/pgw_pco.c             :0252    PCO: Protocol identifier IPCP option 0x0000 unknown
002638 Sat Jan  9 11:53:43 2021 7FB556FDA700 WARNI SPGW-A tasks/sgw/pgw_pco.c             :0252    PCO: Protocol identifier IPCP option 0x0000 unknown
002639 Sat Jan  9 11:53:43 2021 7FB556FDA700 WARNI SPGW-A tasks/sgw/pgw_pco.c             :0252    PCO: Protocol identifier IPCP option 0x0000 unknown
002640 Sat Jan  9 11:53:43 2021 7FB556FDA700 WARNI SPGW-A tasks/sgw/pgw_pco.c             :0252    PCO: Protocol identifier IPCP option 0x0000 unknown
002641 Sat Jan  9 11:53:43 2021 7FB556FDA700 WARNI SPGW-A tasks/sgw/pgw_pco.c             :0252    PCO: Protocol identifier IPCP option 0x0000 unknown
002642 Sat Jan  9 11:53:43 2021 7FB556FDA700 WARNI SPGW-A tasks/sgw/pgw_pco.c             :0252    PCO: Protocol identifier IPCP option 0x0000 unknown
002643 Sat Jan  9 11:53:43 2021 7FB556FDA700 WARNI SPGW-A tasks/sgw/pgw_pco.c             :0252    PCO: Protocol identifier IPCP option 0x0000 unknown
002644 Sat Jan  9 11:53:43 2021 7FB556FDA700 WARNI SPGW-A tasks/sgw/pgw_pco.c             :0252    PCO: Protocol identifier IPCP option 0x0000 unknown
002645 Sat Jan  9 11:53:43 2021 7FB556FDA700 WARNI SPGW-A tasks/sgw/pgw_pco.c             :0252    PCO: Protocol identifier IPCP option 0x0000 unknown
002646 Sat Jan  9 11:53:43 2021 7FB556FDA700 WARNI SPGW-A tasks/sgw/pgw_pco.c             :0252    PCO: Protocol identifier IPCP option 0x0000 unknown
002647 Sat Jan  9 11:53:43 2021 7FB556FDA700 WARNI SPGW-A tasks/sgw/pgw_pco.c             :0252    PCO: Protocol identifier IPCP option 0x0000 unknown
002648 Sat Jan  9 11:53:43 2021 7FB556FDA700 WARNI SPGW-A tasks/sgw/pgw_pco.c             :0252    PCO: Protocol identifier IPCP option 0x0000 unknown
002649 Sat Jan  9 11:53:43 2021 7FB556FDA700 WARNI SPGW-A tasks/sgw/pgw_pco.c             :0252    PCO: Protocol identifier IPCP option 0x0000 unknown
002650 Sat Jan  9 11:53:43 2021 7FB556FDA700 WARNI SPGW-A tasks/sgw/pgw_pco.c             :0252    PCO: Protocol identifier IPCP option 0x0000 unknown
002651 Sat Jan  9 11:53:43 2021 7FB556FDA700 WARNI SPGW-A tasks/sgw/pgw_pco.c             :0252    PCO: Protocol identifier IPCP option 0x0000 unknown
002652 Sat Jan  9 11:53:43 2021 7FB556FDA700 WARNI SPGW-A tasks/sgw/pgw_pco.c             :0252    PCO: Protocol identifier IPCP option 0x0000 unknown
002653 Sat Jan  9 11:53:43 2021 7FB556FDA700 WARNI SPGW-A tasks/sgw/pgw_pco.c             :0252    PCO: Protocol identifier IPCP option 0x0000 unknown
002654 Sat Jan  9 11:53:43 2021 7FB556FDA700 WARNI SPGW-A tasks/sgw/pgw_pco.c             :0252    PCO: Protocol identifier IPCP option 0x0000 unknown
002655 Sat Jan  9 11:53:43 2021 7FB556FDA700 WARNI SPGW-A tasks/sgw/pgw_pco.c             :0252    PCO: Protocol identifier IPCP option 0x0000 unknown
002656 Sat Jan  9 11:53:43 2021 7FB556FDA700 WARNI SPGW-A tasks/sgw/pgw_pco.c             :0252    PCO: Protocol identifier IPCP option 0x0000 unknown
002657 Sat Jan  9 11:53:43 2021 7FB556FDA700 WARNI SPGW-A tasks/sgw/pgw_pco.c             :0252    PCO: Protocol identifier IPCP option 0x0000 unknown
002658 Sat Jan  9 11:53:43 2021 7FB556FDA700 WARNI SPGW-A tasks/sgw/pgw_pco.c             :0252    PCO: Protocol identifier IPCP option 0x0000 unknown
002659 Sat Jan  9 11:53:43 2021 7FB556FDA700 WARNI SPGW-A tasks/sgw/pgw_pco.c             :0252    PCO: Protocol identifier IPCP option 0x0000 unknown
002660 Sat Jan  9 11:53:43 2021 7FB556FDA700 WARNI SPGW-A tasks/sgw/pgw_pco.c             :0252    PCO: Protocol identifier IPCP option 0x0000 unknown
002661 Sat Jan  9 11:53:43 2021 7FB556FDA700 WARNI SPGW-A tasks/sgw/pgw_pco.c             :0252    PCO: Protocol identifier IPCP option 0x0000 unknown
002662 Sat Jan  9 11:53:43 2021 7FB556FDA700 WARNI SPGW-A tasks/sgw/pgw_pco.c             :0252    PCO: Protocol identifier IPCP option 0x0000 unknown
002663 Sat Jan  9 11:53:43 2021 7FB556FDA700 WARNI SPGW-A tasks/sgw/pgw_pco.c             :0252    PCO: Protocol identifier IPCP option 0x0000 unknown
002664 Sat Jan  9 11:53:43 2021 7FB556FDA700 WARNI SPGW-A tasks/sgw/pgw_pco.c             :0252    PCO: Protocol identifier IPCP option 0x0000 unknown
002665 Sat Jan  9 11:53:43 2021 7FB556FDA700 WARNI SPGW-A tasks/sgw/pgw_pco.c             :0252    PCO: Protocol identifier IPCP option 0x0000 unknown
002666 Sat Jan  9 11:53:43 2021 7FB556FDA700 WARNI SPGW-A tasks/sgw/pgw_pco.c             :0252    PCO: Protocol identifier IPCP option 0x0000 unknown
```

## Test Plan

- sanity testing with S1AP tester

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

File: lte/gateway/c/oai/tasks/sgw/pgw_pco.c [hunk 1]
```diff
@@ -71,25 +71,24 @@ int pgw_process_pco_request_ipcp(
...
-  uint8_t ipcp_req_option        = 0;
-  uint8_t ipcp_req_option_length = 0;
+  int8_t ipcp_req_code       = 0;
+  int8_t ipcp_req_identifier = 0;
+  int16_t ipcp_req_length    = 0;
 
-  uint8_t ipcp_out_code    = 0;
-  uint16_t ipcp_out_length = 0;
+  uint8_t ipcp_req_option       = 0;
+  int8_t ipcp_req_option_length = 0;
```
Comment (ulaskozat) [inline lte/gateway/c/oai/tasks/sgw/pgw_pco.c:79]: unused variable (see codacy notice)

File: lte/gateway/c/oai/tasks/sgw/pgw_pco.c [hunk 2]
```diff
@@ -71,25 +71,24 @@ int pgw_process_pco_request_ipcp(
   size_t ipcp_req_remaining_length           = poc_id->length;
```
Comment (ulaskozat) [inline lte/gateway/c/oai/tasks/sgw/pgw_pco.c]: you need to change this to integer type.

**Review by ulaskozat — CHANGES_REQUESTED** [review]
ipcp_req_remaining_length should be defined as int.

**Review by ulaskozat — APPROVED** [review]
LGTM
