### PR TITLE
fix(amf): amf_stateless_test and amf_procedure_test in Bazel test

### LINKED ISSUE #11826: Explore failing //lte/gateway/c/core/oai/test/amf:amf_stateless_test with --config=asan
These commnads should all pass
* `bazel test //lte/gateway/c/core/oai/test/amf:amf_stateless_test --config=asan --compilation_mode=dbg` (currently fails)
* `bazel test //lte/gateway/c/core/oai/test/amf:amf_stateless_test --config=lsan` (passes)
* `bazel test //lte/gateway/c/core/oai/test/amf:amf_stateless_test` (passes)

Output:
```
==================== Test output for //lte/gateway/c/core/oai/test/amf:amf_stateless_test:
Initializing OAI Logging
Initializing OAI Logging to syslog
Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20220226-222554.15482![==========] Running 28 tests from 7 test suites.
[----------] Global test environment set-up.
[----------] 6 tests from TestAMFStateConverter
[ RUN      ] TestAMFStateConverter.TestGutiToString
[       OK ] TestAMFStateConverter.TestGutiToString (0 ms)
[ RUN      ] TestAMFStateConverter.TestStateToProto
[       OK ] TestAMFStateConverter.TestStateToProto (0 ms)
[ RUN      ] TestAMFStateConverter.TestUEm5gmmContextToProto
=================================================================
==15482==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffee811fc86 at pc 0x7f3038dada6d bp 0x7ffee811faa0 sp 0x7ffee811f248
READ of size 7 at 0x7ffee811fc86 thread T0
    #0 0x7f3038dada6c  (/lib/x86_64-linux-gnu/libasan.so.5+0x67a6c)
    #1 0x7f302e641e9b in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&) (/lib/x86_64-linux-gnu/libstdc++.so.6+0x145e9b)
    #2 0x7f30383b85f6 in magma::lte::oai::Tai::set_mcc_mnc(char const*) bazel-out/k8-dbg/bin/lte/protos/oai/nas_state_cpp_proto_pb/lte/protos/oai/nas_state.pb.h:11239
    #3 0x7f30383b30d6 in magma5g::AmfNasStateConverter::tai_to_proto(tai_s const*, magma::lte::oai::Tai*) lte/gateway/c/core/oai/tasks/amf/amf_app_state_converter.cpp:304
    #4 0x7f30383b4114 in magma5g::AmfNasStateConverter::amf_context_to_proto(magma5g::amf_context_s const*, magma::lte::oai::EmmContext*) lte/gateway/c/core/oai/tasks/amf/amf_app_state_converter.cpp:375
    #5 0x7f30383b254d in magma5g::AmfNasStateConverter::ue_m5gmm_context_to_proto(magma5g::ue_m5gmm_context_s const*, magma::lte::oai::UeContext*) lte/gateway/c/core/oai/tasks/amf/amf_app_state_converter.cpp:227
    #6 0x55848a8592ca in magma5g::TestAMFStateConverter_TestUEm5gmmContextToProto_Test::TestBody() lte/gateway/c/core/oai/test/amf/test_amf_stateless.cpp:151
    #7 0x7f302eefcb54 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) external/com_google_googletest/googletest/src/gtest.cc:2439
    #8 0x7f302eef11fb in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) external/com_google_googletest/googletest/src/gtest.cc:2475
    #9 0x7f302eebc6cb in testing::Test::Run() external/com_google_googletest/googletest/src/gtest.cc:2514
    #10 0x7f302eebdb10 in testing::TestInfo::Run() external/com_google_googletest/googletest/src/gtest.cc:2690
    #11 0x7f302eebe7f3 in testing::TestSuite::Run() external/com_google_googletest/googletest/src/gtest.cc:2822
    #12 0x7f302eedae95 in testing::internal::UnitTestImpl::RunAllTests() external/com_google_googletest/googletest/src/gtest.cc:5342
    #13 0x7f302eeffe79 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) external/com_google_googletest/googletest/src/gtest.cc:2439
    #14 0x7f302eef3bbc in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) external/com_google_googletest/googletest/src/gtest.cc:2475
    #15 0x7f302eed7b07 in testing::UnitTest::Run() external/com_google_googletest/googletest/src/gtest.cc:4930
    #16 0x55848a8a8a2d in RUN_ALL_TESTS() external/com_google_googletest/googletest/include/gtest/gtest.h:2472
    #17 0x55848a8a891e in main lte/gateway/c/core/oai/test/amf/amf_app_test.cpp:23
    #18 0x7f302e3160b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #19 0x55848a852ecd in _start (/tmp/bazel/execroot/__main__/bazel-out/k8-dbg/bin/lte/gateway/c/core/oai/test/amf/amf_stateless_test+0x4d6ecd)

Address 0x7ffee811fc86 is located in stack of thread T0 at offset 38 in frame
    #0 0x7f30383b2c63 in magma5g::AmfNasStateConverter::tai_to_proto(tai_s const*, magma::lte::oai::Tai*) lte/gateway/c/core/oai/tasks/amf/amf_app_state_converter.cpp:294

  This frame has 1 object(s):
    [32, 38) 'plmn_array' (line 297) <== Memory access at offset 38 overflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow (/lib/x86_64-linux-gnu/libasan.so.5+0x67a6c) 
Shadow bytes around the buggy address:
  0x10005d01bf40: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10005d01bf50: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 f1 f1
  0x10005d01bf60: f1 f1 f1 f1 01 f2 01 f2 01 f2 00 00 00 00 f2 f2
  0x10005d01bf70: f2 f2 00 00 00 00 00 00 00 f3 f3 f3 f3 f3 00 00
  0x10005d01bf80: 00 00 00 00 00 00 00 00 00 00 00 00 f1 f1 f1 f1
=>0x10005d01bf90:[06]f3 f3 f3 00 00 00 00 00 00 00 00 00 00 00 00
  0x10005d01bfa0: 00 00 00 00 00 00 f1 f1 f1 f1 01 f2 01 f2 00 f2
  0x10005d01bfb0: f2 f2 00 f2 f2 f2 00 f2 f2 f2 00 f2 f2 f2 00 f2
  0x10005d01bfc0: f2 f2 00 f2 f2 f2 00 f2 f2 f2 00 f2 f2 f2 00 f2
  0x10005d01bfd0: f2 f2 00 f2 f2 f2 00 f2 f2 f2 00 f2 f2 f2 00 f2
  0x10005d01bfe0: f2 f2 00 f2 f2 f2 00 f2 f2 f2 00 f2 f2 f2 00 f2
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==15482==ABORTING
================================================================================
Target //lte/gateway/c/core/oai/test/amf:amf_stateless_test up-to-date:
  bazel-bin/lte/gateway/c/core/oai/test/amf/amf_stateless_test
INFO: Elapsed time: 2.354s, Critical Path: 0.98s
INFO: 2 processes: 2 processwrapper-sandbox.
INFO: Build completed, 1 test FAILED, 2 total actions
//lte/gateway/c/core/oai/test/amf:amf_stateless_test                     FAILED in 0.9s
  /tmp/bazel/execroot/__main__/bazel-out/k8-dbg/testlogs/lte/gateway/c/core/oai/test/amf/amf_stateless_test/test.log

INFO: Build completed, 1 test FAILED, 2 total actions
magma % 
```

### LINKED ISSUE #12144: Explore failing //lte/gateway/c/core/oai/test/amf:amf_procedures_test with --config=asan
This bazel test target is failing.

## Reproduction

- If you have access to GitHub Codespaces (you should because you are a member of GH Magma)
- Go over to my [Bazel prototype branch](https://github.com/electronjoe/magma/tree/pr-giant-bazel-mme-rebase)
- Click on the Green colored `Code` drop down button
- Select the `Codespaces` toggle
- Select `New Codespace` and when asked select 16 core (why not!)
- This will spin up a GitHub codespace that contains my branch
- Once the codespace is up (vs code in browswer) in the terminal window type `bazel test //lte/gateway/c/core/oai/test/amf:amf_procedures_test --config=asan` and hit enter. This triggers a bazel build of all necessary components to run the amf_procedures_test, then runs the test

### PR DESCRIPTION
**Pull request by shashidhar-patil**
Signed-off-by: shashidhar-patil <shashidhar.patil@wavelabs.ai>

## Summary
Fixes the following issues: #11826 #12144 

**Cause:** Actual GRPC APIs were being called during the unit testing. This should not happen during unit testing.

**Fix:** Added the required mock APIs in AMFClientServicer. So, now the actual GRPC calls are not made during the unit test.

## Test Plan

- **Bazel tests (on master)**

   1) `bazel test //lte/gateway/c/core/oai/test/amf:amf_stateless_test --runs_per_test=100 --config=asan` 
bazel_stateless_100_asan

   2) `bazel test //lte/gateway/c/core/oai/test/amf:amf_procedures_test --runs_per_test=100 --config=asan`  
bazel_procedures_asan_100

- **Make test_oai**

bazel_100_oai

- **Basic Sanity using Ueransim**

  PCAP snap:
pcap_snap

  Logs:  [mme.log](https://github.com/magma/magma/files/8342320/mme.log)

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Review by ganeshg87 — APPROVED** [review]
lgtm

File: lte/gateway/c/core/oai/tasks/amf/include/amf_client_servicer.h [hunk 1]
```diff
@@ -194,6 +199,12 @@ class AMFClientServicer : public AMFClientServicerBase {
                              amf_ue_ngap_id_t ue_id) override {
     return true;
   }
+
+  int n11_update_location_req(const s6a_update_location_req_t* const ulr_p) {
+    return RETURNok;
+  }
+
+  bool set_smf_notification(SetSmNotificationContext& notify) { return true; }
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/tasks/amf/include/amf_client_servicer.h]:
```suggestion
  bool set_smf_notification(const SetSmNotificationContext& notify) { return true; }
```

File: lte/gateway/c/core/oai/tasks/amf/include/amf_client_servicer.h [hunk 2]
```diff
@@ -101,6 +101,11 @@ class AMFClientServicerBase {
                                      const std::string& ciphertext,
                                      const std::string& mac_tag,
                                      amf_ue_ngap_id_t ue_id);
+
+  virtual int n11_update_location_req(
+      const s6a_update_location_req_t* const ulr_p);
+
+  virtual bool set_smf_notification(SetSmNotificationContext& notify);
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/tasks/amf/include/amf_client_servicer.h]:
```suggestion
  virtual bool set_smf_notification(const SetSmNotificationContext& notify);
```

**Review by ssanadhya — CHANGES_REQUESTED** [review]
Please fix lint warnings

File: lte/gateway/c/core/oai/tasks/amf/include/amf_client_servicer.h (hunk 1 above)
Comment (shashidhar-patil) [reply lte/gateway/c/core/oai/tasks/amf/include/amf_client_servicer.h]: Making this change, required changing the API at `magma/lte/gateway/c/core/oai/lib/n11/SmfServiceClient.h`. Have made the changes. Comment addressed.

File: lte/gateway/c/core/oai/tasks/amf/include/amf_client_servicer.h (hunk 2 above)
Comment (shashidhar-patil) [reply lte/gateway/c/core/oai/tasks/amf/include/amf_client_servicer.h]: Making this change, required changing the API at `magma/lte/gateway/c/core/oai/lib/n11/SmfServiceClient.h`. Have made the changes. Comment addressed.

**Review by ssanadhya — APPROVED** [review]
lgtm
