### PR TITLE
fix(amf): Crash observed when DNN Length is incorrectly encoded by UE

### LINKED ISSUE #12279: [AMF]: Crash observed when DNN Length is incorrectly encoded by UE
Following are the steps :
1. DNN IE : DNN Content Length + DNN Contents
2. DNN Content Length = sizeof(unsigned char) + strlen("DNN Contents") 
    where sizeof(unsigned char) stores the length of DNN.
    If somehow this value is not encoded correctly by UE then memcpy will
    crash. Attaching the Packet snapshot with wrong and correct DNN. In any case crash should be avoided by putting length checks.

### PR DESCRIPTION
**Pull request by sreedharkumartn**
Signed-off-by: sreedharkumartn <sreedhar.kumar@wavelabs.ai>

## Summary
Fixing the issue #12279.

**ISSUE:**
- DNN IE : DNN Content Length + DNN Contents
- DNN Content Length = sizeof(unsigned char) + strlen("DNN Contents")
where sizeof(unsigned char) stores the length of DNN.
If somehow this value is not encoded correctly by UE then memcpy will crash. Attaching the PCAP snapshot of wrong and correct DNN.

Wrong DNN:
image

Correct DNN:
image

**FIX:**
- Added the additional check for DNN Length.

## Test Plan
- Added New Unit test case and validated with UT.
UT 1

- Basic sanity with UERANSIM.
Pcap snap:
image

mme log:
[mme.log](https://github.com/magma/magma/files/8362411/mme.log)

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Review by ganeshg87 — APPROVED** [review]
lgtm

File: lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp [hunk 1]
```diff
@@ -915,6 +915,25 @@ TEST(test_optional_dnn_pdu, test_pdu_session_establish_optional) {
...
+TEST(test_optional_dnn_pdu, test_wrong_dnn_length) {
+  // uplink nas transport(pdu session request)
+  uint8_t pdu[32] = {0x7e, 0x00, 0x67, 0x01, 0x00, 0x07, 0x2e, 0x0a,
+                     0x01, 0xc1, 0xff, 0xff, 0x91, 0x12, 0x0a, 0x81,
+                     0x22, 0x04, 0x01, 0x00, 0x00, 0x01, 0x25, 0x08,
+                     0x08, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74};
+
+  uint32_t len = sizeof(pdu) / sizeof(uint8_t);
+
+  NAS5GPktSnapShot nas5g_pkt_snap;
```
Comment (rsarwad) [inline lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp]: Remove unused variable, nas5g_pkt_snap

File: lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp [hunk 2]
```diff
@@ -915,6 +915,25 @@ TEST(test_optional_dnn_pdu, test_pdu_session_establish_optional) {
...
 }
 
+TEST(test_optional_dnn_pdu, test_wrong_dnn_length) {
+  // uplink nas transport(pdu session request)
+  uint8_t pdu[32] = {0x7e, 0x00, 0x67, 0x01, 0x00, 0x07, 0x2e, 0x0a,
+                     0x01, 0xc1, 0xff, 0xff, 0x91, 0x12, 0x0a, 0x81,
+                     0x22, 0x04, 0x01, 0x00, 0x00, 0x01, 0x25, 0x08,
+                     0x08, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74};
+
+  uint32_t len = sizeof(pdu) / sizeof(uint8_t);
```
Comment (rsarwad) [inline lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp]: Result of sizeof(uint8_t) is always one, right? 
Why do we need this statement?

File: lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp [hunk 3]
```diff
@@ -915,6 +915,25 @@ TEST(test_optional_dnn_pdu, test_pdu_session_establish_optional) {
...
+
+  NAS5GPktSnapShot nas5g_pkt_snap;
+  ULNASTransportMsg pdu_sess_est_req;
```
Comment (rsarwad) [inline lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp]: memset is not required, instead you can initialize all parameters to "zero"

File: lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp [hunk 4]
```diff
@@ -915,6 +915,25 @@ TEST(test_optional_dnn_pdu, test_pdu_session_establish_optional) {
...
+  bool decode_res = false;
+  memset(&pdu_sess_est_req, 0, sizeof(ULNASTransportMsg));
+
+  decode_res = decode_ul_nas_transport_msg(&pdu_sess_est_req, pdu, len);
```
Comment (rsarwad) [inline lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp]: No need of decode_res. It can coded as 
EXPECT_EQ((decode_ul_nas_transport_msg(&pdu_sess_est_req, pdu, len)), false);

File: lte/gateway/c/core/oai/tasks/nas5g/src/ies/M5GDNN.cpp [hunk 5]
```diff
@@ -44,6 +44,14 @@ int DNNMsg::DecodeDNNMsg(DNNMsg* dnn_message, uint8_t iei, uint8_t* buffer,
   uint8_t dnn_length = 0;
   uint8_t dnn_len = 0;
   DECODE_U8(buffer + decoded, dnn_len, decoded);
+
+  if (ielen <= dnn_len) {
+    OAILOG_ERROR(LOG_NAS5G,
+                 "Mismatch Length: IE length : %d, DNN String length: %d",
```
Comment (rsarwad) [inline lte/gateway/c/core/oai/tasks/nas5g/src/ies/M5GDNN.cpp]: Both variables are of type, unit8_t. Change the format specifier to %u

Comment (rsarwad) [inline lte/gateway/c/core/oai/tasks/nas5g/src/ies/M5GDNN.cpp]: Minimum length of DNN is 3 and maximum length of DNN is 102. Can we add this check also?

Comment (sreedharkumartn) [reply lte/gateway/c/core/oai/tasks/nas5g/src/ies/M5GDNN.cpp]: Addressed Review Comment

Comment (sreedharkumartn) [reply lte/gateway/c/core/oai/tasks/nas5g/src/ies/M5GDNN.cpp]: Addressed Review Comment

File: lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp (hunk 4 above)
Comment (sreedharkumartn) [reply lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp]: Addressed Review Comment

File: lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp (hunk 3 above)
Comment (sreedharkumartn) [reply lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp]: Addressed Review Comment

File: lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp (hunk 2 above)
Comment (sreedharkumartn) [reply lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp]: Addressed Review Comment

File: lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp (hunk 1 above)
Comment (sreedharkumartn) [reply lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp]: Addressed Review Comment

**Review by ardzoht — COMMENTED** [review]
not related to the PR, but can we update `dnn_len` on line 61 as there is an outer variable with the same name? this is a legit warning by cpplint

File: lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp [hunk 6]
```diff
@@ -915,6 +915,20 @@ TEST(test_optional_dnn_pdu, test_pdu_session_establish_optional) {
   bdestroy(buffer);
 }
 
+TEST(test_optional_dnn_pdu, test_wrong_dnn_length) {
+  // uplink nas transport(pdu session request)
+  uint8_t pdu[32] = {0x7e, 0x00, 0x67, 0x01, 0x00, 0x07, 0x2e, 0x0a,
+                     0x01, 0xc1, 0xff, 0xff, 0x91, 0x12, 0x0a, 0x81,
+                     0x22, 0x04, 0x01, 0x00, 0x00, 0x01, 0x25, 0x08,
+                     0x08, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74};
+
```
Comment (rsarwad) [inline lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp]: No need of of this line

File: lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp [hunk 7]
```diff
@@ -915,6 +915,20 @@ TEST(test_optional_dnn_pdu, test_pdu_session_establish_optional) {
...
+  uint32_t len = sizeof(pdu);
+
```
Comment (rsarwad) [inline lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp]: No need of of this line

**Comment by sreedharkumartn** [comment]
> not related to the PR, but can we update `dnn_len` on line 61 as there is an outer variable with the same name? this is a legit warning by cpplint

Addressed Review Comment.

File: lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp (hunk 6 above)
Comment (sreedharkumartn) [reply lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp]: Addressed Review Comment

File: lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp (hunk 7 above)
Comment (sreedharkumartn) [reply lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp]: Addressed Review Comment

**Review by rsarwad — APPROVED** [review]
LGTM
