### PR TITLE
fix(session_proxy): add missing code to parse service indicator from …

### LINKED ISSUE #8575: [FeG] add service identifier to terminate request to
### Your Environment

- **Version:** 1.6
- **Affected Component:** FeGs
- **Affected Subcomponent:** FeG containers services
- **Deployment Environment:**  local docker-compose (orc8r), Openstack AGW/FeG)

### Describe the Issue

The CCR-T from FeG to OCS is not including the service-identifier AVP inside the MSCC AVP. OCS is answering 5031 DIAMETER RATING FAILED. In CCR-I and CCR-U, this AVP Service-Identifier it is included, only is missing in the CCR-T.

**Expected behavior**
In order to expect a 2001 as result code inside the MSCC in the CCA-T, the CCR-T needs to include the service-identifier AVP along with Rating Group.

**Screenshots**
No Service-Identifier AVP inside MSCC in the CCR-T
image

Below attached the AGW syslog, FeG session proxy log and trace FeG-DRA:
[Github_issue.zip](https://github.com/magma/magma/files/6958074/Github_issue.zip)

### LINKED ISSUE #8683: TeraVM Regression | Include Service Identifier as part of MSCC in Gy CCR
"Service Identifier” (SID) along with "Rating group”(RG) on Gy CCR under grouped AVP MSCC (multi service credit control) combination is significant, commercial OCS configs generally expects both these values,  generally these SID and RG AVPs are part of a PCC rule (Static or Dynamic) and Gy-CCR_I must have these AVPs under MSCC inorder for OCS to provided right Volume Grants, SID AVP outside of MSCC in Gy CCR message is no more valid for any charging activities hence 3Gpp striked out.

I see in our Gx rules SID+RG is included in rule but on Gy CCR only RG is going in MSCC which need to be changed to include both RG and SID in MSCC. TeraVM OCS function should consider/check both RG+SID values to provide the Volume grants.

GY-CCR , Has only RG, missing to cascade & send SID received in PCC rule on Gx. Need to include RG & SID under MSCC Volume Request, will open GH issue for this.

Screen Shot 2021-08-18 at 10 43 28 PM

Gx Dynamic PCC rule has both Rating Group and Service Identifier. Which looks good.

Screen Shot 2021-08-18 at 10 42 51 PM

PCAP enclosed

[gx_gy_combined_02_210804_062054-1.pcapng.zip](https://github.com/magma/magma/files/7012087/gx_gy_combined_02_210804_062054-1.pcapng.zip)

### PR DESCRIPTION
**Pull request by uri200**
…Gx CCA-I

Signed-off-by: Oriol Batalla <obatalla@fb.com>

## Summary

Added missing Service Indicator parse code from to capture SI from the GX CCR-I response 

## Test Plan
New teravm test `gxgy02b`

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

File: feg/gateway/services/session_proxy/credit_control/gx/model_conversion.go [hunk 1]
```diff
@@ -65,19 +65,27 @@ func (qos *QosRequestInfo) FromProtos(pQos *protos.QosInformationRequest) *QosRe
...
-		Priority:      rd.Precedence,
-		Redirect:      rd.RedirectInformation.ToProto(),
-		FlowList:      rd.GetFlowList(),
-		Qos:           rd.Qos.ToProto(),
-		TrackingType:  rd.GetTrackingType(),
-		Offline:       Int32ToBoolean(rd.Offline),
-		Online:        Int32ToBoolean(rd.Online),
+		Id:                rd.RuleName,
+		RatingGroup:       swag.Uint32Value(rd.RatingGroup),
+		ServiceIdentifier: ServiceIdentifierToProto(rd.ServiceIdentifier),
```
Comment (uri200) [inline feg/gateway/services/session_proxy/credit_control/gx/model_conversion.go:70]: added this line

**Review by emakeev — APPROVED** [review]
LGTM
