### PR TITLE
chore: Fix setup and teardown in Bazel integtest wrapper script

### LINKED ISSUE #13788: Fix setup and teardown in 'bazel/scripts/run_integ_tests.sh'
See https://github.com/vktng/magma/runs/8089413333?check_suite_focus=true#step:13:10286

If the setup and teardown tests for extended or nonsanity tests fail, then the script will exit prematurely. The desired behaviour would be to just skip the relevant tests.

For example if the setup for extended tests fail, then we should skip them and continue with the nonsanity setup. When any of these special tests fail then the printing of the summary and creating of XML reports should still happen.

### PR DESCRIPTION
**Pull request by vktng**
Signed-off-by: Krisztián Varga <krisztian.varga@tngtech.com>

## Summary

When the setup and teardown tests failed, then the script exited prematurely. This PR ensures that if a setup fails, the relevant tests will be skipped and a summary will be printed even if a teardown fails.
This PR closes #13788.

## Test Plan

Damage setup or teardown tests and execute a single test in that category.
 `bazel/scripts/run_integ_tests.sh --help` contains useful information.

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

File: bazel/scripts/run_integ_tests.sh [hunk 1]
```diff
@@ -474,17 +490,30 @@ then
...
+            EXTENDED_SETUP="failed"
+            echo "The setup failed. Skipping extended tests."
+        fi
     fi
 
-    TEST_BATCH_TO_RUN=( "${EXTENDED_TEST_TARGETS[@]}" )
-    run_test_batch
+    if [[ "${EXTENDED_SETUP}" == "success" ]];
+    then
+        TEST_BATCH_TO_RUN=( "${EXTENDED_TEST_TARGETS[@]}" )
```
Comment (LKreutzer) [inline bazel/scripts/run_integ_tests.sh:509]: Perhaps we can move this into line 498, then we do not need the `EXTENDED_SETUP` variable.

File: bazel/scripts/run_integ_tests.sh [hunk 2]
```diff
@@ -493,17 +522,30 @@ then
...
+            echo "The setup failed. Skipping nonsanity tests."
+        fi
     fi
 
-    TEST_BATCH_TO_RUN=( "${NONSANITY_TEST_TARGETS[@]}" )
-    run_test_batch
-
+    if [[ "${NONSANITY_SETUP}" == "success" ]];
+    then
+        TEST_BATCH_TO_RUN=( "${NONSANITY_TEST_TARGETS[@]}" )
```
Comment (LKreutzer) [inline bazel/scripts/run_integ_tests.sh:542]: Same as above.

**Review by LKreutzer — CHANGES_REQUESTED** [review]

File: bazel/scripts/run_integ_tests.sh (hunk 1 above)
Comment (vktng) [reply bazel/scripts/run_integ_tests.sh:509]: If we move it there then the tests will not run if you add the `--skip-setup-teardown-extended` option.

Comment (LKreutzer) [reply bazel/scripts/run_integ_tests.sh:509]: I missed that, got it - lgtm!

**Review by LKreutzer — APPROVED** [review]

File: bazel/scripts/run_integ_tests.sh [hunk 3]
```diff
@@ -493,17 +524,30 @@ then
...
+    NONSANITY_SETUP="success"
     if [[ "${SKIP_NONSANITY_SETUP_AND_TEARDOWN}" == "false" ]];
     then
-        setup_nonsanity_tests
+        if setup_nonsanity_tests;
+        then
+            NONSANITY_SETUP="success"
+        else
+            NONSANITY_SETUP="failed"
+            echo "The setup failed. Skipping nonsanity tests."
```
Comment (LKreutzer) [inline bazel/scripts/run_integ_tests.sh]: We should also add a message to `TEST_RESULTS` here for the nonsanity tests.

**Review by LKreutzer — CHANGES_REQUESTED** [review]

File: bazel/scripts/run_integ_tests.sh (hunk 3 above)
Comment (LKreutzer) [reply bazel/scripts/run_integ_tests.sh]:
```
echo -e "The setup ${RED}failed${NO_FORMATTING}. Skipping nonsanity tests."
TEST_RESULTS["SETUP FOR THE NONSANITY TESTS"]="${RED}FAILED ${YELLOW}(NONSANITY TESTS SKIPPED)${NO_FORMATTING}"
```

**Review by LKreutzer — APPROVED** [review]
