### PR TITLE
fix(amf): bugfix for the issue 9225

### LINKED ISSUE #9225: Support for Regression Failed Testcases "Service request with multiple loops (TC7,TC7a,TC7b,TC7c2,TC7c,TC7d,TC7e,TC7f)"
Below testcases are failing in daily regression. Also these are failing in loop test. This task is created to debug and to fix the issue 

TC7      UE Idle Mode Support (Service Request- Mo Signaling)
TC7a    Verify “PDU session establishment” after Service Request – Signaling & Service Accept
TC7b    UE Idle Mode Support (Service Request - MO Data) + PDU session
TC7c    Verify Service Reject for SReq-MO Signaling
TC7c2  Verify Service Request - Mo Signaling without UE context release - Change the RAN-UE-NGAP-ID in Service Req
TC7d    Verify Service Reject for SReq-MO Data
TC7e    Verify Service Reject cause-#9 after max retry of Registration accept
TC7f	    Verify Service Reject when wrong TMSI is used in Service Request

### PR DESCRIPTION
**Pull request by VinayKumar1591**
fix(amf): bugfix for the issue 9225

## Summary

1. Made changes to fetch uecontext from Guti hash table 
2. fixed issue to support back to back service request procedures

## Test Plan

1. Tested on TVM, NGAP Tester

### CODE REVIEW

File: lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp [hunk 1]
```diff
@@ -82,7 +80,7 @@ void amf_ue_context_update_coll_keys(
         (const hash_key_t) ue_context_p->gnb_ngap_id_key);
     h_rc = hashtable_uint64_ts_insert(
         amf_ue_context_p->gnb_ue_ngap_id_ue_context_htbl,
-        (const hash_key_t) gnb_ngap_id_key, amf_ue_ngap_id);
+        (const hash_key_t) gnb_ngap_id_key, ue_context_p->amf_ue_ngap_id);
```
Comment (ulaskozat) [inline lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp]: why is this change needed? I think the contract of the `amf_ue_context_update_coll_keys` should be well defined.

File: lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp [hunk 2]
```diff
@@ -96,14 +94,14 @@ void amf_ue_context_update_coll_keys(
     ue_context_p->gnb_ngap_id_key = gnb_ngap_id_key;
   }
 
-  if (amf_ue_ngap_id != INVALID_AMF_UE_NGAP_ID) {
+  if (ue_context_p->amf_ue_ngap_id != INVALID_AMF_UE_NGAP_ID) {
```
Comment (ulaskozat) [inline lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp]: same comment. I do not follow why this change is done.

File: lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp [hunk 3]
```diff
@@ -112,22 +110,21 @@ void amf_ue_context_update_coll_keys(
             "amf_ue_ngap_id " AMF_UE_NGAP_ID_FMT PRIX32 " \n",
             amf_ue_ngap_id);
       }
-      ue_context_p->amf_ue_ngap_id = amf_ue_ngap_id;
     }
   } else {
     OAILOG_ERROR(
         LOG_AMF_APP, "Invalid  amf_ue_ngap_id " AMF_UE_NGAP_ID_FMT PRIX32 " \n",
-        amf_ue_ngap_id);
+        ue_context_p->amf_ue_ngap_id);
```
Comment (ulaskozat) [inline lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp]: same comment.

File: lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp [hunk 4]
```diff
@@ -112,22 +110,21 @@ void amf_ue_context_update_coll_keys(
...
   }
 
   h_rc = hashtable_uint64_ts_remove(
       amf_ue_context_p->imsi_amf_ue_id_htbl,
       (const hash_key_t) ue_context_p->amf_context.imsi64);
 
-  if (INVALID_AMF_UE_NGAP_ID != amf_ue_ngap_id) {
+  if (INVALID_AMF_UE_NGAP_ID != ue_context_p->amf_ue_ngap_id) {
```
Comment (ulaskozat) [inline lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp]: same comment.

File: lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp [hunk 5]
```diff
@@ -112,22 +110,21 @@ void amf_ue_context_update_coll_keys(
...
     h_rc = hashtable_uint64_ts_insert(
         amf_ue_context_p->imsi_amf_ue_id_htbl, (const hash_key_t) imsi,
-        amf_ue_ngap_id);
+        ue_context_p->amf_ue_ngap_id);
```
Comment (ulaskozat) [inline lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp]: same comment.

File: lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp [hunk 6]
```diff
@@ -137,7 +134,7 @@ void amf_ue_context_update_coll_keys(
         LOG_AMF_APP,
         "Insertion of Hash entry failed for  "
         "amf_ue_ngap_id " AMF_UE_NGAP_ID_FMT PRIX32 " \n",
-        amf_ue_ngap_id);
+        ue_context_p->amf_ue_ngap_id);
```
Comment (ulaskozat) [inline lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp]: same comment.

File: lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp [hunk 7]
```diff
@@ -146,10 +143,11 @@ void amf_ue_context_update_coll_keys(
       amf_ue_context_p->tun11_ue_context_htbl,
       (const hash_key_t) ue_context_p->amf_teid_n11);
 
-  if (INVALID_AMF_UE_NGAP_ID != amf_ue_ngap_id) {
+  if (INVALID_AMF_UE_NGAP_ID != ue_context_p->amf_ue_ngap_id) {
```
Comment (ulaskozat) [inline lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp]: same comment.

File: lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp [hunk 8]
```diff
@@ -146,10 +143,11 @@ void amf_ue_context_update_coll_keys(
...
     h_rc = hashtable_uint64_ts_insert(
         amf_ue_context_p->tun11_ue_context_htbl,
-        (const hash_key_t) amf_teid_n11, (uint64_t) amf_ue_ngap_id);
+        (const hash_key_t) amf_teid_n11,
+        (uint64_t)ue_context_p->amf_ue_ngap_id);
```
Comment (ulaskozat) [inline lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp]: same comment.

File: lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp [hunk 9]
```diff
@@ -182,10 +180,10 @@ void amf_ue_context_update_coll_keys(
       h_rc = obj_hashtable_uint64_ts_remove(
           amf_ue_context_p->guti_ue_context_htbl,
           &ue_context_p->amf_context.m5_guti, sizeof(*guti_p));
-      if (INVALID_AMF_UE_NGAP_ID != amf_ue_ngap_id) {
+      if (INVALID_AMF_UE_NGAP_ID != ue_context_p->amf_ue_ngap_id) {
```
Comment (ulaskozat) [inline lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp]: same comment.

File: lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp [hunk 10]
```diff
@@ -182,10 +180,10 @@ void amf_ue_context_update_coll_keys(
...
         h_rc = obj_hashtable_uint64_ts_insert(
             amf_ue_context_p->guti_ue_context_htbl, (const void* const) guti_p,
-            sizeof(*guti_p), (uint64_t) amf_ue_ngap_id);
+            sizeof(*guti_p), (uint64_t) ue_context_p->amf_ue_ngap_id);
```
Comment (ulaskozat) [inline lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp]: same comment.

File: lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp [hunk 11]
```diff
@@ -405,6 +405,7 @@ imsi64_t amf_app_handle_initial_ue_message(
 
         /* remove amf_ngap_ud_id entry from ue context */
         amf_remove_ue_context(ue_context_p);
+        old_amf_ue_ngap_id =  ue_context_p->amf_ue_ngap_id;
```
Comment (ulaskozat) [inline lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp]: I think rather than storing the value here like this and using on line 427, line 409 `ue_context_p->amf_ue_ngap_id = INVALID_AMF_UE_NGAP_ID;` should be removed. inside `amf_ue_context_update_coll_keys`, `ue_context_p->amf_ue_ngap_id` should be updated.

**Review by ulaskozat — CHANGES_REQUESTED** [review]
see my comments.

File: lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp (hunk 11 above)
Comment (VinayKumar1591) [reply lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp]: Changes reverted as per comments and made changes as discussed over slack

**Comment by ulaskozat** [comment]
lint-clang-format / lint-clang-format is failing. inside magma vm please run `clang-format --style=file -i \path\to\file`

**Review by ulaskozat — CHANGES_REQUESTED** [review]
just reversion is not sufficient. the update for the `ue_context_p->amf_ue_ngap_id` should not be done by the callee as it is supposed to be done in `amf_ue_context_update_coll_keys`.

**Comment by VinayKumar1591** [comment]
> just reversion is not sufficient. the update for the `ue_context_p->amf_ue_ngap_id` should not be done by the callee as it is supposed to be done in `amf_ue_context_update_coll_keys`.

Addressed

**Review by ulaskozat — APPROVED** [review]
LGTM
