### PR TITLE
fix(nms): Fix feature flag edit

### LINKED ISSUE #13201: Feature flag UI does not get updated
**To Reproduce**
1. Go to host portal ui
2. Go to features 
3. Enable a feature for an organization and save

https://user-images.githubusercontent.com/26038920/177349552-23f6a87c-6e65-4b42-bf6e-cec32502e029.mov

We need to reload to see the changes

### PR DESCRIPTION
**Pull request by HannaFar**
Signed-off-by: HannaFar <hannafarag159@gmail.com>

## Summary

Feature flag ui was not updating if the user did not refresh the page manually.
Closes #13201 

## Test Plan

enabled and disabled features manually 

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Review by Neudrino — APPROVED** [review]
Did a click test. Works for me.

File: nms/server/host/routes.ts [hunk 1]
```diff
@@ -117,10 +117,12 @@ router.post(
       res,
     ) => {
       const featureId = req.params.featureId;
-      const results: Record<FeatureID, FeatureConfig> & {
-        config?: FeatureFlagConfig;
-      } = {...featureConfigs};
-      results.config = {};
+      const results: Record<
```
Comment (thmsschmitt) [inline nms/server/host/routes.ts]: Maybe the code becomes a tiny bit less awkward if start out with one feature flag right away.
I.E.
```ts
const result: FeatureConfig & {
   config?: FeatureFlagConfig;
} = featureConfigs[featureId];
```

**Review by thmsschmitt — APPROVED** [review]
