### PR TITLE
fix(mme): Fix bytes_to_hex stack-buffer-overflow on log.c

### LINKED ISSUE #11970: mme: ASAN crash when running s1aptests/test_attach_detach_with_mme_restart.py
## Repro steps
1. Checkout master
2. Apply CMake changes from https://github.com/magma/magma/pull/11883 to enable ASAN for C++ files in MME
3. Run `s1aptests/test_attach_detach_with_mme_restart.py`

## Error
```bash
sudo jovagrant@magma-dev-focal:~/magma/lte/gateway$ sudo journalctl -fu magma@mme
-- Logs begin at Thu 2021-06-17 23:23:20 UTC. --
Mar 04 16:49:20 magma-dev-focal mme[142341]: Initializing OAI Logging to syslog
Mar 04 16:49:20 magma-dev-focal mme[142341]: Initializing shared logging
Mar 04 16:49:20 magma-dev-focal mme[142341]: Initializing shared logging Done
Mar 04 16:49:20 magma-dev-focal mme[142341]: [SIG][D]MME_UNIT_TEST Flag is Disabled
Mar 04 16:49:20 magma-dev-focal mme[142341]: GetAssignedIPBlock fails with code 14, msg: Connect Failed
Mar 04 16:49:21 magma-dev-focal sudo[142402]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/ovs-vsctl list Open_vSwitch
Mar 04 16:49:21 magma-dev-focal sudo[142402]: pam_unix(sudo:session): session opened for user root by (uid=0)
Mar 04 16:49:21 magma-dev-focal sudo[142402]: pam_unix(sudo:session): session closed for user root
Mar 04 16:49:21 magma-dev-focal mme[142403]: iface_types         : [erspan, geneve, gre, gtpu, internal, ip6erspan, ip6gre, lisp, patch, stt, system, tap, vxlan]
Mar 04 16:49:21 magma-dev-focal mme[142341]: Server running (127.0.0.1:6654)
Mar 04 16:49:38 magma-dev-focal mme[142341]: filename /var/run/mme.pid failed to be written
Mar 04 16:49:38 magma-dev-focal mme[142341]: [INFO] Sending S6A-AUTHENTICATION_INFORMATION_REQUEST with IMSI: 001010000000001
Mar 04 16:49:38 magma-dev-focal mme[142341]: [INFO] Received S6A-AUTHENTICATION_INFORMATION_ANSWER for IMSI: 001010000000001; Status: ; StatusCode: 2001
Mar 04 16:49:38 magma-dev-focal mme[142341]: [DEBUG] Sending S6A-UPDATE_LOCATION_REQUEST with IMSI: 001010000000001
Mar 04 16:49:38 magma-dev-focal mme[142341]: [INFO] Received S6A-LOCATION-UPDATE_ANSWER for IMSI: 001010000000001; Status: ; StatusCode: 2001
Mar 04 16:49:38 magma-dev-focal mme[142341]: [INFO] sent itti S6A-LOCATION-UPDATE_ANSWER for IMSI: 001010000000001
Mar 04 16:49:38 magma-dev-focal mme[142341]: /home/vagrant/magma/lte/gateway/c/core/oai/lib/pcef/pcef_handlers.cpp:344:39: runtime error: index -1 out of bounds for type 'unsigned char [15]'
Mar 04 16:49:38 magma-dev-focal mme[142341]: =================================================================
Mar 04 16:49:38 magma-dev-focal mme[142341]: ==142341==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7f173fae3228 at pc 0x56008ae5e80a bp 0x7f173fae3150 sp 0x7f173fae3140
Mar 04 16:49:38 magma-dev-focal mme[142341]: WRITE of size 1 at 0x7f173fae3228 thread T21
Mar 04 16:49:38 magma-dev-focal mme[142341]:     #0 0x56008ae5e809 in bytes_to_hex /home/vagrant/magma/lte/gateway/c/core/oai/common/log.c:1518
Mar 04 16:49:38 magma-dev-focal mme[142341]:     #1 0x56008ee7594d in get_uli_from_session_req /home/vagrant/magma/lte/gateway/c/core/oai/lib/pcef/pcef_handlers.cpp:329
Mar 04 16:49:38 magma-dev-focal mme[142341]:     #2 0x56008ee77b26 in get_session_req_data /home/vagrant/magma/lte/gateway/c/core/oai/lib/pcef/pcef_handlers.cpp:400
Mar 04 16:49:38 magma-dev-focal mme[142341]:     #3 0x56008e3f74a2 in sgw_handle_ip_allocation_rsp /home/vagrant/magma/lte/gateway/c/core/oai/tasks/sgw/sgw_handlers.c:1856
Mar 04 16:49:38 magma-dev-focal mme[142341]:     #4 0x56008e3d8a7a in handle_message /home/vagrant/magma/lte/gateway/c/core/oai/tasks/sgw/sgw_task.c:189
Mar 04 16:49:38 magma-dev-focal mme[142341]:     #5 0x7f17504625c6 in zloop_start (/lib/x86_64-linux-gnu/libczmq.so.4+0x295c6)
Mar 04 16:49:38 magma-dev-focal mme[142341]:     #6 0x56008e3d8f22 in spgw_app_thread /home/vagrant/magma/lte/gateway/c/core/oai/tasks/sgw/sgw_task.c:227
Mar 04 16:49:38 magma-dev-focal mme[142341]:     #7 0x7f1750f2c608 in start_thread /build/glibc-eX1tMB/glibc-2.31/nptl/pthread_create.c:477
Mar 04 16:49:38 magma-dev-focal mme[142341]:     #8 0x7f174f3b7292 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x122292)
Mar 04 16:49:38 magma-dev-focal mme[142341]: Address 0x7f173fae3228 is located in stack of thread T21 at offset 88 in frame
Mar 04 16:49:38 magma-dev-focal mme[142341]:     #0 0x56008ee73681 in get_uli_from_session_req /home/vagrant/magma/lte/gateway/c/core/oai/lib/pcef/pcef_handlers.cpp:298
Mar 04 16:49:38 magma-dev-focal mme[142341]:   This frame has 1 object(s):
Mar 04 16:49:38 magma-dev-focal mme[142341]:     [48, 88) 'hex_uli' (line 328) <== Memory access at offset 88 overflows this variable
Mar 04 16:49:38 magma-dev-focal mme[142341]: HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
Mar 04 16:49:38 magma-dev-focal mme[142341]:       (longjmp and C++ exceptions *are* supported)
Mar 04 16:49:38 magma-dev-focal mme[142341]: Thread T21 created by T0 here:
Mar 04 16:49:38 magma-dev-focal mme[142341]:     #0 0x7f175118c805 in pthread_create (/lib/x86_64-linux-gnu/libasan.so.5+0x3a805)
Mar 04 16:49:38 magma-dev-focal mme[142341]:     #1 0x56008eebba14 in itti_create_task /home/vagrant/magma/lte/gateway/c/core/oai/lib/itti/intertask_interface.c:333
Mar 04 16:49:38 magma-dev-focal mme[142341]:     #2 0x56008e3d936d in spgw_app_init /home/vagrant/magma/lte/gateway/c/core/oai/tasks/sgw/sgw_task.c:259
Mar 04 16:49:38 magma-dev-focal mme[142341]:     #3 0x56008ae43a7b in main /home/vagrant/magma/lte/gateway/c/core/oai/oai_mme/oai_mme.c:145
Mar 04 16:49:38 magma-dev-focal mme[142341]:     #4 0x7f174f2bc0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
Mar 04 16:49:38 magma-dev-focal mme[142341]: SUMMARY: AddressSanitizer: stack-buffer-overflow /home/vagrant/magma/lte/gateway/c/core/oai/common/log.c:1518 in bytes_to_hex
Mar 04 16:49:38 magma-dev-focal mme[142341]: Shadow bytes around the buggy address:
Mar 04 16:49:38 magma-dev-focal mme[142341]:   0x0fe367f545f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Mar 04 16:49:38 magma-dev-focal mme[142341]:   0x0fe367f54600: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Mar 04 16:49:38 magma-dev-focal mme[142341]:   0x0fe367f54610: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Mar 04 16:49:38 magma-dev-focal mme[142341]:   0x0fe367f54620: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Mar 04 16:49:38 magma-dev-focal mme[142341]:   0x0fe367f54630: 00 00 00 00 00 00 00 00 00 00 f1 f1 f1 f1 f1 f1
Mar 04 16:49:38 magma-dev-focal mme[142341]: =>0x0fe367f54640: 00 00 00 00 00[f3]f3 f3 f3 f3 00 00 00 00 00 00
Mar 04 16:49:38 magma-dev-focal mme[142341]:   0x0fe367f54650: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Mar 04 16:49:38 magma-dev-focal mme[142341]:   0x0fe367f54660: 00 00 00 00 00 00 00 00 00 00 f1 f1 f1 f1 00 04
Mar 04 16:49:38 magma-dev-focal mme[142341]:   0x0fe367f54670: f2 f2 00 00 f2 f2 00 00 00 00 00 00 00 00 00 00
Mar 04 16:49:38 magma-dev-focal mme[142341]:   0x0fe367f54680: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Mar 04 16:49:38 magma-dev-focal mme[142341]:   0x0fe367f54690: 00 00 00 00 00 f2 f2 f2 f2 f2 f2 f2 f2 f2 00 00
Mar 04 16:49:38 magma-dev-focal mme[142341]: Shadow byte legend (one shadow byte represents 8 application bytes):
Mar 04 16:49:38 magma-dev-focal mme[142341]:   Addressable:           00
Mar 04 16:49:38 magma-dev-focal mme[142341]:   Partially addressable: 01 02 03 04 05 06 07
Mar 04 16:49:38 magma-dev-focal mme[142341]:   Heap left redzone:       fa
Mar 04 16:49:38 magma-dev-focal mme[142341]:   Freed heap region:       fd
Mar 04 16:49:38 magma-dev-focal mme[142341]:   Stack left redzone:      f1
Mar 04 16:49:38 magma-dev-focal mme[142341]:   Stack mid redzone:       f2
Mar 04 16:49:38 magma-dev-focal mme[142341]:   Stack right redzone:     f3
Mar 04 16:49:38 magma-dev-focal mme[142341]:   Stack after return:      f5
Mar 04 16:49:38 magma-dev-focal mme[142341]:   Stack use after scope:   f8
Mar 04 16:49:38 magma-dev-focal mme[142341]:   Global redzone:          f9
Mar 04 16:49:38 magma-dev-focal mme[142341]:   Global init order:       f6
Mar 04 16:49:38 magma-dev-focal mme[142341]:   Poisoned by user:        f7
Mar 04 16:49:38 magma-dev-focal mme[142341]:   Container overflow:      fc
Mar 04 16:49:38 magma-dev-focal mme[142341]:   Array cookie:            ac
Mar 04 16:49:38 magma-dev-focal mme[142341]:   Intra object redzone:    bb
Mar 04 16:49:38 magma-dev-focal mme[142341]:   ASan internal:           fe
Mar 04 16:49:38 magma-dev-focal mme[142341]:   Left alloca redzone:     ca
Mar 04 16:49:38 magma-dev-focal mme[142341]:   Right alloca redzone:    cb
Mar 04 16:49:38 magma-dev-focal mme[142341]:   Shadow gap:              cc
Mar 04 16:49:38 magma-dev-focal mme[142341]: ==142341==ABORTING
Mar 04 16:49:43 magma-dev-focal systemd[1]: magma@mme.service: Main process exited, code=killed, status=6/ABRT
Mar 04 16:49:43 magma-dev-focal systemd[1]: magma@mme.service: Failed with result 'signal'.
Mar 04 16:49:49 magma-dev-focal systemd[1]: magma@mme.service: Scheduled restart job, restart counter is at 1.
```

### PR DESCRIPTION
**Pull request by ardzoht**
Signed-off-by: Alex Rodriguez <alexrod@fb.com>

## Summary

- Fixes #11970 
- Replace `sprintf` on bytes_to_hex array to `snprintf`
- https://www.cplusplus.com/reference/cstdio/snprintf/ `snprintf` already leaves space for the terminating null character.

## Test Plan

- `make integ_test` 
- `make integ_test` with https://github.com/magma/magma/pull/11883 changes

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Review by ssanadhya — APPROVED** [review]
lgtm

File: lte/gateway/c/core/oai/common/log.c [hunk 1]
```diff
@@ -1509,12 +1509,10 @@ const char* get_short_file_name(const char* const source_file_nameP) {
 }
 
 // Return the hex representation of a char array
-
 char* bytes_to_hex(char* byte_array, int length, char* hex_array) {
   int i;
   for (i = 0; i < length; i++) {
     sprintf(hex_array + i * 3, " %02x", (unsigned char)byte_array[i]);
   }
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/common/log.c]: @ardzoht, can we replace this `sprintf` with `snprintf`?

Comment (ardzoht) [reply lte/gateway/c/core/oai/common/log.c]: will update the PR, I also think this function should live under `conversions.h/c`, so will move it there as well.
