### PR TITLE
fix(amf): Converting ue_m5gmm_context_t to ue_proto and ue_proto to ue_m5gmm_context_t

### LINKED ISSUE #10763: Converting  ue_m5gmm_context_t to ue_proto and ue_proto to ue_m5gmm_context_t
https://docs.google.com/spreadsheets/d/1ZC2Pv-9OzQgRIhas4UE9DhxVPgOUb_NT/edit#gid=779979932

Please refer above shared Xl book.
write conversation APIs for UE context to Proto for basic types and viseversa.

### PR DESCRIPTION
**Pull request by pratibhag1234**
Signed-off-by: Pratibha Gavhade <pratibha.gavhade@wavelabs.ai>

## Summary
Converting UE context APIs to Proto
 

## Test Plan
 - Verified basic sanity with ueransim
 - Verified using Functional UT
 - Please find attached logs and pcap for basic registration
 
mme log : 
[mme1.log](https://github.com/magma/magma/files/7719693/mme1.log)

pcap snap : 
image

validated ut cases : 
MicrosoftTeams-image (7)

MicrosoftTeams-image (8)

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Review by ssanadhya — APPROVED** [review]

**Comment by ssanadhya** [comment]
@pratibhag1234 , does this PR depend on any other PR? If not, I can merge it.

**Comment by pratibhag1234** [comment]
Thanks for the review comment @ssanadhya.
#10805 #10903 #10853 this three PR should get merge before this PR. I will notify you once all this get merge.

File: lte/gateway/c/core/oai/tasks/amf/amf_app_state_converter.cpp [hunk 1]
```diff
@@ -199,13 +199,70 @@ void AmfNasStateConverter::proto_to_ue(
...
     magma::lte::oai::UeContext* ue_context_proto) {
-  // Actual implementation logic will be added as part of upcoming pr
+  ue_context_proto->set_rel_cause(
+      state_ue_m5gmm_context->ue_context_rel_cause.present);
+  ue_context_proto->set_mm_state(state_ue_m5gmm_context->mm_state);
+  ue_context_proto->set_ecm_state(state_ue_m5gmm_context->ecm_state);
+
+  ue_context_proto->set_sctp_assoc_id_key(
+      state_ue_m5gmm_context->sctp_assoc_id_key);
+  ue_context_proto->set_enb_ue_s1ap_id(state_ue_m5gmm_context->gnb_ue_ngap_id);
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/tasks/amf/amf_app_state_converter.cpp]: Revisiting this in the context of https://github.com/magma/magma/pull/11014#discussion_r788388443. Could you please add a new field for `gnb_ue_ngap_id` in the UE Context proto, instead of overloading the `enb_ue_s1ap_id` field.

File: lte/gateway/c/core/oai/tasks/amf/amf_app_state_converter.cpp [hunk 2]
```diff
@@ -199,13 +199,70 @@ void AmfNasStateConverter::proto_to_ue(
...
+  ue_context_proto->set_enb_s1ap_id_key(
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/tasks/amf/amf_app_state_converter.cpp]: Same comment as above. Please add a field `gnb_ngap_id_key` in the UE Context proto, instead of repurposing the `enb_s1ap_id_key`

File: lte/gateway/c/core/oai/tasks/amf/amf_app_state_converter.cpp [hunk 3]
```diff
@@ -199,13 +199,70 @@ void AmfNasStateConverter::proto_to_ue(
...
+      state_ue_m5gmm_context->gnb_ngap_id_key);
+
+  StateConverter::apn_config_profile_to_proto(
+      state_ue_m5gmm_context->amf_context.apn_config_profile,
+      ue_context_proto->mutable_apn_config());
+
+  ue_context_proto->set_mme_teid_s11(state_ue_m5gmm_context->amf_teid_n11);
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/tasks/amf/amf_app_state_converter.cpp]: Please add a field for `amf_teid_n11` instead of repurposing `mme_teid_s11`

**Review by ssanadhya — CHANGES_REQUESTED** [review]
Minor fixes based on the discussion in https://github.com/magma/magma/pull/11014#discussion_r788388443 .

File: lte/gateway/c/core/oai/tasks/amf/amf_app_state_converter.cpp [hunk 4]
```diff
@@ -199,13 +199,70 @@ void AmfNasStateConverter::proto_to_ue(
...
+      static_cast<ngap_Cause_PR>(ue_context_proto.rel_cause());
+  state_ue_m5gmm_context->mm_state =
+      static_cast<m5gmm_state_t>(ue_context_proto.mm_state());
+  state_ue_m5gmm_context->ecm_state =
+      static_cast<m5gcm_state_t>(ue_context_proto.ecm_state());
+
+  state_ue_m5gmm_context->sctp_assoc_id_key =
+      ue_context_proto.sctp_assoc_id_key();
+  state_ue_m5gmm_context->gnb_ue_ngap_id  = ue_context_proto.enb_ue_s1ap_id();
+  state_ue_m5gmm_context->gnb_ngap_id_key = ue_context_proto.enb_s1ap_id_key();
```
Comment (ardzoht) [inline lte/gateway/c/core/oai/tasks/amf/amf_app_state_converter.cpp]: extending Shruti's remarks, please update these as well with gNB proto properties

**Review by ardzoht — CHANGES_REQUESTED** [review]

File: lte/gateway/c/core/oai/tasks/amf/amf_app_state_converter.cpp (hunk 1 above)
Comment (pratibhag1234) [reply lte/gateway/c/core/oai/tasks/amf/amf_app_state_converter.cpp]: Addressed review comment

File: lte/gateway/c/core/oai/tasks/amf/amf_app_state_converter.cpp (hunk 3 above)
Comment (pratibhag1234) [reply lte/gateway/c/core/oai/tasks/amf/amf_app_state_converter.cpp]: Addressed review comment.

File: lte/gateway/c/core/oai/tasks/amf/amf_app_state_converter.cpp (hunk 4 above)
Comment (pratibhag1234) [reply lte/gateway/c/core/oai/tasks/amf/amf_app_state_converter.cpp]: Addressed review comment.

File: lte/gateway/c/core/oai/tasks/amf/amf_app_state_converter.cpp (hunk 2 above)
Comment (pratibhag1234) [reply lte/gateway/c/core/oai/tasks/amf/amf_app_state_converter.cpp]: Addressed review comment.

**Comment by pratibhag1234** [comment]
@ssanadhya @ardzoht , Added the new proto fields as commented. Please provide your feedback.

**Test Plan**
- Verified basic sanity with ueransim
- Verified using Functional UT
- Please find attached logs and pcap for basic registration

mme log:
[mme2.log](https://github.com/magma/magma/files/7934151/mme2.log)

pcap:
pcap 1

validated ut cases:
Screenshot 2022-01-25 1
Screenshot 2022-01-25 2

**Review by ssanadhya — APPROVED** [review]
LGTM, can be merged once @ardzoht approves.

**Review by ardzoht — APPROVED** [review]
lgtm
