### PR TITLE
[lte][orc8r][agw] SMS bug fix for sms report decoding

### LINKED ISSUE #3187: SMS debugging and follow-up

### PR DESCRIPTION
**Pull request by ulaskozat**
Signed-off-by: Ulas Kozat <kozat@fb.com>

## Summary

Fixed two bugs for SMS handling:
- GRPC exception handling was passing too many parameters.
- Delivery report handling at Orc8r was missing IEI field as the octet preceding each IE.

## Test Plan
Modified and run SMS unit tests.

### CODE REVIEW

**Review by ardzoht — APPROVED** [review]

File: lte/cloud/go/sms_ll/sms_cp.go [hunk 1]
```diff
@@ -84,29 +84,41 @@ func (cpm cpMessage) marshalBinary() []byte {
...
-	case CpError:
-		if _, ok := CpCauseStr[input[2]]; ok {
-			cpm.cause = input[2]
+	if cpm.messageType != CpData && cpm.messageType != CpError && cpm.messageType != CpAck {
+		return smsCpError(fmt.Sprintf("Invalid Message type: %x", cpm.messageType))
+	}
+	// Decode IEs
+	decoded := 2
+
+	for decoded < msgLen {
```
Comment (xjtian) [inline lte/cloud/go/sms_ll/sms_cp.go:102]: this is a weird for loop to me because it seems like if you ever execute the body more than once, you'll hit the error clause.

I would do something like

```
messageType := input[2]
switch messageType:
  case CpIei...:
  case: ...
  default:
    return error(...)
```

**Review by xjtian — CHANGES_REQUESTED** [review]

File: lte/cloud/go/sms_ll/sms_cp.go (hunk 1 above)
Comment (ulaskozat) [reply lte/cloud/go/sms_ll/sms_cp.go:102]: there can be more than 1 IE packed (i.e., both IEs can be present in the same message type and the ordering of IEs does not need to be fixed).

Comment (ulaskozat) [reply lte/cloud/go/sms_ll/sms_cp.go:102]: note how the decoded variable is incremented. If encoding is done right, after all IEs are checked, decoded will be msgLen. Check out the modified test case TestPiecewiseDecodeDeliveryFailure that packs both IEs in the message type CpError.

Comment (ulaskozat) [reply lte/cloud/go/sms_ll/sms_cp.go:102]: and also TestPiecewiseDecodeDeliveryFailureChangeIEOrder that changes the IE orders.

**Review by xjtian — APPROVED** [review]
