### PR TITLE
[NMS] Fix the incomplete bucket chart issue and minor bugs

### LINKED ISSUE #2368: [NMS] Fix the gateway checkin chart to use right theme color
Gateway Checkin chart uses default colors in AsyncMetric component. We should be passing in dodger blue for the checkin chart instead of using default color theme. 

For e.g.
Look at DateTimeMetricChart.js

### LINKED ISSUE #2383: [NMS] Add option to drop incomplete time buckets on all graphs
Graphs will misleadingly dip down if an incomplete time bucket is rendered (e.g. if you are currently 1 hour into a 3 hour bucket). Add an option to all graphs to drop incomplete time buckets and default to true.

### PR DESCRIPTION
**Pull request by karthiksubraveti**
## Summary
1. This PR fixes the issue where we might be displaying data for incomplete buckets towards the end. This behavior is similar to response of prometheus query (which doesn't return incomplete buckets either). We mimic that behavior in the building charts for event and log table charts.
2. minor fix to set the color of gateway checkin chart with the new theme
3. minor fix to ensure that tabs get selected properly when we directly go to the url. Erik's TopBar changes broke this. This fix addresses that bug. 

## Test Plan

Yarn test passes successfully
chart_gif

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

File: nms/app/packages/magmalte/app/components/CustomMetrics.js [hunk 1]
```diff
@@ -46,6 +46,28 @@ export function getStep(start: moment, end: moment): [number, string, string] {
...
+  let s = start.clone();
+  // go back delta time so that we get the total number of events
+  // or logs at that 's' point of time
+  s = s.subtract(delta, unit);
+  while (end.diff(s, unit) >= delta) {
+    const e = s.clone();
+    e.add(delta, unit);
+    queries.push([s, e]);
+    s = e;
+    console.log('TIMESTAMP = ', s);
```
Comment (Scott8440) [inline nms/app/packages/magmalte/app/components/CustomMetrics.js]: whoops

File: nms/app/packages/magmalte/app/components/CustomMetrics.js [hunk 2]
```diff
@@ -46,6 +46,28 @@ export function getStep(start: moment, end: moment): [number, string, string] {
   return [24, 'hour', 'DD-MM-YYYY'];
 }
 
+export function getQueryRanges(
```
Comment (Scott8440) [inline nms/app/packages/magmalte/app/components/CustomMetrics.js:52]: Can you add a comment explaining what this does and why?

**Review by Scott8440 — APPROVED** [review]

File: nms/app/packages/magmalte/app/components/CustomMetrics.js (hunk 1 above)
Comment (karthiksubraveti) [reply nms/app/packages/magmalte/app/components/CustomMetrics.js]: Good catch.Thanks
