### PR TITLE
fix(agw): Better logging for NAS/EMM, tracing IMSI when possible

### LINKED ISSUE #6396: [lte] Increase OAI IMSI logging on MME entities (emm, esm) gaps
### Description

Currently, MME makes use of macros to log each procedure on the tasks. For some of these procedures, we log information about the UE being processed, with information about the subscriber relevant to the MME service. For better tracing, we added macros that accept IMSI in `uint64` version so it's added as a prefix to each log line, however there are many gaps, particularly on `emm` and `esm` entities functions that don't have the IMSI information, making difficult to know which is the UE being processed. 

### Examples

Here is an example of `Authentication.c` procedure usage of OAI log macros, *without* IMSI prefix: https://github.com/magma/magma/blob/master/lte/gateway/c/core/oai/tasks/nas/emm/Authentication.c#L163-L167

Here is an example of `sgw_handlers.c` procedure usage of OAI log macros, *with* IMSI prefix: 
https://github.com/magma/magma/blob/master/lte/gateway/c/core/oai/tasks/sgw/sgw_handlers.c#L118-L121

### Code pointers of logging gaps

A good starting point to cover these gaps is any file under these directories:

- https://github.com/magma/magma/tree/master/lte/gateway/c/core/oai/tasks/nas/emm
- https://github.com/magma/magma/tree/master/lte/gateway/c/core/oai/tasks/nas/esm

For any questions, feel free to contact POC @ardzoht or @ulaskozat

### PR DESCRIPTION
**Pull request by lionelgo**
## Summary

For better readability of NAS EMM logs, use when possible OAI_LOG_loglevel_UE macro instead of  OAI_LOG_loglevel.
This macro displays the UE IMSI.

## Test Plan
Check that when IMSI in known that the EMM log lines display the IMSI.

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

File: lte/gateway/c/core/oai/tasks/nas/emm/Authentication.c [hunk 1]
```diff
@@ -406,8 +406,8 @@ static int auth_info_proc_success_cb(struct emm_context_s* emm_ctx) {
 
   if (auth_info_proc) {
     if (!emm_ctx) {
-      OAILOG_ERROR(
-          LOG_NAS_EMM,
+      OAILOG_ERROR_UE(
+          LOG_NAS_EMM, emm_ctx->_imsi64,
```
Comment (ardzoht) [inline lte/gateway/c/core/oai/tasks/nas/emm/Authentication.c]: This will cause a segfault since emm_ctx is not valid

File: lte/gateway/c/core/oai/tasks/nas/emm/Authentication.c [hunk 2]
```diff
@@ -930,12 +935,12 @@ status_code_e emm_proc_authentication_complete(
     }
 
     if (is_val_fail == true) {
-      OAILOG_WARNING(
-          LOG_NAS_EMM,
-          "XRES/RES Validation Failed for (ue_id=" MME_UE_S1AP_ID_FMT ")\n",
-          ue_id);
       if (!IS_EMM_CTXT_PRESENT_IMSI(
               emm_ctx)) {  // VALID means received in IDENTITY RESPONSE
+        OAILOG_WARNING(
```
Comment (ardzoht) [inline lte/gateway/c/core/oai/tasks/nas/emm/Authentication.c:921]: why was this moved ?

File: lte/gateway/c/core/oai/tasks/nas/emm/ServiceRequestHdl.c [hunk 3]
```diff
@@ -112,9 +107,19 @@ static int emm_service_reject(mme_ue_s1ap_id_t ue_id, uint8_t emm_cause)
...
+        LOG_NAS_EMM, emm_ctx->_imsi64,
+        "EMM-PROC- Sending Service Reject. ue_id=" MME_UE_S1AP_ID_FMT
+        ", cause=%d)\n",
+        ue_id, emm_cause);
     emm_as_set_security_data(
         &emm_sap.u.emm_as.u.establish.sctx, &emm_ctx->_security, false, false);
   } else {
+    OAILOG_WARNING(
+        LOG_NAS_EMM,
+        "EMM-PROC- Sending Service Reject. ue_id=" MME_UE_S1AP_ID_FMT
```
Comment (ardzoht) [inline lte/gateway/c/core/oai/tasks/nas/emm/ServiceRequestHdl.c]:
```suggestion
        "EMM-PROC- Sending Service Reject. No EMM context for the UE. ue_id=" MME_UE_S1AP_ID_FMT
```

**Review by ardzoht — CHANGES_REQUESTED** [review]
Left a couple of comments

File: lte/gateway/c/core/oai/tasks/nas/emm/EmmStatusHdl.c [hunk 4]
```diff
@@ -115,6 +114,11 @@ int emm_proc_status(mme_ue_s1ap_id_t ue_id, emm_cause_t emm_cause) {
     if (ctx) {
       sctx = &ctx->_security;
     }
+    OAILOG_INFO_UE(
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/tasks/nas/emm/EmmStatusHdl.c]: Check if ctx is not-null here.

File: lte/gateway/c/core/oai/tasks/nas/emm/SecurityModeControl.c [hunk 5]
```diff
@@ -485,11 +481,15 @@ status_code_e emm_proc_security_mode_complete(
     if (!emm_ctx) {
       OAILOG_ERROR(
           LOG_NAS_EMM,
-          "EMM-PROC  - emm context is NULL for (ue_id=" MME_UE_S1AP_ID_FMT
-          ")\n",
+          "EMM-PROC  - Security mode complete emm context is NULL for "
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/tasks/nas/emm/SecurityModeControl.c]:
```suggestion
          "EMM-PROC  - Security mode complete received but emm context is NULL for "
```

File: lte/gateway/c/core/oai/tasks/nas/emm/SecurityModeControl.c [hunk 6]
```diff
@@ -638,19 +638,24 @@ status_code_e emm_proc_security_mode_reject(mme_ue_s1ap_id_t ue_id) {
...
+    OAILOG_WARNING_UE(
+        LOG_NAS_EMM, emm_ctx->_imsi64,
+        "EMM-PROC  - Security mode command not accepted by the UE"
+        "(ue_id=" MME_UE_S1AP_ID_FMT ")\n",
+        ue_id);
   } else {
+    OAILOG_WARNING(
+        LOG_NAS_EMM,
+        "EMM-PROC  - Security mode command not accepted by the UE"
+        "(ue_id=" MME_UE_S1AP_ID_FMT ") Emm Context NULL!\n",
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/tasks/nas/emm/SecurityModeControl.c]:
```suggestion
        "(ue_id=" MME_UE_S1AP_ID_FMT ") UE Context NULL!\n",
```

**Review by ssanadhya — CHANGES_REQUESTED** [review]

File: lte/gateway/c/core/oai/tasks/nas/emm/Authentication.c (hunk 2 above)
Comment (lionelgo) [reply lte/gateway/c/core/oai/tasks/nas/emm/Authentication.c:921]: There is already a trace in next else{}, making it redundant

File: lte/gateway/c/core/oai/tasks/nas/emm/EmmStatusHdl.c (hunk 4 above)
Comment (lionelgo) [reply lte/gateway/c/core/oai/tasks/nas/emm/EmmStatusHdl.c]: ctx can't be null here since ue_mm_context is not null. (  emm_context_t emm_context; is part of struct mme_ue_context_t)

File: lte/gateway/c/core/oai/tasks/nas/emm/ServiceRequestHdl.c (hunk 3 above)
Comment (lionelgo) [reply lte/gateway/c/core/oai/tasks/nas/emm/ServiceRequestHdl.c]: Done

File: lte/gateway/c/core/oai/tasks/nas/emm/SecurityModeControl.c (hunk 5 above)
Comment (lionelgo) [reply lte/gateway/c/core/oai/tasks/nas/emm/SecurityModeControl.c]: Done

File: lte/gateway/c/core/oai/tasks/nas/emm/SecurityModeControl.c (hunk 6 above)
Comment (lionelgo) [reply lte/gateway/c/core/oai/tasks/nas/emm/SecurityModeControl.c]: Done

File: lte/gateway/c/core/oai/tasks/nas/emm/Authentication.c (hunk 1 above)
Comment (lionelgo) [reply lte/gateway/c/core/oai/tasks/nas/emm/Authentication.c]: reverted

File: lte/gateway/c/core/oai/tasks/nas/emm/ServiceRequestHdl.c [hunk 7]
```diff
@@ -237,6 +229,21 @@ status_code_e emm_recv_initial_ext_service_request(
     OAILOG_FUNC_RETURN(LOG_NAS_EMM, RETURNerror);
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/tasks/nas/emm/ServiceRequestHdl.c:229]: Can we modify the above log message from: 
"No EMM context exists for the UE (ue_id=" MME_UE_S1AP_ID_FMT ") \n",
to

"EMM-PROC- Extended Service Request received but no EMM context exists for the UE (ue_id=" MME_UE_S1AP_ID_FMT ") \n",

**Review by ssanadhya — APPROVED** [review]
LGTM, with minor nit

File: lte/gateway/c/core/oai/tasks/nas/emm/ServiceRequestHdl.c (hunk 7 above)
Comment (lionelgo) [reply lte/gateway/c/core/oai/tasks/nas/emm/ServiceRequestHdl.c:229]: done

**Review by ardzoht — APPROVED** [review]
lgtm

**Comment by ardzoht** [comment]
@lionelgo there's a failure on the mme unit tests job:

```
[ RUN      ] MmeAppProcedureTest.TestImsiAttachEpsOnlyAuthMacFailure

GMOCK WARNING:
/workspaces/magma/lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp:550: Too many actions specified in EXPECT_CALL(*s1ap_handler, s1ap_handle_conn_est_cnf(_))...
Expected to be never called, but has 0 WillOnce()s and a WillRepeatedly().
GMOCK WARNING:
/workspaces/magma/lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp:550: Too many actions specified in EXPECT_CALL(*spgw_handler, sgw_handle_delete_session_request())...
Expected to be never called, but has 0 WillOnce()s and a WillRepeatedly()./workspaces/magma/lte/gateway/c/core/oai/tasks/nas/emm/Authentication.c:610:3: runtime error: member access within null pointer of type 'struct emm_context_t'
AddressSanitizer:DEADLYSIGNAL
=================================================================
==9885==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000038 (pc 0x563df8a7eb95 bp 0x7f9209468090 sp 0x7f92094650d0 T67)
==9885==The signal is caused by a READ memory access.
==9885==Hint: address points to the zero page.
    #0 0x563df8a7eb94 in emm_proc_authentication_failure /workspaces/magma/lte/gateway/c/core/oai/tasks/nas/emm/Authentication.c:610
    #1 0x563df8b15b54 in emm_recv_authentication_failure /workspaces/magma/lte/gateway/c/core/oai/tasks/nas/emm/sap/emm_recv.c:1096
    #2 0x563df8b8e1ac in emm_as_recv /workspaces/magma/lte/gateway/c/core/oai/tasks/nas/emm/sap/emm_as.c:419
    #3 0x563df8b92c15 in emm_as_data_ind /workspaces/magma/lte/gateway/c/core/oai/tasks/nas/emm/sap/emm_as.c:688
    #4 0x563df8b8c331 in emm_as_send /workspaces/magma/lte/gateway/c/core/oai/tasks/nas/emm/sap/emm_as.c:177
    #5 0x563df8b1a131 in emm_sap_send /workspaces/magma/lte/gateway/c/core/oai/tasks/nas/emm/sap/emm_sap.c:103
    #6 0x563df898e1a3 in nas_proc_ul_transfer_ind /workspaces/magma/lte/gateway/c/core/oai/tasks/nas/nas_proc.c:329
    #7 0x563df865cbbb in handle_message /workspaces/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_main.c:107
    #8 0x7f92267dd5c6 in zloop_start (/lib/x86_64-linux-gnu/libczmq.so.4+0x295c6)
    #9 0x563df86604d2 in mme_app_thread /workspaces/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_main.c:504
    #10 0x7f922682b608 in start_thread /build/glibc-eX1tMB/glibc-2.31/nptl/pthread_create.c:477
    #11 0x7f9224d7c292 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x122292)
```

You can run the specific failing unit test by running:
```
cd ~/build/c/core/oai/test/mme_app_task
sudo ./mme_app_test --gtest_filter=MmeAppProcedureTest.TestImsiAttachEpsOnlyAuthMacFailure
``

**Comment by lionelgo** [comment]
I look

**Comment by lionelgo** [comment]
fixed
