### PR TITLE
fix(cwg): wait for radius server in TestProxy

### LINKED ISSUE #14659: Track failing FeG radius unit tests
There are some flaky/failing FeG radius unit tests, which are skipped and therefore not run in the CI, having been excluded in https://github.com/magma/magma/pull/14655/. These tests should be investigated with the view to them no longer being skipped.

Currently skipped tests (where relevant, number of times failing when running `cd $MAGMA_ROOT/feg/radius/src && go clean -testcache && gotestsum ./...` locally):

Fixes merged:
- [x] TestPostODS https://github.com/magma/magma/pull/14698
- [x] TestBasicInsertGetRedis https://github.com/magma/magma/pull/14692
- [x] TestMultipleConcurrentInsertDeleteGetRedis https://github.com/magma/magma/pull/14692
- [x] TestCoaFixed https://github.com/magma/magma/pull/14701
- [x] TestCoaNas https://github.com/magma/magma/pull/14701
- [x] TestCoaNasNoResponse https://github.com/magma/magma/pull/14701
- [x] TestCoaNasFieldInvalid https://github.com/magma/magma/pull/14701
- [x] TestLBServeProxiesRequestToRadiusAndReturnsResponse https://github.com/magma/magma/pull/14701
- [x] TestLBServeFailsWithRadiusError https://github.com/magma/magma/pull/14701
- [x] TestProxy https://github.com/magma/magma/pull/14845
- [x] TestSendOdsCounters https://github.com/magma/magma/pull/14845
- [x] TestCoaDynamic https://github.com/magma/magma/pull/14880
- [x] TestAnalyticsModulesAuthenticate https://github.com/magma/magma/pull/14906
- [x] TestAnalyticsModulesAccountingStart https://github.com/magma/magma/pull/14906
- [x] TestAnalyticsModulesAccountingUpdate https://github.com/magma/magma/pull/14906
- [x] TestAnalyticsModulesAccountingStop https://github.com/magma/magma/pull/14906
- [x] TestFullRADIUSSessiontWithAnalyticsModules https://github.com/magma/magma/pull/14906
- [x] TestRequestWithModules https://github.com/magma/magma/pull/14906
- [x] TestModuleFailsToHandle https://github.com/magma/magma/pull/14906
- [x] TestFilterFailsToProcess https://github.com/magma/magma/pull/14906
- [x] TestDedup https://github.com/magma/magma/pull/14906

### PR DESCRIPTION
**Pull request by wolfseb**
Part of #14659 

## Summary

* Wait for the radius server to be ready in `TestProxy`
* Increase the wait time of `WaitForRadiusServerToBeReady` from 10 to 20 loops (the test `TestCoaFixed` was observed to fail sometimes due to reaching the limit here)
* Wait for the server to start in `TestSendOdsCounters` (probably better to query the server somehow instead of a flat sleep)

## Test Plan

Run the unit tests

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

File: feg/radius/src/monitoring/scuba/scuba_test.go [hunk 1]
```diff
@@ -59,6 +59,8 @@ func TestSendOdsCounters(t *testing.T) {
 			panic(err)
 		}
 	}()
+	// wait for server to start
```
Comment (voisey) [inline feg/radius/src/monitoring/scuba/scuba_test.go]:
```suggestion
	// Wait for server to start
```

Comment (voisey) [reply feg/radius/src/monitoring/scuba/scuba_test.go]: Nit: just for consistency with the rest of the comments in the file

**Review by voisey — APPROVED** [review]
