### PR TITLE
fix(mme): NGAP module warning cleanup

### LINKED ISSUE #8984: NGAP module warning cleanup
- build manga and capture all warnings from ngap

### PR DESCRIPTION
**Pull request by shashidhar-patil**
Signed-off-by: Shashidhar Patil <shashidhar.patil@wavelabs.ai>

fix(mme): NGAP module warning cleanup (Issue : 8984)

## Summary

Added fixes for NGAP warnings.

## Test Plan

Verified basic sanity with UERANSIM.

 Please find attached logs and pcap snap for basic registration and PDU Session setup.

Logs:
[mme_warning_cleanup.log](https://github.com/magma/magma/files/7204381/mme_warning_cleanup.log)

pcap snap:
pcap_snap

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

File: lte/gateway/c/core/oai/tasks/ngap/ngap_amf_nas_procedures.c [hunk 1]
```diff
@@ -59,6 +59,9 @@
 #include "ngap_amf_handlers.h"
 #include "ngap_common.h"
 
+int ngap_fill_pdu_session_resource_setup_request_transfer(
+    const pdu_session_resource_setup_request_transfer_t* session_transfer,
+    Ngap_PDUSessionResourceSetupRequestTransfer_t* transfer_request);
```
Comment (lionelgo) [inline lte/gateway/c/core/oai/tasks/ngap/ngap_amf_nas_procedures.c]: seems you could use the declaration in lte/gateway/c/core/oai/tasks/ngap/ngap_common.h ?

**Review by lionelgo — CHANGES_REQUESTED** [review]

File: lte/gateway/c/core/oai/tasks/ngap/ngap_amf_nas_procedures.c (hunk 1 above)
Comment (shashidhar-patil) [reply lte/gateway/c/core/oai/tasks/ngap/ngap_amf_nas_procedures.c]: Yes, will make the change

**Review by ulaskozat — APPROVED** [review]
LGTM

**Comment by ulaskozat** [comment]
@lionelgo looks like your comment is addressed, could you check and approve?
