### PR TITLE
[agw] [stateless MME] Fix for failing stateless AGW integration tests

### LINKED ISSUE #3188: Flaky stateless test case with Mobilityd restart
Running test case `test_attach_detach_with_mobilityd_restart.py`  multiple times randomly gets stuck when trying to detach the UE after service restart. MME log reports:
`000292 Wed Oct  7 21:57:12 2020 7FC38C99D700 WARNI S1AP   tasks/s1ap/s1ap_mme_nas_procedur:0283      Received S1AP UPLINK_NAS_TRANSPORT No UE is attached to this mme_ue_s1ap_id: 0x00000003`

### PR DESCRIPTION
**Pull request by ssanadhya**
## Summary

Running the test `test_attach_detach_with_<service>_restart.py` for mme or mobilityd multiple times in a row was showing a failure while trying to detach an attached UE. This was happening as the `s1ap_imsi_map` table was getting cleared from Redis every time the MME process exited, leading to the error: 

`Received S1AP UPLINK_NAS_TRANSPORT No UE is attached to this mme_ue_s1ap_id`

This error only showed up for the second run of the test case even though each test case attaches/detaches two UEs. This is because the first UE detaches with detach-type "Normal detach", which triggered procedures to re-insert the entry in `s1ap_imsi_map`. Only for the second UE, which detached with detach-type "Switch-off" the map stays empty forever.

This change fixes this issue by
- Removing the logic that clears the S1ap imsi map whenever service exits
- Increasing the delay on the stateless config switch script to 30 seconds to work around https://github.com/magma/magma/issues/3077
- Minor edit on a logging statement
- Re-add control plane stateless tests to sanity test suite, data tests still need to be fixed

## Test Plan

- S1AP integration tests with all stateless test cases included
- Run `test_attach_detach_with_mme_restart.py` multiple times and make sure the above error does not occur
- Integration test with CUPS SPGW will be done in Jenkins CI

### CODE REVIEW

File: lte/gateway/c/oai/tasks/s1ap/s1ap_state_manager.cpp [hunk 1]
```diff
@@ -165,12 +165,6 @@ void S1apStateManager::clear_s1ap_imsi_map() {
   hashtable_uint64_ts_destroy(s1ap_imsi_map_->mme_ue_id_imsi_htbl);
 
   free_wrapper((void**) &s1ap_imsi_map_);
-
-  if (persist_state_enabled) {
-    std::vector<std::string> keys_to_del;
-    keys_to_del.emplace_back(S1AP_IMSI_MAP_TABLE_NAME);
-    redis_client->clear_keys(keys_to_del);
-  }
 }
```
Comment (ulaskozat) [inline lte/gateway/c/oai/tasks/s1ap/s1ap_state_manager.cpp:168]: is `S1apStateManager::clear_s1ap_imsi_map()` called only during the service exit?

**Review by ulaskozat — APPROVED** [review]
LGTM

File: lte/gateway/c/oai/tasks/s1ap/s1ap_state_manager.cpp (hunk 1 above)
Comment (ssanadhya) [reply lte/gateway/c/oai/tasks/s1ap/s1ap_state_manager.cpp:168]: Yes, it is only called at service exit, to clear all the memory allocated to the hashtable.

**Review by ardzoht — APPROVED** [review]

**Comment by ssanadhya** [comment]
Merging despite Jenkins CI failures as those failures are unrelated to this change.
