### PR TITLE
fix(mme): Closing latest OF connection on OpenFlowController

### LINKED ISSUE #3538: [agw][mme] Memory leaks
Using this issue to track all memory leaks in MME, triggered by running:

`active_idle_sequencer_mode.py` with defaults (200 UEs) 5 iterations and restarting MME
`configurable_attach_detach.py` with defaults (200 UEs) 5 iterations and restarting MME

```
| Spirent 1.5.2                                  | Spirent 1.6                                    | Spirent master                                      |
|------------------------------------------------|------------------------------------------------|-----------------------------------------------------|
| s1ap_mme_handle_initial_context_setup_response | s1ap_mme_handle_initial_context_setup_response |                                                     |
| fluid_base::BaseOFConnection::OFReadBuffer     | fluid_base::BaseOFConnection::OFReadBuffer     | fluid_base::BaseOFConnection::OFReadBuffer          |
|  esm_recv_pdn_connectivity_request             |                                                |                                                     |
| nas_new_emm_procedures                         |                                                |                                                     |
| nas_new_attach_procedure                       |                                                |                                                     |
| emm_recv_attach_request                        |                                                |                                                     |
| emm_cn_cs_response_success                     |                                                |                                                     |
| emm_cn_ula_success                             |                                                |                                                     |
| decode_esm_message_container                   | decode_esm_message_container                   |                                                     |
| emm_tracking_area_update_accept                | emm_tracking_area_update_accept                |                                                     |
|                                                |                                                |                                                     |

```

Memory leaks on 1.5.2" **[P0]**
`s1ap_mme_handle_initial_context_setup_response` fixed by https://github.com/magma/magma/pull/8481/ (**backported**)
`fluid_base::BaseOFConnection::OFReadBuffer` fixed by https://github.com/magma/magma/pull/8495 (**backported**)
`emm_tracking_area_update_accept` fixed by https://github.com/magma/magma/pull/8029 (**backported**)
`decode_esm_message_container` fixed by https://github.com/magma/magma/pull/8594 (**backported**)
`esm_recv_pdn_connectivity_request` https://github.com/magma/magma/issues/8568 (**closed, not reproducible on latest v1.5**)
`nas_new_attach_procedure` https://github.com/magma/magma/issues/8570 (**closed, not reproducible on latest v1.5**)
`emm_recv_attach_request` https://github.com/magma/magma/issues/8574 (**closed, not reproducible on latest v1.5**)
`emm_cn_ula_success` https://github.com/magma/magma/issues/8571 (**closed, not reproducible on latest v1.5**)

Memory leaks on 1.6: **[P1]**
`s1ap_mme_handle_initial_context_setup_response` fixed by https://github.com/magma/magma/pull/8481/ (pending 1.6 backport)
`fluid_base::BaseOFConnection::OFReadBuffer` fixed by #8495 (pending 1.6 backport)
`emm_tracking_area_update_accept` fixed by https://github.com/magma/magma/pull/8029 (**backported**)
`decode_esm_message_container`  fixed by https://github.com/magma/magma/pull/8594 (**backported**)

Memory leaks on master: **[P1]**
`fluid_base::BaseOFConnection::OFReadBuffer` fixed by https://github.com/magma/magma/pull/8481/
`emm_tracking_area_update_accept` fixed by https://github.com/magma/magma/pull/8029
`decode_esm_message_container`  fixed by https://github.com/magma/magma/pull/8594

### PR DESCRIPTION
**Pull request by ardzoht**
Signed-off-by: Alex Rodriguez <ardzoht@gmail.com>

## Summary

- Fixes a memory leak of `OFBaseConnection` object held on `OpenFlowController` class, seen on https://github.com/magma/magma/issues/5086
```
Feb 22 16:08:55 agw1 mme[26668]:     #0 0x7f56e2ff1cdf in operator new[](unsigned long) (/usr/lib/x86_64-linux-gnu/liblsan.so.0+0xdcdf)
Feb 22 16:08:55 agw1 mme[26668]:     #1 0x7f56e01b4783 in fluid_base::BaseOFConnection::OFReadBuffer::read_notify(unsigned short) fluid/base/BaseOFConnection.cc:84
Feb 22 16:08:55 agw1 mme[26668]:     #2 0x7f56e01b4783 in fluid_base::BaseOFConnection::LibEventBaseOFConnection::read_cb(bufferevent*, void*) fluid/base/BaseOFConnection.cc:353
```
-  Removing assertFatal on s1ap_state_manager if eNB is not found in hashtable

## Test Plan

- running integ tests and restarting MME
- running spirent tests `active_idle` and `attach_detach` iterations 
- unit tests on `TestOpenFlowController`

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

File: lte/gateway/c/core/oai/tasks/s1ap/s1ap_state_manager.cpp [hunk 1]
```diff
@@ -111,17 +111,20 @@ void free_s1ap_state(s1ap_state_t* state_cache_p) {
       assoc_id = (sctp_assoc_id_t) keys->keys[i];
       ht_rc    = hashtable_ts_get(
           &state_cache_p->enbs, (hash_key_t) assoc_id, (void**) &enb);
-      AssertFatal(ht_rc == HASH_TABLE_OK, "eNB UE id not in assoc_id");
+      if (ht_rc != HASH_TABLE_OK) {
+        OAILOG_ERROR(LOG_S1AP, "eNB entry not found in eNB S1AP state");
+      }
       hashtable_uint64_ts_destroy(&enb->ue_id_coll);
```
Comment (ulaskozat) [inline lte/gateway/c/core/oai/tasks/s1ap/s1ap_state_manager.cpp]: would not this lead to crash if `ht_rc != HASH_TABLE_OK`

**Review by ulaskozat — CHANGES_REQUESTED** [review]
Could you check my comment?

File: lte/gateway/c/core/oai/tasks/s1ap/s1ap_state_manager.cpp (hunk 1 above)
Comment (ardzoht) [reply lte/gateway/c/core/oai/tasks/s1ap/s1ap_state_manager.cpp]: updated the if / else case

**Review by ulaskozat — COMMENTED** [review]
can you add a unit test for this? Looks straightforward to add.

**Review by pshelar — APPROVED** [review]
Thanks for taking care of this.

**Review by ulaskozat — APPROVED** [review]
LGTM
