### PR TITLE
fix(agw): Modified code to handle TAU Req for connected UEs

### LINKED ISSUE #11050: bug[MME] unknown-mme-ue-s1ap-id In a specific multi-sim UE scenario
Your Environment:

- Version: 1.7.0-1640913705-e6e795fd (master)
- Affected Component: AGW MME
- Deployment Environment: bare-metal (AGW)

Hi, I'm testing a scenario when Magma acts as a core for data only mobile LTE network.

Environment: **Dual Sim UE**.
One sim slot is for data only services (our LTE network with Magma in a center).
Second sim slot is for voice and sms service from regular mobile operator.

I found inconvenience with some dual sim dual standby UE like Samsung A01s, Redmi Note 9 and other:
When multiple sms come to mobile operator sim, our sim card inserted to first slot lost connection for few minutes.
Many different combination of Android configuration has been tested, like sim card priority, network type restrictions, etc.
No luck.

To Reproduce:
1. Some UE like Samsung A01s, Redmi Note 9 with two sim card activated. One sim with data services, another one with voice and sms.
2. Send multiple sms in a short period of time to sim with voice and sms services. This behaivior is common for many  sms chat application.

Here is log and capture:
[magmaDoubleSimTest.zip](https://github.com/magma/magma/files/7809271/magmaDoubleSimTest.zip)

### PR DESCRIPTION
**Pull request by rsarwad**
fix(agw): Modified code to handle TAU Req for connected UEs
## Test Plan
Executed s1ap sanity test suite, for which test_multi_enb_complete_reset.py was failing because as part of this TC; it first connects 5 eNBs and for each eNB there shall be one UE connected. 
When complete reset is initiated for one eNB; but all UE contexts were getting deleted; Ideally we need to delete the contexts only for the UE for which eNB Reset is triggered. The changes are available in PR, https://github.com/facebookexperimental/S1APTester/pull/70

### CODE REVIEW

File: lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.c [hunk 1]
```diff
@@ -1610,7 +1619,18 @@ status_code_e s1ap_mme_handle_ue_context_release_complete(
           " UE Context Release commplete: S1 context should have been cleared "
           "for ueid " MME_UE_S1AP_ID_FMT "\n",
           (uint32_t) mme_ue_s1ap_id);
-      OAILOG_FUNC_RETURN(LOG_S1AP, RETURNerror);
+      // Dont remove UE context if UE handed over to another eNB
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.c]: Align the comment with the if condition
```suggestion
      // Remove UE context only if UE is not handed over to another eNB
```

Comment (ssanadhya) [reply lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.c]: Further, the logs/comments in lines 1601-1621 can be removed since the UE context is not cleared when UE context release is sent in this new logic.

File: lte/gateway/c/core/oai/tasks/s1ap/s1ap_timer_management.cpp [hunk 2]
```diff
@@ -0,0 +1,85 @@
...
+This source code is licensed under the BSD-style license found in the
+LICENSE file in the root directory of this source tree.
+
+Unless required by applicable law or agreed to in writing, software
+distributed under the License is distributed on an "AS IS" BASIS,
+WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+See the License for the specific language governing permissions and
+limitations under the License.
+*/
+//--C includes -----------------------------------------------------------------
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/tasks/s1ap/s1ap_timer_management.cpp]: Please address lint warnings

File: lte/gateway/c/core/oai/tasks/s1ap/s1ap_timer_management.h [hunk 3]
```diff
@@ -0,0 +1,62 @@
...
+This source code is licensed under the BSD-style license found in the
+LICENSE file in the root directory of this source tree.
+
+Unless required by applicable law or agreed to in writing, software
+distributed under the License is distributed on an "AS IS" BASIS,
+WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+See the License for the specific language governing permissions and
+limitations under the License.
+*/
+#ifndef FILE_S1AP_UE_CONTEXT_H_SEEN
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/tasks/s1ap/s1ap_timer_management.h]: Replace with `#pragma once`

File: lte/gateway/c/core/oai/tasks/s1ap/s1ap_timer_management.h [hunk 4]
```diff
@@ -0,0 +1,62 @@
...
+#define FILE_S1AP_UE_CONTEXT_H_SEEN
+// C includes --------------------------------------------------------------
+extern "C" {
+#include "lte/gateway/c/core/oai/lib/itti/intertask_interface.h"
+#include "lte/gateway/c/core/oai/tasks/s1ap/s1ap_timer.h"
+}
+// C++ includes ------------------------------------------------------------
+#include <czmq.h>
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/tasks/s1ap/s1ap_timer_management.h]: Please fix lint warninngs

File: lte/gateway/c/core/oai/tasks/mme_app/mme_app_context.c [hunk 5]
```diff
@@ -1183,14 +1190,51 @@ void mme_app_handle_s1ap_ue_context_release_complete(
...
     }
   } else {
-    // Update keys and ECM state
+    move_ue_to_idle = true;
+  }
+  // Move the UE to Idle state
+  if (move_ue_to_idle) {
     mme_ue_context_update_ue_sig_connection_state(
         &mme_app_desc_p->mme_ue_contexts, ue_context_p, ECM_IDLE);
+    if ((ue_context_p->ue_context_rel_cause == S1AP_INVALID_ENB_ID) &&
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/tasks/mme_app/mme_app_context.c:1191]: Please add a comment here to explain when this condition is met, i.e. if UE Context Release was sent after receiving Initial UE Message for UE in Ecm_connected state. The "saved" Initial UE Message needs to be processed once UE context release complete is received

**Review by ssanadhya — CHANGES_REQUESTED** [review]

File: lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.c [hunk 6]
```diff
@@ -1589,15 +1598,10 @@ status_code_e s1ap_mme_handle_ue_context_release_complete(
...
-    /*
-     * The UE context has already been deleted when the UE context release
-     * command was sent
-     * Ignore this message.
-     */
     OAILOG_DEBUG(
         LOG_S1AP,
-        " UE Context Release commplete: S1 context cleared. Ignore message for "
-        "ueid " MME_UE_S1AP_ID_FMT "\n",
+        "On reception of UE Context Release commplete: Failed to find ue "
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.c]:
```suggestion
        "On reception of UE Context Release complete: Failed to find ue "
```

File: lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.c [hunk 7]
```diff
@@ -1610,7 +1614,18 @@ status_code_e s1ap_mme_handle_ue_context_release_complete(
           " UE Context Release commplete: S1 context should have been cleared "
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.c]: Please remove the comment before this log message and update the log message
```suggestion
          " UE Context Release complete: clearing S1 context"
```

**Review by ssanadhya — APPROVED** [review]
LGTM, with minor comments. Please revise and mark it as `ready2merge`.
