### PR TITLE
fix(mme): Fix mme_app_remove_ue_ipv6_addr and get_msisdn_from_session…

### LINKED ISSUE #12019: [mme] Runtime error while running integ_tests on pcef_handlers.cpp
### Your Environment

- **Version:** master
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** MME

### Describe the Issue

- Subtask of https://github.com/magma/magma/issues/11978

- Running any integ test under `make integ_test` on magma VM with ASAN enabled for C++ code raises this error:
```
Mar 09 01:07:21 magma-dev-focal mme[988832]: Directoryd RPC failed with code 5, msg: Record for ID IMSI was not found.
Mar 09 01:07:21 magma-dev-focal mme[988832]: [INFO] Sending S6A-AUTHENTICATION_INFORMATION_REQUEST with IMSI: 001010000000002
Mar 09 01:07:21 magma-dev-focal mme[988832]: [INFO] Received S6A-AUTHENTICATION_INFORMATION_ANSWER for IMSI: 001010000000002; Status: ; StatusCode: 2001
Mar 09 01:07:21 magma-dev-focal mme[988832]: [DEBUG] Sending S6A-UPDATE_LOCATION_REQUEST with IMSI: 001010000000002
Mar 09 01:07:21 magma-dev-focal mme[988832]: [INFO] Received S6A-LOCATION-UPDATE_ANSWER for IMSI: 001010000000002; Status: ; StatusCode: 2001
Mar 09 01:07:21 magma-dev-focal mme[988832]: [INFO] sent itti S6A-LOCATION-UPDATE_ANSWER for IMSI: 001010000000002
Mar 09 01:07:21 magma-dev-focal mme[988832]: /home/vagrant/magma/lte/gateway/c/core/oai/lib/pcef/pcef_handlers.cpp:343:39: runtime error: index -1 out of bounds for type 'unsigned char [15]'
```

### LINKED ISSUE #12021: [mme] heap-use-after-free crash while running s1ap test: test_ipv6_paging_with_dedicated_bearer
1. Run `test_ipv6_paging_with_dedicated_bearer.py` with changes applied from https://github.com/magma/magma/pull/11883

```
Mar 09 05:12:27 magma-dev-focal mme[1162173]: ==1162173==ERROR: AddressSanitizer: heap-use-after-free on address 0x60700007f5c0 at pc 0x55e42755d35c bp 0x7f9bcf4a9140 sp 0x7f9bcf4a9130
Mar 09 05:12:27 magma-dev-focal mme[1162173]: READ of size 8 at 0x60700007f5c0 thread T14
Mar 09 05:12:27 magma-dev-focal mme[1162173]:     #0 0x55e42755d35b in __gnu_cxx::__normal_iterator<unsigned long*, std::vector<unsigned long, std::allocator<unsigned long> > >::__normal_iterator(unsigned long* const&) /usr/include/c++/9/bits/stl_iterator.h:807
Mar 09 05:12:27 magma-dev-focal mme[1162173]:     #1 0x55e427557d0a in std::vector<unsigned long, std::allocator<unsigned long> >::end() /usr/include/c++/9/bits/stl_vector.h:827
Mar 09 05:12:27 magma-dev-focal mme[1162173]:     #2 0x55e42755358a in mme_app_remove_ue_ipv6_addr /home/vagrant/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_ip_imsi.cpp:233
Mar 09 05:12:27 magma-dev-focal mme[1162173]:     #3 0x55e427400f85 in mme_app_handle_delete_session_rsp /home/vagrant/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_bearer.c:917
Mar 09 05:12:27 magma-dev-focal mme[1162173]:     #4 0x55e4273e9c21 in handle_message /home/vagrant/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_main.c:198
Mar 09 05:12:27 magma-dev-focal mme[1162173]:     #5 0x7f9bdc5965c6 in zloop_start (/lib/x86_64-linux-gnu/libczmq.so.4+0x295c6)
Mar 09 05:12:27 magma-dev-focal mme[1162173]:     #6 0x55e4273ec449 in mme_app_thread /home/vagrant/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_main.c:516
Mar 09 05:12:27 magma-dev-focal mme[1162173]:     #7 0x7f9bdd060608 in start_thread /build/glibc-eX1tMB/glibc-2.31/nptl/pthread_create.c:477
Mar 09 05:12:27 magma-dev-focal mme[1162173]:     #8 0x7f9bdb4eb292 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x122292)
Mar 09 05:12:27 magma-dev-focal mme[1162173]: 0x60700007f5c0 is located 48 bytes inside of 72-byte region [0x60700007f590,0x60700007f5d8)
Mar 09 05:12:27 magma-dev-focal mme[1162173]: freed by thread T14 here:
Mar 09 05:12:27 magma-dev-focal mme[1162173]:     #0 0x7f9bdd3968df in operator delete(void*) (/lib/x86_64-linux-gnu/libasan.so.5+0x1108df)
Mar 09 05:12:27 magma-dev-focal mme[1162173]:     #1 0x55e427566149 in __gnu_cxx::new_allocator<std::__detail::_Hash_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<unsigned long, std::allocator<unsigned long> > >, true> >::deallocate(std::__detail::_Hash_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<unsigned long, std::allocator<unsigned long> > >, true>*, unsigned long) /usr/include/c++/9/ext/new_allocator.h:128
Mar 09 05:12:27 magma-dev-focal mme[1162173]:     #2 0x55e427562db1 in std::allocator_traits<std::allocator<std::__detail::_Hash_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<unsigned long, std::allocator<unsigned long> > >, true> > >::deallocate(std::allocator<std::__detail::_Hash_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<unsigned long, std::allocator<unsigned long> > >, true> >&, std::__detail::_Hash_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<unsigned long, std::allocator<unsigned long> > >, true>*, unsigned long) /usr/include/c++/9/bits/alloc_traits.h:470
Mar 09 05:12:27 magma-dev-focal mme[1162173]:     #3 0x55e427566e6d in std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<unsigned long, std::allocator<unsigned long> > >, true> > >::_M_deallocate_node_ptr(std::__detail::_Hash_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<unsigned long, std::allocator<unsigned long> > >, true>*) /usr/include/c++/9/bits/hashtable_policy.h:2113
Mar 09 05:12:27 magma-dev-focal mme[1162173]:     #4 0x55e427563dc3 in std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<unsigned long, std::allocator<unsigned long> > >, true> > >::_M_deallocate_node(std::__detail::_Hash_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<unsigned long, std::allocator<unsigned long> > >, true>*) /usr/include/c++/9/bits/hashtable_policy.h:2103
Mar 09 05:12:27 magma-dev-focal mme[1162173]:     #5 0x55e427565572 in std::_Hashtable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<unsigned long, std::allocator<unsigned long> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<unsigned long, std::allocator<unsigned long> > > >, std::__detail::_Select1st, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_erase(unsigned long, std::__detail::_Hash_node_base*, std::__detail::_Hash_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<unsigned long, std::allocator<unsigned long> > >, true>*) (/home/vagrant/build/c/core/oai/oai_mme/mme+0x7a05572)
Mar 09 05:12:27 magma-dev-focal mme[1162173]:     #6 0x55e427561f31 in std::_Hashtable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<unsigned long, std::allocator<unsigned long> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<unsigned long, std::allocator<unsigned long> > > >, std::__detail::_Select1st, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_erase(std::integral_constant<bool, true>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (/home/vagrant/build/c/core/oai/oai_mme/mme+0x7a01f31)
Mar 09 05:12:27 magma-dev-focal mme[1162173]:     #7 0x55e42755e493 in std::_Hashtable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<unsigned long, std::allocator<unsigned long> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<unsigned long, std::allocator<unsigned long> > > >, std::__detail::_Select1st, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::erase(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (/home/vagrant/build/c/core/oai/oai_mme/mme+0x79fe493)
Mar 09 05:12:27 magma-dev-focal mme[1162173]:     #8 0x55e427558de3 in std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<unsigned long, std::allocator<unsigned long> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<unsigned long, std::allocator<unsigned long> > > > >::erase(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (/home/vagrant/build/c/core/oai/oai_mme/mme+0x79f8de3)
Mar 09 05:12:27 magma-dev-focal mme[1162173]:     #9 0x55e427553208 in mme_app_remove_ue_ipv6_addr /home/vagrant/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_ip_imsi.cpp:227
Mar 09 05:12:27 magma-dev-focal mme[1162173]:     #10 0x55e427400f85 in mme_app_handle_delete_session_rsp /home/vagrant/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_bearer.c:917
Mar 09 05:12:27 magma-dev-focal mme[1162173]:     #11 0x55e4273e9c21 in handle_message /home/vagrant/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_main.c:198
Mar 09 05:12:27 magma-dev-focal mme[1162173]:     #12 0x7f9bdc5965c6 in zloop_start (/lib/x86_64-linux-gnu/libczmq.so.4+0x295c6)
Mar 09 05:12:27 magma-dev-focal mme[1162173]: previously allocated by thread T14 here:
Mar 09 05:12:27 magma-dev-focal mme[1162173]:     #0 0x7f9bdd395947 in operator new(unsigned long) (/lib/x86_64-linux-gnu/libasan.so.5+0x10f947)
Mar 09 05:12:27 magma-dev-focal mme[1162173]:     #1 0x55e427565cb4 in __gnu_cxx::new_allocator<std::__detail::_Hash_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<unsigned long, std::allocator<unsigned long> > >, true> >::allocate(unsigned long, void const*) /usr/include/c++/9/ext/new_allocator.h:114
Mar 09 05:12:27 magma-dev-focal mme[1162173]:     #2 0x55e427562b8f in std::allocator_traits<std::allocator<std::__detail::_Hash_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<unsigned long, std::allocator<unsigned long> > >, true> > >::allocate(std::allocator<std::__detail::_Hash_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<unsigned long, std::allocator<unsigned long> > >, true> >&, unsigned long) (/home/vagrant/build/c/core/oai/oai_mme/mme+0x7a02b8f)
Mar 09 05:12:27 magma-dev-focal mme[1162173]:     #3 0x55e42755f4d0 in std::__detail::_Hash_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<unsigned long, std::allocator<unsigned long> > >, true>* std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<unsigned long, std::allocator<unsigned long> > >, true> > >::_M_allocate_node<std::piecewise_construct_t const&, std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&>, std::tuple<> >(std::piecewise_construct_t const&, std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&>&&, std::tuple<>&&) (/home/vagrant/build/c/core/oai/oai_mme/mme+0x79ff4d0)
Mar 09 05:12:27 magma-dev-focal mme[1162173]:     #4 0x55e42755aa48 in std::__detail::_Map_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<unsigned long, std::allocator<unsigned long> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<unsigned long, std::allocator<unsigned long> > > >, std::__detail::_Select1st, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true>, true>::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&) (/home/vagrant/build/c/core/oai/oai_mme/mme+0x79faa48)
Mar 09 05:12:27 magma-dev-focal mme[1162173]:     #5 0x55e427555976 in std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<unsigned long, std::allocator<unsigned long> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<unsigned long, std::allocator<unsigned long> > > > >::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&) /usr/include/c++/9/bits/unordered_map.h:989
Mar 09 05:12:27 magma-dev-focal mme[1162173]:     #6 0x55e42754da00 in mme_app_insert_ue_ipv6_addr /home/vagrant/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_ip_imsi.cpp:90
Mar 09 05:12:27 magma-dev-focal mme[1162173]:     #7 0x55e427408075 in mme_app_handle_create_sess_resp /home/vagrant/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_bearer.c:1218
Mar 09 05:12:27 magma-dev-focal mme[1162173]:     #8 0x55e4273e8d78 in handle_message /home/vagrant/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_main.c:132
Mar 09 05:12:27 magma-dev-focal mme[1162173]:     #9 0x7f9bdc5965c6 in zloop_start (/lib/x86_64-linux-gnu/libczmq.so.4+0x295c6)
Mar 09 05:12:27 magma-dev-focal mme[1162173]: Thread T14 created by T0 here:
Mar 09 05:12:27 magma-dev-focal mme[1162173]:     #0 0x7f9bdd2c0805 in pthread_create (/lib/x86_64-linux-gnu/libasan.so.5+0x3a805)
Mar 09 05:12:27 magma-dev-focal mme[1162173]:     #1 0x55e42adb88c6 in itti_create_task /home/vagrant/magma/lte/gateway/c/core/oai/lib/itti/intertask_interface.c:333
Mar 09 05:12:27 magma-dev-focal mme[1162173]:     #2 0x55e4273eccca in mme_app_init /home/vagrant/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_main.c:556
Mar 09 05:12:27 magma-dev-focal mme[1162173]:     #3 0x55e426d794a2 in main /home/vagrant/magma/lte/gateway/c/core/oai/oai_mme/oai_mme.c:139
Mar 09 05:12:27 magma-dev-focal mme[1162173]:     #4 0x7f9bdb3f00b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
Mar 09 05:12:27 magma-dev-focal mme[1162173]: SUMMARY: AddressSanitizer: heap-use-after-free /usr/include/c++/9/bits/stl_iterator.h:807 in __gnu_cxx::__normal_iterator<unsigned long*, std::vector<unsigned long, std::allocator<unsigned long> > >::__normal_iterator(unsigned long* const&)
```

### PR DESCRIPTION
**Pull request by ardzoht**
…_req length

Signed-off-by: Alex Rodriguez <alexrod@fb.com>

## Summary

- Closes #12019 and #12021
- Updates `mme_app_remove_ue_ipv6_addr` with extra check for non-existing lookup and also updates `vec_it` traversal on the for loop for both `mme_app_remove_ue_...` ipv4/v6 versions
- Adds check for zero length msisdn in case it's empty 

## Test Plan

- `make integ_test` with and without https://github.com/magma/magma/pull/11883 changes applied

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

File: lte/gateway/c/core/oai/tasks/mme_app/mme_app_ip_imsi.cpp [hunk 1]
```diff
@@ -217,20 +218,22 @@ void mme_app_remove_ue_ipv6_addr(struct in6_addr ipv6_addr, imsi64_t imsi64) {
     OAILOG_FUNC_OUT(LOG_MME_APP);
   } else {
     auto vec_it = itr_map->second.begin();
-    for (; vec_it != itr_map->second.end(); ++vec_it) {
+    for (; vec_it != itr_map->second.end();) {
```
Comment (ulaskozat) [inline lte/gateway/c/core/oai/tasks/mme_app/mme_app_ip_imsi.cpp]: why not simply make this a while loop?

File: lte/gateway/c/core/oai/tasks/mme_app/mme_app_ip_imsi.cpp [hunk 2]
```diff
@@ -178,17 +178,18 @@ void mme_app_remove_ue_ipv4_addr(uint32_t ipv4_addr, imsi64_t imsi64) {
...
```
Comment (ulaskozat) [inline lte/gateway/c/core/oai/tasks/mme_app/mme_app_ip_imsi.cpp]: why not a simpler while loop?

**Review by ulaskozat — APPROVED** [review]
LGTM with a minor comment.
