### PR TITLE
[agw] [stateless mme] Fix memory leaks in stateless MME

### LINKED ISSUE #3398: Stress testing with real UE:
- Restart each service multiple times while UE is connected and sending traffic
- Restart each service while UE is in idle mode
- Restart service when UE is not authorized
- Fix memory leaks as seen in [mem_leaks0.log](https://github.com/magma/magma/files/5454892/mem_leaks0.log)

### PR DESCRIPTION
**Pull request by ssanadhya**
## Summary

This change fixes several memory leaks observed while running stateless MME S1AP tests and while testing stateless AGW in testbed in:
- Guti hash table
- Attach request IEs
- Protocol configuration options
- GetEnbConnected
- SPGW bearer context

This does not fix the leaks from:
- zlist_new in libczmq
- fluid_base::BaseOFConnection::OFReadBuffer::read_notify in libfluid (seen only on first run of MME)

These need to be suppressed using Lsan suppresion as they are leaks in third-party library. Future PR will handle them.

## Test Plan

- S1ap integration tests
- Build Magma package and test on FWA testbed

In both cases syslog shows only memory leaks from libzmq and/or libfluid

### CODE REVIEW

File: lte/gateway/c/oai/tasks/sgw/sgw_task.c [hunk 1]
```diff
@@ -77,6 +77,8 @@ static int handle_message(zloop_t* loop, zsock_t* reader, void* arg) {
       sgw_handle_s11_create_session_request(
           spgw_state, &received_message_p->ittiMsg.s11_create_session_request,
           imsi64);
+      clear_protocol_configuration_options(
+          &received_message_p->ittiMsg.s11_create_session_request.pco);
```
Comment (ulaskozat) [inline lte/gateway/c/oai/tasks/sgw/sgw_task.c]: you should move this to `itti_free_msg_content`.

**Review by ulaskozat — CHANGES_REQUESTED** [review]
One minor comment needs to be addressed before merge.

File: lte/gateway/c/oai/tasks/sgw/sgw_task.c (hunk 1 above)
Comment (ssanadhya) [reply lte/gateway/c/oai/tasks/sgw/sgw_task.c]: Fixed in latest version

**Review by ulaskozat — APPROVED** [review]
LGTM

**Comment by ssanadhya** [comment]
Merging despite Jenkins CI is failing as the CI is failing on CUPS SPGW setup, unrelated to MME.
