### PR TITLE
feg(session_proxy): fix HOST-IP-ADDRESS on CER

### LINKED ISSUE #8752: [FEG] Host-IP-Address AVP in CER is hardcoded to 127.0.0.1
According to Diameter RFC https://datatracker.ietf.org/doc/html/rfc6733 
the AVP Host-IP-Address in CER should be set to the IP address which will be used to send diameter messages. As of now its  hardcoded to localhost ip  address 127.0.0.1.
During a recent interop with a 3rdParty PCRF, this  caused an issue as the PCRF was expecting the IP address of the transport endpoint sending CER. 

After we changed the Host-IP-Address AVP to contain valid IP address, the  CER-CEA exchange was successful. (Please see screenshots
Screen Shot 2021-08-25 at 10 27 00 AM
) 

### Your Environment

AGW-Feg. Orc8r in AWS. 
Operator PCRF from Huawei.  
Screen Shot 2021-08-23 at 3 55 53 PM

### LINKED ISSUE #10001: Attach Reject due to Network Failure Cause 17
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Your Environment

- **Version:**  1.6.0-1625592603-1f26ba81
- **Affected Component:**  Access Gateway, or FeGW
- **Affected Subcomponent:** OCS
- **Deployment Environment:** e.g. AWS (orc8r),  bare-metal (AGW), bare-metal (FeGW)

### Describe the Issue 

I am  facing the problem in my setup. I configured Sigscale OCS with Magma FeGW.
When UE will be send InitialUEMessage, Attach request message to MME then
MME giving response Attach reject message (Network failure). I debug this Network Failure & in this Attach reject message (Network Failure). I saw the MME logs and I found It show Attach reject message (cause #17).
Cause #17 = Network failure This EMM cause is sent to the UE if the MME cannot service an UE generated request because of PLMN failures.
I verified the PLMN is both side AGW and SigScale OCS but PLMN value configured is same.

PFA pcap screenshot & MME logs for reference.

OCS Diameter
S1AP snap
GX
GY
S6A

[OCS PCAP LOGS.zip](https://github.com/magma/magma/files/7453356/OCS.PCAP.LOGS.zip)
[AGW PCAP LOGS.zip](https://github.com/magma/magma/files/7453358/AGW.PCAP.LOGS.zip)
[MME logs.zip](https://github.com/magma/magma/files/7453370/MME.logs.zip)

### PR DESCRIPTION
**Pull request by uri200**
Signed-off-by: Oriol Batalla <obatalla@fb.com>

## Summary
Host-IP-Address AVP on session proxy was always defaulted to 127.0.0.1. That was causing issues with CER reported here https://github.com/magma/magma/issues/8752 and https://github.com/magma/magma/issues/10001

This PR uses the field defined in server/local_address to set this AVP. If that field just consist on a port, it will then use the default value `127.0.0.1`

image

## Test Plan
TeraVM

pcap here 
[cer.pcap.zip](https://github.com/magma/magma/files/7915943/cer.pcap.zip)

image

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Review by themarwhal — APPROVED** [review]

File: feg/gateway/diameter/diameter_client.go [hunk 1]
```diff
@@ -86,17 +86,27 @@ func (c *Client) ServiceContextId() string {
...
-// Input: clientCfg containing relevant diameter settings
-func NewClient(clientCfg *DiameterClientConfig) *Client {
+// Input:
+// 		clientCfg containing relevant diameter settings.
+//		localAddress which represents the Host-IP-Address AVP. If empty 127.0.0.1 will be used.
+func NewClient(clientCfg *DiameterClientConfig, localAddress string) *Client {
 	originStateID := uint32(time.Now().Unix())
+
+	// Set Host-IP-Address AVP on CER
+	localAddress = strings.Split(localAddress, ":")[0]
```
Comment (emakeev) [inline feg/gateway/diameter/diameter_client.go]: this is not going to work for IPV6 addresses. I'd use net.SplitHostPort with proper error handling logic (case of addr without port)

File: feg/gateway/diameter/diameter_client.go [hunk 2]
```diff
@@ -86,17 +86,27 @@ func (c *Client) ServiceContextId() string {
 }
 
 // NewClient creates a new client based on the config passed.
-// Input: clientCfg containing relevant diameter settings
-func NewClient(clientCfg *DiameterClientConfig) *Client {
+// Input:
+// 		clientCfg containing relevant diameter settings.
+//		localAddress which represents the Host-IP-Address AVP. If empty 127.0.0.1 will be used.
+func NewClient(clientCfg *DiameterClientConfig, localAddress string) *Client {
```
Comment (emakeev) [inline feg/gateway/diameter/diameter_client.go]: Since diam SM takes a slice of host addresses, I'd use variadic arguments here:


    
      func NewClient(clientCfg *DiameterClientConfig, localAddresses ... string) *Client {
        if len(localAddresses) == 0 {
		localAddresses = []string{"127.0.0.1"}
		glog.Warningf("No local address defined. Diameter client will use %s as Host-IP-Address AVP on CER", localAddress)
	  }
	
	...

File: feg/gateway/diameter/diameter_client.go (hunk 1 above)
Comment (uri200) [reply feg/gateway/diameter/diameter_client.go]: oh I thought our diameter didn't support ipv6

will do the changes theen

File: feg/gateway/diameter/diameter_client.go [hunk 3]
```diff
@@ -504,3 +508,32 @@ func getVendorSpecificApplicationIDAVPs(clientCfg *DiameterClientConfig,
...
+// Returns 127.0.0.1 if no address is passed or if address is invalid
+// Those addresses will be used at Host-IP-Address AVP on CER
+// localAddresses must have IP:Port format
+func getHostIPAddresses(localAddresses []string) []datatype.Address {
+	var localAddressesIP []datatype.Address
+	for _, localAddress := range localAddresses {
+		host, _, err := net.SplitHostPort(localAddress)
+		if err != nil {
+			glog.Errorf("Skipping %s: Could not parse as a valid IP:port. Error: %s", localAddress, err)
+			continue
```
Comment (emakeev) [inline feg/gateway/diameter/diameter_client.go]: glog.Warningf("Could not parse '%s' as a valid IP:port. Error: %s", localAddress, err)
host = strings.TrimSpace(host)

Comment (uri200) [reply feg/gateway/diameter/diameter_client.go]: done.

**Review by emakeev — APPROVED** [review]
