### PR TITLE
fix(amf): QOS flow descriptors are not updated correctly as configured

### LINKED ISSUE #13604: [AMF] : Multiple QoS Flow descriptors attached to Subscriberdb not working as expected
- **Version:** 1.8.0-1660257461-1b734b83
- **Affected Component:** Access Gateway
- **Deployment Environment:** Bare-metal (AGW) - VM Based

While performing Test case with 1UE, 1PDU attaching 3 policies to UE, it is being observed that the QOS flow descriptions are not being updated in pcap as configured.

APN - AMBR Subscribed:

Profiles attached to 3 Policies:
 

Subscribed IMSI:

PCAP Values:

Attaching the logs and pcap for the same:
[https://app.zenhub.com/files/170803235/f386cfea-d5ae-44df-a0cc-f8646d09700d/download](https://app.zenhub.com/files/170803235/f386cfea-d5ae-44df-a0cc-f8646d09700d/download)
[https://app.zenhub.com/files/170803235/31a4dad9-97e4-4e94-9cff-74888345880d/download](https://app.zenhub.com/files/170803235/31a4dad9-97e4-4e94-9cff-74888345880d/download)
[https://app.zenhub.com/files/170803235/b689d0a5-3338-483a-8bc6-d14220f6fa0e/download](https://app.zenhub.com/files/170803235/b689d0a5-3338-483a-8bc6-d14220f6fa0e/download)

### PR DESCRIPTION
**Pull request by Akshayp77**
Signed-off-by: Akshayp77 <akshay.patidar@wavlabs.ai>

## Summary
Fix #13604

QOS flow descriptors are not updated correctly as configured due to type mismatch,
Add support to handle higher values of mfbr and gbr because qos flow descriptor element of type uint16_t is not able handle higher values.

## Test Plan
Tested with UT
Tested with Spirent

[logs.tgz](https://github.com/magma/magma/files/9721926/logs.tgz)

## Additional Information
Screenshot (57)
Screenshot (56)

UT_snapshot

### CODE REVIEW

File: lte/gateway/c/core/oai/tasks/nas5g/include/ies/M5GQosFlowParam.hpp [hunk 1]
```diff
@@ -33,7 +33,7 @@ class M5GQosFlowParam {
 #define M5G_QOS_FLOW_PARAM_BIT_RATE_UNITS_KBPS 1
   uint8_t length;
   uint8_t units;
-  uint16_t element;
```
Comment (ganeshg87) [inline lte/gateway/c/core/oai/tasks/nas5g/include/ies/M5GQosFlowParam.hpp:36]: 1. add Unittest case for issue and fix.
2. need to fix encode and decode functions according to data type 
3. add UT for encode and decode.

Comment (Akshayp77) [reply lte/gateway/c/core/oai/tasks/nas5g/include/ies/M5GQosFlowParam.hpp:36]: Used existing UT for validation.

File: lte/gateway/c/core/oai/tasks/nas5g/src/ies/M5GQosFlowParam.cpp [hunk 2]
```diff
@@ -251,4 +251,21 @@ int M5GQosFlowParam::DecodeM5GQosFlowParam(M5GQosFlowParam* param,
   return decoded;
 }
 
+// Convert mfbr and gfbr values in proper format
+void M5GQosFlowParam::mfbr_gbr_convert(
+    magma5g::M5GQosFlowParam* flow_des_paramList, uint64_t element) {
+  if (element / (1024 * 1024) > 65535) {
+    flow_des_paramList->element = (uint16_t)(element / (1024 * 1024 * 1024));
```
Comment (ajahl) [inline lte/gateway/c/core/oai/tasks/nas5g/src/ies/M5GQosFlowParam.cpp]: The type cast does not work for very large numbers if they are bigger than uint16 max.

Comment (Akshayp77) [reply lte/gateway/c/core/oai/tasks/nas5g/src/ies/M5GQosFlowParam.cpp]: Modified the required changes.

**Review by panyogesh — APPROVED** [review]
Minor comments on Macros..Rest all looks ok.

**Review by ganeshg87 — APPROVED** [review]
lgtm
