### PR TITLE
[NMS] Fix misc NMS issues

### LINKED ISSUE #4566: NMS: After associating policy with a subscriber, NMS screen goes blank
### Your Environment

- **Version:** staging
- **Affected Component:** NMS
- **Affected Subcomponent:** Policy rule association.
- **Deployment Environment:** staging

### Describe the Issue

**To Reproduce**
1. Define a policy
2. Go to 'Subscribers' page, select subscriber
2. Click on: config
3. Click on: 'Traffic Policy" edit 
4. Activate any policy with subscriber, the screen goes blank.

**Expected behavior**
NMS should show subscriber config page.

**Additional context**
After refresh page, it shows subscriber page with activated policy.

### PR DESCRIPTION
**Pull request by karthiksubraveti**
Signed-off-by: Karthik Subraveti <ksubraveti@fb.com>

## Summary

- Fix issue where the number of critical alerts shown was incorrect
- Fix issue where saving a policy caused the component to fail to rerender. The main issue was due to the new order in which hooks were rendered. When collapse prop is used for datagrid, we should set it to a default value instead of hiding it. useState hook is invoked when collapse component gets rendered. So this causes the order of hooks for the last hook to go from undefined-> useState causing the failure
- Fix the subscriber table to show ip address and APN information in the table. This is a useful feature asked by partners
- Fix the subscriber table to show "-" when last reported time is 0 instead of showing it as some random 1969 date. 
- Fix the equipment overview table and equipment detail table to show "-" when last reported time is 0 instead of showing it as some random 1969 date. 
- Fix the case where useEffect for PolicyProvider gets invoked multiple times due to lteContext object changing constantly. Fixed the dependency to be set to fegNetworkID instead. 
- Add predefined alerts for gateway_checkin, dip in connected UEs, disk usage 
## Test Plan

https://user-images.githubusercontent.com/8224854/105933497-5ad4dc80-6003-11eb-9066-6dcc5a0d4835.mov

Screen Shot 2021-01-27 at 12 17 08 PM

yarn test succeeds. 

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

File: nms/app/packages/magmalte/app/views/equipment/EquipmentGateway.js [hunk 1]
```diff
@@ -349,15 +322,15 @@ function GatewayStatusTable(props: WithAlert & {refresh: boolean}) {
         numEnodeBs = gateway.connected_enodeb_serials.length;
       }
 
-      let checkInTime = new Date(0);
+      let checkInTime = '-';
```
Comment (Scott8440) [inline nms/app/packages/magmalte/app/views/equipment/EquipmentGateway.js:325]: I'm assuming you're doing this so you can display checkin time as "-" if it doesn't exist (correct me if I'm wrong). I don't think you should change the type (above) just to allow that to happen this way. Instead, keep it as a `Date` and then when you go to display it check if the `checkinTime == Date(0)` or something and then display whatever you want there.

File: nms/app/packages/magmalte/app/views/subscriber/SubscriberAddDialog.js [hunk 2]
```diff
@@ -518,14 +519,17 @@ function AddSubscriberDetails(props: DialogProps) {
...
-        enqueueSnackbar('Subscriber(s) saved successfully', {
-          variant: 'success',
-        });
+        successCount++;
       } catch (e) {
         const errMsg = e.response?.data?.message ?? e.message ?? e;
         setError('error saving ' + subscriber.imsi + ' : ' + errMsg);
         return;
       }
+      if (successCount % 50 === 0 || successCount === subscribers.length) {
```
Comment (Scott8440) [inline nms/app/packages/magmalte/app/views/subscriber/SubscriberAddDialog.js]: Why are we checking if this is divisible by 50? If there's a reason for this pull it out and name it something meaningful so it isn't a magic number.

File: nms/app/packages/magmalte/app/views/subscriber/SubscriberAddDialog.js [hunk 3]
```diff
@@ -518,14 +519,17 @@ function AddSubscriberDetails(props: DialogProps) {
...
+        enqueueSnackbar(`${successCount} Subscriber(s) saved successfully`, {
```
Comment (Scott8440) [inline nms/app/packages/magmalte/app/views/subscriber/SubscriberAddDialog.js]: This is the nittiest nit I've ever made but I'm always mad when websites don't implement simple checks to write plural vs. singular correctly. When we get back to the office I'll give you a cookie if you make this say "subscriber" or "subscribers" based on the number.

File: nms/app/packages/magmalte/app/components/GatewayCommandFields.js [hunk 4]
```diff
@@ -466,24 +468,41 @@ export function TroubleshootingControl(props: ChildProps) {
...
+    tdAgentLogsContent,
+    setTdAgentLogsContent,
+  ] = useState<generic_command_response>({});
   const networkId = nullthrows(match.params.networkId);
-  const parameters = {
+  const controlProxyParams = {
     command: 'bash',
     params: {
-      shell_params: ["-c 'cat /etc/magma/control_proxy.yml'"],
+      shell_params: ["-c 'cat /var/opt/magma/configs/control_proxy.yml'"],
```
Comment (Scott8440) [inline nms/app/packages/magmalte/app/components/GatewayCommandFields.js]: I know this is probably the only way to do it, but do you think there's a way we can get this to work without having to know the exact filepath of this config file?

At the very least it would be nice to pull this (or just the directory path) out into a constant.

**Review by Scott8440 — APPROVED** [review]
Just a few nits. Also please address the Codacy comments (except for the function complexity one that seems a little vague and potentially unnecessary). If you can simplify that function easily then it would be nice though!

File: nms/app/packages/magmalte/alerts/lteAlerts.js [hunk 5]
```diff
@@ -22,15 +22,31 @@ export default function getLteAlerts(
...
     'Service Restart Alert': {
       alert: 'Service Restart Alert',
-      expr: `avg_over_time(service_restart_status{networkID=~"${networkID}"}[5m]) > 0`,
+      expr: `increase(service_restart_status{networkID=~"${networkID}"}[5m]) > 0`,
       labels: {severity: 'minor'},
       annotations: {description: 'Alerts upon service restarts'},
     },
     'Cpu Percent Alert': {
       alert: 'Cpu Percent Alert',
-      expr: `avg_over_time(cpu_percent{networkID=~"${networkID}"}[5m]) > 75`,
```
Comment (andreilee) [inline nms/app/packages/magmalte/alerts/lteAlerts.js:31]: How are we picking these percentages?

File: nms/app/packages/magmalte/alerts/lteAlerts.js [hunk 6]
```diff
@@ -66,5 +82,20 @@ export default function getLteAlerts(
...
+      labels: {severity: 'critical'},
+      annotations: {description: 'Alerts when we have gateway checkin failure'},
+    },
+    'Dip in Connected UEs': {
+      alert: 'Dip in Connected UEs',
+      expr: `(ue_connected{networkID=~"${networkID}"} - ue_connected{networkID=~"${networkID}"} offset 5m) / (ue_connected{networkID=~"${networkID}"}) < -0.5`,
+      labels: {severity: 'critical'},
+      annotations: {
+        description:
+          'Alerts when there is a sudden dip in number of connected UEs',
```
Comment (andreilee) [inline nms/app/packages/magmalte/alerts/lteAlerts.js]: Could this be updated to be specific about it being a 50% dip in UEs over 5 minutes?

File: nms/app/packages/magmalte/app/views/equipment/EquipmentGateway.js (hunk 1 above)
Comment (karthiksubraveti) [reply nms/app/packages/magmalte/app/views/equipment/EquipmentGateway.js:325]: checkinTime is an row attribute taken by the MaterialTable, it takes in an array of rows as a prop and displays them on the table. If I keep the attribute as Date, I end up with flow errors, so modified it this way.

File: nms/app/packages/magmalte/alerts/lteAlerts.js (hunk 5 above)
Comment (karthiksubraveti) [reply nms/app/packages/magmalte/alerts/lteAlerts.js:31]: Heuristically, cpu percent greater than 75% seems to be a good indicator that something might be going on.

File: nms/app/packages/magmalte/app/components/GatewayCommandFields.js (hunk 4 above)
Comment (karthiksubraveti) [reply nms/app/packages/magmalte/app/components/GatewayCommandFields.js]: Yeah. Makes sense. I will make it as a constant.

File: nms/app/packages/magmalte/app/views/subscriber/SubscriberAddDialog.js (hunk 2 above)
Comment (karthiksubraveti) [reply nms/app/packages/magmalte/app/views/subscriber/SubscriberAddDialog.js]: I'm really trying to do a crappy way of displaying a progress bar. I will see if I can use something else here. Thanks for the feedback.

Comment (karthiksubraveti) [reply nms/app/packages/magmalte/app/views/subscriber/SubscriberAddDialog.js]: Removed the snackbar and replaced it with a linear progress indicator giving current status of number of subscribers saved 

Screen Shot 2021-01-30 at 8 00 11 AM

**Comment by karthiksubraveti** [comment]
Fixes #4328

**Comment by karthiksubraveti** [comment]
Closes https://github.com/magma/magma/issues/4238
