### PR TITLE
[orc8r][certifier] Improved cert lifespan error logging and non-fatal

### LINKED ISSUE #7548: [Orc8r] Certifier pod crashing due to certificate expiry alert changes
Certifier pod has been crashing due to recent changes. Need to investigate further.
```
ksubraveti@ksubraveti-mbp ~ % kubectl -n orc8r logs orc8r-certifier-7997d7b6d6-frj2f --previous
I0614 12:00:01.470225       1 service_config.go:169] Successfully loaded 'cwf::service_registry' service configs from '/etc/magma/configs/cwf/service_registry.yml'
I0614 12:00:01.470476       1 service_config.go:169] Successfully loaded 'fbinternal::service_registry' service configs from '/etc/magma/configs/fbinternal/service_registry.yml'
I0614 12:00:01.470704       1 service_config.go:169] Successfully loaded 'feg::service_registry' service configs from '/etc/magma/configs/feg/service_registry.yml'
I0614 12:00:01.471496       1 service_config.go:169] Successfully loaded 'lte::service_registry' service configs from '/etc/magma/configs/lte/service_registry.yml'
I0614 12:00:01.472226       1 service_config.go:169] Successfully loaded 'orc8r::service_registry' service configs from '/etc/magma/configs/orc8r/service_registry.yml'
I0614 12:00:01.472530       1 service_config.go:169] Successfully loaded 'wifi::service_registry' service configs from '/etc/magma/configs/wifi/service_registry.yml'
I0614 12:00:01.472986       1 service_config.go:111] Successfully loaded structured 'orc8r::shared' service configs from '/etc/magma/configs/orc8r/shared.yml'
I0614 12:00:01.473203       1 service_config.go:169] Successfully loaded 'orc8r::certifier' service configs from '/etc/magma/configs/orc8r/certifier.yml'
I0614 12:00:01.536785       1 service_config.go:111] Successfully loaded structured 'orc8r::certifier' service configs from '/etc/magma/configs/orc8r/certifier.yml'
I0614 12:00:01.537094       1 service_config.go:169] Successfully loaded 'orc8r::metricsd' service configs from '/etc/magma/configs/orc8r/metricsd.yml'
I0614 12:00:01.537551       1 service_config.go:180] Successfully loaded Override configs for service orc8r:metricsd from '/var/opt/magma/configs/orc8r/metricsd.yml'
E0614 18:00:00.001488       1 lifespan.go:53] Could not get lifespan for cert rootCA.pem: open /var/opt/magma/certs/rootCA.pem: no such file or directory
E0614 18:00:00.001517       1 lifespan.go:53] Could not get lifespan for cert admin_operator.pem: open /var/opt/magma/certs/admin_operator.pem: no such file or directory
2021/06/14 18:00:00 failed to decode PEM block containing public key
```

### PR DESCRIPTION
**Pull request by andreilee**
Signed-off-by: Andrei Lee <andreilee@fb.com>

## Summary

Non-essential metrics when failed to publish should not cause a service to fail. Instead, alerts will fire for missing metrics. This change is made to `certifier` service

## Test Plan

Ran with a local development setup with verbose logging

```
certifier stderr | I0616 00:59:00.294997     104 lifespan.go:42] Calculating cert_expires_in_hours
certifier stderr | E0616 00:59:00.295039     104 lifespan.go:43] Calculating cert_expires_in_hours
certifier stderr | I0616 00:59:00.297375     104 lifespan.go:80] Calculated metric cert_expires_in_hours for rootCA.pem: 2562047.000000
certifier stderr | E0616 00:59:00.297414     104 lifespan.go:81] Calculated metric cert_expires_in_hours for rootCA.pem: 2562047.000000
certifier stderr | I0616 00:59:00.299357     104 lifespan.go:80] Calculated metric cert_expires_in_hours for admin_operator.pem: 1222.000000
certifier stderr | E0616 00:59:00.299392     104 lifespan.go:81] Calculated metric cert_expires_in_hours for admin_operator.pem: 1222.000000
certifier stderr | I0616 00:59:00.300046     104 lifespan.go:80] Calculated metric cert_expires_in_hours for controller.crt: 873599.000000
certifier stderr | E0616 00:59:00.300063     104 lifespan.go:81] Calculated metric cert_expires_in_hours for controller.crt: 873599.000000
certifier stderr | I0616 00:59:00.301935     104 lifespan.go:80] Calculated metric cert_expires_in_hours for certifier.pem: 2562047.000000
certifier stderr | E0616 00:59:00.301974     104 lifespan.go:81] Calculated metric cert_expires_in_hours for certifier.pem: 2562047.000000
certifier stderr | E0616 00:59:00.302533     104 lifespan.go:55] Could not get lifespan for cert fluentd.pem: open /var/opt/magma/certs/fluentd.pem: no such file or directory
certifier stderr | failed to read cert file /var/opt/magma/certs/fluentd.pem
```

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

File: orc8r/cloud/go/services/certifier/analytics/calculations/lifespan.go [hunk 1]
```diff
@@ -82,12 +83,14 @@ func calculateCertLifespanHours(certsDirectory string, certName string, metricCo
...
+		return nil, errors.Wrap(err, fmt.Sprintf("failed to read cert file %s", certPath))
 	}
 	if strings.HasSuffix(certPath, ".pem") || strings.HasSuffix(certPath, ".crt") {
 		block, _ := pem.Decode(dat)
-		if block == nil || block.Type != "PUBLIC KEY" {
-			log.Fatal("failed to decode PEM block containing public key")
+		if block == nil {
+			return nil, fmt.Errorf("failed to decode a PEM block containing public key for certificate %s", certPath)
+		} else if block.Type != "PUBLIC KEY" && block.Type != "CERTIFICATE" {
+			return nil, fmt.Errorf("certificate %s has a PEM block type that is not PUBLIC KEY or CERTIFICATE, and instead is %s", certPath, block.Type)
```
Comment (karthiksubraveti) [inline orc8r/cloud/go/services/certifier/analytics/calculations/lifespan.go:93]: @andreilee Can you help me understand this better. Why are we unable to decode these certs and determine the expiration period ?

Comment (andreilee) [reply orc8r/cloud/go/services/certifier/analytics/calculations/lifespan.go:93]: We're expecting these types - `PRIVATE KEY` or a CSR would indicate a misuse I think.

**Comment by andreilee** [comment]
@hcgatewood Could you review this?

**Review by karthiksubraveti — APPROVED** [review]
