### PR TITLE
[NMS] Refresh equipment and subscriber state

### LINKED ISSUE #3708: NMS UI not auto refreshing status of gateways
### Your Environment

- **Version:** v1.3
- **Affected Component:**  NMS
- **Affected Subcomponent:** page <tenant>/equipment/overview/gateway
- **Deployment Environment:** AWS (orc8r)

### Describe the Issue

The NMS page does not auto-refresh the status of Gateways. This causes "good/green" to switch to "bad/red" after ~5 min. If the user refreshes the browser page, the status refreshes and becomes correct again.  

**To Reproduce**
1. Go to <tenant>/equipment/overview/gateway in NMS
2. Note the checkin time / status for each gateway displayed
3. Let the page sit for 5min or more
4. See that status has changed to red/bad for any AGW that had been green and last checkin time is old
5. refresh the browser page, see that AGWs that were just "bad" are now "good" again. 

**Expected behavior**
The expected behavior is that page triggers browser pulls data periodically on its own to keep status accurate. 

I have tested with Chrome, Safari, and Firefox, so I don't think it is browser specific issue.

### PR DESCRIPTION
**Pull request by HannaFar**
## Summary
Refresh equipment and subscriber state every 30 seconds
Add autoRefresh checkbox.

Capture d’écran 2021-01-14 à 19 24 29

Capture d’écran 2021-01-14 à 19 26 54

Capture d’écran 2021-01-14 à 19 26 36

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

File: nms/app/packages/magmalte/app/state/lte/EquipmentState.js [hunk 1]
```diff
@@ -213,20 +235,59 @@ export async function SetEnodebState(props: EnodebStateProps) {
...
+    try {
+      const gateway = await MagmaV1API.getLteByNetworkIdGatewaysByGatewayId({
+        networkId: networkId,
+        gatewayId: id,
+      });
+      if (gateway) {
+        return {[id]: gateway};
+      }
+    } catch (e) {
+      enqueueSnackbar?.('failed fetching gateway informations', {
```
Comment (karthiksubraveti) [inline nms/app/packages/magmalte/app/state/lte/EquipmentState.js]: minor nit: gateway information

File: nms/app/packages/magmalte/app/state/lte/EquipmentState.js [hunk 2]
```diff
@@ -213,20 +235,59 @@ export async function SetEnodebState(props: EnodebStateProps) {
...
+  } else {
+    try {
+      const gateways = await MagmaV1API.getLteByNetworkIdGateways({
+        networkId: networkId,
+      });
+      if (gateways) {
+        return gateways;
+      }
+    } catch (e) {
+      enqueueSnackbar?.('failed fetching gateway informations', {
```
Comment (karthiksubraveti) [inline nms/app/packages/magmalte/app/state/lte/EquipmentState.js]: minor nit: same as above

File: nms/app/packages/magmalte/app/views/equipment/EquipmentEnodeb.js [hunk 3]
```diff
@@ -109,96 +116,140 @@ type EnodebRowType = {
...
+    new Date().toLocaleString(),
   );
 
+  // Auto refresh  every 30 seconds
+  const state = useRefreshingContext({
+    context: EnodebContext,
+    networkId: networkId,
+    type: 'enodeb',
+    interval: REFRESH_INTERVAL,
+    enqueueSnackbar: enqueueSnackbar,
```
Comment (karthiksubraveti) [inline nms/app/packages/magmalte/app/views/equipment/EquipmentEnodeb.js]: in case of an error, let's skip printing every 30 seconds. Retain the attribute in the prop, but you can remove it here.

File: nms/app/packages/magmalte/app/views/equipment/GatewayDetailStatus.js [hunk 4]
```diff
@@ -14,21 +14,39 @@
...
+  const gatewayId: string = nullthrows(match.params.gatewayId);
+  const enqueueSnackbar = useEnqueueSnackbar();
+  // Auto refresh gateways every 30 seconds
+  const state = useRefreshingContext({
+    context: GatewayContext,
+    networkId: networkId,
+    type: 'gateway',
+    interval: REFRESH_INTERVAL,
+    id: gatewayId,
+    enqueueSnackbar: enqueueSnackbar,
```
Comment (karthiksubraveti) [inline nms/app/packages/magmalte/app/views/equipment/GatewayDetailStatus.js]: in case of an error, let's skip printing every 30 seconds. Retain the attribute in the prop, but you can remove it here.

File: nms/app/packages/magmalte/app/views/subscriber/SubscriberDetail.js [hunk 5]
```diff
@@ -158,6 +163,37 @@ export default function SubscriberDetail() {
...
+  const subscriberId: string = nullthrows(match.params.subscriberId);
+  const networkId: string = nullthrows(match.params.networkId);
+  const enqueueSnackbar = useEnqueueSnackbar();
+
+  const ctx = useRefreshingContext({
+    context: SubscriberContext,
+    networkId: networkId,
+    type: 'subscriber',
+    interval: REFRESH_INTERVAL,
+    enqueueSnackbar: enqueueSnackbar,
```
Comment (karthiksubraveti) [inline nms/app/packages/magmalte/app/views/subscriber/SubscriberDetail.js]: in case of an error, let's skip printing every 30 seconds. Retain the attribute in the prop, but you can remove it here.

File: nms/app/packages/magmalte/app/components/context/RefreshContext.js [hunk 6]
```diff
@@ -0,0 +1,178 @@
...
+      networkId,
+      enqueueSnackbar: enqueueSnackbar,
+    });
+
+    return gateways;
+  } else {
+    const enodebs = await FetchEnodebs({
+      id: id,
+      networkId,
+      enqueueSnackbar: enqueueSnackbar,
```
Comment (karthiksubraveti) [inline nms/app/packages/magmalte/app/components/context/RefreshContext.js]: you can just use shorthand notation 
```
+ enqueueSnackbar 
- enqueueSnackbar : enqueueSnackbar
```

File: nms/app/packages/magmalte/app/components/context/RefreshContext.js [hunk 7]
```diff
@@ -0,0 +1,178 @@
...
+        sessionState: {[id]: sessions || {}},
+        state: {[id]: subscribers || {}},
+      };
+    }
+    return {sessionState: sessions, state: subscribers};
+  } else if (type === 'gateway') {
+    const gateways = await FetchGateways({
+      id: id,
+      networkId,
+      enqueueSnackbar: enqueueSnackbar,
```
Comment (karthiksubraveti) [inline nms/app/packages/magmalte/app/components/context/RefreshContext.js]: you can just use shorthand notation 
```
+ enqueueSnackbar 
- enqueueSnackbar : enqueueSnackbar
```

File: nms/app/packages/magmalte/app/views/equipment/EnodebDetailSummaryStatus.js [hunk 8]
```diff
@@ -36,17 +45,35 @@ export function EnodebSummary() {
...
+  const enqueueSnackbar = useEnqueueSnackbar();
+
+  // Auto refresh enodeb every 30 seconds
+  const state = useRefreshingContext({
+    context: EnodebContext,
+    networkId: networkId,
+    type: 'enodeb',
+    interval: REFRESH_INTERVAL,
+    id: enodebSerial,
+    enqueueSnackbar: enqueueSnackbar,
```
Comment (karthiksubraveti) [inline nms/app/packages/magmalte/app/views/equipment/EnodebDetailSummaryStatus.js]: you can just use shorthand notation 
```
+ enqueueSnackbar 
- enqueueSnackbar : enqueueSnackbar
```

File: nms/app/packages/magmalte/app/views/subscriber/__tests__/SubscriberAddEditTest.js [hunk 9]
```diff
@@ -277,72 +284,72 @@ describe('<AddSubscriberButton />', () => {
...
-    const [subscribers, setSubscribers] = useState(subscribersMock);
-    const policyCtx = {
-      state: policies,
-      qosProfiles: {},
-      ratingGroups: {},
-      setRatingGroups: async () => {},
-      setQosProfiles: async () => {},
-      setState: async () => {},
-    };
+  // const DetailWrapper = () => {
```
Comment (karthiksubraveti) [inline nms/app/packages/magmalte/app/views/subscriber/__tests__/SubscriberAddEditTest.js:287]: Can you add an issue to fix this test and add that issue as a comment here and assign it to yourself

File: nms/app/packages/magmalte/app/state/lte/SubscriberState.js [hunk 10]
```diff
@@ -24,14 +24,126 @@ import type {
...
+        variant: 'error',
+      });
+      return;
+    }
+  } else {
+    try {
+      const subscribers = await MagmaV1API.getLteByNetworkIdSubscribers({
+        networkId,
+      });
+      if (subscribers) {
```
Comment (karthiksubraveti) [inline nms/app/packages/magmalte/app/state/lte/SubscriberState.js]: May be I added it originally. It seems redundant, we can just return 
```
return await MagmaV1API.getLteByNetworkIdSubscribers({
        networkId,
      });
```

File: nms/app/packages/magmalte/app/state/lte/SubscriberState.js [hunk 11]
```diff
@@ -24,14 +24,126 @@ import type {
...
   setSubscriberMap: ({[string]: subscriber}) => void,
   setSessionState: ({[string]: subscriber_state}) => void,
   setSubscriberMetrics?: ({[string]: Metrics}) => void,
   enqueueSnackbar?: (msg: string, cfg: {}) => ?(string | number),
 };
+export async function FetchSubscribers(props: FetchProps) {
+  const {networkId, enqueueSnackbar, id} = props;
+  if (id !== null && id !== undefined) {
+    try {
+      const subscriber = await MagmaV1API.getLteByNetworkIdSubscribersBySubscriberId(
```
Comment (karthiksubraveti) [inline nms/app/packages/magmalte/app/state/lte/SubscriberState.js]: May be I added it originally. It seems redundant, we can just return 
```
return await MagmaV1API.getLteByNetworkIdSubscribers({
        networkId,
      });
```

File: nms/app/packages/magmalte/app/state/lte/SubscriberState.js [hunk 12]
```diff
@@ -24,14 +24,126 @@ import type {
...
+      return;
+    }
+  }
+}
+
+export async function FetchSubscriberState(props: FetchProps) {
+  const {networkId, enqueueSnackbar, id} = props;
+  if (id !== null && id !== undefined) {
+    try {
+      const session = await MagmaV1API.getLteByNetworkIdSubscriberStateBySubscriberId(
```
Comment (karthiksubraveti) [inline nms/app/packages/magmalte/app/state/lte/SubscriberState.js]: minor nit:
remove pattern of
```
const foo = await <>
if(foo) {
return foo
}
```
Let's just 
```return await foo()```

File: nms/app/packages/magmalte/app/components/context/RefreshContext.js [hunk 13]
```diff
@@ -0,0 +1,178 @@
...
+  useEffect(() => {
+    const intervalId = setInterval(
+      () => setAutoRefreshTime(new Date().toLocaleString()),
+      props.interval,
+    );
+    if (!props.refresh) {
+      return clearInterval(intervalId);
+    }
+    return () => {
+      if (props.id !== undefined && props.id !== null) {
```
Comment (karthiksubraveti) [inline nms/app/packages/magmalte/app/components/context/RefreshContext.js]: are we missing something here. there is nothing inside the conditional

File: nms/app/packages/magmalte/app/components/context/RefreshContext.js [hunk 14]
```diff
@@ -0,0 +1,178 @@
...
+      }
+      updateContext(props.id, state);
+      clearInterval(intervalId);
+    };
+    // eslint-disable-next-line
+  }, [props.interval, props.refresh, state]);
+
+  useEffect(() => {
+    fetchState({
```
Comment (karthiksubraveti) [inline nms/app/packages/magmalte/app/components/context/RefreshContext.js]: perhaps we can fetchState only when lastRefreshTime != autoRefreshTime and we can remove dependency of props.refresh from this useEffect

File: nms/app/packages/magmalte/app/components/context/RefreshContext.js [hunk 15]
```diff
@@ -0,0 +1,178 @@
...
+      id: id,
+      networkId,
+      enqueueSnackbar,
+    });
+    const sessions = await FetchSubscriberState({
+      id: id,
+      networkId,
+      enqueueSnackbar,
+    });
+    if (id?.length) {
```
Comment (karthiksubraveti) [inline nms/app/packages/magmalte/app/components/context/RefreshContext.js]: ```use !== null or !== undefined instead ``` this will be consistent with the id check in fetch method as well

**Review by karthiksubraveti — COMMENTED** [review]
Thanks for making these changes. Most LGTM. Left a few comments.

File: nms/app/packages/magmalte/app/views/subscriber/__tests__/SubscriberAddEditTest.js (hunk 9 above)
Comment (HannaFar) [reply nms/app/packages/magmalte/app/views/subscriber/__tests__/SubscriberAddEditTest.js:287]: https://github.com/magma/magma/issues/4405

**Review by karthiksubraveti — APPROVED** [review]
