### PR TITLE
fix(nms): Improve sync of NMS organizations and orc8r tenants

### LINKED ISSUE #11331: NMS organizations and orc8r tenants not kept in sync consistently
### Planned tasks
- [x] Create a proof of concept in the NMS backend. Wherever we get information from the NMS organizations table, we additionally query the orc8r API for tenants and take the network information from there / write the network information into that.
- [x] Test this implementation with a local NMS / Orc8r.
- [x] Consider the dev_setup script for NMS.
- [x] Analyze result of the POC; pros vs cons (and afterwards maybe change strategy)
- [x] Consider migration of existing NMS / Orc8r prod setups.
  - The mitigation approach makes more frequent syncs but does not change the data model, so no migration is necessary.
- [x] ~Remove the sync functionality if everything works.~
  - The current mitigation approach only improves the sync functionality, syncing is still necessary, so it won't be removed. 
- [x] Prepare internal review meeting.

### Your Environment

- **Version:** 1.7 (current master)
- **Affected Component:** Orchestrator, NMS
- **Deployment Environment:** local docker-compose (orc8r), Vagrant (AGW)

### Describe the Issue

Orc8r's postgres table "tenants" and NMS' postgres "Organizations" table both describe a list of tenants in Magma. They are kept in sync but only if the 'Metrics' tab in NMS GUI is opened. I think this is handled by `syncTenants` in `grafana/handlers.js` and seems to be called by a Grafana synchronization routine.

**To Reproduce**
1. Start an orc8r and NMS locally as described in: https://magma.github.io/magma/docs/next/basics/quick_start_guide
As a last step of the setup, users and corresponding organizations should be created via the script `dev_setup.sh`.
2. Confirm that these organizations are created in the NMS postgres DB (log into docker container, connect via `psql -U nms`).
3. Confirm that they don't exist as tenants via orc8r swagger `GET /tenants`
4. Open the metrics dashboard of the network in NMS.
5. Use orc8r swagger `GET /tenants` again and confirm that the organizations now exist as tenants with IDs starting at 1. (Any previous tenants with these IDs would be overwritten.)

**Expected behavior**
The tables should be kept in sync independent of whether a user opens a Grafana dashboard.

**Additional context**
See discussion in Magma slack:
https://magmacore.slack.com/archives/C0191LLL03S/p1643297471171500

### PR DESCRIPTION
**Pull request by sebathomas**
## Summary

- When an NMS endpoint is called that modifies organizations, sync all organization changes to orc8r tenants.
- Add documentation that orc8r tenant API should not be used to modify tenants
tenantswagger

- Fix wrong description in NMS organization edit dialog
editorg

## Test Plan

- Adapted unit tests to mock new API calls and added assertions and a new test case.
- Manually tested:
  - POST organization in NMS with and without existing tenant in orc8r
  - PUT organization in NMS with and without existing tenant in orc8r
  - DELETE organization in NMS with and without existing tenant in orc8r

## Additional Information

We originally tried to remove the duplicate information and move the org / tenant config fully to orc8r, and thus avoid synchronization, see #13748. However, this turns out to be infeasible because the organization name is used as a foreign key in NMS, but the orc8r side does not support queries by name (the name is only stored inside a json blob).

A solution avoiding synchronization would require a complete rewrite of the data model on both sides.

- [ ] This change is backwards-breaking

### CODE REVIEW

File: nms/app/views/organizations/OrganizationInfoDialog.tsx [hunk 1]
```diff
@@ -83,7 +83,7 @@ export default function (props: DialogProps) {
         {!shouldEnableAllNetworks && (
           <AltFormField
             label={'Accessible Networks'}
-            subLabel={'The networks that the organization have access to'}>
+            subLabel={'The networks that the organization has access to'}>
```
Comment (Neudrino) [inline nms/app/views/organizations/OrganizationInfoDialog.tsx:86]: This should be `have` as it refers to "The networks".

File: nms/server/host/__tests__/organization-test.ts [hunk 2]
```diff
@@ -90,9 +161,15 @@ describe('Organization routes', () => {
...
+    expect(OrchestratorAPI.tenants.tenantsTenantIdDelete).toBeCalledWith({
+      tenantId: organization.id,
+    });
   });
 
-  it('deleting an unknown organization is a noop', async () => {
+  it('deleting an unknown organization forwards the deletion to orc8r', async () => {
     await request(app).delete(`/organization/async/4711`).expect(200);
+    expect(OrchestratorAPI.tenants.tenantsTenantIdDelete).toBeCalledWith({
+      tenantId: 4711,
```
Comment (Neudrino) [inline nms/server/host/__tests__/organization-test.ts:172]: Someone seems to be a fan of "Kölnisch Wasser". :rofl:

File: nms/server/host/routes.ts [hunk 3]
```diff
@@ -168,7 +171,7 @@ router.post(
         ),
       });
       if (organization) {
-        return res.status(404).send({error: 'Organization already exists'});
+        return res.status(409).send({error: 'Organization already exists'});
```
Comment (Neudrino) [inline nms/server/host/routes.ts]: _Optional:_ As rephrasing was done above already, could we have `Organization exists already` here please.

File: orc8r/cloud/go/services/tenants/obsidian/models/swagger.v1.yml [hunk 4]
```diff
@@ -83,7 +83,7 @@ paths:
         default:
           $ref: './orc8r-swagger-common.yml#/responses/UnexpectedError'
     delete:
-      summary: Delete tenant
+      summary: Delete tenant. This should not be called manually, tenants and organizations are updated in NMS and synced to orc8r.
```
Comment (Neudrino) [inline orc8r/cloud/go/services/tenants/obsidian/models/swagger.v1.yml]: If there is an `a` in the "create", there should be one here, too.

File: nms/server/host/routes.ts [hunk 5]
```diff
@@ -282,8 +287,59 @@ router.delete(
...
+  let orc8rTenant;
+  try {
+    orc8rTenant = (
+      await OrchestratorAPI.tenants.tenantsTenantIdGet({
+        tenantId: organization.id,
+      })
+    ).data;
+  } catch (error) {
+    // Ignore "not found" since there is no guarantee NMS and Orc8r are in sync
+    if (!axios.isAxiosError(error) || error?.response?.status !== 404) {
```
Comment (Neudrino) [inline nms/server/host/routes.ts]: Imho the equivalent expression containing only one negation, always feels much simpler to comprehend to me: I.e.
$$\neg ( A \land B) \iff \neg A \lor \neg B$$

File: nms/server/host/routes.ts [hunk 6]
```diff
@@ -282,8 +287,59 @@ router.delete(
...
+async function deleteOrc8rTenant(organizationId: number) {
+  try {
+    await OrchestratorAPI.tenants.tenantsTenantIdDelete({
+      tenantId: organizationId,
+    });
+  } catch (error) {
+    // Ignore "not found" since there is no guarantee NMS and Orc8r are in sync
+    if (!axios.isAxiosError(error) || error?.response?.status !== 404) {
+      throw error;
+    }
```
Comment (Neudrino) [inline nms/server/host/routes.ts]: Do two occurrences already justify abstraction in a method here?

**Comment by sebathomas** [comment]
Thanks for the review. Pushed again, I think I got all your comments.

**Review by Neudrino — APPROVED** [review]

**Review by alexzurbonsen — APPROVED** [review]

**Review by maxhbr — COMMENTED** [review]
LGTM

**Review by maxhbr — APPROVED** [review]
