### PR TITLE
[SessionD] Clean up SessionD unit tests by looking at ASAN outputs

### LINKED ISSUE #5439: Ubuntu20: SessionD: unit tests are failing.
### Your Environment

- **Version:** master
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** sessionD
- **Deployment Environment:** Vagrant (AGW) magma_focal.

### Describe the Issue

`make test_session_manager` fails due to multiple test failure.

**To Reproduce**
1. Stop magma VM
2. bring up magma_focal VM
3. `cd magma/lte/gateway/`
4. `make test_session_manager`

Log:
```
vagrant@magma-dev-focal:~/magma/lte/gateway$ make test_session_manager
OAI_FLAGS -DS6A_OVER_GRPC=True -DEMBEDDED_SGW=True -DENABLE_OPENFLOW=True -DSPGW_ENABLE_SESSIOND_AND_MOBILITYD=True
sudo service magma@* stop
find /home/vagrant/magma/orc8r/gateway/c/common \( -iname "*.c" -o -iname "*.cpp" -o -iname "*.h" \) -exec \
clang-format --style=file -i {} \;
mkdir -p  /home/vagrant/build/c//magma_common
cd  /home/vagrant/build/c//magma_common &&  cmake  /home/vagrant/magma/orc8r/gateway/c/common -DCMAKE_BUILD_TYPE=Debug  -DCMAKE_C_FLAGS="-Wall" -GNinja
Proto_srcs are /home/vagrant/build/c/magma_common/service303/orc8r/protos/common.pb.cc;/home/vagrant/build/c/magma_common/service303/orc8r/protos/metricsd.pb.cc;/home/vagrant/build/c/magma_common/service303/orc8r/protos/service303.pb.cc;/home/vagrant/build/c/magma_common/service303/orc8r/protos/service303.grpc.pb.cc;/home/vagrant/build/c/magma_common/service303/orc8r/protos/metrics.pb.cc
Async Proto_srcs are /home/vagrant/build/c/magma_common/async_grpc/lte/protos/session_manager.pb.cc;/home/vagrant/build/c/magma_common/async_grpc/lte/protos/abort_session.pb.cc;/home/vagrant/build/c/magma_common/async_grpc/lte/protos/policydb.pb.cc;/home/vagrant/build/c/magma_common/async_grpc/lte/protos/subscriberdb.pb.cc;/home/vagrant/build/c/magma_common/async_grpc/lte/protos/mobilityd.pb.cc;/home/vagrant/build/c/magma_common/async_grpc/lte/protos/session_manager.grpc.pb.cc;/home/vagrant/build/c/magma_common/async_grpc/lte/protos/abort_session.grpc.pb.cc;/home/vagrant/build/c/magma_common/async_grpc/lte/protos/mobilityd.grpc.pb.cc;/home/vagrant/build/c/magma_common/async_grpc/orc8r/protos/common.pb.cc;/home/vagrant/build/c/magma_common/async_grpc/orc8r/protos/redis.pb.cc;/home/vagrant/build/c/magma_common/async_grpc/orc8r/protos/eventd.pb.cc;/home/vagrant/build/c/magma_common/async_grpc/orc8r/protos/eventd.grpc.pb.cc
Async Proto_srcs are /home/vagrant/build/c/magma_common/datastore/lte/protos/session_manager.pb.cc;/home/vagrant/build/c/magma_common/datastore/lte/protos/policydb.pb.cc;/home/vagrant/build/c/magma_common/datastore/lte/protos/mobilityd.pb.cc;/home/vagrant/build/c/magma_common/datastore/lte/protos/subscriberdb.pb.cc;/home/vagrant/build/c/magma_common/datastore/lte/protos/session_manager.grpc.pb.cc;/home/vagrant/build/c/magma_common/datastore/orc8r/protos/common.pb.cc;/home/vagrant/build/c/magma_common/datastore/orc8r/protos/redis.pb.cc
Proto_srcs are /home/vagrant/build/c/magma_common/policydb/orc8r/protos/common.pb.cc;/home/vagrant/build/c/magma_common/policydb/lte/protos/policydb.pb.cc
-- Configuring done
-- Generating done
-- Build files have been written to: /home/vagrant/build/c/magma_common
ninja -C  /home/vagrant/build/c//magma_common
ninja: Entering directory `/home/vagrant/build/c//magma_common'
ninja: no work to do.
mkdir -p   /home/vagrant/build/c//session_manager
cd   /home/vagrant/build/c//session_manager &&  cmake   /home/vagrant/magma/lte/gateway/c/session_manager -DCMAKE_BUILD_TYPE=Debug    -DBUILD_TESTS=1 -GNinja
Found CLANG_FORMAT: /usr/bin/clang-format
Build type is Debug
Proto_srcs are /home/vagrant/build/c/session_manager/orc8r/protos/common.pb.cc;/home/vagrant/build/c/session_manager/orc8r/protos/directoryd.pb.cc;/home/vagrant/build/c/session_manager/lte/protos/session_manager.pb.cc;/home/vagrant/build/c/session_manager/lte/protos/subscriberdb.pb.cc;/home/vagrant/build/c/session_manager/lte/protos/policydb.pb.cc;/home/vagrant/build/c/session_manager/lte/protos/pipelined.pb.cc;/home/vagrant/build/c/session_manager/lte/protos/spgw_service.pb.cc;/home/vagrant/build/c/session_manager/lte/protos/mconfig/mconfigs.pb.cc;/home/vagrant/build/c/session_manager/feg/gateway/services/aaa/protos/accounting.pb.cc;/home/vagrant/build/c/session_manager/feg/gateway/services/aaa/protos/context.pb.cc;/home/vagrant/build/c/session_manager/orc8r/protos/directoryd.grpc.pb.cc;/home/vagrant/build/c/session_manager/lte/protos/session_manager.grpc.pb.cc;/home/vagrant/build/c/session_manager/lte/protos/pipelined.grpc.pb.cc;/home/vagrant/build/c/session_manager/lte/protos/spgw_service.grpc.pb.cc;/home/vagrant/build/c/session_manager/feg/gateway/services/aaa/protos/accounting.grpc.pb.cc
-- Configuring done
-- Generating done
-- Build files have been written to: /home/vagrant/build/c/session_manager
ninja -C   /home/vagrant/build/c//session_manager
ninja: Entering directory `/home/vagrant/build/c//session_manager'
[22/22] Linking CXX executable test/cloud_reporter_test
cd  /home/vagrant/build/c//session_manager && ctest --output-on-failure
Test project /home/vagrant/build/c/session_manager
      Start  1: test_session_credit
 1/14 Test  #1: test_session_credit ..................   Passed    1.03 sec
      Start  2: test_local_enforcer
 2/14 Test  #2: test_local_enforcer ..................   Passed    2.38 sec
      Start  3: test_cloud_reporter
 3/14 Test  #3: test_cloud_reporter ..................***Failed    0.04 sec
Running main() from gmock_main.cc
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from SessionReporterTest
[ RUN      ] SessionReporterTest.test_single_call
[/home/vagrant/magma/orc8r/gateway/c/common/config/ServiceConfigLoader.cpp:33] Override file not found for service control_proxy
[/home/vagrant/magma/orc8r/gateway/c/common/config/ServiceConfigLoader.cpp:33] Override file not found for service service_registry
Started reporter thread
Started cloud thread
/home/vagrant/magma/lte/gateway/c/session_manager/test/test_cloud_reporter.cpp:74: Failure
Value of: false
  Actual: false
Expected: true
/home/vagrant/magma/lte/gateway/c/session_manager/test/test_cloud_reporter.cpp:94: Failure
Actual function call count doesn't match EXPECT_CALL(mock_callback, create_callback(_, CheckCreateResponseRuleSize(1)))...
         Expected: to be called once
           Actual: never called - unsatisfied and active
Stopped cloud thread
/home/vagrant/magma/lte/gateway/c/session_manager/test/test_cloud_reporter.cpp:99: Failure
Actual function call count doesn't match EXPECT_CALL(*mock_cloud, CreateSession(_, _, _))...
         Expected: to be called once
           Actual: never called - unsatisfied and active
[  FAILED  ] SessionReporterTest.test_single_call (18 ms)
[ RUN      ] SessionReporterTest.test_multi_call
Started reporter thread
Started cloud thread
Stopped cloud thread
Stopped reporter thread
[       OK ] SessionReporterTest.test_multi_call (14 ms)
[----------] 2 tests from SessionReporterTest (32 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test suite ran. (32 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] SessionReporterTest.test_single_call

 1 FAILED TEST

      Start  4: test_session_manager_handler
 4/14 Test  #4: test_session_manager_handler .........   Passed    0.03 sec
      Start  5: test_sessiond_integ
```

### LINKED ISSUE #5481: [SessionD] Sanitize SessionD unit tests with ASAN
### Your Environment

- **Version:**
- **Affected Component:** Orchestrator, Access Gateway, or NMS
- **Affected Subcomponent:** Orchestrator pod/service or AGW service
- **Deployment Environment:** e.g. AWS (orc8r), local docker-compose (orc8r), bare-metal (AGW), Vagrant (AGW)

### Describe the Issue
SessionD unit tests cannot complete with ASAN enabled due to crashes. Clean this up as this may help with our resource issue.

Gist of ASAN outputs...
test_metering_reporter: https://gist.github.com/themarwhal/4531c2306faf4b451e437b0b90827e6f
test_proxy_responder_handler: resolved
test_store_client: resolved
test_session_store: https://gist.github.com/themarwhal/615ae3a149205858537cffd1c298d026
test_sessiond_integ: https://gist.github.com/themarwhal/9a7c49f11a70624d8b8e7a0d25c886fd

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here (e.g. logs).

### PR DESCRIPTION
**Pull request by themarwhal**
Signed-off-by: Marie Bremner <marwhal@fb.com>

## Summary
Currently, we disable ASAN for SessionD unit tests as the tests cannot pass with ASAN enabled. This PR solves *most* of the issues. 
1. Cleaning up all unit tests to not use `new` to allocate memory. If we need a pointer, we should use `shared_ptr` or `unique_ptr`. And if we must use `new`, use the `TearDown` function to clean up all resources.
2. There was a stack corruption issues when a future object was passed into `set_timeout` as a stack allocated pointer, not a dynamically created object. I suspect this was causing some exceptions in the tests, but I'm not 100% sure.  
```
call_promise used to be stack allocated here, which could cause some issues
void set_timeout(uint32_t ms, std::promise<void>* call_promise) {
	std::thread([&]() {
	std::this_thread::sleep_for(std::chrono::milliseconds(ms));
	EXPECT_TRUE(false);
	call_promise->set_value();
	}).detach();
}
```
3. For GRPC receivers, make sure we clean up the queue when shutting down the server. This probably does not affect production code, but is good for cleanliness.
 
I still have one GRPC related ASAN outputs, but I'm going to leave it for now. https://gist.github.com/themarwhal/10dcc8a0d319d0d3301988fb21e2e655

## Test Plan
make precommit_sm

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

File: lte/gateway/c/session_manager/test/test_cloud_reporter.cpp [hunk 1]
```diff
@@ -65,14 +67,14 @@ class SessionReporterTest : public ::testing::Test {
   virtual void TearDown() {
     magma_service->Stop();
     reporter->stop();
+    delete evb;
   }
 
   // Timeout to not block test
   void set_timeout(uint32_t ms) {
-    std::thread([&]() {
+    std::thread([ms]() {
```
Comment (uri200) [inline lte/gateway/c/session_manager/test/test_cloud_reporter.cpp:75]: per your comment, do you mean that capturing all elements by reference `[&]` may have been caused issues to the promise?

**Review by uri200 — APPROVED** [review]

File: lte/gateway/c/session_manager/test/test_cloud_reporter.cpp (hunk 1 above)
Comment (themarwhal) [reply lte/gateway/c/session_manager/test/test_cloud_reporter.cpp:75]: @uri200  My hunch was that it is a bit suspicious to pass a stack defined parameter by reference into a thread. not 100% sure if it was causing any issues though. 
There's another `set_timeout` in `test_sessiond_integ` that has a similar issue. We define a promise/future on the stack in the main test function, and then pass a pointer to that to a separate thread.

Comment (themarwhal) [reply lte/gateway/c/session_manager/test/test_cloud_reporter.cpp:75]: Something about this PR makes the tests less flaky, so I think I'm doing something right :D
