### PR TITLE
[feg][CI] Check FEG crash looping

### LINKED ISSUE #6284: [CI][PrecommitCheck] Add a sanity check to bring up all FeG, CWAG containers to see everything builds and doesn't crash
-> We do not check at the precommit stage that docker containers are healthy for FeG
-> We do not check at the precommit stage that docker containers are healthy for CWAG

We can do a simple check like this: https://sourcegraph.com/github.com/magma/magma/-/blob/cwf/gateway/fabfile.py#L344:5

### LINKED ISSUE #6287: [feg][Makefile][CI] Add a way to check if services are crashlooping
Right now we don't have any check on CI to see if FEG services are able to start.

We need to create an endpoint on feg Makefile to check that the services are up and running.

We need to add that check on CI

### PR DESCRIPTION
**Pull request by uri200**
Signed-off-by: Oriol Batalla <obatalla@fb.com>

## Summary

This PR adds some endpoints to Makefile to deal with start, stop and health check of the processes

Note if you are running this on MAC you will have to comment the `LOG_DRIVER=journald` form the .env file at `~/magma/feg/gateway/docker`

Health Check will run docker-compose up -d and check for few seconds if any of the containers restarts

This PR also adds this check on CI in every PR on as part of the `feg-build` task

## Test Plan
`ci/circleci: feg-build`  will pass once this https://github.com/magma/magma/issues/6282 is fixed

Output of running the command manually
```
╰─ make docker_health_check
cd /Users/obatalla/magma/feg/gateway/docker; docker-compose up -d
WARNING: The LOG_DRIVER variable is not set. Defaulting to a blank string.
WARNING: The USE_GY_FOR_AUTH_ONLY variable is not set. Defaulting to a blank string.
WARNING: The GY_SUPPORTED_VENDOR_IDS variable is not set. Defaulting to a blank string.
WARNING: The GY_SERVICE_CONTEXT_ID variable is not set. Defaulting to a blank string.
aaa_server is up-to-date
eventd is up-to-date
s8_proxy is up-to-date
td-agent-bit is up-to-date
feg_hello is up-to-date
eap_aka is up-to-date
hss is up-to-date
Recreating redis ...
eap_sim is up-to-date
s6a_proxy is up-to-date
session_proxy is up-to-date
test is up-to-date
health is up-to-date
csfb is up-to-date
swx_proxy is up-to-date
radiusd is up-to-date
control_proxy is up-to-date
Recreating redis ... done
cd /Users/obatalla/magma/feg/gateway/docker/tools/; ./health_check_docker_ps.sh /Users/obatalla/magma/feg/gateway/docker
aaa_server      envdir /var/opt/magma/envd ...   Up
control_proxy   /bin/bash -c /usr/local/bi ...   Up
csfb            envdir /var/opt/magma/envd ...   Up
eap_aka         envdir /var/opt/magma/envd ...   Up
eap_sim         envdir /var/opt/magma/envd ...   Up
eventd          python3.8 -m magma.eventd.main   Up
feg_hello       envdir /var/opt/magma/envd ...   Up
health          envdir /var/opt/magma/envd ...   Up
hss             envdir /var/opt/magma/envd ...   Up
radiusd         envdir /var/opt/magma/envd ...   Up
redis           /bin/bash -c /usr/local/bi ...   Up
s6a_proxy       envdir /var/opt/magma/envd ...   Up
s8_proxy        envdir /var/opt/magma/envd ...   Up
session_proxy   envdir /var/opt/magma/envd ...   Up
swx_proxy       envdir /var/opt/magma/envd ...   Up
td-agent-bit    /bin/bash -c /usr/local/bi ...   Up
test            /bin/bash -c mkdir -p ../. ...   Up

--- Checking docker services ---

--- ERROR: Docker services are restarting ---

    Name                   Command                 State      Ports
-------------------------------------------------------------------
aaa_server      envdir /var/opt/magma/envd ...   Up
control_proxy   /bin/bash -c /usr/local/bi ...   Up
csfb            envdir /var/opt/magma/envd ...   Up
eap_aka         envdir /var/opt/magma/envd ...   Up
eap_sim         envdir /var/opt/magma/envd ...   Up
eventd          python3.8 -m magma.eventd.main   Up
feg_hello       envdir /var/opt/magma/envd ...   Up
health          envdir /var/opt/magma/envd ...   Up
hss             envdir /var/opt/magma/envd ...   Up
magmad          python3.8 -m magma.magmad.main   Restarting
radiusd         envdir /var/opt/magma/envd ...   Up
redis           /bin/bash -c /usr/local/bi ...   Up
s6a_proxy       envdir /var/opt/magma/envd ...   Up
s8_proxy        envdir /var/opt/magma/envd ...   Up
session_proxy   envdir /var/opt/magma/envd ...   Up
swx_proxy       envdir /var/opt/magma/envd ...   Up
td-agent-bit    /bin/bash -c /usr/local/bi ...   Up
test            /bin/bash -c mkdir -p ../. ...   Up
make: *** [docker_health_check] Error 1

```
## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Review by themarwhal — APPROVED** [review]
:) happy about this!!

**Comment by uri200** [comment]
this can't be land it for now because Circle CI image has two missing files that are needed to run docker-compose up without restarts


See two missing files (in fact they are directories instead of files)
```
circleci@default-774bcf47-9172-4b43-bce7-181083daaf73:~/project/feg/gateway/docker$ ls -la ../../../.cache/feg
total 12
drwxr-xr-x 3 root root 4096 Apr 23 00:57 .
drwxr-xr-x 4 root root 4096 Apr 23 00:57 ..
drwxr-xr-x 2 root root 4096 Apr 23 01:16 snowflake
 (edited) 

Oriol  6:40 PM
same with root ca
ircleci@default-774bcf47-9172-4b43-bce7-181083daaf73:~/project/feg/gateway/docker$ ls -la ../../../.cache/test_certs
total 12
drwxr-xr-x 3 root root 4096 Apr 23 00:57 .
drwxr-xr-x 4 root root 4096 Apr 23 00:57 ..
drwxr-xr-x 2 root root 4096 Apr 23 00:57 rootCA.pem

```
@tmdzk

**Comment by themarwhal** [comment]
Hey @uri200 you'll have to manually create those on the CircleCI node. 
Since the env file points to these directories
```
ROOTCA_PATH=../../../.cache/test_certs/rootCA.pem
CONTROL_PROXY_PATH=../configs/control_proxy.yml
SNOWFLAKE_PATH=../../../.cache/feg/snowflake
```
I think if you just run 
```
touch ../../../.cache/test_certs/rootCA.pem
touch ../../../.cache/feg/snowflake
```
before running `docker-compose up` that should work.

**Comment by uri200** [comment]
Hey @themarwhal  Yep I tested all of that with ssh on CI and nothing works. We need proper files or services crash.

The only way to make it work is to manually add it to circleci.yml command. Snowflake is fine since it is a short number. But adding by command the rootCA.pem looks awful 

I will see with @tmdzk if we can recreate the image fixing those two files. Otherwise I will manually put it there for now

**Comment by uri200** [comment]
adding an issue to add `.cache` folder to the image https://github.com/magma/magma/issues/6369

**Comment by themarwhal** [comment]
@uri200 yeah you are right. blank snowflake file is ok, but for control_proxy it seems we need a valid pem. (Ran into the same issue for bringing up CWAG)

File: feg/gateway/docker/tools/docker_ps_healthcheck.sh [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+  echo "--- ERROR: Docker services are not running ---"
+  exit 2
+fi
+
+echo "--- Waiting 10 seconds... --- "
+sleep 10
+printf "\n--- Checking docker services --- \n"
+
+for _ in {1..10}
+do
```
Comment (emakeev) [inline feg/gateway/docker/tools/docker_ps_healthcheck.sh:18]: maybe:

`sleep $[ ( $RANDOM % 3 ) ]s`

here instead sleep 10 above

File: .circleci/config.yml [hunk 2]
```diff
@@ -714,9 +714,27 @@ jobs:
...
+          command: |
+            # TODO add rootCA.pem and snowflake files in the ubuntu-1604:201903-01 image
+            # create directories
+            cd ${MAGMA_ROOT} && mkdir -p .cache/test_certs/ && mkdir -p .cache/feg/
+            # create test certs
+            cd ${MAGMA_ROOT}/.cache/test_certs/
+            openssl genrsa -out rootCA.key 2048
+            openssl req -x509 -new -nodes -key rootCA.key -sha256 -days 365000 -out rootCA.pem -subj "/C=US/CN=rootca.magma.test"
+            # create snowflake
+            cd ${MAGMA_ROOT}/.cache/feg/ && touch snowflake
```
Comment (uri200) [inline .circleci/config.yml:727]: in this task we just 
- Create the missing directories 
```
.cache/test_certs/ 
.cache/feg/
```
- Create a custom rootCA with openssl
- Create an empty snowflake file

File: feg/gateway/docker/tools/docker_ps_healthcheck.sh [hunk 3]
```diff
@@ -0,0 +1,28 @@
+#!/bin/bash
+
+# add the path to the command if docker-compose.yml is not in the same folder
+cd "$1" || exit 1
+
+# check if docker services are really running or not
+sleep 3
```
Comment (emakeev) [inline feg/gateway/docker/tools/docker_ps_healthcheck.sh:7]:
```
for _ in {1..3}
  do
    if  (docker-compose ps | grep "...   Up"); then
      break
    fi
    sleep 1
 done
```

**Review by emakeev — APPROVED** [review]
lgtm, some suggestions inline on speeding up the healthcheck script

**Comment by emakeev** [comment]
BTW, in your scripts, you can check that they are running on Mac by using something like this: 'echo "$(uname -s)" | grep Darwin'
Then, set LOG_DRIVER accordingly.

File: feg/gateway/docker/tools/docker_ps_healthcheck.sh (hunk 3 above)
Comment (uri200) [reply feg/gateway/docker/tools/docker_ps_healthcheck.sh:7]: makes sense

File: feg/gateway/docker/tools/docker_ps_healthcheck.sh (hunk 1 above)
Comment (uri200) [reply feg/gateway/docker/tools/docker_ps_healthcheck.sh:18]: note `docker-compose ps` has around 1 second delay. So executing `docker-compose ps` it is already giving us some randomness. 

The 10 second delay at line 14 is just to wait for feg to settle. If after 10 seconds of having done `docker-compose up -d` we see restarts, there is something wrong for sure.

File: .circleci/config.yml [hunk 4]
```diff
@@ -714,9 +714,27 @@ jobs:
       - build/determinator:
           <<: *federated_build_verify
       - run:
+          name: generate test certs and snowflake
+          command: |
+            # TODO add rootCA.pem and snowflake files in the ubuntu-1604:201903-01 image
+            # create directories
+            cd ${MAGMA_ROOT} && mkdir -p .cache/test_certs/ && mkdir -p .cache/feg/
```
Comment (tmdzk) [inline .circleci/config.yml:721]: I would use  `mkdir ${MAGMA_ROOT}/.cache/test_certs/` && `mkdir ${MAGMA_ROOT}.cache/feg/`and remove the cd.

**Review by tmdzk — APPROVED** [review]

File: .circleci/config.yml (hunk 4 above)
Comment (uri200) [reply .circleci/config.yml:721]: ohh I forgot I had  automerge. 

Will create a pr with the changes

**Comment by themarwhal** [comment]
@uri200 If you still want this in 1.5, do you mind raising a PR against the 1.5 branch? There are merge conflicts in the Makefile. Thanks :)

**Comment by themarwhal** [comment]
Removing the apply-1.5 tag since we will manually raise a PR.

**Comment by uri200** [comment]
Oh no no need to added to 1.5. I should have removed it.

Thanks
