### PR TITLE
test(cwg): Make radius test sequential

### LINKED ISSUE #14659: Track failing FeG radius unit tests
There are some flaky/failing FeG radius unit tests, which are skipped and therefore not run in the CI, having been excluded in https://github.com/magma/magma/pull/14655/. These tests should be investigated with the view to them no longer being skipped.

Currently skipped tests (where relevant, number of times failing when running `cd $MAGMA_ROOT/feg/radius/src && go clean -testcache && gotestsum ./...` locally):

Fixes merged:
- [x] TestPostODS https://github.com/magma/magma/pull/14698
- [x] TestBasicInsertGetRedis https://github.com/magma/magma/pull/14692
- [x] TestMultipleConcurrentInsertDeleteGetRedis https://github.com/magma/magma/pull/14692
- [x] TestCoaFixed https://github.com/magma/magma/pull/14701
- [x] TestCoaNas https://github.com/magma/magma/pull/14701
- [x] TestCoaNasNoResponse https://github.com/magma/magma/pull/14701
- [x] TestCoaNasFieldInvalid https://github.com/magma/magma/pull/14701
- [x] TestLBServeProxiesRequestToRadiusAndReturnsResponse https://github.com/magma/magma/pull/14701
- [x] TestLBServeFailsWithRadiusError https://github.com/magma/magma/pull/14701
- [x] TestProxy https://github.com/magma/magma/pull/14845
- [x] TestSendOdsCounters https://github.com/magma/magma/pull/14845
- [x] TestCoaDynamic https://github.com/magma/magma/pull/14880
- [x] TestAnalyticsModulesAuthenticate https://github.com/magma/magma/pull/14906
- [x] TestAnalyticsModulesAccountingStart https://github.com/magma/magma/pull/14906
- [x] TestAnalyticsModulesAccountingUpdate https://github.com/magma/magma/pull/14906
- [x] TestAnalyticsModulesAccountingStop https://github.com/magma/magma/pull/14906
- [x] TestFullRADIUSSessiontWithAnalyticsModules https://github.com/magma/magma/pull/14906
- [x] TestRequestWithModules https://github.com/magma/magma/pull/14906
- [x] TestModuleFailsToHandle https://github.com/magma/magma/pull/14906
- [x] TestFilterFailsToProcess https://github.com/magma/magma/pull/14906
- [x] TestDedup https://github.com/magma/magma/pull/14906

### PR DESCRIPTION
**Pull request by MoritzThomasHuebner**
In pairing with @wolfseb 
## Summary

This change ensures that radius src tests are run sequentially. `go test` can run tests in parallel if they are defined in different packages, which is effectively the case in `radius/src`. By adding the `-p 1` flag, we ensure that no tests run in parallel. This change fixes the flakiness we observed in `TestCoaDynamic`. 

## Test Plan

We ran the test manually with other tests in `radius/src` many times with and without the `-p 1` flag. The flakiness in `TestCoaDynamic` only occurs without the `-p 1` flag.

### CODE REVIEW

File: feg/radius/src/run.sh [hunk 1]
```diff
@@ -51,7 +51,8 @@ function pretty {
 }
 
 function test {
-    gotestsum ./...
+    go clean -testcache
```
Comment (nstng) [inline feg/radius/src/run.sh]: I assume in CI there are no caches to benefit from - but does this impact local execution times?

Comment (MoritzThomasHuebner) [reply feg/radius/src/run.sh]: I removed the line as caches will be ignored if there have been any changes. We used `go clean -testcache` previously to trigger flaky tests.

**Review by nstng — APPROVED** [review]

File: feg/radius/src/run.sh [hunk 2]
```diff
@@ -51,7 +51,7 @@ function pretty {
 }
 
 function test {
-    gotestsum ./...
+    gotestsum -- -p 1 ./...
```
Comment (voisey) [inline feg/radius/src/run.sh:55]: Maybe a comment would be helpful here? Something like "Running tests in parallel to avoid radius server cross-talk between tests"

Comment (MoritzThomasHuebner) [reply feg/radius/src/run.sh:55]: The comment would be about running sequentially, not in parallel. I will add something to that effect before merging.

Comment (voisey) [reply feg/radius/src/run.sh:55]: Oops, that's what I meant, sorry. Looks good, thanks!
