### PR TITLE
fix(amf): Convert MLOG to OAILOG for all core transaction logic for n…

### LINKED ISSUE #10650: [AMF]: Convert MLOG to OAILOG for all core transaction logic for nas5g files
### Describe the Issue

Currently all logging in nas5g makes use of MLOG framework to direct all the logs to syslog, instead we should use MLOG only for gRPC calls, event logging and for all core transaction logic should make use of OAILOG

### PR DESCRIPTION
**Pull request by Chandhu-Wavelabs**
Signed-off-by: chandhu-wavelabs <chandhu.naga@wavelabs.ai>

## Summary

MLOGs in nas5g are converted to OAI LOGs and unwanted DEBUG logs are removed, 

## Test Plan

Tested with UERANSIM, NAS5G log level : DEBUG, INFO, WARNING and ERROR are working fine.
Sample_logs
UT_result1
UT_result2

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Comment by ulaskozat** [comment]
@panyogesh can you review this? Make sure that the debug level logs are sparsely used for the sequence of func in and func out for major functions. Things that should be covered by unit tests should not be substituted by extensive logs.

File: lte/gateway/c/core/oai/tasks/nas5g/src/M5GAuthenticationFailure.cpp [hunk 1]
```diff
@@ -25,6 +25,7 @@ int AuthenticationFailureMsg::DecodeAuthenticationFailureMsg(
   CHECK_PDU_POINTER_AND_LENGTH_DECODER(
       buffer, AUTHENTICATION_FAILURE_MINIMUM_LENGTH, len);
 
+  OAILOG_DEBUG(LOG_NAS5G, "Decoding AuthenticationFailure message");
```
Comment (panyogesh) [inline lte/gateway/c/core/oai/tasks/nas5g/src/M5GAuthenticationFailure.cpp]: AmfMsgDecodeMsg already prints the message type. So we can skip it here.

Comment (panyogesh) [reply lte/gateway/c/core/oai/tasks/nas5g/src/M5GAuthenticationFailure.cpp]: In AmfMsgDecodeMsg() we can make of use of get_message_type_str() to print the message type.

File: lte/gateway/c/core/oai/tasks/nas5g/src/M5GAuthenticationFailure.cpp [hunk 2]
```diff
@@ -88,6 +89,7 @@ int AuthenticationFailureMsg::EncodeAuthenticationFailureMsg(
   CHECK_PDU_POINTER_AND_LENGTH_ENCODER(
       buffer, AUTHENTICATION_FAILURE_MINIMUM_LENGTH, len);
 
+  OAILOG_DEBUG(LOG_NAS5G, "Encoding AuthenticationFailure message");
```
Comment (panyogesh) [inline lte/gateway/c/core/oai/tasks/nas5g/src/M5GAuthenticationFailure.cpp]: This debug can be removed with the previous comment.

File: lte/gateway/c/core/oai/tasks/nas5g/src/M5GAuthenticationReject.cpp [hunk 3]
```diff
@@ -62,6 +63,7 @@ int AuthenticationRejectMsg::EncodeAuthenticationRejectMsg(
   CHECK_PDU_POINTER_AND_LENGTH_ENCODER(
       buffer, AUTHENTICATION_REJECT_MINIMUM_LENGTH, len);
 
+  OAILOG_DEBUG(LOG_NAS5G, "Encoding AuthenticationReject message");
```
Comment (panyogesh) [inline lte/gateway/c/core/oai/tasks/nas5g/src/M5GAuthenticationReject.cpp]: Can be removed.

File: lte/gateway/c/core/oai/tasks/nas5g/src/M5GAuthenticationResponse.cpp [hunk 4]
```diff
@@ -27,8 +27,7 @@ int AuthenticationResponseMsg::DecodeAuthenticationResponseMsg(
   CHECK_PDU_POINTER_AND_LENGTH_DECODER(
       buffer, AUTHENTICATION_RESPONSE_MINIMUM_LENGTH, len);
 
-  MLOG(MDEBUG) << "\n\n---Decoding Authentication Response Message---\n"
-               << std::endl;
+  OAILOG_DEBUG(LOG_NAS5G, "Decoding Authentication Response Message");
```
Comment (panyogesh) [inline lte/gateway/c/core/oai/tasks/nas5g/src/M5GAuthenticationResponse.cpp]: Same as mentioned above.

File: lte/gateway/c/core/oai/tasks/nas5g/src/M5GDeRegistrationRequestUEInit.cpp [hunk 5]
```diff
@@ -28,8 +28,7 @@ int DeRegistrationRequestUEInitMsg::DecodeDeRegistrationRequestUEInitMsg(
   CHECK_PDU_POINTER_AND_LENGTH_DECODER(
       buffer, DEREGISTRATION_REQUEST_UEINIT_MINIMUM_LENGTH, len);
 
-  MLOG(MDEBUG) << "\n\n---Decoding De-Registration Request Message---\n"
-               << std::endl;
+  OAILOG_DEBUG(LOG_NAS5G, "Decoding De-Registration Request Message");
```
Comment (panyogesh) [inline lte/gateway/c/core/oai/tasks/nas5g/src/M5GDeRegistrationRequestUEInit.cpp]: Generalize the comments for all encoding/decoding.

File: lte/gateway/c/core/oai/tasks/nas5g/src/SmfMessage.cpp [hunk 6]
```diff
@@ -84,16 +88,15 @@ int SmfMsg::SmfMsgDecodeMsg(SmfMsg* msg, uint8_t* buffer, uint32_t len) {
   int decode_result = 0;
   int header_result = 0;
 
-  MLOG(MDEBUG) << "SmfMsgDecodeMsg:" << std::endl;
+  OAILOG_DEBUG(LOG_NAS5G, "Decoding SMF message");
```
Comment (panyogesh) [inline lte/gateway/c/core/oai/tasks/nas5g/src/SmfMessage.cpp]: Convert the Message type to string so that in field level the logs can be avoided.

File: lte/gateway/c/core/oai/tasks/nas5g/src/SmfMessage.cpp [hunk 7]
```diff
@@ -136,16 +139,15 @@ int SmfMsg::SmfMsgEncodeMsg(SmfMsg* msg, uint8_t* buffer, uint32_t len) {
   int encode_result = 0;
   int header_result = 0;
 
-  MLOG(MDEBUG) << " SmfMsgEncodeMsg : " << std::endl;
+  OAILOG_DEBUG(LOG_NAS5G, "Encoding SMF message");
```
Comment (panyogesh) [inline lte/gateway/c/core/oai/tasks/nas5g/src/SmfMessage.cpp]: Same comment as for decode.

File: lte/gateway/c/core/oai/tasks/nas5g/src/ies/M5GIntegrityProtMaxDataRate.cpp [hunk 8]
```diff
@@ -24,15 +24,17 @@ int IntegrityProtMaxDataRateMsg::DecodeIntegrityProtMaxDataRateMsg(
...
+  OAILOG_DEBUG(LOG_NAS5G, "Decoding IntegrityProtMaxDataRateMsg");
   integrity_prot_max_data_rate->max_uplink = *(buffer + decoded);
   decoded++;
   integrity_prot_max_data_rate->max_downlink = *(buffer + decoded);
   decoded++;
-  MLOG(MDEBUG) << " max_uplink = " << std::dec
-               << int(integrity_prot_max_data_rate->max_uplink);
-  MLOG(MDEBUG) << " max_downlink = " << std::dec
-               << int(integrity_prot_max_data_rate->max_downlink);
+  OAILOG_DEBUG(
```
Comment (panyogesh) [inline lte/gateway/c/core/oai/tasks/nas5g/src/ies/M5GIntegrityProtMaxDataRate.cpp]: Remove these value prints as this can be derived from packets.

File: lte/gateway/c/core/oai/tasks/nas5g/src/ies/M5GSMobileIdentity.cpp [hunk 9]
```diff
@@ -82,24 +82,25 @@ int M5GSMobileIdentityMsg::DecodeGutiMobileIdentityMsg(
...
-               << "\n";
-  MLOG(MDEBUG) << "   Amf Set ID = " << std::dec << int(guti->amf_setid)
-               << "\n";
-  MLOG(MDEBUG) << "   Amf Pointer = " << std::dec << int(guti->amf_pointer)
-               << "\n";
-  MLOG(MDEUBG) << "   M5G-TMSI = "
-               << "0x0" << std::hex << int(guti->tmsi1) << "0" << std::hex
-               << int(guti->tmsi2) << "0" << std::hex << int(guti->tmsi3) << "0"
-               << std::hex << int(guti->tmsi4) << "\n\n";
+  OAILOG_DEBUG(
```
Comment (panyogesh) [inline lte/gateway/c/core/oai/tasks/nas5g/src/ies/M5GSMobileIdentity.cpp]: Remove these logs.

**Comment by panyogesh** [comment]
LGTM. Can you just put the Unit Test Report and Sample logs in the PR for quick reference.

**Comment by themarwhal** [comment]
@electronjoe I think this might solve our LOG_WITH_GLOG issue (https://github.com/magma/magma/issues/11586)

File: lte/gateway/c/core/oai/tasks/nas5g/include/M5GCommonDefs.h [hunk 10]
```diff
@@ -1,5 +1,12 @@
...
 #include <arpa/inet.h>
+#ifdef __cplusplus
+extern "C" {
+#endif
+#include "lte/gateway/c/core/oai/common/log.h"
+#ifdef __cplusplus
+}
+#endif
 #include "lte/gateway/c/core/oai/common/common_defs.h"
 #include "orc8r/gateway/c/common/logging/magma_logging.h"
```
Comment (themarwhal) [inline lte/gateway/c/core/oai/tasks/nas5g/include/M5GCommonDefs.h]: This should be removed

**Review by themarwhal — COMMENTED** [review]
What about this one? This seems to be the lone MLOG in the oai directory after this change: https://sourcegraph.com/github.com/magma/magma/-/blob/lte/gateway/c/core/oai/lib/n11/M5GSUCIRegistrationServiceClient.cpp?L58

File: lte/gateway/c/core/oai/tasks/nas5g/include/M5GCommonDefs.h (hunk 10 above)
Comment (Chandhu-Wavelabs) [reply lte/gateway/c/core/oai/tasks/nas5g/include/M5GCommonDefs.h]: This **M5GCommonDef.h** file is included in maximum files, if we are not including "lte/gateway/c/core/oai/common/log.h" in this file, we need to include it in all files which are having OAI logs.

Comment (themarwhal) [reply lte/gateway/c/core/oai/tasks/nas5g/include/M5GCommonDefs.h]: If I'm understanding this PR correctly, we should no longer have a dependency on `#include "orc8r/gateway/c/common/logging/magma_logging.h"`, right? 

But to your point, I would strongly recommend only including header files that are needed in each file. The implicit chained includes will get out of hand very quickly, from my experience. 

If a file requires OAI_LOG, I would vouch for always including `"lte/gateway/c/core/oai/common/log.h"`

File: lte/gateway/c/core/oai/tasks/nas5g/src/AmfMessage.cpp [hunk 11]
```diff
@@ -14,6 +14,7 @@
 #include "lte/gateway/c/core/oai/tasks/nas5g/include/AmfMessage.h"
 #include "lte/gateway/c/core/oai/tasks/nas5g/include/M5gNasMessage.h"
 #include "lte/gateway/c/core/oai/tasks/nas5g/include/M5GCommonDefs.h"
+#include "lte/gateway/c/core/oai/tasks/amf/amf_app_defs.h"
```
Comment (themarwhal) [inline lte/gateway/c/core/oai/tasks/nas5g/src/AmfMessage.cpp:24]: Is this added to include `lte/gateway/c/core/oai/common/log.h`? In that case, include the log file directly, please.

File: lte/gateway/c/core/oai/tasks/nas5g/src/M5GULNASTransport.cpp [hunk 12]
```diff
@@ -139,7 +138,7 @@ int ULNASTransportMsg::DecodeULNASTransportMsg(
         break;
     }
     if (decoded_result < 0) {
-      MLOG(MDEBUG) << "ERROR: decode ULNASTransportMsg failed";
+      OAILOG_ERROR(LOG_NAS5G, "ULNASTransportMsg Decoding FAILED");
```
Comment (themarwhal) [inline lte/gateway/c/core/oai/tasks/nas5g/src/M5GULNASTransport.cpp:148]: This file should also include the oai log header directly, if it's not already doing so.

**Review by themarwhal — CHANGES_REQUESTED** [review]
Please survey your changes to make sure all the files that depend on OAI_LOG includes the log.h file directly. (See https://google.github.io/styleguide/cppguide.html#Include_What_You_Use)

File: lte/gateway/c/core/oai/tasks/nas5g/include/M5GCommonDefs.h (hunk 10 above)
Comment (Chandhu-Wavelabs) [reply lte/gateway/c/core/oai/tasks/nas5g/include/M5GCommonDefs.h]: your comments are addressed. "lte/gateway/c/core/oai/common/log.h" is included in all required files

File: lte/gateway/c/core/oai/tasks/nas5g/src/AmfMessage.cpp (hunk 11 above)
Comment (Chandhu-Wavelabs) [reply lte/gateway/c/core/oai/tasks/nas5g/src/AmfMessage.cpp:24]: addressed

File: lte/gateway/c/core/oai/tasks/nas5g/src/M5GULNASTransport.cpp (hunk 12 above)
Comment (Chandhu-Wavelabs) [reply lte/gateway/c/core/oai/tasks/nas5g/src/M5GULNASTransport.cpp:148]: taken care

File: lte/gateway/c/core/oai/tasks/nas5g/include/M5GCommonDefs.h [hunk 13]
```diff
@@ -1,7 +1,6 @@
 #pragma once
 #include <arpa/inet.h>
 #include "lte/gateway/c/core/oai/common/common_defs.h"
-#include "orc8r/gateway/c/common/logging/magma_logging.h"
```
Comment (themarwhal) [inline lte/gateway/c/core/oai/tasks/nas5g/include/M5GCommonDefs.h:4]: This file also seems to need log.h

**Review by themarwhal — APPROVED** [review]
Thanks for addressing the include comments :)

**Review by ulaskozat — APPROVED** [review]
LGTM
