### PR TITLE
fix(feg): config_test.go in session_proxy

### LINKED ISSUE #12260: Missing config_test.go in session_proxy
Feg services use `config.go` to parse configuration from `gateway.mconfig`. That code is protected with `config_test.go`. For example [here](http://github.com/magma/magma/blob/6af92a9865c9eed5e34f4255f69ed75109f0e27a/feg/gateway/services/s6a_proxy/servicers/config_test.go#L24-L24) for s6a_proxy or [here](http://github.com/magma/magma/blob/6af92a9865c9eed5e34f4255f69ed75109f0e27a/feg/gateway/services/swx_proxy/servicers/conf_test.go#L27-L27) for swx_proxy.

Session_proxy does not have config_test.go files, so we are not able to protect that file from changes. 

To prevent regression we should add coverage to those files

http://github.com/magma/magma/blob/6af92a9865c9eed5e34f4255f69ed75109f0e27a/feg/gateway/services/session_proxy/credit_control/gx/config.go#L1-L1

http://github.com/magma/magma/blob/6af92a9865c9eed5e34f4255f69ed75109f0e27a/feg/gateway/services/session_proxy/credit_control/gy/config.go#L1-L1

### PR DESCRIPTION
**Pull request by vikramgreddy**
Signed-off-by: Vikram G <vikram.gurrappagaru@radisys.com>

## Summary
Fixes #12260 
Added config_test.go in session_proxy for Gx and Gy

## Test Plan
./build.py -c

## Additional Information

### CODE REVIEW

File: feg/gateway/services/session_proxy/credit_control/gy/config_test.go [hunk 1]
```diff
@@ -0,0 +1,73 @@
...
+                                                  "productName": "magma",
+                                                  "realm": "magma.com",
+                                                  "host": "magma-fedgw.magma.com"
+                                         }
+                                 },
+                                 "requestFailureThreshold": 0.5,
+                                 "minimumRequestThreshold": 1
+                         }
+		}
+	}`
```
Comment (uri200) [inline feg/gateway/services/session_proxy/credit_control/gy/config_test.go]: generate this outside this function so you can reuse it once you extend it

File: feg/gateway/services/session_proxy/credit_control/gx/config_test.go [hunk 2]
```diff
@@ -0,0 +1,73 @@
...
+		}
+	}`
+
+	err := managed_configs.CreateLoadTempConfig(fegConfigFmt)
+	assert.NoError(t, err)
+
+	configsPtr := &mconfig.SessionProxyConfig{}
+	managed_configs.GetServiceConfigs(credit_control.SessionProxyServiceName, configsPtr)
+
+	gxConfig := configsPtr.GetGx()
```
Comment (uri200) [inline feg/gateway/services/session_proxy/credit_control/gx/config_test.go]: Hey @vikramgreddy,  note the test you are adding are only covering `mconfig` functions.  The intention of this test is not to check`GetGx()` but functions defined on the config.go on gx and gy.

Note they created partial test for this file at  https://github.com/magma/magma/pull/12286. But that code only covers `GetGxClientConfiguration`. It is missing other functions on the config files like `GetPCRFConfiguration` or `GetGxGlobalConfig`. You can use that same code and extend it to cover the other functions on gx and gy

**Review by uri200 — CHANGES_REQUESTED** [review]

File: feg/gateway/services/session_proxy/credit_control/gx/config_test.go [hunk 3]
```diff
@@ -0,0 +1,73 @@
...
+	"testing"
+
+	"github.com/stretchr/testify/assert"
+
+	"magma/feg/cloud/go/protos/mconfig"
+
+	"magma/feg/gateway/services/session_proxy/credit_control"
+
+	managed_configs "magma/gateway/mconfig"
+)
```
Comment (uri200) [inline feg/gateway/services/session_proxy/credit_control/gx/config_test.go:24]: please use same format and separation as in other files (group them by go modules, public, magma)

**Review by uri200 — CHANGES_REQUESTED** [review]

**Comment by uri200** [comment]
Please @vikramgreddy , run `./build.py -c` under `magma/feg/gateway/docker` to run linter, format and precommit checks

File: feg/gateway/services/session_proxy/credit_control/gx/config_test.go [hunk 4]
```diff
@@ -64,4 +75,23 @@ func TestGxClientConfig(t *testing.T) {
...
+
+	globalConfig := GetGxGlobalConfig()
+	vApnRules := globalConfig.VirtualApnRules[0]
+
+	assert.Equal(t, "apn.magma.com", globalConfig.PCFROverwriteApn)
+	assert.Equal(t, bool(false), globalConfig.DisableGx)
+	assert.Regexp(t, ".*", vApnRules.ApnFilter)
+	assert.Regexp(t, "1*", vApnRules.ChargingCharacteristicsFilter)
+	assert.Equal(t, "vApnGy.magma-fedgw.magma.com", vApnRules.ApnOverwrite)
+
```
Comment (uri200) [inline feg/gateway/services/session_proxy/credit_control/gx/config_test.go]: can you separate this into three different test cases please 
```
func TestGxClientConfig(t *testing.T) {...

func TestGetPCRFConfiguration(t *testing.T) {...

func TestGetGxGlobalConfig(t *testing.T) {...

```

File: feg/gateway/services/session_proxy/credit_control/gy/config_test.go [hunk 5]
```diff
@@ -68,4 +79,31 @@ func TestGyClientConfig(t *testing.T) {
...
+	vApnRules := globalConfig.VirtualApnRules[0]
+
+	assert.Equal(t, "apn.magma.com", globalConfig.OCSOverwriteApn)
+	assert.Equal(t, "example-service-id", globalConfig.OCSServiceIdentifier)
+	assert.Equal(t, bool(false), globalConfig.DisableGy)
+	assert.Regexp(t, ".*", vApnRules.ApnFilter)
+	assert.Regexp(t, "1*", vApnRules.ChargingCharacteristicsFilter)
+	assert.Equal(t, "vApnGy.magma-fedgw.magma.com", vApnRules.ApnOverwrite)
+	assert.Equal(t, bool(false), globalConfig.DisableServiceGrantedUnitsAVP)
+
```
Comment (uri200) [inline feg/gateway/services/session_proxy/credit_control/gy/config_test.go]: same here, separate into tests

**Comment by uri200** [comment]
awesome, just make sure you run `./build.py -c` at /magma/feg/gateway` to make sure all test passed and linter is applied

**Review by uri200 — APPROVED** [review]

**Comment by uri200** [comment]
oh i see it passed. I will merge this then
