### PR TITLE
[lte][agw] Fix segfault in issue 7128

### LINKED ISSUE #7128: segv in mme_app_get_imsi_from_ipv4
Sentry Issue: [LAB-AGWS-NATIVE-E](https://sentry.io/organizations/lf-9c/issues/2411954603/?referrer=github_integration)

```
SIGSEGV /0x00000080: Fatal Error: SIGSEGV /0x00000080
  File "mme_app_ip_imsi.cpp", line 84, in mme_app_get_imsi_from_ipv4
  File "mme_app_bearer.c", line 2203, in mme_app_handle_initial_paging_request
  File "mme_app_main.c", line 223, in handle_message
  ?
  File "mme_app_main.c", line 481, in mme_app_thread
...
(2 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by ulaskozat**
Signed-off-by: Ulas Kozat <kozat@fb.com>

## Summary

Issue #7128 provides the context. (*imsi_list) is the dynamic array that will hold the list of imsi64's but the assignment on line 84 is not writing to this array but to an arbitrary location as `[]` has precedence over `*`.

## Test Plan

Sanity tests.

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

File: lte/gateway/c/core/oai/tasks/mme_app/mme_app_ip_imsi.cpp [hunk 1]
```diff
@@ -77,11 +77,11 @@ int mme_app_get_imsi_from_ipv4(uint32_t ipv4_addr, imsi64_t** imsi_list) {
   } else {
     uint8_t idx = 0;
     num_imsis   = itr->second.size();
-    *imsi_list  = (imsi64_t*) calloc(num_imsis, sizeof(imsi64_t));
+    (*imsi_list)  = (imsi64_t*) calloc(num_imsis, sizeof(imsi64_t));
```
Comment (amarpad) [inline lte/gateway/c/core/oai/tasks/mme_app/mme_app_ip_imsi.cpp:80]: Wow nice catch, another stylistic way I have seen is that you create a local imsi_list_ = nullptr, then calloc to it and then reassign *imsi_list = imsi_list_ when we exit scope and only work with imsi_list_ so it syntactically looks better.

**Review by amarpad — APPROVED** [review]

**Review by ardzoht — APPROVED** [review]
Lgtm
