### PR TITLE
[feg] s8_proxy fix TEIDs on Create Session and add DeleteSession to s8_cli and made s8 stateless

### LINKED ISSUE #3595: [Inbound Roaming][FEG] Create s8_proxy
As discussed in the Inbound Roaming system architecture https://docs.google.com/document/d/1zJZpt5dCBjy54ODQ5DzbJZ2HufJgLxAIoVPyZPZL5UY/edit#heading=h.ysnq6v9qfm5k , we need an S8 proxy on FeG, which can:
- Communicate over GRPC with MME service on AGW
- Communicate over GTP-C to home PGW

### PR DESCRIPTION
**Pull request by uri200**
Signed-off-by: Oriol Batalla <obatalla@fb.com>

## Summary

This PR includes changes to the original s8_proxy and some new additions:
- Fix an issue where FTEIDs were displaying with no IP
- Changed the way the server finds out its own ip and uses it to send it as a parameter on the GTP-C create session message.
- Changed tests to add more checks, specially on teids. Added a way to see what TEIDs were assigned by the MockPgw
- Improved functions in sender.go to display better logs in debugging mode
- Added DeleteSession and EchoRequest to tools/s8_cli
- Improved proto definiton
- Disabled validation in go-gtp (triggered a refactor on how we handle IE to proto conversion)
- Added multithread test with multiple users creating and deleting sessions at the same time
- Final commit includes a major refactor to remove state from s8_proxy and rely on mme to store state (mainly teids being used). S8_proxy now can be restarted and sessions will not be affected

## Test Plan

./build -g && ./build --test at orc8r
make precommit at feg
Test on teravm and HCore with s8_cli

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

File: feg/gateway/gtp/gtp_client.go [hunk 1]
```diff
@@ -125,34 +141,43 @@ func (c *Client) Run(ctx context.Context) error {
...
 // WaitUntilClientIsReady is a hack to know when the client is ready and avoid null pointer issues using
 // the GTP-C client too early. Since go-gtp doesn't offer any visibuility on the readines of the connection
 // we use LocalAddrs as indicator
 func (c *Client) WaitUntilClientIsReady(count int) {
+
+	// TODO: only use those 3 waits for debugging
+	time.Sleep(time.Millisecond * 20)
+	time.Sleep(time.Millisecond * 20)
+	time.Sleep(time.Millisecond * 20)
+
```
Comment (uri200) [inline feg/gateway/gtp/gtp_client.go:178]: This is going to stay here for now. Otherwise test may fail on ci

There is a PR on go-gtp already approved to fix this issue. Still waiting for the new tag to apply the new version to our s8_proxy

**Review by themarwhal — APPROVED** [review]
