### PR TITLE
fix(agw): Fixed compilation error

### LINKED ISSUE #10282: mme: linking error seen when running `make build_oai` after running `make test_oai`
## Repro steps

in the Magma VM (or GitHub Codespaces), run make test_oai and then make build_oai. The test command should execute fine, but then the build command will fail with the following linking error.

```
[2031/2033] Linking CXX executable test/spgw_task/spgw_procedures_test
FAILED: test/spgw_task/spgw_procedures_test
: && /usr/lib/ccache/c++  -g -DDEBUG_IS_ON=1 -g -O0 -fprofile-arcs -ftest-coverage  -fsanitize=address -fsanitize=undefined -fprofile-arcs -ftest-coverage test/spgw_task/CMakeFiles/spgw_procedures_test.dir/test_spgw_procedures.cpp.o  -o test/spgw_task/spgw_procedures_test -L/usr/src/googletest/googlemock/lib -Wl,-rpath,/usr/src/googletest/googlemock/lib:/usr/local/lib  test/spgw_task/libSPGW_TASK_TEST_LIB.a  tasks/sgw/libTASK_SGW.a  tasks/gtpv1-u/libTASK_GTPV1U.a  lib/openflow/controller/libLIB_OPENFLOW_CONTROLLER.a  lib/pipelined_client/libLIB_PIPELINED_CLIENT.a  tasks/nas/libTASK_NAS.a  tasks/mme_app/libTASK_MME_APP.a  tasks/sgw_s8/libTASK_SGW_S8.a  tasks/s1ap/libTASK_S1AP.a  tasks/sgw/libTASK_SGW.a  tasks/gtpv1-u/libTASK_GTPV1U.a  lib/openflow/controller/libLIB_OPENFLOW_CONTROLLER.a  lib/pipelined_client/libLIB_PIPELINED_CLIENT.a  tasks/nas/libTASK_NAS.a  tasks/mme_app/libTASK_MME_APP.a  tasks/sgw_s8/libTASK_SGW_S8.a  tasks/s1ap/libTASK_S1AP.a  -lfluid_base  -lfluid_msg  lib/secu/libLIB_SECU.a  -lnettle  tasks/s6a/libTASK_S6A.a  lib/s6a_proxy/libLIB_S6A_PROXY.a  tasks/s6a/libTASK_S6A.a  lib/s6a_proxy/libLIB_S6A_PROXY.a  -lconfig  lib/directoryd/libLIB_DIRECTORYD.a  lib/event_client/libLIB_EVENT_CLIENT.a  /home/vagrant/build/c/core/common/eventd/libEVENTD.a  tasks/sctp/libTASK_SCTP_SERVER.a  tasks/sgs/libTASK_SGS.a  lib/sgs_client/libLIB_SGS_CLIENT.a  common/redis_utils/libredis_utils.a  -lfolly  lib/s8_proxy/libLIB_S8_PROXY.a  lib/mobility_client/libLIB_MOBILITY_CLIENT.a  lib/pcef/libLIB_PCEF.a  lib/mobility_client/libLIB_MOBILITY_CLIENT.a  lib/pcef/libLIB_PCEF.a  -lcpp_redis  -ltacopie  tasks/service303/libTASK_SERVICE303.a  /home/vagrant/build/c/core/common/async_grpc/libASYNC_GRPC.a  /usr/lib/x86_64-linux-gnu/libprotobuf.so  -pthread  test/mock_tasks/libMOCK_TASKS.a  common/libCOMMON.a  lib/hashtable/libLIB_HASHTABLE.a  lib/itti/libLIB_ITTI.a  lib/3gpp/libLIB_3GPP.a  lib/message_utils/libLIB_MESSAGE_UTILS.a  tasks/s1ap/libLIB_S1AP.a  tasks/ngap/libLIB_NGAP.a  common/libCOMMON.a  lib/hashtable/libLIB_HASHTABLE.a  lib/itti/libLIB_ITTI.a  lib/3gpp/libLIB_3GPP.a  lib/message_utils/libLIB_MESSAGE_UTILS.a  tasks/s1ap/libLIB_S1AP.a  tasks/ngap/libLIB_NGAP.a  -llfds710  -lssl  -lcrypto  common/glogwrapper/libglogwrapper.a  /home/vagrant/build/c/core/common/sentry/libMAGMA_SENTRY.a  /usr/local/lib/libsentry.so  /home/vagrant/build/c/core/common/service303/libSERVICE303_LIB.a  /home/vagrant/build/c/core/common/service_registry/libSERVICE_REGISTRY.a  /home/vagrant/build/c/core/common/config/libMAGMA_CONFIG.a  -lglog  -ldl  -lprometheus-cpp  -lprotobuf  -lgrpc  -lgrpc++  -lczmq  lib/bstr/libLIB_BSTR.a  -lgmock_main  -lgtest  -lgtest_main  -lgmock  -lpthread  -lrt  -lyaml-cpp && :
/usr/bin/ld: lib/s8_proxy/libLIB_S8_PROXY.a(s8_client_api.cpp.o): in function `recv_s8_delete_session_response(unsigned long, unsigned int, grpc::Status const&, magma::feg::DeleteSessionResponsePgw&)':
/home/vagrant/magma/lte/gateway/c/core/oai/lib/s8_proxy/s8_client_api.cpp:149: undefined reference to `grpc_service_task_zmq_ctx'
/usr/bin/ld: lib/s8_proxy/libLIB_S8_PROXY.a(s8_client_api.cpp.o): in function `recv_s8_create_session_response(unsigned long, unsigned int, bearer_qos_s, grpc::Status const&, magma::feg::CreateSessionResponsePgw&)':
/home/vagrant/magma/lte/gateway/c/core/oai/lib/s8_proxy/s8_client_api.cpp:193: undefined reference to `grpc_service_task_zmq_ctx'
/usr/bin/ld: lib/mobility_client/libLIB_MOBILITY_CLIENT.a(MobilityClientAPI.cpp.o): in function `handle_allocate_ipv4_address_status(grpc::Status const&, in_addr, int, char const*, char const*, char const*, unsigned int, unsigned char)':
/home/vagrant/magma/lte/gateway/c/core/oai/lib/mobility_client/MobilityClientAPI.cpp:153: undefined reference to `grpc_service_task_zmq_ctx'
/usr/bin/ld: lib/mobility_client/libLIB_MOBILITY_CLIENT.a(MobilityClientAPI.cpp.o): in function `handle_allocate_ipv6_address_status(grpc::Status const&, in6_addr, int, char const*, char const*, char const*, unsigned int, unsigned char)':
/home/vagrant/magma/lte/gateway/c/core/oai/lib/mobility_client/MobilityClientAPI.cpp:273: undefined reference to `grpc_service_task_zmq_ctx'
/usr/bin/ld: lib/mobility_client/libLIB_MOBILITY_CLIENT.a(MobilityClientAPI.cpp.o): in function `handle_allocate_ipv4v6_address_status(grpc::Status const&, in_addr, in6_addr, int, char const*, char const*, char const*, unsigned int, unsigned char)':
/home/vagrant/magma/lte/gateway/c/core/oai/lib/mobility_client/MobilityClientAPI.cpp:379: undefined reference to `grpc_service_task_zmq_ctx'
/usr/bin/ld: lib/pcef/libLIB_PCEF.a(pcef_handlers.cpp.o):/home/vagrant/magma/lte/gateway/c/core/oai/lib/pcef/pcef_handlers.cpp:133: more undefined references to `grpc_service_task_zmq_ctx' follow
collect2: error: ld returned 1 exit status
[2032/2033] Linking CXX executable oai_mme/mme
/usr/bin/ld: warning: libnettle.so.7, needed by /lib/x86_64-linux-gnu/librtmp.so.1, may conflict with libnettle.so.4
[2033/2033] Linking CXX executable test/sgw_s8_task/sgw_s8_test

```

Commit that may have caused this according to git-disect: https://github.com/magma/magma/pull/9865

### PR DESCRIPTION
**Pull request by rsarwad**
Signed-off-by: Rashmi <rashmi.sarwad@radisys.com>

## Summary

fix(agw): Fixed compilation error

## Test Plan

Executed s1ap sanity test suite

### CODE REVIEW

File: lte/gateway/c/core/oai/test/sgw_s8_task/sgw_s8_utility.cpp [hunk 1]
```diff
@@ -244,6 +244,8 @@ static int handle_message_test_sgw_s8(
 void SgwS8ConfigAndCreateMock::SetUp() {
   mme_app_handler = std::make_shared<MockMmeAppHandler>();
 
+  // stop mme service, so that there are no active grpc server running
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/test/sgw_s8_task/sgw_s8_utility.cpp]: This should be part of Makefile, as part of `test_oai` target.

**Review by ssanadhya — CHANGES_REQUESTED** [review]

**Comment by ssanadhya** [comment]
@themarwhal , could you please confirm if the changes to Makefile are okay with current CI job configuration?

**Review by ssanadhya — APPROVED** [review]

File: lte/gateway/c/core/oai/test/spgw_task/CMakeLists.txt [hunk 2]
```diff
@@ -36,7 +36,9 @@ target_link_libraries(SPGW_TASK_TEST_LIB
 set_target_properties(SPGW_TASK_TEST_LIB PROPERTIES LINKER_LANGUAGE CXX)
 
 foreach (sgw_test spgw_state_converter spgw_procedures)
-  add_executable(${sgw_test}_test test_${sgw_test}.cpp)
-  target_link_libraries(${sgw_test}_test SPGW_TASK_TEST_LIB)
+  add_executable(${sgw_test}_test test_${sgw_test}.cpp
+              ${PROJECT_SOURCE_DIR}/tasks/grpc_service/grpc_service_task.c
```
Comment (themarwhal) [inline lte/gateway/c/core/oai/test/spgw_task/CMakeLists.txt]: Is this line necessary? Is the file not included by linking `TASK_GRPC_SERVICE`?

File: lte/gateway/Makefile [hunk 3]
```diff
@@ -211,7 +211,7 @@ ifdef UT_PATH
 endif
 	make -C $(MAGMA_ROOT)/lte/gateway/python unit_tests MAGMA_SERVICE=$(MAGMA_SERVICE) UT_PATH=$(ut_path) DONT_BUILD_ENV=$(DONT_BUILD_ENV)
 
-test_oai: ## Run all OAI-specific tests
+test_oai: stop ## Run all OAI-specific tests
```
Comment (themarwhal) [inline lte/gateway/Makefile]: This will not work in CI as it doesn't have a concept of running services with systemd in that environment. Is this necessary? If it's useful to have a target that stops the running services and execute unit tests, we can create a separate target for this. :)

**Review by themarwhal — COMMENTED** [review]
left some comments!

**Comment by ssanadhya** [comment]
Adding label `DONOTLAND` until we resolve the plan for CI

File: lte/gateway/c/core/oai/test/spgw_task/CMakeLists.txt (hunk 2 above)
Comment (rsarwad) [reply lte/gateway/c/core/oai/test/spgw_task/CMakeLists.txt]: No, grpc_service_task.c is not included while generating TASK_GRPC_SERVICE. Even while generating mme binary, it's explicitly included. 
https://github.com/magma/magma/blob/master/lte/gateway/c/core/oai/oai_mme/CMakeLists.txt#L37

Comment (themarwhal) [reply lte/gateway/c/core/oai/test/spgw_task/CMakeLists.txt]: Hmm that seems weird. Have you tried adding the file to the library? /workspaces/magma/lte/gateway/c/core/oai/tasks/grpc_service/CMakeLists.txt

Comment (themarwhal) [reply lte/gateway/c/core/oai/test/spgw_task/CMakeLists.txt]: ok i was curious so tried it out :) This seems to fix the weird anti pattern https://github.com/magma/magma/pull/10324 (feel free to cherrypick into your PR)

Comment (rsarwad) [reply lte/gateway/c/core/oai/test/spgw_task/CMakeLists.txt]: I followed the existing pattern.
Thanks @themarwhal Sure I will cherry-pick these changes.

**Review by ssanadhya — CHANGES_REQUESTED** [review]
Please update after rebasing on latest master since #10324 is merged

**Review by themarwhal — APPROVED** [review]

**Review by ssanadhya — APPROVED** [review]

File: lte/gateway/c/core/oai/include/grpc_service.h [hunk 4]
```diff
@@ -20,14 +20,16 @@
 #include "lte/gateway/c/core/oai/lib/bstr/bstrlib.h"
 #include "lte/gateway/c/core/oai/common/mme_default_values.h"
 
+#define TEST_GRPCSERVICES_SERVER_ADDRESS "127.0.0.1:50095"
```
Comment (ulaskozat) [inline lte/gateway/c/core/oai/include/grpc_service.h:23]: why is this defined here but not part of the test suite?

Comment (ulaskozat) [reply lte/gateway/c/core/oai/include/grpc_service.h:23]: @rsarwad

Comment (rsarwad) [reply lte/gateway/c/core/oai/include/grpc_service.h:23]: grpc_service_init() was declared in this file. TEST_GRPCSERVICES_SERVER_ADDRESS is passed as an argument. So I declared it here.

Comment (ssanadhya) [reply lte/gateway/c/core/oai/include/grpc_service.h:23]: @rsarwad , to @ulaskozat's point, you can move this to `mock_tasks.h` and still use it in the call to `grpc_service_init()` in `sgw_s8_recv_grpc_messages.cpp`

Comment (rsarwad) [reply lte/gateway/c/core/oai/include/grpc_service.h:23]: Addressed the comment in PR, https://github.com/magma/magma/pull/10370

**Comment by electronjoe** [comment]
Root cause not yet known (it may not be this PR) but I am failing to build Magma/master tests from within devcontainer (I am now repeating the test in Vagrant VM - will update shortly):

```
git log
commit 1a65e574e010222e21abaac1f9190c90205df58d (HEAD -> master, upstream/master, origin/master)
Author: Fritz Lehnert <Fritz.Lehnert@tngtech.com>
Date:   Wed Nov 17 15:17:11 2021 +0100

    feat: create new Github action for bazel docker image build (#10312)
    
    * feat: create new Github action for bazel docker image build
    
    Signed-off-by: Fritz Lehnert <Fritz.Lehnert@tngtech.com>
    
    * fix: github action with unexpected behaviour on Dockerfile
    
    Signed-off-by: Fritz Lehnert <Fritz.Lehnert@tngtech.com>
```

```
cd lte/gateway
make test_oai
```

```
In file included from /workspaces/magma/lte/gateway/c/core/oai/test/mock_tasks/grpc_mock.cpp:18:
/workspaces/magma/lte/gateway/c/core/oai/tasks/grpc_service/S8ServiceImpl.h:19:10: fatal error: feg/protos/s8_proxy.grpc.pb.h: No such file or directory
   19 | #include "feg/protos/s8_proxy.grpc.pb.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by electronjoe** [comment]
I did the following just now:

```
git log
commit 1a65e574e010222e21abaac1f9190c90205df58d (HEAD -> master, origin/master, origin/HEAD)
Author: Fritz Lehnert <Fritz.Lehnert@tngtech.com>
Date:   Wed Nov 17 15:17:11 2021 +0100

    feat: create new Github action for bazel docker image build (#10312)

    * feat: create new Github action for bazel docker image build

    Signed-off-by: Fritz Lehnert <Fritz.Lehnert@tngtech.com>

    * fix: github action with unexpected behaviour on Dockerfile

    Signed-off-by: Fritz Lehnert <Fritz.Lehnert@tngtech.com>
```

```
cd lte/gateway
vagrant destroy Magma
vagrant up Magma
vagrant ssh magma
cd magma/lte/gateway
make oai_test
```

And got the same error.

```
In file included from /home/vagrant/magma/lte/gateway/c/core/oai/test/mock_tasks/grpc_mock.cpp:18:
/home/vagrant/magma/lte/gateway/c/core/oai/tasks/grpc_service/S8ServiceImpl.h:19:10: fatal error: feg/protos/s8_proxy.grpc.pb.h: No such file or directory
   19 | #include "feg/protos/s8_proxy.grpc.pb.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by electronjoe** [comment]
I've determined that the breakage is unrelated to this PR, see my fix in #10383
