### PR TITLE
fix(agw): Added asynchronous grpc server to handle grpc messages over s6a interface

### LINKED ISSUE #6884: [mme] Unimplemented send_cancel_location_ans on s6a_client_api
s6a_task MME is not implementing `send_cancel_location_ans`. It just returns False, which triggers an error on the FEG and on the HSS.

http://github.com/magma/magma/blob/b8ac7839b660ac38a5a7949bc6bf031d5182f6d6/lte/gateway/c/oai/tasks/s6a/s6a_grpc_iface.cpp#L47-L47

This can be reproduced running `cancel_location_19` test from teravm GUI.

### LINKED ISSUE #8609: [FeG] Cancel Location Answer with a Result Code 3002 UNABLE TO DELIVER
### Your Environment

- **Version:** 1.6 
- **Affected Component:**  Fed Gateway
- **Affected Subcomponent:** Fed Gateway
- **Deployment Environment:** local docker-compose (orc8r), Openstack AGW/FeG)

### Describe the Issue
FeG receives a Command Code: 317 3GPP-Cancel-Location from HSS. FeG answers with a result code 3002 DIAMETER_UNABLE_TO_DELIVER in frame # 703
image

Logs of the s6a_proxy shows this failure:
```
[36ms6a_proxy        |[0m I0810 20:36:20.814825       1 service_config.go:169] Successfully loaded '::control_proxy' service configs from '/etc/magma/control_proxy.yml'
[36ms6a_proxy        |[0m I0810 20:36:20.815072       1 service_config.go:180] Successfully loaded Override configs for service :control_proxy from '/var/opt/magma/configs/control_proxy.yml'
[36ms6a_proxy        |[0m I0810 20:36:20.815116       1 cloud_connection.go:116] connecting to: 127.0.0.1:8443, authority: feg_relay-controller.magma.test
[36ms6a_proxy        |[0m E0810 20:36:20.851575       1 cl.go:49] Failed to forward CLR to gateway. err: rpc error: code = Unknown desc = OK: HTTP status code 200; transport: missing content-type field. Retries left: 3
[36ms6a_proxy        |[0m I0810 20:36:20.851659       1 cloud_connection.go:116] connecting to: 127.0.0.1:8443, authority: feg_relay-controller.magma.test
[36ms6a_proxy        |[0m E0810 20:36:20.874176       1 cl.go:49] Failed to forward CLR to gateway. err: rpc error: code = Unknown desc = OK: HTTP status code 200; transport: missing content-type field. Retries left: 2
[36ms6a_proxy        |[0m I0810 20:36:20.874305       1 cloud_connection.go:116] connecting to: 127.0.0.1:8443, authority: feg_relay-controller.magma.test
[36ms6a_proxy        |[0m E0810 20:36:20.911323       1 cl.go:49] Failed to forward CLR to gateway. err: rpc error: code = Unknown desc = OK: HTTP status code 200; transport: missing content-type field. Retries left: 1
[36ms6a_proxy        |[0m I0810 20:36:20.911393       1 cloud_connection.go:116] connecting to: 127.0.0.1:8443, authority: feg_relay-controller.magma.test
[36ms6a_proxy        |[0m E0810 20:36:20.932022       1 cl.go:49] Failed to forward CLR to gateway. err: rpc error: code = Unknown desc = OK: HTTP status code 200; transport: missing content-type field. Retries left: 0
```
In syslog of the AGW cannot see any related log to this failure.

**Expected behavior**
FeG must be able to parse and answer correctly a Cancel Location Request from HSS.

**Additional context**
* Attached trace, see frame # 703 
[trace1008_fegentel_02.zip](https://github.com/magma/magma/files/6971879/trace1008_fegentel_02.zip)
* Attached the s6a_proxy logs in FeG, can see logs from line # 160 to 203 
[s6a_proxy.zip](https://github.com/magma/magma/files/6971883/s6a_proxy.zip)
* Attached syslog of AGW. Cannot find any related failure log about this issue. The time window when the message came should be between 20:34 - 20:36
[syslog.zip](https://github.com/magma/magma/files/6971885/syslog.zip)

### PR DESCRIPTION
**Pull request by rsarwad**
fix(agw): Added asynchronous grpc server to handle grpc messages over s6a interface
Provided fix for issue, https://github.com/magma/magma/issues/8609

## Summary
As part of fixing issue, https://github.com/magma/magma/issues/8609, it's required to support asynchronous server, create a task to handle messages received on asynchronous server.

## Test Plan
1. Executed s1ap sanity test suite on local setup
2. Executed CLR and reset test case on Tera VM

### CODE REVIEW

File: lte/gateway/c/core/oai/tasks/async_grpc_service/S6aGatewayImpl.cpp [hunk 1]
```diff
@@ -0,0 +1,170 @@
...
+      server.GetNewCompletionQueue(), async_service_handler);
+  server.AddServiceToServer(&s6a_async_service);
+
+  server.Start();
+  OAILOG_INFO(LOG_S6A, "Started async grpc server for s6a interface \n");
+
+  std::thread proxy_thread([&]() {
+    s6a_async_service.wait_for_requests();  // block here instead of on server
+  });
+  proxy_thread.join();
```
Comment (ulaskozat) [inline lte/gateway/c/core/oai/tasks/async_grpc_service/S6aGatewayImpl.cpp]: if you do this, you are waiting for proxy_thread to end and will not be able to start the zloop thread. Remove the join line. Also do not use a global in c++ land, if you really need to have a single instance, utilize singleton class.

File: lte/gateway/c/core/oai/tasks/async_grpc_service/grpc_async_service_task.c [hunk 2]
```diff
@@ -0,0 +1,81 @@
...
+
+  itti_mark_task_ready(TASK_ASYNC_GRPC_SERVICE);
+
+  init_task_context(
+      TASK_ASYNC_GRPC_SERVICE, (task_id_t[]){TASK_MME_APP, TASK_S6A}, 2,
+      handle_message, grpc_async_service_task_zmq_ctx_p);
+  init_async_grpc_server();
+  zloop_start(grpc_async_service_task_zmq_ctx.event_loop);
+  AssertFatal(
+      0, "Asserting as grpc_service_thread should not be exiting on its own!");
```
Comment (ulaskozat) [inline lte/gateway/c/core/oai/tasks/async_grpc_service/grpc_async_service_task.c]: this is grpc_async_service_thread

File: lte/gateway/c/core/oai/tasks/async_grpc_service/grpc_async_service_task.c [hunk 3]
```diff
@@ -0,0 +1,81 @@
+/*
```
Comment (ulaskozat) [inline lte/gateway/c/core/oai/tasks/async_grpc_service/grpc_async_service_task.c]: please use magma copyright not OAI.
Also you should code this thing in c++. You can use `extern "C" status_code_e grpc_async_service_init()`

File: lte/gateway/c/core/oai/tasks/async_grpc_service/grpc_async_service_task.c [hunk 4]
```diff
@@ -0,0 +1,81 @@
...
+static void* grpc_async_service_thread(__attribute__((unused)) void* args) {
+  task_zmq_ctx_t* grpc_async_service_task_zmq_ctx_p =
+      &grpc_async_service_task_zmq_ctx;
+
+  itti_mark_task_ready(TASK_ASYNC_GRPC_SERVICE);
+
+  init_task_context(
+      TASK_ASYNC_GRPC_SERVICE, (task_id_t[]){TASK_MME_APP, TASK_S6A}, 2,
+      handle_message, grpc_async_service_task_zmq_ctx_p);
+  init_async_grpc_server();
```
Comment (ulaskozat) [inline lte/gateway/c/core/oai/tasks/async_grpc_service/grpc_async_service_task.c]: define the async server and proxy thread in this scope.

**Comment by uri200** [comment]
this issue is tracked here https://github.com/magma/magma/issues/6884

**Comment by ulaskozat** [comment]
what is the status of this PR? is it stale?

**Comment by rsarwad** [comment]
> what is the status of this PR? is it stale?

Hi Ulas, this PR is not stale. I prioritize working on dedicated bearer support for roaming UE. Soon I will start to work on this PR

File: lte/gateway/c/core/oai/tasks/async_grpc_service/grpc_async_service_task.cpp [hunk 5]
```diff
@@ -0,0 +1,232 @@
...
+
+void stop_async_s6a_grpc_server(void) {
+  magma::S6aProxyResponderAsyncService* s6a_proxy_async_instance =
+      magma::S6aProxyResponderAsyncService::getInstance();
+  s6a_proxy_async_instance->stop();  // stop queue after server shuts down
+  free(s6a_proxy_async_instance);
+}
+AsyncService::AsyncService(std::unique_ptr<ServerCompletionQueue> cq)
+    : cq_(std::move(cq)) {}
+void AsyncService::wait_for_requests() {
```
Comment (ulaskozat) [inline lte/gateway/c/core/oai/tasks/async_grpc_service/grpc_async_service_task.cpp:54]: can you leave single line space between functions/methods?

File: lte/gateway/c/core/oai/tasks/async_grpc_service/grpc_async_service_task.cpp [hunk 6]
```diff
@@ -0,0 +1,232 @@
...
+
+void AsyncService::stop() {
+  running_ = false;
+  // Pop all items in the queue until it is empty
+  void* tag;
+  bool ok;
+  while (cq_->Next(&tag, &ok)) {
+  }
+}
+S6aProxyResponderAsyncService::S6aProxyResponderAsyncService(
```
Comment (ulaskozat) [inline lte/gateway/c/core/oai/tasks/async_grpc_service/grpc_async_service_task.cpp]: leave a single line of space between all functions and methods consistently.

File: lte/gateway/c/core/oai/tasks/async_grpc_service/grpc_async_service_task.h [hunk 7]
```diff
@@ -0,0 +1,248 @@
...
+
+/**
+ * General async gRPC service. It runs a loop pulling requests off a server
+ * queue and then processing them. In general, the C++ implementation of async
+ * gRPC servers is quite confusing and requires a lot of groundwork. Hopefully
+ * this documentation can clear up some of the "magic".
+ *
+ * Every request is represented by a CallData, with one implementation per
+ * RPC call. The CallData has a state machine of the life cycle of the request.
+ * A request appears on the queue when it needs to be *processed* for the first
```
Comment (ulaskozat) [inline lte/gateway/c/core/oai/tasks/async_grpc_service/grpc_async_service_task.h]: why processed is between two asterisk?

File: lte/gateway/c/core/oai/tasks/async_grpc_service/grpc_async_service_task.cpp [hunk 8]
```diff
@@ -0,0 +1,232 @@
+/**
```
Comment (ulaskozat) [inline lte/gateway/c/core/oai/tasks/async_grpc_service/grpc_async_service_task.cpp:1]: @uri200 @rsarwad a lot of code and class definitions look like copied from sessiond. why don't we put these into a common folder across c/c++ services?

File: lte/gateway/c/core/oai/tasks/async_grpc_service/grpc_async_service_task.cpp [hunk 9]
```diff
@@ -0,0 +1,232 @@
...
+    ServerContext* context, const CancelLocationRequest* request,
+    std::function<void(grpc::Status, CancelLocationAnswer)> response_callback) {
+  auto& request_cpy = *request;
+  CancelLocationAnswer ans;
+  Status status;
+  status = Status::OK;
+  ans.set_error_code(ErrorCode::SUCCESS);
+  if (response_callback) {
+    response_callback(status, ans);
+  }
```
Comment (ulaskozat) [inline lte/gateway/c/core/oai/tasks/async_grpc_service/grpc_async_service_task.cpp:140]: if we are responding back like this immediately, what is the purpose of having an async call?

File: lte/gateway/c/core/oai/tasks/async_grpc_service/grpc_async_service_task.cpp [hunk 10]
```diff
@@ -0,0 +1,232 @@
...
+void S6aProxyAsyncResponderHandler::Reset(
+    ServerContext* context, const ResetRequest* request,
+    std::function<void(grpc::Status, ResetAnswer)> response_callback) {
+  auto& request_cpy = *request;
+  ResetAnswer ans;
+  Status status;
+  status = Status::OK;
+  ans.set_error_code(ErrorCode::SUCCESS);
+  if (response_callback) {
+    response_callback(status, ans);
```
Comment (ulaskozat) [inline lte/gateway/c/core/oai/tasks/async_grpc_service/grpc_async_service_task.cpp:162]: same question as above.

File: lte/gateway/c/core/oai/tasks/async_grpc_service/grpc_async_service_task.cpp (hunk 8 above)
Comment (uri200) [reply lte/gateway/c/core/oai/tasks/async_grpc_service/grpc_async_service_task.cpp:1]: Hey @ulaskozat  we can do that, but I think it would be better to try to do this on a different PR

The issue this PR fixes has been blocking some s6a regression tests since inception of the service. So it would be nice to have Cancel Location test pass eventually

File: lte/gateway/c/core/oai/tasks/async_grpc_service/grpc_async_service_task.cpp (hunk 9 above)
Comment (uri200) [reply lte/gateway/c/core/oai/tasks/async_grpc_service/grpc_async_service_task.cpp:140]: Hey @ulaskozat  note the issue is `send_cancel_location_ans` not implementing the cancel location answer. 

Per my understanding  we needed an async service to be able to answer back with the proper error code. @rsarwad 
 can you confirm?

http://github.com/magma/magma/blob/master/lte/gateway/c/core/oai/tasks/s6a/s6a_grpc_iface.cpp#L48-L48

File: lte/gateway/c/core/oai/tasks/async_grpc_service/grpc_async_service_task.h (hunk 7 above)
Comment (rsarwad) [reply lte/gateway/c/core/oai/tasks/async_grpc_service/grpc_async_service_task.h]: Not sure, copied from file, "SessionManagerServer.h"
@uri200 Any idea on this?

File: lte/gateway/c/core/oai/tasks/async_grpc_service/grpc_async_service_task.cpp (hunk 8 above)
Comment (rsarwad) [reply lte/gateway/c/core/oai/tasks/async_grpc_service/grpc_async_service_task.cpp:1]: Yes @ulaskozat , we can create a separate PR

File: lte/gateway/c/core/oai/tasks/async_grpc_service/grpc_async_service_task.cpp (hunk 9 above)
Comment (rsarwad) [reply lte/gateway/c/core/oai/tasks/async_grpc_service/grpc_async_service_task.cpp:140]: Yes @uri200, what you say is right. Earlier AGW was not responding to cancel location request. As part of this PR, we added code to send Cancel location answer in response to cancel location request, with result code "DIAMETER_SUCCESS" because as per spec, https://www.etsi.org/deliver/etsi_ts/129200_129299/129272/12.06.00_60/ts_129272v120600p.pdf section, 5.2.1.2.2 
It indicates that MME always send Cancel location answer with result code "DIAMETER_SUCCESS".
So we can send the response immediately

File: lte/gateway/c/core/oai/tasks/async_grpc_service/grpc_async_service_task.h (hunk 7 above)
Comment (uri200) [reply lte/gateway/c/core/oai/tasks/async_grpc_service/grpc_async_service_task.h]: I think that  is just for docstring formatting. I guess it will set that works as bold

**Review by ulaskozat — APPROVED** [review]
LGTM

**Comment by rsarwad** [comment]
I rebased the PR to latest master codebase and executed cancel_location_19 and cancel_location_20 on Teravm, both works fine
