### PR TITLE
fix(amf): "Code refactoring and fix errors"

### LINKED ISSUE #12156: [AMF]: Tracker for open items as part of implicit deregistration PR (#11995)
Few comments on PR #11995 is yet to be resolved. As it's a critical PR and already become XXL in size, these comments should be resolved as part of this task.

### PR DESCRIPTION
**Pull request by Akshayp77**
Signed-off-by: Akshayp77 <akshay.patidar@wavelabs.ai>

fix(amf): "Code refactoring and fix errors"

## Summary
1. In lte/gateway/c/core/oai/lib/3gpp/3gpp_24.501.h  rename variable.
2. In lte/gateway/c/core/oai/tasks/amf/amf_cn.cpp  add log.
3. In lte/gateway/c/core/oai/tasks/amf/amf_config.c   rename variable.
4. In lte/gateway/c/core/oai/test/amf/amf_app_test_util.cpp  minimize statements.
5. In lte/gateway/c/core/oai/test/amf/test_amf_procedures.cpp  fix single line comments

## Test Plan
1. UE_RAN_SIM
6. Unit Test

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

File: lte/gateway/c/core/oai/test/amf/amf_app_test_util.cpp [hunk 1]
```diff
@@ -669,8 +665,7 @@ bool check_ue_context_state(amf_ue_ngap_id_t ue_id,
   }
 
   n2cause_e ue_context_rel_cause;
-  rc = amf_get_ue_context_rel_cause(ue_id, &ue_context_rel_cause);
-  if (rc != RETURNok) {
+  if (amf_get_ue_context_rel_cause(ue_id, &ue_context_rel_cause) != RETURNok) {
```
Comment (pruthvihebbani) [inline lte/gateway/c/core/oai/test/amf/amf_app_test_util.cpp:676]: Not related to your changes, since you are refactoring you can remove "n2cause_e expected_ue_context_rel_cause" passed to this function as it is being over written at 667

File: lte/gateway/c/core/oai/test/amf/amf_app_test_util.cpp [hunk 2]
```diff
@@ -647,10 +647,7 @@ bool check_ue_context_state(amf_ue_ngap_id_t ue_id,
                             m5gcm_state_t expected_cm_state,
                             n2cause_e expected_ue_context_rel_cause) {
   m5gmm_state_t mm_state;
-  int rc = RETURNerror;
-
-  rc = amf_get_ue_context_mm_state(ue_id, &mm_state);
-  if (rc != RETURNok) {
+  if (amf_get_ue_context_mm_state(ue_id, &mm_state) != RETURNok) {
```
Comment (pruthvihebbani) [inline lte/gateway/c/core/oai/test/amf/amf_app_test_util.cpp:650]: Add an error log. Helps in debugging

File: lte/gateway/c/core/oai/test/amf/amf_app_test_util.cpp [hunk 3]
```diff
@@ -659,8 +656,7 @@ bool check_ue_context_state(amf_ue_ngap_id_t ue_id,
   }
 
   m5gcm_state_t cm_state;
-  rc = amf_get_ue_context_cm_state(ue_id, &cm_state);
-  if (rc != RETURNok) {
+  if (amf_get_ue_context_cm_state(ue_id, &cm_state) != RETURNok) {
```
Comment (pruthvihebbani) [inline lte/gateway/c/core/oai/test/amf/amf_app_test_util.cpp:663]: Add an error log. Helps in debugging

File: lte/gateway/c/core/oai/tasks/amf/amf_cn.cpp [hunk 4]
```diff
@@ -93,7 +93,10 @@ static int amf_cn_implicit_deregister_ue(const amf_ue_ngap_id_t ue_id) {
     rc = amf_proc_deregistration_request(ue_id, &params);
     OAILOG_FUNC_RETURN(LOG_NAS_AMF, rc);
   } else {
-    OAILOG_ERROR(LOG_NAS_AMF, "Error: amf_ctx does not exits");
+    OAILOG_ERROR(LOG_NAS_AMF,
+                 "Error: amf_ctx does not exits, ue_id: " AMF_UE_NGAP_ID_FMT
+                 "\n",
+                 ue_id);
```
Comment (pruthvihebbani) [inline lte/gateway/c/core/oai/tasks/amf/amf_cn.cpp:99]: Directly return RETURNerror at 101 instead of assigning it to rc

**Review by pruthvihebbani — CHANGES_REQUESTED** [review]

File: lte/gateway/c/core/oai/test/amf/amf_app_test_util.cpp (hunk 2 above)
Comment (Akshayp77) [reply lte/gateway/c/core/oai/test/amf/amf_app_test_util.cpp:650]: "lte/gateway/c/core/oai/test/amf/amf_app_test_util.cpp" this file is part of unit test framework and logging functionalities are not available while running the 5G unit test framework.

File: lte/gateway/c/core/oai/test/amf/amf_app_test_util.cpp (hunk 3 above)
Comment (Akshayp77) [reply lte/gateway/c/core/oai/test/amf/amf_app_test_util.cpp:663]: "lte/gateway/c/core/oai/test/amf/amf_app_test_util.cpp" this file is part of unit test framework and logging functionalities are not available while running the 5G unit test framework.

**Review by pruthvihebbani — APPROVED** [review]

File: lte/gateway/c/core/oai/test/amf/amf_app_test_util.cpp (hunk 2 above)
Comment (panyogesh) [reply lte/gateway/c/core/oai/test/amf/amf_app_test_util.cpp:650]: @Akshayp77 : Can you please check "mme_app_task/mme_app_test.cpp" -> OAILOG_INIT. If it helps in any ways.

Comment (Akshayp77) [reply lte/gateway/c/core/oai/test/amf/amf_app_test_util.cpp:650]: Error logs are added.

**Comment by panyogesh** [comment]
LGTM
