### PR TITLE
fix(amf): fix for test_amf_stateless in Bazel test

### LINKED ISSUE #12163: Fix //lte/gateway/c/core/oai/test/amf:amf_encode_decode_test with --config=asan
The target is added by this PR https://github.com/magma/magma/pull/12162

## Reproduce error
After the PR above has merged, run `bazel test //lte/gateway/c/core/oai/test/amf:amf_encode_decode_test --config=asan
`.
This should result in an output similar to
```bash
[ RUN      ] test_amf_nas5g_pkt_process.test_amf_service_request_messagetype_data
=================================================================
==31798==ERROR: AddressSanitizer: global-buffer-overflow on address 0x555944788325 at pc 0x7f519c217625 bp 0x7ffe1cc63250 sp 0x7ffe1cc63240
READ of size 1 at 0x555944788325 thread T0
    #0 0x7f519c217624 in magma5g::ServiceRequestMsg::DecodeServiceRequestMsg(magma5g::ServiceRequestMsg*, unsigned char*, unsigned int) lte/gateway/c/core/oai/tasks/nas5g/src/M5GServiceRequest.cpp:83
    #1 0x7f519c217943 in magma5g::ServiceRequestMsg::DecodeServiceRequestMsg(magma5g::ServiceRequestMsg*, unsigned char*, unsigned int) lte/gateway/c/core/oai/tasks/nas5g/src/M5GServiceRequest.cpp:105
    #2 0x7f519e7c02df in magma5g::decode_service_request_msg(magma5g::ServiceRequestMsg*, unsigned char const*, unsigned int) lte/gateway/c/core/oai/test/amf/util_nas5g_service_request_pkt.cpp:26
    #3 0x5559444e2e21 in magma5g::test_amf_nas5g_pkt_process_test_amf_service_request_messagetype_data_Test::TestBody() lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp:473
    #4 0x7f51944b8de1 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) external/com_google_googletest/googletest/src/gtest.cc:2439
    #5 0x7f51944b3c30 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) external/com_google_googletest/googletest/src/gtest.cc:2475
    #6 0x7f519449cbb3 in testing::Test::Run() external/com_google_googletest/googletest/src/gtest.cc:2514
    #7 0x7f519449d578 in testing::TestInfo::Run() external/com_google_googletest/googletest/src/gtest.cc:2690
    #8 0x7f519449dc94 in testing::TestSuite::Run() external/com_google_googletest/googletest/src/gtest.cc:2822
    #9 0x7f51944a9c30 in testing::internal::UnitTestImpl::RunAllTests() external/com_google_googletest/googletest/src/gtest.cc:5342
    #10 0x7f51944ba0f1 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) external/com_google_googletest/googletest/src/gtest.cc:2439
    #11 0x7f51944b4d50 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) external/com_google_googletest/googletest/src/gtest.cc:2475
    #12 0x7f51944a84ee in testing::UnitTest::Run() external/com_google_googletest/googletest/src/gtest.cc:4930
    #13 0x7f5194504b07 in RUN_ALL_TESTS() external/com_google_googletest/googletest/include/gtest/gtest.h:2472
    #14 0x7f5194504a89 in main external/com_google_googletest/googlemock/src/gmock_main.cc:63
    #15 0x7f51930230b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x240b2)
    #16 0x5559444d52ed in _start (/tmp/bazel/execroot/__main__/bazel-out/k8-dbg/bin/lte/gateway/c/core/oai/test/amf/amf_encode_decode+0x21e2ed)

0x555944788325 is located 0 bytes to the right of global variable 'service_request' defined in 'lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp:106:9' (0x555944788300) of size 37
0x555944788325 is located 59 bytes to the left of global variable 'service_req_signaling' defined in 'lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp:113:9' (0x555944788360) of size 13
SUMMARY: AddressSanitizer: global-buffer-overflow lte/gateway/c/core/oai/tasks/nas5g/src/M5GServiceRequest.cpp:83 in magma5g::ServiceRequestMsg::DecodeServiceRequestMsg(magma5g::ServiceRequestMsg*, unsigned char*, unsigned int)
Shadow bytes around the buggy address:
  0x0aaba88e9010: 00 00 00 00 00 00 00 00 00 00 00 03 f9 f9 f9 f9
  0x0aaba88e9020: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0aaba88e9030: 03 f9 f9 f9 f9 f9 f9 f9 00 00 00 00 00 07 f9 f9
  0x0aaba88e9040: f9 f9 f9 f9 00 00 00 00 02 f9 f9 f9 f9 f9 f9 f9
  0x0aaba88e9050: 00 04 f9 f9 f9 f9 f9 f9 00 00 01 f9 f9 f9 f9 f9
=>0x0aaba88e9060: 00 00 00 00[05]f9 f9 f9 f9 f9 f9 f9 00 05 f9 f9
  0x0aaba88e9070: f9 f9 f9 f9 00 00 01 f9 f9 f9 f9 f9 04 f9 f9 f9
  0x0aaba88e9080: f9 f9 f9 f9 00 00 00 00 00 00 00 00 01 f9 f9 f9
  0x0aaba88e9090: f9 f9 f9 f9 00 00 00 00 01 f9 f9 f9 f9 f9 f9 f9
  0x0aaba88e90a0: 06 f9 f9 f9 f9 f9 f9 f9 00 01 f9 f9 f9 f9 f9 f9
  0x0aaba88e90b0: 00 00 00 02 f9 f9 f9 f9 00 00 03 f9 f9 f9 f9 f9
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==31798==ABORTING
================================================================================
Target //lte/gateway/c/core/oai/test/amf:amf_encode_decode up-to-date:
  bazel-bin/lte/gateway/c/core/oai/test/amf/amf_encode_decode
INFO: Elapsed time: 13.073s, Critical Path: 11.60s
INFO: 8 processes: 4 internal, 4 processwrapper-sandbox.
INFO: Build completed, 1 test FAILED, 8 total actions
```

## Exit Criteria
The following commands should pass
```bash
bazel test //lte/gateway/c/core/oai/test/amf:amf_encode_decode --config=asan
# To test for flakiness, you can run
bazel test //lte/gateway/c/core/oai/test/amf:amf_encode_decode --config=asan --runs_per_test=100
```

Once they are passing, you can remove the line `tags = ["manual"],` from the corresponding BUILD target.

### PR DESCRIPTION
**Pull request by shashidhar-patil**
Signed-off-by: shashidhar-patil <shashidhar.patil@wavelabs.ai>

## Summary
Fixes the following issues :
1)  heap-use-after-free in the test_amf_stateless UT. 
     Issue #11826 
2)  Fixing the above led to heap-buffer-overflow at `DecodeServiceRequestMsg`. The NasContainer was not being decoded in the right way. Fixed by `len - (decoded + 3)`. Issue #12144

## Test Plan

- Bazel testing using (@electronjoe repo)   [Updated: 16/03/2022]
bazel_test

- Validated with Unit test  [Updated: 16/03/2022]
bazel_oai_test

- Verified basic sanity with UERANSIM
   PCAP Snap shot: [Updated: 16/03/2022]
bazel_pcap

   mme log: [Updated: 16/03/2022]
[mme.log](https://github.com/magma/magma/files/8260152/mme.log)

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Comment by electronjoe** [comment]
Didn't see in PR Description but I think this addresses #11826. Thanks for the fix!

**Comment by ulaskozat** [comment]
@shashidhar-patil why is this changed to draft?

**Comment by shashidhar-patil** [comment]
Hi @electronjoe and @ulaskozat, the changes are still in progress, so it is converted into a draft.

**Comment by electronjoe** [comment]
Good afternoon @shashidhar-patil!

Just in case you rebase on master - I wanted to warn you that this Bazel test target has been split into two test targets now (so that they can run concurrently / one can run smaller test targets if desired).

Your changes here can now be tested on Master branch from GH CodeSpaces (or local devcontainer) by:

```
bazel test //lte/gateway/c/core/oai/test/amf:amf_stateless_test --config=asan
bazel test //lte/gateway/c/core/oai/test/amf:amf_procedures_test --config=asan
```

I modified your PR description to include #12144 - hope you don't mind!

**Comment by shashidhar-patil** [comment]
Good afternoon @electronjoe.
Yes noted and tried it out. Thank you!

bazel_stateless

bazel_procedures

**Review by ganeshg87 — APPROVED** [review]

**Review by ganeshg87 — APPROVED** [review]
lgtm

File: lte/gateway/c/core/oai/test/amf/test_amf_stateless.cpp [hunk 1]
```diff
@@ -1034,13 +1024,8 @@ TEST_F(AMFAppStatelessTest, TestAfterPDUSessionReleaseComplete) {
...
   AMFAppStatelessTest::pseudo_amf_restart();
-
-  EXPECT_TRUE(amf_state_ue_id_ht->isEmpty());
-  EXPECT_TRUE(
-      amf_app_desc_p->amf_ue_contexts.gnb_ue_ngap_id_ue_context_htbl.isEmpty());
-  EXPECT_TRUE(amf_app_desc_p->amf_ue_contexts.imsi_amf_ue_id_htbl.isEmpty());
-  EXPECT_TRUE(amf_app_desc_p->amf_ue_contexts.tun11_ue_context_htbl.isEmpty());
-  EXPECT_TRUE(amf_app_desc_p->amf_ue_contexts.guti_ue_context_htbl.isEmpty());
+  EXPECT_TRUE(AmfNasStateManager::getInstance().get_ue_state_map()->isEmpty());
+  EXPECT_EQ(get_amf_nas_state(false), nullptr);
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/test/amf/test_amf_stateless.cpp:1031]: @shashidhar-patil , is this to confirm that no state exists in the Redis DB after restart? Could you please add a comment here to explain this?

**Review by ssanadhya — CHANGES_REQUESTED** [review]

File: lte/gateway/c/core/oai/test/amf/test_amf_stateless.cpp (hunk 1 above)
Comment (shashidhar-patil) [reply lte/gateway/c/core/oai/test/amf/test_amf_stateless.cpp:1031]: This checks if the state data in Amf is cleared after pseudo_amf_restart(). Added this comment.

 Also renamed `pseudo_amf_restart()` to `pseudo_amf_stop()` , as this is a more appropriate name. Calling `pseudo_amf_stop()` and `SetUp()` simulates a service restart.

Comment (ssanadhya) [reply lte/gateway/c/core/oai/test/amf/test_amf_stateless.cpp:1031]: Thanks for the cleanup!

**Review by ssanadhya — APPROVED** [review]
LGTM
