### PR TITLE
[Orc8r] Fix the subscriber policy setting bug 

### LINKED ISSUE #4473: LTE policy configuration discrepancy
### Your Environment

- **Version:** staging
- **Affected Component:** Orchestrator,  NMS
- **Affected Subcomponent:** Orchestrator 
- **Deployment Environment:** stagging

### Describe the Issue

**To Reproduce**
1. Go to 'subscriber configuration for adding policy
2. Click on 'add policy and save'
3. check active policy which is empty.

**Expected behavior**
New policy should be listed in the active policies

**Additional context**
Post  call:
```
{
   "active_apns":[
      "multi.ipv4",
      "oai.ipv4"
   ],
   "id":"IMSI001010000091190",
   "lte":{
      "auth_algo":"MILENAGE",
      "auth_key":"i69HPy+P0JSHzMvXCXxoYg==",
      "state":"ACTIVE",
      "sub_profile":"default"
   },
   "monitoring":{
      
   },
   "name":"ens_1190",
   "state":{
      "directory":{
         "location_history":[
            "4f254d8f-ca00-448a-851a-3ccf026e5bdf"
         ]
      },
      "subscriber_state":{
         "oai.ipv4":[
            {
               "active_duration_sec":6224,
               "active_policy_rules":[
                  "{\"id\":\"allowlist_sid-IMSI001010000091190-oai.ipv4\",\"priority\":2,\"flowList\":[{\"match\":{}},{\"match\":{\"direction\":\"DOWNLINK\"}}],\"trackingType\":\"NO_TRACKING\"}"
               ],
               "apn":"oai.ipv4",
               "ipv4":"10.252.1.87",
               "lifecycle_state":"SESSION_ACTIVE",
               "msisdn":"",
               "session_id":"IMSI001010000091190-629273",
               "session_start_time":1611192039
            }
         ]
      }
   },
   "active_policies":[
      "test"
   ],
   "static_ips":{
      
   }
}
```

GET:
```
{
   "active_apns":[
      "multi.ipv4",
      "oai.ipv4"
   ],
   "config":{
      "lte":{
         "auth_algo":"MILENAGE",
         "auth_key":"i69HPy+P0JSHzMvXCXxoYg==",
         "state":"ACTIVE",
         "sub_profile":"default"
      }
   },
   "id":"IMSI001010000091190",
   "lte":{
      "auth_algo":"MILENAGE",
      "auth_key":"i69HPy+P0JSHzMvXCXxoYg==",
      "state":"ACTIVE",
      "sub_profile":"default"
   },
   "monitoring":{
      
   },
   "name":"ens_1190",
   "state":{
      "directory":{
         "location_history":[
            "4f254d8f-ca00-448a-851a-3ccf026e5bdf"
         ]
      },
      "subscriber_state":{
         "oai.ipv4":[
            {
               "active_duration_sec":6285,
               "active_policy_rules":[
                  "{\"id\":\"allowlist_sid-IMSI001010000091190-oai.ipv4\",\"priority\":2,\"flowList\":[{\"match\":{}},{\"match\":{\"direction\":\"DOWNLINK\"}}],\"trackingType\":\"NO_TRACKING\"}"
               ],
               "apn":"oai.ipv4",
               "ipv4":"10.252.1.87",
               "lifecycle_state":"SESSION_ACTIVE",
               "msisdn":"",
               "session_id":"IMSI001010000091190-629273",
               "session_start_time":1611192039
            }
         ]
      }
   }
}

```
GET response is missing policy.

### PR DESCRIPTION
**Pull request by karthiksubraveti**
Signed-off-by: Karthik Subraveti <ksubraveti@fb.com>

## Summary

Subscriber specific attributes active_policies and active_basenames aren't handled at all in the current orc8r code.
This patch fixes this bug and adds a regression test for verifying the change. 

## Test Plan
Enhanced the handler_test for verifying this fix.

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

File: lte/cloud/go/services/subscriberdb/obsidian/models/conversion.go [hunk 1]
```diff
@@ -170,6 +178,12 @@ func (m *MutableSubscriber) GetAssocs() []storage.TypeAndKey {
 	var assocs []storage.TypeAndKey
 	assocs = append(assocs, m.ActivePoliciesByApn.ToTKs(string(m.ID))...)
 	assocs = append(assocs, m.ActiveApns.ToTKs()...)
+	for _, policyID := range m.ActivePolicies {
```
Comment (hcgatewood) [inline lte/cloud/go/services/subscriberdb/obsidian/models/conversion.go]: Here and below: add a `ToTKs` method for the respective types, rather than explicitly constructing the slice here

File: lte/cloud/go/services/subscriberdb/obsidian/models/conversion.go [hunk 2]
```diff
@@ -150,6 +150,14 @@ func (m *MutableSubscriber) FromEnt(ent configurator.NetworkEntity, policyProfil
 		model.ActiveApns = append(model.ActiveApns, tk.Key)
 	}
 
+	for _, tk := range ent.Associations.Filter(lte.PolicyRuleEntityType) {
+		model.ActivePolicies = append(model.ActivePolicies, policymodels.PolicyID(tk.Key))
+	}
+
```
Comment (hcgatewood) [inline lte/cloud/go/services/subscriberdb/obsidian/models/conversion.go:156]: Nit: since these 3 for loops are related, remove the newlines between them

File: lte/cloud/go/services/subscriberdb/obsidian/handlers/handlers_test.go [hunk 3]
```diff
@@ -1656,6 +1656,227 @@ func TestUpdateSubscriberProfile(t *testing.T) {
...
+	urlManage := urlBase + "/:subscriber_id"
+	subscriberdbHandlers := handlers.GetHandlers()
+	getAllSubscribers := tests.GetHandlerByPathAndMethod(t, subscriberdbHandlers, urlBase, obsidian.GET).HandlerFunc
+	postSubscriber := tests.GetHandlerByPathAndMethod(t, subscriberdbHandlers, urlBase, obsidian.POST).HandlerFunc
+	putSubscriber := tests.GetHandlerByPathAndMethod(t, subscriberdbHandlers, urlManage, obsidian.PUT).HandlerFunc
+
+	imsi := "IMSI1234567890"
+	mutableSub := newMutableSubscriber(imsi)
+
+	// post a policy association with a non existent policy
```
Comment (hcgatewood) [inline lte/cloud/go/services/subscriberdb/obsidian/handlers/handlers_test.go]: Nit: here and below, start comments with capital letter

File: lte/cloud/go/services/subscriberdb/obsidian/handlers/handlers_test.go [hunk 4]
```diff
@@ -1656,6 +1656,227 @@ func TestUpdateSubscriberProfile(t *testing.T) {
...
+	// successful put request
+	mutableSub.ActiveBaseNames = policydbModels.BaseNames{"basename2"}
+	tc = tests.Test{
+		Method:         "PUT",
+		URL:            "/magma/v1/lte/n0/subscribers/" + imsi,
+		Payload:        mutableSub,
+		ParamNames:     []string{"network_id", "subscriber_id"},
+		ParamValues:    []string{"n0", imsi},
+		Handler:        putSubscriber,
+		ExpectedStatus: 204, // would make more sense as 400
```
Comment (hcgatewood) [inline lte/cloud/go/services/subscriberdb/obsidian/handlers/handlers_test.go]: This comment is not accurate

File: lte/cloud/go/services/subscriberdb/obsidian/handlers/handlers_test.go [hunk 5]
```diff
@@ -1656,6 +1656,227 @@ func TestUpdateSubscriberProfile(t *testing.T) {
...
+	// successful put requrst
+	mutableSub.ActivePolicies = policydbModels.PolicyIds{"rule2"}
+	tc = tests.Test{
+		Method:         "PUT",
+		URL:            "/magma/v1/lte/n0/subscribers/" + imsi,
+		Payload:        mutableSub,
+		ParamNames:     []string{"network_id", "subscriber_id"},
+		ParamValues:    []string{"n0", imsi},
+		Handler:        putSubscriber,
+		ExpectedStatus: 204, // would make more sense as 400
```
Comment (hcgatewood) [inline lte/cloud/go/services/subscriberdb/obsidian/handlers/handlers_test.go]: Same as above -- inaccurate comment

**Review by hcgatewood — APPROVED** [review]
Couple small things, otherwise lgtm. Thanks for adding this Karthik!

File: lte/cloud/go/services/subscriberdb/obsidian/handlers/handlers_test.go [hunk 6]
```diff
@@ -1656,6 +1656,227 @@ func TestUpdateSubscriberProfile(t *testing.T) {
...
+	tc = tests.Test{
+		Method:         "GET",
+		URL:            "/magma/v1/lte/n0/subscribers",
+		Handler:        getAllSubscribers,
+		ParamNames:     []string{"network_id"},
+		ParamValues:    []string{"n0"},
+		ExpectedStatus: 200,
+		ExpectedResult: tests.JSONMarshaler(map[string]*subscriberModels.Subscriber{imsi: mutableSub.ToSubscriber()}),
+	}
+	tests.RunUnitTest(t, e, tc)
```
Comment (pshelar) [inline lte/cloud/go/services/subscriberdb/obsidian/handlers/handlers_test.go:1877]: Can you also add test case for ActivePoliciesByApn.

**Comment by rdefosse** [comment]
Can one of the admins verify this patch?

File: lte/cloud/go/services/subscriberdb/obsidian/handlers/handlers_test.go (hunk 6 above)
Comment (karthiksubraveti) [reply lte/cloud/go/services/subscriberdb/obsidian/handlers/handlers_test.go:1877]: Tests for ActivePoliciesByApn already exists today.
