### PR TITLE
[SessionD] Address some clang-tidy warnings

### LINKED ISSUE #5310: [AGW] Address any pertinent Clang-Tidy findings in lte/gateway/c/session_manager
Description of [Clang-Tidy Checks](https://clang.llvm.org/extra/clang-tidy/checks/list.html)

We will be working to get Continuous Integration Clang-Tidy analysis running, aggregating counts by check type and supporting telemetry over time. But until then, here are early findings for early investigation / combing through any alarming findings.

Unfortunately it's not possible to negative-filter files to be analyzed with clang-tidy (It does not support "file does not contain pb.h") due to the regex library used. Longstanding issue. So the below include pb.h / pb.cc compiled protoc results (which do have warnings in them).

Summary of findings for MME on Magma @ [6c13c49](https://github.com/magma/magma/commit/9cc4be1e362e4cd0171be2bfcb47a054d6c13c49)

```shell
root@ecee08edef4b:/magma/lte/gateway/c/session_manager/build# cat clang.findings | egrep "android|bugprone|cert|clang|concurrency|misc" | awk -F'[][]
' '{print $2}' | sort | uniq -c
    268 
      1 bugprone-branch-clone
      1 bugprone-exception-escape
     45 bugprone-narrowing-conversions
     26 bugprone-sizeof-expression
     52 cert-err58-cpp
      1 cert-msc30-c,cert-msc50-cpp
      1 cert-msc32-c,cert-msc51-cpp
     10 clang-analyzer-core.CallAndMessage
      1 clang-analyzer-unix.MismatchedDeallocator
      3 misc-unused-using-decls
```

Gist [Here](https://gist.github.com/electronjoe/fc30ee558945e4d0c9906ced990a98b1) gives full Clang-Tidy log output.

### PR DESCRIPTION
**Pull request by themarwhal**
Signed-off-by: Marie Bremner <marwhal@fb.com>

## Summary
This PR addresses several clang-tidy warning. I'll list them out at the bottom.

## Test Plan
Run unit tests + s1ap tests

## Clang-tidy warnings
These two below are very straightforward, with unused namespaces.
```
/magma/lte/gateway/c/session_manager/SessionManagerServer.cpp:17:13: warning: using decl 'ServerContext' is unused [misc-unused-using-decls]
using grpc::ServerContext;
```
```
/magma/lte/gateway/c/session_manager/RuleStore.cpp:18:13: warning: using decl 'Status' is unused [misc-unused-using-decls]
using grpc::Status;
            ^
/magma/lte/gateway/c/session_manager/RuleStore.cpp:18:13: note: remove the using
using grpc::Status;
~~~~~~~~~~~~^~~~~~~
```
C++ oopsies
```
/magma/lte/gateway/c/session_manager/sessiond_main.cpp:418:3: warning: Memory allocated by 'new' should be deallocated by 'delete', not free() [clang-analyzer-unix.MismatchedDeallocator]
  free(session_store);
```
Apparently using `rand()` is a big NO NO. Fun talk about it here: https://channel9.msdn.com/Events/GoingNative/2013/rand-Considered-Harmful
```
/magma/lte/gateway/c/session_manager/SessionID.cpp:21:3: warning: random number generator seeded with a disallowed source of seed value will generate a predictable sequence of values [cert-msc32-c,cert-msc51-cpp]
  srand(time(NULL));
  ^
/magma/lte/gateway/c/session_manager/SessionID.cpp:26:38: warning: rand() has limited randomness; use C++11 random library instead [cert-msc30-c,cert-msc50-cpp]
  return imsi + "-" + std::to_string(rand() % 1000000);
                                     ^
```

### CODE REVIEW

File: lte/gateway/c/session_manager/RedisStoreClient.cpp [hunk 1]
```diff
@@ -67,13 +67,12 @@ SessionMap RedisStoreClient::read_sessions(
...
-      // value just doesn't exist
-      session_map[key] = SessionVector{};
-    } else if (reply.is_error()) {
+    if (reply.is_error()) {
       MLOG(MERROR) << "RedisStoreClient: Unable to get value for key " << key;
       throw RedisReadFailed();
-    } else if (!reply.is_string()) {
+    }
+    if (reply.is_null() || !reply.is_string()) {
+      // value just doesn't exist
```
Comment (uri200) [inline lte/gateway/c/session_manager/RedisStoreClient.cpp:75]: was this also caught by clang tidy?

**Review by uri200 — APPROVED** [review]
I did watch the video. Thanks for sharing!
