### PR TITLE
fix(amf): support nssai, dnn parameters in PDU Session Establishment

### LINKED ISSUE #6513: Handle DNN IE on the uplink PDU session establishment request from UE

### PR DESCRIPTION
**Pull request by sreedharkumartn**
Signed-off-by: sreedharkumartn <sreedhar.kumar@wavelabs.ai>

## Summary
- DNN optional IE support in PDU Session Establishment Accept.
- NSSAI optional IE support in PDU Session Establishment Accept.

## Test Plan
- Verified UT cases.
- Verified NSSAI and DNN parameters in PDU Session Establishment Accept using UERANSIM.
- Please find the attached mme log and Pcap snap.

mme logs:
[mme_Nssai.log](https://github.com/magma/magma/files/7520188/mme_Nssai.log)

Pcap Snap:
DNN and S-NSSAI

S-NSSAI:
S - NSSAI

DNN:
DNN

UT Test cases compiled:
UT test

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

File: lte/gateway/c/core/oai/tasks/amf/amf_as.cpp [hunk 1]
```diff
@@ -477,13 +477,15 @@ int amf_reg_acceptmsg(const guti_m5_t* guti, amf_nas_message_t* nas_msg) {
...
-  nas_msg->security_protected.plain.amf.msg.registrationacceptmsg.nssai
-      .nssaival[1] = 0x01;
+  nas_msg->security_protected.plain.amf.msg.registrationacceptmsg.allowed_nssai
+      .iei = ALLOWED_NSSAI;
+  nas_msg->security_protected.plain.amf.msg.registrationacceptmsg.allowed_nssai
+      .len = 2;
+  nas_msg->security_protected.plain.amf.msg.registrationacceptmsg.allowed_nssai
+      .nssai.len = 1;
+  nas_msg->security_protected.plain.amf.msg.registrationacceptmsg.allowed_nssai
+      .nssai.sst = 0x01;
```
Comment (ulaskozat) [inline lte/gateway/c/core/oai/tasks/amf/amf_as.cpp:487]: why is this hardcoded?

Comment (sreedharkumartn) [reply lte/gateway/c/core/oai/tasks/amf/amf_as.cpp:487]: 1. we have added a fix in the S-NSSAI structure as per spec to support PDU Session Establishment Request/Accept.
2. but RegistrationAccept msg is also using the same S-NSSAI(NSSAIMsg) structure for "Allowed S-NSSAI", it was wrong.
to Support "Allowed S-NSSAI"(list of S-NSSAIs), defined a new Structure(NSSAIMsgList), and replaced the same code.

I agree to replace hardcoded values with configured values defined from amfconfig/MACRO.
configured S-NSSAI is a list under plmn_support_list,
we need to add logic to update "Allowed-S-NSSAI" in Registration Accept msg.
this fix we will include as part of slicing feature implementation, this PR is to support in PDU Session.

**Review by ulaskozat — APPROVED** [review]
LGTM
