### PR TITLE
Move access of MME_APP stats into the MME_APP thread

### LINKED ISSUE #7421: magma::lte::MmeNasStateManager::get_state
Hitting assert fatal: AssertFatal(state_cache_p, "mme_nas_state is NULL");

Sentry Issue: [LAB-AGWS-NATIVE-N](https://sentry.io/organizations/lf-9c/issues/2444965165/?referrer=github_integration)

```
SIGILL / ILL_ILLOPN: Fatal Error: SIGILL / ILL_ILLOPN
  File "mme_app_state_manager.cpp", line 90, in magma::lte::MmeNasStateManager::get_state
  File "mme_app_state.cpp", line 41, in get_mme_nas_state
  File "service303_mme_stats.c", line 26, in service303_mme_statistics_read
  File "service303_mme_stats.c", line 34, in service303_statistics_read
  File "service303_task.c", line 76, in handle_timer
...
(4 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by amarpad**
## Summary
Currently service303 reaches across service boundaries to read
mme_app state. Fix this by pushing the stats over an ITTI message
Also remove the check for MME service as the timer is not started
in the SPGW context (as it is only run in the MME_APP)

Also may close #7421 where the nas datastructure is null as there is probably
races with clearing out the state_p.

Signed-off-by: Amar Padmanabhan <amar@freedomfi.com>

## Test Plan

- Ran test_attach_detach.py
- Added logs to verify the timer was getting fired and the service303_mme_statistics_read

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

File: lte/gateway/c/core/oai/include/service303_messages_types.h [hunk 1]
```diff
@@ -33,4 +33,11 @@ typedef struct application_unhealthy_msg {
   uint8_t unused;
 } application_unhealthy_msg_t;
 
+// Message capturing stats as communicated by the mme_app
+typedef struct application_stats_msg {
```
Comment (ardzoht) [inline lte/gateway/c/core/oai/include/service303_messages_types.h]: how about naming this `application_mme_stats_msg`?

**Review by ardzoht — APPROVED** [review]
one nit about itti msg naming, overall lgtm

File: lte/gateway/c/core/oai/include/service303_messages_types.h (hunk 1 above)
Comment (amarpad) [reply lte/gateway/c/core/oai/include/service303_messages_types.h]: will do.

**Comment by rdefosse** [comment]
@amarpad 

Why did you merge?

Your pull request was not passing the OAI pipeline.

Is it possible to revert?

Regards
Raphael

**Comment by rdefosse** [comment]
@amarpad 

you ran 3 times the OAI CI pipleine and it failed 3 times at the test stages.

I did not look at all 3 runs but on the last run on both `Ubuntu-18` and `RHEL8` tests the MME asserts at the beginning:

```bash
oai_mme: src/zloop.c:548: zloop_timer: Assertion `self' failed.
```

Regards
Raphael

**Comment by amarpad** [comment]
I set it as merge on success, and so it auto commits. I assume the test is not a block. I will run the test and validate.

**Comment by rdefosse** [comment]
@amarpad 

I like automation, but you don't even give us the time to review (even if we are not the assigned reviewer).

Tim will make the OAI pipeline `required`.

Raphael

**Comment by amarpad** [comment]
@rdefosse can you post the log file somewhere or core? I am still not able to figure out how to run this.
