### PR TITLE
[feg] fixed testGxUsageMonitoring

### LINKED ISSUE #3314: [teravm][feg] fix TestGxUsageMonitoring
This test was disabled (probably because it was flaky)
But disabling it meant that we were not covered for any change on usage monitoring done at feg.

We need to add it back cover that part. That may need some debugging since the code has changed since it was disabled

### LINKED ISSUE #3337: testGxUsageMonitoring failing on ci

### PR DESCRIPTION
**Pull request by uri200**
Signed-off-by: Oriol Batalla <obatalla@fb.com>

## Summary

For some reason `testGxUsageMonitoring` was disabled. 

Once enabled, we observed the test was flaky and failing in some runs without apparent reason. After deep investigation, we found the timeout value was set to 1 millisecond. That caused the client to timeout in some occasions.

Also, after fixing the issue we found the test case was outdated. So we also had to update the test to include the latest modifications on monitoring.

## Test Plan

make precommit

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

File: feg/gateway/services/session_proxy/servicers/session_controller_test.go [hunk 1]
```diff
@@ -1242,7 +1248,7 @@ func getTestConfig() []*servicers.SessionControllerConfig {
 				Addr:     fmt.Sprintf("127.0.0.1:%s", pcrf_port),
 				Protocol: "tcp"},
 			},
-			RequestTimeout: time.Millisecond,
```
Comment (uri200) [inline feg/gateway/services/session_proxy/servicers/session_controller_test.go:1245]: the bug

**Review by themarwhal — APPROVED** [review]
