### PR TITLE
[cwf_integ_test] add iperf server restart function to uesim

### LINKED ISSUE #3060: gy_enforcement_test test flaky
```[magma@10.240.0.49] out: [vagrant@127.0.0.1:2201] out: Running TestGyCreditExhaustionWithCRRU...
[magma@10.240.0.49] out: [vagrant@127.0.0.1:2201] out: ************************* TestRunner setup
[magma@10.240.0.49] out: [vagrant@127.0.0.1:2201] out: Adding Mock HSS service at 192.168.70.101:9204
[magma@10.240.0.49] out: [vagrant@127.0.0.1:2201] out: Adding Mock PCRF service at 192.168.70.101:9202
[magma@10.240.0.49] out: [vagrant@127.0.0.1:2201] out: Adding Mock OCS service at 192.168.70.101:9201
[magma@10.240.0.49] out: [vagrant@127.0.0.1:2201] out: Adding Pipelined service at 192.168.70.101:8443
[magma@10.240.0.49] out: [vagrant@127.0.0.1:2201] out: Adding Redis service at 192.168.70.101:6380
[magma@10.240.0.49] out: [vagrant@127.0.0.1:2201] out: Adding Directoryd service at 192.168.70.101:8443
[magma@10.240.0.49] out: [vagrant@127.0.0.1:2201] out: ************************* Configuring 1 UE(s), PCRF instance: PCRF_REMOTE
[magma@10.240.0.49] out: [vagrant@127.0.0.1:2201] out: Added UE to Simulator, HSS_REMOTE, PCRF_REMOTE, and OCS_REMOTE:
[magma@10.240.0.49] out: [vagrant@127.0.0.1:2201] out: 	IMSI: 194903515200125	Key: d6d0913a0710c2838b7f6e6da88ebc58	Opc: f95144ca2abbf6f9c30cb20af6352fd6	Seq: 5823533353273
[magma@10.240.0.49] out: [vagrant@127.0.0.1:2201] out: Successfully configured UE(s)
[magma@10.240.0.49] out: [vagrant@127.0.0.1:2201] out: ************************* Adding PCRF Usage Monitor for UE with IMSI: 194903515200125
[magma@10.240.0.49] out: [vagrant@127.0.0.1:2201] out: ************************* Adding a Pass-All static rule: static-pass-all-ocs1
[magma@10.240.0.49] out: [vagrant@127.0.0.1:2201] out: ************************* Adding a Pass-All static rule: static-pass-all-ocs2
[magma@10.240.0.49] out: [vagrant@127.0.0.1:2201] out: ************************* Adding PCRF Rule for UE with IMSI: 194903515200125 with ruleNames=[static-pass-all-ocs1 static-pass-all-ocs2], baseNames=[]
[magma@10.240.0.49] out: [vagrant@127.0.0.1:2201] out: ************************* Authenticating UE with IMSI: 194903515200125
[magma@10.240.0.49] out: [vagrant@127.0.0.1:2201] out: Finished Authenticating UE
[magma@10.240.0.49] out: [vagrant@127.0.0.1:2201] out: ************************* Generating Traffic for UE with Req: imsi:"194903515200125" volume:<value:"4.5M" > 
[magma@10.240.0.49] out: [vagrant@127.0.0.1:2201] out: Record sid:"IMSI194903515200125" rule_id:"static-pass-all-ocs1" 
[magma@10.240.0.49] out: [vagrant@127.0.0.1:2201] out: Record sid:"IMSI194903515200125" rule_id:"static-pass-all-ocs2" bytes_tx:4121125 bytes_rx:66709 
[magma@10.240.0.49] out: [vagrant@127.0.0.1:2201] out: Asserting all Gy expectations were met...
[magma@10.240.0.49] out: [vagrant@127.0.0.1:2201] out: Passed!
[magma@10.240.0.49] out: [vagrant@127.0.0.1:2201] out: ************************* Generating Traffic for UE with Req: imsi:"194903515200125" volume:<value:"10M" > 
[magma@10.240.0.49] out: [vagrant@127.0.0.1:2201] out: Record sid:"IMSI194903515200125" rule_id:"static-pass-all-ocs1" 
[magma@10.240.0.49] out: [vagrant@127.0.0.1:2201] out: Record sid:"IMSI194903515200125" rule_id:"static-pass-all-ocs2" bytes_tx:14105898 bytes_rx:137224 
[magma@10.240.0.49] out: [vagrant@127.0.0.1:2201] out: Asserting all Gy expectations were met...
[magma@10.240.0.49] out: [vagrant@127.0.0.1:2201] out: Passed!
[magma@10.240.0.49] out: [vagrant@127.0.0.1:2201] out:     assertions.go:134: 
[magma@10.240.0.49] out: [vagrant@127.0.0.1:2201] out:         	Error Trace:	assertions.go:134
[magma@10.240.0.49] out: [vagrant@127.0.0.1:2201] out:         	            				assertions.go:127
[magma@10.240.0.49] out: [vagrant@127.0.0.1:2201] out:         	            				gy_enforcement_test.go:175
[magma@10.240.0.49] out: [vagrant@127.0.0.1:2201] out:         	Error:      	element expectation_index:1 expectation_met:true  appears more times in [expectation_met:true  expectation_index:1 expectation_met:true ] than in [expectation_met:true  expectation_index:1 ]
[magma@10.240.0.49] out: [vagrant@127.0.0.1:2201] out:         	Test:       	TestGyCreditExhaustionWithCRRU
[magma@10.240.0.49] out: [vagrant@127.0.0.1:2201] out:     assertions.go:136: []
[magma@10.240.0.49] out: [vagrant@127.0.0.1:2201] out:     gy_enforcement_test.go:197: 
[magma@10.240.0.49] out: [vagrant@127.0.0.1:2201] out:         	Error Trace:	gy_enforcement_test.go:197
[magma@10.240.0.49] out: [vagrant@127.0.0.1:2201] out:         	Error:      	Expected nil, but got: &protos.RuleRecord{Sid:"IMSI194903515200125", RuleId:"static-pass-all-ocs2", BytesTx:0xd73d2a, BytesRx:0x21808, UeIpv4:"", XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}
[magma@10.240.0.49] out: [vagrant@127.0.0.1:2201] out:         	Test:       	TestGyCreditExhaustionWithCRRU
[magma@10.240.0.49] out: [vagrant@127.0.0.1:2201] out:         	Messages:   	Policy usage record for imsi: 194903515200125 was not removed
[magma@10.240.0.49] out: [vagrant@127.0.0.1:2201] out:     assertions.go:134: 
[magma@10.240.0.49] out: [vagrant@127.0.0.1:2201] out:         	Error Trace:	assertions.go:134
[magma@10.240.0.49] out: [vagrant@127.0.0.1:2201] out:         	            				assertions.go:127
[magma@10.240.0.49] out: [vagrant@127.0.0.1:2201] out:         	            				gy_enforcement_test.go:200
[magma@10.240.0.49] out: [vagrant@127.0.0.1:2201] out:         	Error:      	element expectation_met:true  appears more times in [expectation_met:true ] than in []
[magma@10.240.0.49] out: [vagrant@127.0.0.1:2201] out:         	Test:       	TestGyCreditExhaustionWithCRRU
[magma@10.240.0.49] out: [vagrant@127.0.0.1:2201] out:     assertions.go:136: [error:"Expected: Imsi: 194903515200125, Type: TERMINATION, Received: Imsi: 194903515200125, Type: UPDATE"  error:"Expected: Imsi: 194903515200125, Type: TERMINATION, Received: Imsi: 194903515200125, Type: UPDATE"  error:"Expected: Imsi: 194903515200125, Type: TERMINATION, Received: Imsi: 194903515200125, Type: UPDATE"  error:"Expected: Imsi: 194903515200125, Type: TERMINATION, Received: Imsi: 194903515200125, Type: UPDATE"  error:"Expected: Imsi: 194903515200125, Type: TERMINATION, Received: Imsi: 194903515200125, Type: UPDATE"  error:"Expected: Imsi: 194903515200125, Type: TERMINATION, Received: Imsi: 194903515200125, Type: UPDATE"  error:"Expected: Imsi: 194903515200125, Type: TERMINATION, Received: Imsi: 194903515200125, Type: UPDATE"  error:"Expected: Imsi: 194903515200125, Type: TERMINATION, Received: Imsi: 194903515200125, Type: UPDATE" ]
[magma@10.240.0.49] out: [vagrant@127.0.0.1:2201] out: 
[magma@10.240.0.49] out: [vagrant@127.0.0.1:2201] out: 
[magma@10.240.0.49] out: [vagrant@127.0.0.1:2201] out: DONE 34 tests, 4 skipped, 1 failure in 848.321s```

### PR DESCRIPTION
**Pull request by uri200**
Signed-off-by: Oriol Batalla <obatalla@fb.com>

## Summary

Sometimes iperf process on traffic server gets stuck. This PR adds a feature for UESIM to stop and start the process again right before genearing traffic 

This PR also adds the collection of uesim logs in CI in case there is a failed tests  

## Test Plan

make precommit cwag
cwag integ test

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

File: cwf/gateway/services/uesim/servicers/iperf_server_restarter.go [hunk 1]
```diff
@@ -0,0 +1,86 @@
...
+	"fmt"
+	"github.com/golang/glog"
+	"golang.org/x/crypto/ssh"
+	"time"
+)
+
+// restartIperfServer is a best efort function to restart iperf server, Will try to
+// access the iperf server through ssh using the address and port defined in uesim.
+// If ssh is not accessible it will just print error.
+
```
Comment (uri200) [inline cwf/gateway/services/uesim/servicers/iperf_server_restarter.go:14]: note this is an experimental code. So we use hardcoded user and passwords. 

If this works, we will update this into a config file

BTW, those user/passwd are default, no secret is revealed

**Review by koolzz — APPROVED** [review]
