### PR TITLE
fix(agw): Added code to send event for attach failure

### LINKED ISSUE #10756: No event triggered for Attach Failure in case on unknown User
### Your Environment

- **Version:** v1.6.1
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** eventd
- **Deployment Environment:** bare-metal (AGW)

### Describe the Issue
We are trying out a simply attach failure scenario and checking for event trigger/generated for the same. During attach failure due to 5001 DIAMETER_ERROR_USER_UNKNOWN, no event by eventd generated for same.
**Scenario:** Trying for initial attach with UE Identity (IMSI) which is not configured in AGW through NMS UI subscriber DB.
 **Result:** Attach Failed
 **Expected:** An event to be triggered from eventd, so remote user can understand that attach got failed.

Logs:
**MME log:** [invalid_imsi_mme.log](https://github.com/magma/magma/files/7684773/invalid_imsi_mme.log)
**syslog:** [wrong_imsi.log](https://github.com/magma/magma/files/7684777/wrong_imsi.log)

**Call Trace**: 
[wrong_imsi.zip](https://github.com/magma/magma/files/7684801/wrong_imsi.zip)

### PR DESCRIPTION
**Pull request by rsarwad**
fix(agw): Added code to send event for attach failure
## Summary
Added code at mme_app to send "attach failure" event when UE fails to attach
The PR provides fixes for issue, https://github.com/magma/magma/issues/10756
## Test Plan
Executed s1ap sanity test suite, unit test cases and verified changes in Terra VM

### CODE REVIEW

File: lte/gateway/c/core/oai/tasks/nas/emm/Attach.c [hunk 1]
```diff
@@ -1031,6 +1031,7 @@ status_code_e _emm_attach_reject(
   OAILOG_FUNC_IN(LOG_NAS_EMM);
   int rc = RETURNerror;
 
+  attach_failure_event(emm_context->_imsi64);
```
Comment (ardzoht) [inline lte/gateway/c/core/oai/tasks/nas/emm/Attach.c]: does it makes more sense to call this `attach_reject` event?

**Review by ssanadhya — APPROVED** [review]
