### PR TITLE
[SessionD] Add a EventDClient base class with virtual methods

### LINKED ISSUE #5439: Ubuntu20: SessionD: unit tests are failing.
### Your Environment

- **Version:** master
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** sessionD
- **Deployment Environment:** Vagrant (AGW) magma_focal.

### Describe the Issue

`make test_session_manager` fails due to multiple test failure.

**To Reproduce**
1. Stop magma VM
2. bring up magma_focal VM
3. `cd magma/lte/gateway/`
4. `make test_session_manager`

Log:
```
vagrant@magma-dev-focal:~/magma/lte/gateway$ make test_session_manager
OAI_FLAGS -DS6A_OVER_GRPC=True -DEMBEDDED_SGW=True -DENABLE_OPENFLOW=True -DSPGW_ENABLE_SESSIOND_AND_MOBILITYD=True
sudo service magma@* stop
find /home/vagrant/magma/orc8r/gateway/c/common \( -iname "*.c" -o -iname "*.cpp" -o -iname "*.h" \) -exec \
clang-format --style=file -i {} \;
mkdir -p  /home/vagrant/build/c//magma_common
cd  /home/vagrant/build/c//magma_common &&  cmake  /home/vagrant/magma/orc8r/gateway/c/common -DCMAKE_BUILD_TYPE=Debug  -DCMAKE_C_FLAGS="-Wall" -GNinja
Proto_srcs are /home/vagrant/build/c/magma_common/service303/orc8r/protos/common.pb.cc;/home/vagrant/build/c/magma_common/service303/orc8r/protos/metricsd.pb.cc;/home/vagrant/build/c/magma_common/service303/orc8r/protos/service303.pb.cc;/home/vagrant/build/c/magma_common/service303/orc8r/protos/service303.grpc.pb.cc;/home/vagrant/build/c/magma_common/service303/orc8r/protos/metrics.pb.cc
Async Proto_srcs are /home/vagrant/build/c/magma_common/async_grpc/lte/protos/session_manager.pb.cc;/home/vagrant/build/c/magma_common/async_grpc/lte/protos/abort_session.pb.cc;/home/vagrant/build/c/magma_common/async_grpc/lte/protos/policydb.pb.cc;/home/vagrant/build/c/magma_common/async_grpc/lte/protos/subscriberdb.pb.cc;/home/vagrant/build/c/magma_common/async_grpc/lte/protos/mobilityd.pb.cc;/home/vagrant/build/c/magma_common/async_grpc/lte/protos/session_manager.grpc.pb.cc;/home/vagrant/build/c/magma_common/async_grpc/lte/protos/abort_session.grpc.pb.cc;/home/vagrant/build/c/magma_common/async_grpc/lte/protos/mobilityd.grpc.pb.cc;/home/vagrant/build/c/magma_common/async_grpc/orc8r/protos/common.pb.cc;/home/vagrant/build/c/magma_common/async_grpc/orc8r/protos/redis.pb.cc;/home/vagrant/build/c/magma_common/async_grpc/orc8r/protos/eventd.pb.cc;/home/vagrant/build/c/magma_common/async_grpc/orc8r/protos/eventd.grpc.pb.cc
Async Proto_srcs are /home/vagrant/build/c/magma_common/datastore/lte/protos/session_manager.pb.cc;/home/vagrant/build/c/magma_common/datastore/lte/protos/policydb.pb.cc;/home/vagrant/build/c/magma_common/datastore/lte/protos/mobilityd.pb.cc;/home/vagrant/build/c/magma_common/datastore/lte/protos/subscriberdb.pb.cc;/home/vagrant/build/c/magma_common/datastore/lte/protos/session_manager.grpc.pb.cc;/home/vagrant/build/c/magma_common/datastore/orc8r/protos/common.pb.cc;/home/vagrant/build/c/magma_common/datastore/orc8r/protos/redis.pb.cc
Proto_srcs are /home/vagrant/build/c/magma_common/policydb/orc8r/protos/common.pb.cc;/home/vagrant/build/c/magma_common/policydb/lte/protos/policydb.pb.cc
-- Configuring done
-- Generating done
-- Build files have been written to: /home/vagrant/build/c/magma_common
ninja -C  /home/vagrant/build/c//magma_common
ninja: Entering directory `/home/vagrant/build/c//magma_common'
ninja: no work to do.
mkdir -p   /home/vagrant/build/c//session_manager
cd   /home/vagrant/build/c//session_manager &&  cmake   /home/vagrant/magma/lte/gateway/c/session_manager -DCMAKE_BUILD_TYPE=Debug    -DBUILD_TESTS=1 -GNinja
Found CLANG_FORMAT: /usr/bin/clang-format
Build type is Debug
Proto_srcs are /home/vagrant/build/c/session_manager/orc8r/protos/common.pb.cc;/home/vagrant/build/c/session_manager/orc8r/protos/directoryd.pb.cc;/home/vagrant/build/c/session_manager/lte/protos/session_manager.pb.cc;/home/vagrant/build/c/session_manager/lte/protos/subscriberdb.pb.cc;/home/vagrant/build/c/session_manager/lte/protos/policydb.pb.cc;/home/vagrant/build/c/session_manager/lte/protos/pipelined.pb.cc;/home/vagrant/build/c/session_manager/lte/protos/spgw_service.pb.cc;/home/vagrant/build/c/session_manager/lte/protos/mconfig/mconfigs.pb.cc;/home/vagrant/build/c/session_manager/feg/gateway/services/aaa/protos/accounting.pb.cc;/home/vagrant/build/c/session_manager/feg/gateway/services/aaa/protos/context.pb.cc;/home/vagrant/build/c/session_manager/orc8r/protos/directoryd.grpc.pb.cc;/home/vagrant/build/c/session_manager/lte/protos/session_manager.grpc.pb.cc;/home/vagrant/build/c/session_manager/lte/protos/pipelined.grpc.pb.cc;/home/vagrant/build/c/session_manager/lte/protos/spgw_service.grpc.pb.cc;/home/vagrant/build/c/session_manager/feg/gateway/services/aaa/protos/accounting.grpc.pb.cc
-- Configuring done
-- Generating done
-- Build files have been written to: /home/vagrant/build/c/session_manager
ninja -C   /home/vagrant/build/c//session_manager
ninja: Entering directory `/home/vagrant/build/c//session_manager'
[22/22] Linking CXX executable test/cloud_reporter_test
cd  /home/vagrant/build/c//session_manager && ctest --output-on-failure
Test project /home/vagrant/build/c/session_manager
      Start  1: test_session_credit
 1/14 Test  #1: test_session_credit ..................   Passed    1.03 sec
      Start  2: test_local_enforcer
 2/14 Test  #2: test_local_enforcer ..................   Passed    2.38 sec
      Start  3: test_cloud_reporter
 3/14 Test  #3: test_cloud_reporter ..................***Failed    0.04 sec
Running main() from gmock_main.cc
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from SessionReporterTest
[ RUN      ] SessionReporterTest.test_single_call
[/home/vagrant/magma/orc8r/gateway/c/common/config/ServiceConfigLoader.cpp:33] Override file not found for service control_proxy
[/home/vagrant/magma/orc8r/gateway/c/common/config/ServiceConfigLoader.cpp:33] Override file not found for service service_registry
Started reporter thread
Started cloud thread
/home/vagrant/magma/lte/gateway/c/session_manager/test/test_cloud_reporter.cpp:74: Failure
Value of: false
  Actual: false
Expected: true
/home/vagrant/magma/lte/gateway/c/session_manager/test/test_cloud_reporter.cpp:94: Failure
Actual function call count doesn't match EXPECT_CALL(mock_callback, create_callback(_, CheckCreateResponseRuleSize(1)))...
         Expected: to be called once
           Actual: never called - unsatisfied and active
Stopped cloud thread
/home/vagrant/magma/lte/gateway/c/session_manager/test/test_cloud_reporter.cpp:99: Failure
Actual function call count doesn't match EXPECT_CALL(*mock_cloud, CreateSession(_, _, _))...
         Expected: to be called once
           Actual: never called - unsatisfied and active
[  FAILED  ] SessionReporterTest.test_single_call (18 ms)
[ RUN      ] SessionReporterTest.test_multi_call
Started reporter thread
Started cloud thread
Stopped cloud thread
Stopped reporter thread
[       OK ] SessionReporterTest.test_multi_call (14 ms)
[----------] 2 tests from SessionReporterTest (32 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test suite ran. (32 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] SessionReporterTest.test_single_call

 1 FAILED TEST

      Start  4: test_session_manager_handler
 4/14 Test  #4: test_session_manager_handler .........   Passed    0.03 sec
      Start  5: test_sessiond_integ
```

### LINKED ISSUE #5461: [SessionD][UnitTests] Fix SessionD unit tests's unconventional GMock usage
### Your Environment

- **Version:** master
- **Affected Component:** SessionD Unit Tests

### Describe the Issue
GMock Docs:
 * https://github.com/google/googletest/blob/master/docs/gmock_cook_book.md#creating-mock-classes

In SessionD unit tests, we are currently generating mocks for non-virtual methods. The way we do it for non-virtual methods is a bit of an undefined situation. So cleaning this up for sanity. (I'm hoping it'll solve other issue regarding SessionD unit tests surprising high resource usage, but I do not know if this will help)
* DirectoryDClient
* EventDClient

### PR DESCRIPTION
**Pull request by themarwhal**
## Summary
* Add a EventClient base class that AsyncEventClient inherits from. This way, the class we mock in tests have virtual methods. (The way we're currently using gmock for EventdClient is undocumented :o ) https://github.com/google/googletest/blob/master/docs/gmock_for_dummies.md#writing-the-mock-class
* `RESPONSE_TIMEOUT` -> `RESPONSE_TIMEOUT_SEC` to be more descriptive
* For any class with virtual methods, setup a default virtual destructor. (More info: https://stackoverflow.com/questions/461203/when-to-use-virtual-destructors)

## Test Plan
make test in AGW + S1AP tests to make sure event logging still works

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Review by uri200 — APPROVED** [review]

**Comment by themarwhal** [comment]
MAGMA-OAI-TESTS

File: lte/gateway/c/session_manager/SessionEvents.h [hunk 1]
```diff
@@ -29,34 +29,37 @@ namespace lte {
 
 class EventsReporter {
  public:
+  virtual ~EventsReporter() = default;
+
   virtual void session_created(
       const std::string& imsi, const std::string& session_id,
       const SessionConfig& session_context,
-      const std::unique_ptr<SessionState>& session){};
```
Comment (themarwhal) [inline lte/gateway/c/session_manager/SessionEvents.h:35]: for consistency with other classes `{}` -> `= 0`

**Comment by mattymo** [comment]
RestartLTETests

**Comment by mattymo** [comment]
RestartCWAGTests

**Comment by electronjoe** [comment]
The incorrect use of gMock was also breaking some of my docker based tests in GCC 9.3. I anticipate this PR will fix it!
