### PR TITLE
[NMS] Fix gateway json editor

### LINKED ISSUE #2523: [NMS] Save Gateway JSON
Save gateway that does not have connected enodebs

### PR DESCRIPTION
**Pull request by HannaFar**
Signed-off-by: HannaFar <hannafarag159@gmail.com>

## Summary

Fix gateway JSON editor.

### CODE REVIEW

File: nms/app/packages/magmalte/app/views/equipment/GatewayDetailConfig.js [hunk 1]
```diff
@@ -67,7 +67,10 @@ export function GatewayJsonConfig() {
 
   return (
     <JsonEditor
-      content={gwInfoJson}
+      content={{
+        ...gwInfoJson,
+        connected_enodeb_serials: gwInfoJson.connected_enodeb_serials ?? [],
```
Comment (karthiksubraveti) [inline nms/app/packages/magmalte/app/views/equipment/GatewayDetailConfig.js:71]: Can you make a small change to GatewayContext setState to accept the flow parameter of mutable_lte_gateway rather than lte_gateway. 

export type GatewayContextType = {
  state: {[string]: lte_gateway},
-  setState: (key: gateway_id, val?: lte_gateway) => Promise<void>,
-  setState: (key: gateway_id, val?: mutable_lte_gateway) => Promise<void>,
  updateGateway: (props: $Shape<UpdateGatewayProps>) => Promise<void>,
};

We should ensure that we only pass in the mutable_lte_gateway for saving in the config. Also let us do a get to store the latest state in gatewayState For e.g.

https://github.com/magma/magma/blob/1b7439ec8f6a4af9eee971f8726d5306763f1209/nms/app/packages/magmalte/app/state/SubscriberState.js#L115

File: nms/app/packages/magmalte/app/views/equipment/GatewayDetailConfig.js [hunk 2]
```diff
@@ -76,6 +79,7 @@ export function GatewayJsonConfig() {
             variant: 'success',
           });
           setError('');
+          history.goBack();
```
Comment (karthiksubraveti) [inline nms/app/packages/magmalte/app/views/equipment/GatewayDetailConfig.js:81]: minor comment: You can get rid of the status in the setState, mutable_lte_gateway doesn't need status attribute

**Review by karthiksubraveti — APPROVED** [review]

**Review by karthiksubraveti — APPROVED** [review]
