### PR TITLE
fix(amf): Handling PDU session establishment reject Scenarios

### LINKED ISSUE #6574: Add support for PDU session establishment Reject

### PR DESCRIPTION
**Pull request by sreedharkumartn**
Signed-off-by: sreedharkumartn <sreedhar.kumar@wavelabs.ai>

## Summary
- Handled below Failure Cases:
-------------------------------------------------------------------------------------------------------------------------
Cause 27 – Missing or unknown DNN
This 5GSM cause is used by the network to indicate that the requested service was rejected by the external DN
because the DNN was not included although required or if the DNN could not be resolved.

Cause 28 – Unknown PDU session type
This 5GSM cause is used by the network to indicate that the requested service was rejected by the external DN
because the requested PDU session type could not be recognized or is not allowed.

Cause 43 - Invalid PDU session identity
Use case: If AMF receives new PDU Session Establishment Request and
                AMF have already another active PDU Session in progress with Same PDU Session Identity,
                AMF will not process PDU Session Establishment requests for 5 times, after that AMF rejects with reason 43.

-----------------------------------------------------------------------------------------------------------------------------------
- DNN optional IE support in PDU Session Establishment Request.

## Test Plan
- Verified below Failures cases Using UERANSIM.
- Attached Pcap snap and log file of all failure cases.
1. PDU Session Establishment Failure with reason 27

Log file:
[mme_missing_dnn.log](https://github.com/magma/magma/files/7389235/mme_missing_dnn.log)

Pcap snap:
missing_dnn

2. PDU Session Establishment Failure with reason 28

Log file:
[mme_unknown_session_type.log](https://github.com/magma/magma/files/7389239/mme_unknown_session_type.log)

Pcap snap:
unknown_pdu_session_type

3. PDU Session Establishment Failure with reason 43

Log file:
[mme_invalid_pdu_session_identity.log](https://github.com/magma/magma/files/7389242/mme_invalid_pdu_session_identity.log)

Pcap snap:
invalid_pdu_session_identity

- Added UT cases to validate Failure Structure and validated.
UT Cases

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

File: lte/gateway/c/core/oai/tasks/amf/amf_app_ue_context_and_proc.h [hunk 1]
```diff
@@ -268,6 +268,8 @@ typedef struct smf_context_s {
   int retransmission_count;
   protocol_configuration_options_t pco;
 
+  uint32_t count_duplicate_pdu_session_est_req;
+
```
Comment (panyogesh) [inline lte/gateway/c/core/oai/tasks/amf/amf_app_ue_context_and_proc.h:271]: Can you please rename it as pdu_session_est_req_count..(or duplicate_pdu_session_est_req_count)

File: lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp [hunk 2]
```diff
@@ -35,16 +35,23 @@ extern "C" {
...
 
 namespace magma5g {
 #define IMSI_LEN 15
 #define AMF_CAUSE_SUCCESS 1
-const uint32_t MAX_UE_PDU_SESSION_LIMIT = 15;
+const uint32_t MAX_UE_PDU_SESSION_LIMIT                             = 15;
+const uint32_t MAX_UE_INITIAL_PDU_SESSION_ESTABLISHMENT_REQ_ALLOWED = 5;
 
 int amf_max_pdu_session_reject(amf_ue_ngap_id_t ue_id, ULNASTransportMsg* msg);
+int amf_pdu_session_establishment_reject(
```
Comment (panyogesh) [inline lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp]: Can we have these definitions in another header files like :  "include/amf_smf_packet_handler.h"

File: lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp [hunk 3]
```diff
@@ -374,14 +381,39 @@ int amf_smf_send(
...
+  the requested PDU session type could not be recognized or is not allowed.
+  */
+  M5GPduSessionType session_type = static_cast<M5GPduSessionType>(
+      msg->payload_container.smf_msg.msg.pdu_session_estab_request
+          .pdu_session_type.type_val);
+  if (M5GPduSessionType::UNSTRUCTURED == session_type ||
+      M5GPduSessionType::ETHERNET == session_type) {
+    cause = M5GSmCause::UNKNOWN_PDU_SESSION_TYPE;
+  }
+
```
Comment (panyogesh) [inline lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp]: This function is getting bigger. Can you please split it like                                        _amf_smf_validate_params and then rest of regular functionality

File: lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp [hunk 4]
```diff
@@ -824,4 +885,182 @@ int amf_max_pdu_session_reject(
...
+ **				         secure msg                        **
+ **   		   msg                 : out parmaeter Session             **
+ **                                      Establishment Reject              **
+ **                                                                        **
+ **  Return     :  len                 : buffer required for               **
+ **                                      DLNASTransportMsg                 **
+ **                                                                        **
+ ***************************************************************************/
+
+int construct_pdu_session_reject_dl_req(
```
Comment (panyogesh) [inline lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp:1010]: Mostly it seems will be used here. Can you please make it static. Also in test program call the parent function. Check the possibility.

File: lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp [hunk 5]
```diff
@@ -682,6 +686,83 @@ TEST(test_amf_nas5g_pkt_process, test_amf_security_mode_reject_message_data) {
...
+  uint8_t sequence_number  = 0;
+  bool is_security_enabled = false;
+  amf_nas_message_t msg    = {};
+  uint8_t cause            = 27;
+  uint8_t pti              = 1;
+  uint8_t session_id       = 1;
+  bstring buffer;
+  uint32_t bytes = 0;
+
+  int len = construct_pdu_session_reject_dl_req(
```
Comment (panyogesh) [inline lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp:702]: Is it possible to call "amf_pdu_session_establishment_reject". amf_send_msg_to_task() gets stubbed. So we can make use of it.

File: lte/gateway/c/core/oai/tasks/amf/amf_app_ue_context_and_proc.h (hunk 1 above)
Comment (sreedharkumartn) [reply lte/gateway/c/core/oai/tasks/amf/amf_app_ue_context_and_proc.h:271]: Addressed review comment

File: lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp (hunk 2 above)
Comment (sreedharkumartn) [reply lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp]: created new header file as specified.

File: lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp (hunk 3 above)
Comment (sreedharkumartn) [reply lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp]: Two new functions are created from this function. 1. For 5GSM Causes - amf_smf_validate_ie_params() and 2. For 5GMM Cause - amf_smf_validate_context().

**Comment by sreedharkumartn** [comment]
- Verified below Failures cases Using UERANSIM.
- Attached Pcap snap and log file of all failure cases.
1. PDU Session Establishment Failure with reason 27
Log file:
[mme_missing_dnn.log](https://github.com/magma/magma/files/7462326/mme_missing_dnn.log)
Pcap Snap:
Missing_dnn
2. PDU Session Establishment Failure with reason 28
Log file:
[mme_unknown_pdu_type.log](https://github.com/magma/magma/files/7462339/mme_unknown_pdu_type.log)
Pcap Snap:
Unknown_PDU_type
3. PDU Session Establishment Failure with reason 43
Log file:
[mme_invalid_pdu_identity.log](https://github.com/magma/magma/files/7462351/mme_invalid_pdu_identity.log)
Pcap snap:
Invalid_PDU_Session_Identity
UT cases validated:
UT_Test

File: lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp (hunk 5 above)
Comment (sreedharkumartn) [reply lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp:702]: Zenhub ticket #9944 is handling this comment.

File: lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp (hunk 4 above)
Comment (sreedharkumartn) [reply lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp:1010]: This function is calling by two different files (amf_smf_send.cpp, test_amf_encode_decode.cpp). Right now we can't make it as static.

**Comment by panyogesh** [comment]
Comments seems to be addressed.

**Comment by ulaskozat** [comment]
@ssanadhya please steer this PR.

File: lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp [hunk 6]
```diff
@@ -563,7 +562,100 @@ int amf_smf_send(
...
+
+  /*
+  Cause #28 – Unknown PDU session type
+  the requested PDU session type could not be recognized or is not allowed.
+  */
+  M5GPduSessionType session_type = static_cast<M5GPduSessionType>(
+      msg->payload_container.smf_msg.msg.pdu_session_estab_request
+          .pdu_session_type.type_val);
+  if (M5GPduSessionType::UNSTRUCTURED == session_type ||
+      M5GPduSessionType::ETHERNET == session_type) {
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp]: Please use the variable on the left hand side of comparison for readability
```suggestion
  if (session_type == M5GPduSessionType::UNSTRUCTURED  ||
      session_type ==  M5GPduSessionType::ETHERNET) {
```

File: lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp [hunk 7]
```diff
@@ -563,7 +562,100 @@ int amf_smf_send(
...
+  */
+  ue_m5gmm_context_s* ue_context = amf_ue_context_exists_amf_ue_ngap_id(ue_id);
+  M5GRequestType requestType =
+      static_cast<M5GRequestType>(msg->request_type.type_val);
+  smf_ctx = amf_get_smf_context_by_pdu_session_id(
+      ue_context, msg->payload_container.smf_msg.header.pdu_session_id);
+
+  if ((msg->payload_container.smf_msg.header.message_type ==
+       PDU_SESSION_ESTABLISHMENT_REQUEST) &&
+      (M5GRequestType::INITIAL_REQUEST == requestType) && smf_ctx) {
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp]:
```suggestion
      (requestType == M5GRequestType::INITIAL_REQUEST) && smf_ctx) {
```

File: lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp [hunk 8]
```diff
@@ -563,7 +562,100 @@ int amf_smf_send(
...
+    if (smf_ctx->duplicate_pdu_session_est_req_count >=
+        MAX_UE_INITIAL_PDU_SESSION_ESTABLISHMENT_REQ_ALLOWED - 1) {
+      cause = M5GSmCause::INVALID_PDU_SESSION_IDENTITY;
+    } else {
+      smf_ctx->duplicate_pdu_session_est_req_count += 1;
+      OAILOG_INFO(
+          LOG_AMF_APP,
+          "duplicate Initial PDU Session establishment request received");
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp]:
```suggestion
          "Duplicate Initial PDU Session establishment request received");
```

File: lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp [hunk 9]
```diff
@@ -563,7 +562,100 @@ int amf_smf_send(
...
 }
+/***************************************************************************
+**                                                                        **
+** Name:    amf_smf_validate_ie_params()                                  **
+**                                                                        **
+** Description: function to handle PDU Session Establishment Failures     **
+**                                                                        **
+**                                                                        **
+***************************************************************************/
+M5GSmCause amf_smf_validate_ie_params(
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp]: This function is not validating all ies in message, just checking for session establishment failure cause. Can we instead call it `amf_smf_get_smcause()`

File: lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp [hunk 10]
```diff
@@ -563,7 +562,100 @@ int amf_smf_send(
...
+          "duplicate Initial PDU Session establishment request received");
+    }
+  }
+  return cause;
+}
+/***************************************************************************
+**                                                                        **
+** Name:    amf_smf_validate_context()                                    **
+**                                                                        **
+** Description: function to handle 5GMM cause                             **
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp]:
```suggestion
** Description: function to check if max PDU sessions reached             **
```

File: lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp [hunk 11]
```diff
@@ -362,13 +359,13 @@ static int pdu_session_resource_release_t3592_handler(
...
+** Name:    amf_smf_process_pdu_session_packet()                          **
 **                                                                        **
 ** Description: handler to send session request to SMF                    **
 **                                                                        **
 **                                                                        **
 ***************************************************************************/
-int amf_smf_send(
+int amf_smf_process_pdu_session_packet(
     amf_ue_ngap_id_t ue_id, ULNASTransportMsg* msg, int amf_cause) {
   int rc = 1;
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp]: Please define a macro to indicate what 1 means (success/failure).

File: lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp [hunk 12]
```diff
@@ -889,4 +981,182 @@ int handle_sm_message_routing_failure(
...
+  len++;
+
+  SmfMsg& pdu_sess_est_reject = dlmsg->payload_container.smf_msg;
+  // header
+  pdu_sess_est_reject.header.extended_protocol_discriminator =
+      M5G_SESSION_MANAGEMENT_MESSAGES;
+  pdu_sess_est_reject.header.pdu_session_id = session_id;
+  pdu_sess_est_reject.header.message_type   = PDU_SESSION_ESTABLISHMENT_REJECT;
+  pdu_sess_est_reject.header.procedure_transaction_id = pti;
+  // container_len++;
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp]: Remove commented code

File: lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp [hunk 13]
```diff
@@ -889,4 +981,182 @@ int handle_sm_message_routing_failure(
...
+    OAILOG_WARNING(LOG_AMF_APP, "PDU Construction is failed \n");
+    return M5G_AS_FAILURE;
+  }
+  buffer = bfromcstralloc(len, "\0");
+  bytes  = nas5g_message_encode(
+      buffer->data, &msg, len, &ue_context->amf_context._security);
+
+  if (bytes > 0) {
+    buffer->slen = bytes;
+    amf_app_handle_nas_dl_req(ue_id, buffer, rc);
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp:1157]: Is the memory allocated for `buffer` always released inside `amf_app_handle_nas_dl_req`?

**Review by ssanadhya — CHANGES_REQUESTED** [review]
@sreedharkumartn , can you also add unit tests for other functions added in this pull request, such as `amf_smf_validate_ie_params` ?

File: lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp [hunk 14]
```diff
@@ -889,4 +981,182 @@ int handle_sm_message_routing_failure(
...
+ **   		   pti                 : Procedure transaction identity    **
+ **		   is_security_enabled : indcates to construct plain msg   **
+ **				         secure msg                        **
+ **   		   msg                 : out parmaeter Session             **
+ **                                      Establishment Reject              **
+ **                                                                        **
+ **  Return     :  len                 : buffer required for               **
+ **                                      DLNASTransportMsg                 **
+ **                                                                        **
+ ***************************************************************************/
```
Comment (ulaskozat) [inline lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp]: fix these lines

File: lte/gateway/c/core/oai/tasks/nas5g/src/SmfMessage.cpp [hunk 15]
```diff
@@ -103,6 +103,11 @@ int SmfMsg::SmfMsgDecodeMsg(SmfMsg* msg, uint8_t* buffer, uint32_t len) {
                           .DecodePDUSessionEstablishmentRequestMsg(
                               &msg->msg.pdu_session_estab_request, buffer, len);
       break;
+    case PDU_SESSION_ESTABLISHMENT_REJECT:
+      decode_result = msg->msg.pdu_session_estab_reject
+                          .DecodePDUSessionEstablishmentRejectMsg(
```
Comment (ulaskozat) [inline lte/gateway/c/core/oai/tasks/nas5g/src/SmfMessage.cpp:108]: is this covered by any test case?

File: lte/gateway/c/core/oai/tasks/nas5g/src/M5GPDUSessionEstablishmentReject.cpp [hunk 16]
```diff
@@ -21,8 +21,51 @@ PDUSessionEstablishmentRejectMsg::~PDUSessionEstablishmentRejectMsg(){};
 int PDUSessionEstablishmentRejectMsg::DecodePDUSessionEstablishmentRejectMsg(
```
Comment (ulaskozat) [inline lte/gateway/c/core/oai/tasks/nas5g/src/M5GPDUSessionEstablishmentReject.cpp:21]: is this covered by a test case?

**Comment by ssanadhya** [comment]
> * Verified below Failures cases Using UERANSIM.
> * Attached Pcap snap and log file of all failure cases.
> 
> 1. PDU Session Establishment Failure with reason 27
>    Log file:
>    [mme_missing_dnn.log](https://github.com/magma/magma/files/7462326/mme_missing_dnn.log)
>    Pcap Snap:
>    Missing_dnn
> 2. PDU Session Establishment Failure with reason 28
>    Log file:
>    [mme_unknown_pdu_type.log](https://github.com/magma/magma/files/7462339/mme_unknown_pdu_type.log)
>    Pcap Snap:
>    Unknown_PDU_type
> 3. PDU Session Establishment Failure with reason 43
>    Log file:
>    [mme_invalid_pdu_identity.log](https://github.com/magma/magma/files/7462351/mme_invalid_pdu_identity.log)
>    Pcap snap:
>    Invalid_PDU_Session_Identity
>    UT cases validated:
>    UT_Test

@sreedharkumartn , The pcap and MME log for cause 28 has no packets/logs related to PDU session establishment.

**Comment by sreedharkumartn** [comment]
@ssanadhya , added the test cases for three PDU Session Establishment rejection scenarios in amf_smf_get_smcause() function. Updated the PCAP and MME log files for three PDU Session Establishment rejection scenarios.
@ssanadhya and @ulaskozat , addressed the review comments.

- Verified the below failure cases with UERANSIM.
- Attached PCAP snap and log file of all failure cases.

1. PDU Session Establishment Failure with reason 27
    Case 1: UE DNN: None, Subscriberdb DNN: None.
    Log file:  
[mme_missing_dnn_ue_subscriberdb.log](https://github.com/magma/magma/files/7529422/mme_missing_dnn_ue_subscriberdb.log)
    PCAP snap:
missing_dnn_ue_subscriberdb
    Case 2: UE have DNN, Subscriberdb DNN: None.
    Log file:
[mme_with_dnn_ue_missing_dnn_subscriberdb.log](https://github.com/magma/magma/files/7529555/mme_with_dnn_ue_missing_dnn_subscriberdb.log)
    PCAP snap:
with_dnn_ue_missing_dnn_subscriberdb
    Case 3: UE DNN: None, Subscriberdb have DNN.
     Log file:
[mme_missing_dnn_ue_subscriberdb.log](https://github.com/magma/magma/files/7529560/mme_missing_dnn_ue_subscriberdb.log)
    PCAP snap:
missing_dnn_ue_with_dnn_subscriberdb
2. PDU Session Establishment Failure with reason 28
Log file:
[mme_unknown_pdu_session_type.log](https://github.com/magma/magma/files/7529571/mme_unknown_pdu_session_type.log)
PCAP snap:
unknown_pdu_session_type
3. PDU Session Establishment Failure with reason 43
Log file:
[mme_invalid_pdu_session_identity.log](https://github.com/magma/magma/files/7529586/mme_invalid_pdu_session_identity.log)
PCAP snap:
invalid_pdu_session_identity

UT cases validated with added test cases.
UT_Test_cases

File: lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp (hunk 14 above)
Comment (sreedharkumartn) [reply lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp]: Addressed review comment.

File: lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp (hunk 12 above)
Comment (sreedharkumartn) [reply lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp]: Addressed review comment.

File: lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp (hunk 11 above)
Comment (sreedharkumartn) [reply lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp]: Addressed review comment.

File: lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp (hunk 10 above)
Comment (sreedharkumartn) [reply lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp]: Addressed review comment

File: lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp (hunk 9 above)
Comment (sreedharkumartn) [reply lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp]: Addressed review comment.

File: lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp (hunk 8 above)
Comment (sreedharkumartn) [reply lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp]: Addressed review comment

File: lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp (hunk 7 above)
Comment (sreedharkumartn) [reply lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp]: Addressed review comment.

File: lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp (hunk 6 above)
Comment (sreedharkumartn) [reply lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp]: Addressed review comment.

File: lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp (hunk 13 above)
Comment (sreedharkumartn) [reply lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp:1157]: Yes, Memory allocated for buffer always released inside amf_app_handle_nas_dl_req.
buffer destroy

File: lte/gateway/c/core/oai/tasks/nas5g/src/SmfMessage.cpp (hunk 15 above)
Comment (sreedharkumartn) [reply lte/gateway/c/core/oai/tasks/nas5g/src/SmfMessage.cpp:108]: pdu_session_establish_reject
Yes, this is covered in the above test case.

File: lte/gateway/c/core/oai/tasks/nas5g/src/M5GPDUSessionEstablishmentReject.cpp (hunk 16 above)
Comment (sreedharkumartn) [reply lte/gateway/c/core/oai/tasks/nas5g/src/M5GPDUSessionEstablishmentReject.cpp:21]: pdu_session_establish_reject
This is covered in the above test case.

**Comment by ulaskozat** [comment]
@ssanadhya could you check if your review comments are all addressed?

File: lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp (hunk 13 above)
Comment (ssanadhya) [reply lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp:1157]: @sreedharkumartn , note that the bstring nas_msg is not destroyed if the function returns due to null value of amf_app_desc_p or null ue_context. Can you create a separate PR to destroy nas_msg in those cases as well?

File: lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp [hunk 17]
```diff
@@ -563,7 +562,104 @@ int amf_smf_send(
...
+    return cause;
+  }
+  /*
+  Cause #27 – Missing or unknown DNN
+  the external DNN because the DNN was not included
+  although required or if the DNN could not be resolved.
+  */
+  if (msg->dnn.dnn.empty() &&
+      (ue_context->amf_context.apn_config_profile.nb_apns == 0)) {
+    cause = M5GSmCause::MISSING_OR_UNKNOWN_DNN;
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp:588]: You can return from here, no?

File: lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp [hunk 18]
```diff
@@ -563,7 +562,104 @@ int amf_smf_send(
...
+  /*
+  Cause #28 – Unknown PDU session type
+  the requested PDU session type could not be recognized or is not allowed.
+  */
+  M5GPduSessionType session_type = static_cast<M5GPduSessionType>(
+      msg->payload_container.smf_msg.msg.pdu_session_estab_request
+          .pdu_session_type.type_val);
+  if (session_type == M5GPduSessionType::UNSTRUCTURED ||
+      session_type == M5GPduSessionType::ETHERNET) {
+    cause = M5GSmCause::UNKNOWN_PDU_SESSION_TYPE;
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp:601]: Return from here

File: lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp [hunk 19]
```diff
@@ -563,7 +562,104 @@ int amf_smf_send(
...
+   * has already been reached for the UE, the AMF shall send back to the UE the
+   * 5GSM message which was not forwarded and 5GMM cause #65
+   */
+
+  if ((N1_SM_INFO == msg->payload_container_type.type_val) &&
+      ((M5GRequestType::INITIAL_REQUEST == requestType) ||
+       (M5GRequestType::EXISTING_PDU_SESSION == requestType))) {
+    if (ue_context->amf_context.smf_ctxt_map.size() >=
+        MAX_UE_PDU_SESSION_LIMIT) {
+      M5GMmCause mm_cause = M5GMmCause::MAX_PDU_SESSIONS_REACHED;
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp]: Duplicate declaration of mm_cause, already done in line 640 above

File: lte/gateway/c/core/oai/tasks/amf/include/amf_smf_packet_handler.h [hunk 20]
```diff
@@ -0,0 +1,36 @@
...
+ * limitations under the License.
+ */
+#pragma once
+
+#include <sstream>
+#include "lte/gateway/c/core/oai/tasks/amf/amf_app_ue_context_and_proc.h"
+#include "lte/gateway/c/core/oai/tasks/nas5g/include/M5gNasMessage.h"
+
+namespace magma5g {
+#define PAYLOAD_CONTAINER_LENGTH 2
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/tasks/amf/include/amf_smf_packet_handler.h]:
```suggestion
#define PAYLOAD_CONTAINER_TAG_LENGTH 2
```

File: lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp [hunk 21]
```diff
@@ -889,4 +985,181 @@ int handle_sm_message_routing_failure(
...
+  container_len++;
+  pdu_sess_est_reject.msg.pdu_session_estab_reject.message_type.msg_type =
+      PDU_SESSION_ESTABLISHMENT_REJECT;
+  container_len++;
+  pdu_sess_est_reject.msg.pdu_session_estab_reject.m5gsm_cause.cause_value =
+      cause;
+  container_len++;
+
+  dlmsg->payload_container.len = container_len;
+  len += PAYLOAD_CONTAINER_LENGTH;
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp]:
```suggestion
  len += PAYLOAD_CONTAINER_TAG_LENGTH;
```

File: lte/gateway/c/core/oai/tasks/amf/include/amf_smf_packet_handler.h [hunk 22]
```diff
@@ -0,0 +1,36 @@
...
+#define AMF_CAUSE_SUCCESS 1
+const uint32_t MAX_UE_PDU_SESSION_LIMIT                             = 15;
+const uint32_t MAX_UE_INITIAL_PDU_SESSION_ESTABLISHMENT_REQ_ALLOWED = 5;
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/tasks/amf/include/amf_smf_packet_handler.h]: For consistency, please use #define instead of `const uint32_t`

File: lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp [hunk 23]
```diff
@@ -842,6 +879,115 @@ TEST(test_dnn, test_amf_validate_dnn) {
...
+                     0x12, 0x01, 0x81, 0x22, 0x01, 0x01, 0x25, 0x09, 0x08,
+                     0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x65, 0x74};
+
+  uint32_t len = sizeof(pdu) / sizeof(uint8_t);
+
+  ULNASTransportMsg pdu_sess_est_req;
+  bool decode_res = false;
+  memset(&pdu_sess_est_req, 0, sizeof(ULNASTransportMsg));
+
+  decode_res = decode_ul_nas_transport_msg(&pdu_sess_est_req, pdu, len);
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp:900]: Please add a check that decode was successful

File: lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp [hunk 24]
```diff
@@ -842,6 +879,115 @@ TEST(test_dnn, test_amf_validate_dnn) {
...
+
+  // build uplinknastransport
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp]: Irrelevant comment

File: lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp [hunk 25]
```diff
@@ -842,6 +879,115 @@ TEST(test_dnn, test_amf_validate_dnn) {
...
+                     0x12, 0x01, 0x81, 0x22, 0x01, 0x01};
+  uint32_t len    = sizeof(pdu) / sizeof(uint8_t);
+
+  ULNASTransportMsg pdu_sess_est_req;
+  bool decode_res = false;
+  memset(&pdu_sess_est_req, 0, sizeof(ULNASTransportMsg));
+
+  decode_res = decode_ul_nas_transport_msg(&pdu_sess_est_req, pdu, len);
+
+  // build uplinknastransport
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp]: Irrelevant comment

File: lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp [hunk 26]
```diff
@@ -842,6 +879,115 @@ TEST(test_dnn, test_amf_validate_dnn) {
...
+                     0xc1, 0xff, 0xff, 0x91, 0xa1, 0x28, 0x01, 0x00, 0x7b,
+                     0x00, 0x07, 0x80, 0x00, 0x0a, 0x00, 0x00, 0x0d, 0x00,
+                     0x12, 0x01, 0x81, 0x22, 0x01, 0x01};
+  uint32_t len    = sizeof(pdu) / sizeof(uint8_t);
+
+  ULNASTransportMsg pdu_sess_est_req;
+  bool decode_res = false;
+  memset(&pdu_sess_est_req, 0, sizeof(ULNASTransportMsg));
+
+  decode_res = decode_ul_nas_transport_msg(&pdu_sess_est_req, pdu, len);
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp:933]: Add a check that decode was successful

File: lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp [hunk 27]
```diff
@@ -842,6 +879,115 @@ TEST(test_dnn, test_amf_validate_dnn) {
...
+  uint32_t len = sizeof(pdu) / sizeof(uint8_t);
+
+  ULNASTransportMsg pdu_sess_est_req;
+  bool decode_res = false;
+  memset(&pdu_sess_est_req, 0, sizeof(ULNASTransportMsg));
+
+  decode_res = decode_ul_nas_transport_msg(&pdu_sess_est_req, pdu, len);
+
+  EXPECT_EQ(decode_res, true);
+  // build uplinknastransport
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp]: Irrelevant comment

File: lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp [hunk 28]
```diff
@@ -842,6 +879,115 @@ TEST(test_dnn, test_amf_validate_dnn) {
...
+  ue_context_map.insert(
+      std::pair<amf_ue_ngap_id_t, ue_m5gmm_context_s*>(ue_id, ue_context));
+  std::shared_ptr<smf_context_t> smf_ctx =
+      amf_insert_smf_context(ue_context, pdu_session_id);
+
+  M5GSmCause cause     = amf_smf_get_smcause(ue_id, &pdu_sess_est_req);
+  M5GSmCause cause_2   = amf_smf_get_smcause(ue_id, &pdu_sess_est_req);
+  M5GSmCause cause_3   = amf_smf_get_smcause(ue_id, &pdu_sess_est_req);
+  M5GSmCause cause_4   = amf_smf_get_smcause(ue_id, &pdu_sess_est_req);
+  M5GSmCause cause_5   = amf_smf_get_smcause(ue_id, &pdu_sess_est_req);
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp]:
```suggestion
  for (int req_cnt=0; req_cnt < MAX_UE_INITIAL_PDU_SESSION_ESTABLISHMENT_REQ_ALLOWED; req_cnt++) {
  amf_smf_get_smcause(ue_id, &pdu_sess_est_req);
  }
```

File: lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp [hunk 29]
```diff
@@ -842,6 +879,115 @@ TEST(test_dnn, test_amf_validate_dnn) {
...
+  M5GSmCause cause_dup = amf_smf_get_smcause(ue_id, &pdu_sess_est_req);
+  EXPECT_EQ(M5GSmCause::INVALID_PDU_SESSION_IDENTITY, cause_dup);
```
Comment (ssanadhya) [inline lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp]:
```suggestion
  EXPECT_EQ(cause_dup, M5GSmCause::INVALID_PDU_SESSION_IDENTITY);
```

**Review by ssanadhya — APPROVED** [review]
LGTM, with minor comments. Please address these before merging.

File: lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp (hunk 17 above)
Comment (sreedharkumartn) [reply lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp:588]: Addressed review comment

File: lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp (hunk 18 above)
Comment (sreedharkumartn) [reply lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp:601]: Addressed review comment.

File: lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp (hunk 19 above)
Comment (sreedharkumartn) [reply lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp]: Addressed review comment.

File: lte/gateway/c/core/oai/tasks/amf/include/amf_smf_packet_handler.h (hunk 20 above)
Comment (sreedharkumartn) [reply lte/gateway/c/core/oai/tasks/amf/include/amf_smf_packet_handler.h]: Addressed review comment

File: lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp (hunk 21 above)
Comment (sreedharkumartn) [reply lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp]: Addressed review comment.

File: lte/gateway/c/core/oai/tasks/amf/include/amf_smf_packet_handler.h (hunk 22 above)
Comment (sreedharkumartn) [reply lte/gateway/c/core/oai/tasks/amf/include/amf_smf_packet_handler.h]: Addressed review comment.

File: lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp (hunk 23 above)
Comment (sreedharkumartn) [reply lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp:900]: Addressed review comment.

File: lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp (hunk 24 above)
Comment (sreedharkumartn) [reply lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp]: Addressed review comment.

File: lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp (hunk 25 above)
Comment (sreedharkumartn) [reply lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp]: Addressed review comment.

File: lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp (hunk 26 above)
Comment (sreedharkumartn) [reply lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp:933]: Addressed review comment.

File: lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp (hunk 27 above)
Comment (sreedharkumartn) [reply lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp]: Addressed review comment.

File: lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp (hunk 28 above)
Comment (sreedharkumartn) [reply lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp]: Addressed review comment.

File: lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp (hunk 29 above)
Comment (sreedharkumartn) [reply lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp]: Addressed review comment.

**Comment by sreedharkumartn** [comment]
@ssanadhya and @ulaskozat , addressed the review comments.

- Verified the below failure cases with UERANSIM.
- Attached PCAP snap and log file of all failure cases.

1. PDU Session Establishment Failure with reason 27
    Case 1: UE DNN: None, Subscriberdb DNN: None.
    Log file:    
[mme_missing_dnn_case_1.log](https://github.com/magma/magma/files/7551311/mme_missing_dnn_case_1.log)
    PCAP snap:
missing_dnn_case_1
    Case 2: UE have DNN, Subscriberdb DNN: None.
    Log file:
[mme_missing_dnn_case_2.log](https://github.com/magma/magma/files/7551341/mme_missing_dnn_case_2.log)
    PCAP snap:
missing_dnn_case_2
    Case 3: UE DNN: None, Subscriberdb have DNN.
     Log file:
[mme_missing_dnn_case_3.log](https://github.com/magma/magma/files/7551342/mme_missing_dnn_case_3.log)
     PCAP snap:
missing_dnn_case_3
2. PDU Session Establishment Failure with reason 28
Log file:
[mme_unknown_pdu_session_type.log](https://github.com/magma/magma/files/7551343/mme_unknown_pdu_session_type.log)
PCAP snap:
unknown_pdu_session_type
3. PDU Session Establishment Failure with reason 43
Log file:
[mme_invalid_pdu_session_identity.log](https://github.com/magma/magma/files/7551345/mme_invalid_pdu_session_identity.log)
PCAP snap:
invalid_pdu_session_identity

UT cases validated.
UT_cases
