### PR TITLE
fix(mme): Updating S1AP UE state IMSI write on connection_establishment_cnf

### LINKED ISSUE #8657: [agw] S1AP UE contexts are not recovered on redis after UE goes IDLE
### Your Environment

- **Version:** master
- **Affected Component:** Access Gateway
- **Affected Subcomponent:**  MME
- **Deployment Environment:** Vagrant (AGW)

### Describe the Issue

- S1AP UE context is created on Initial UE message, and it's generated on redis once IMSI is available on S1AP task (`Downlink NAS Transport` msg is sent)
- S1AP UE context on redis is deleted whenever local entry on S1AP task is deleted (`UE detach`, `Error IND sent by eNB`, `UE inactivity`)
- e.g. If UE goes to IDLE mode, and comes active again, the context is lost on redis as it's only generated on `Downlink NAS Transport` msg, and not on `Service Request` for Idle mode)

**To Reproduce**
- Run `lte/gateway/python/integ_tests/s1aptests/test_idle_mode_with_mme_restart.py` on S1AP integ tests

**Expected behavior**
- S1AP UE context should have an entry on redis after UE comes back to active from idle mode.

### PR DESCRIPTION
**Pull request by ardzoht**
Signed-off-by: Alex Rodriguez <ardzoht@gmail.com>

## Summary

- Closes #8657 
- There was an issue on UE idle cases, where S1AP UE state was not recovered / written to redis after restart. This was due to a missing update on IMSI map after MME sent connection_establishment_cnf message to S1AP, after service request was processed. 

## Test Plan

- make integ_test for sanity
- Ran `test_idle_mode_with_mme_restart.py` and ensure there's entry on redis for S1AP UE state 

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

File: lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_nas_procedures.c [hunk 1]
```diff
@@ -901,11 +902,10 @@ void s1ap_handle_conn_est_cnf(
     OAILOG_FUNC_OUT(LOG_S1AP);
   }
 
-  imsi64_t imsi64;
   s1ap_imsi_map_t* imsi_map = get_s1ap_imsi_map();
-  hashtable_uint64_ts_get(
+  hashtable_rc_t rc         = hashtable_uint64_ts_insert(
```
Comment (ulaskozat) [inline lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_nas_procedures.c]: legit github actions comment

**Review by ulaskozat — APPROVED** [review]
LGTM with a nit.
